ever-co/ever-gauzy

- apps/gauzy-e2e/src/support/Base/pagedata/RegisterPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/OnboardingPageObject.ts
- apps/gauzy-e2e/src/support/step_definitions/HumanResourcesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/HumanResourcesTest/HumanResourcesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/JobsProposalsTest/JobsProposalsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/RegisterTest/RegisterTest.ts
- apps/gauzy-e2e/src/support/step_definitions/SettingsButtonTest.feature
- apps/gauzy-e2e/src/support/step_definitions/SettingsButtonTest/SettingsButtonTest.ts
> fix: small e2e adjustments

- apps/gauzy-e2e/src/support/Base/pageobjects/CreateButtonPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/CreateButton.po.ts
- apps/gauzy-e2e/src/support/step_definitions/CreateButtonTest.feature
- apps/gauzy-e2e/src/support/step_definitions/CreateButtonTest/CreateButtonTest.ts
> feat: create button e2e tests with gherkin

- apps/gauzy-e2e/src/support/step_definitions/ReportsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ReportsTest/ReportsTest.ts
> feat: reports e2e tests with gherkin

- apps/gauzy-e2e/src/support/Base/pagedata/StatisticPageData.ts
- apps/gauzy-e2e/src/support/step_definitions/StatisticTest.feature
- apps/gauzy-e2e/src/support/step_definitions/StatisticTest/StatisticTest.ts
> feat: statistics e2e with gherkin

- packages/core/src/accounting-template/accounting-template.controller.ts
- packages/core/src/accounting-template/accounting-template.module.ts
- packages/core/src/accounting-template/accounting-template.service.ts
- packages/core/src/accounting-template/queries/accounting-template.query.ts
- packages/core/src/accounting-template/queries/handlers/accouting-template.handler.ts
- packages/core/src/accounting-template/queries/handlers/index.ts
- packages/core/src/accounting-template/queries/index.ts
- packages/core/src/email-template/commands/handlers/email-template.save.handler.ts
- packages/core/src/email-template/email-template.controller.ts
- packages/core/src/email-template/email-template.module.ts
- packages/core/src/email-template/email-template.service.ts
- packages/core/src/email-template/queries/email-template.find.query.ts
- packages/core/src/email-template/queries/email-template.query.ts
- packages/core/src/email-template/queries/handlers/email-template.find.handler.ts
- packages/core/src/email-template/queries/handlers/email-template.handler.ts
- packages/core/src/email-template/queries/handlers/index.ts
- packages/core/src/email-template/queries/index.ts
> Fix/Email & Accounting Query

- apps/gauzy-e2e/src/support/step_definitions/CreateButtonTest/CreateButtonTest.ts
- apps/gauzy-e2e/src/support/step_definitions/SettingsButtonTest.feature
- apps/gauzy-e2e/src/support/step_definitions/SettingsButtonTest/SettingsButtonTest.ts
> fix: settings and create btn e2e tests small fixes

- apps/gauzy/src/app/@core/services/custom-smtp.service.ts
- apps/gauzy/src/app/@core/services/employee-appointment.service.ts
- apps/gauzy/src/app/@core/services/role.service.ts
- packages/contracts/src/employee-settings.model.ts
- packages/contracts/src/employee.model.ts
- packages/core/src/core/crud/crud.controller.ts
- packages/core/src/custom-smtp/custom-smtp.controller.ts
- packages/core/src/custom-smtp/custom-smtp.module.ts
- packages/core/src/custom-smtp/custom-smtp.service.ts
- packages/core/src/email/email.module.ts
- packages/core/src/employee-appointment/commands/index.ts
- packages/core/src/employee-appointment/employee-appointment.controller.ts
- packages/core/src/employee-appointment/employee-appointment.module.ts
- packages/core/src/employee-proposal-template/employee-proposal-template.controller.ts
- packages/core/src/employee-setting/employee-setting.controller.ts
- packages/core/src/employee-setting/employee-setting.entity.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/organization-contact/organization-contact.controller.ts
- packages/core/src/organization-department/organization-department.controller.ts
- packages/core/src/organization-recurring-expense/organization-recurring-expense.controller.ts
- packages/core/src/role-permissions/role-permissions.service.ts
- packages/core/src/role/role.controller.ts
- packages/core/src/tenant/tenant.controller.ts
> Fix/Routing Order

- apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationTagsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/OrganizationTags.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationTagsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/OrganizationTagsTest/OrganizationTagsTest.ts
> feat: extend coverage for filtering in OrganizationTagsTest

- apps/gauzy/src/app/@core/services/time-off.service.ts
- packages/contracts/src/time-off.model.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/time-off-policy/time-off-policy.controller.ts
- packages/core/src/time-off-policy/time-off-policy.entity.ts
- packages/core/src/time-off-request/time-off-request.controller.ts
- packages/core/src/time-off-request/time-off-request.entity.ts
- packages/core/src/time-off-request/time-off-request.service.ts
> Fix/Time Off route & entity

- apps/gauzy/src/app/@shared/employee/employee-rates/employee-rates.component.html
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-employment/edit-employee-employment.component.html
> fix: after save employment and rate tab edit employment not working

- apps/gauzy/src/app/pages/invoices/invoices.module.ts
> fix: Share Estimate Invoice Not Working

- apps/gauzy-e2e/src/support/Base/pages/AddTasks.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Clients.po.ts
- apps/gauzy-e2e/src/support/commands.ts
- apps/gauzy-e2e/src/support/step_definitions/TimeTrackingTest/TimeTrackingTest.ts
> fix: small e2e fixes for time tracking page

- apps/gauzy/src/app/@core/services/approval-policy.service.ts
- apps/gauzy/src/app/@shared/language-base/index.ts
- apps/gauzy/src/app/pages/approval-policy/approval-policy.component.html
- apps/gauzy/src/app/pages/approval-policy/approval-policy.component.ts
- apps/gauzy/src/app/pages/approvals/approvals.component.html
- packages/contracts/src/approval-policy.model.ts
- packages/contracts/src/request-approval.model.ts
- packages/core/src/approval-policy/approval-policy.controller.ts
- packages/core/src/approval-policy/approval-policy.module.ts
- packages/core/src/request-approval/request-approval.controller.ts
- packages/core/src/request-approval/request-approval.entity.ts
- packages/core/src/request-approval/request-approval.module.ts
- packages/core/src/request-approval/request-approval.service.ts
- packages/core/src/time-off-request/time-off-request.module.ts
> Fix/Approval Request & Policy Route

- apps/gauzy/src/app/@core/services/equipment-sharing-policy.service.ts
- apps/gauzy/src/app/@core/services/equipment-sharing.service.ts
- apps/gauzy/src/app/@shared/equipment-sharing-policy/index.ts
- apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.component.ts
- apps/gauzy/src/app/@shared/equipment-sharing/index.ts
- apps/gauzy/src/app/pages/equipment-sharing-policy/equipment-sharing-policy.component.ts
- apps/gauzy/src/app/pages/equipment-sharing/equipment-sharing.component.ts
- apps/gauzy/src/app/pages/equipment-sharing/table-components/index.ts
- packages/contracts/src/equipment-sharing-policy.model.ts
- packages/contracts/src/equipment-sharing.model.ts
- packages/core/src/equipment-sharing-policy/equipment-sharing-policy.controller.ts
- packages/core/src/equipment-sharing-policy/equipment-sharing-policy.entity.ts
- packages/core/src/equipment-sharing/equipment-sharing.controller.ts
- packages/core/src/equipment-sharing/equipment-sharing.entity.ts
- packages/core/src/equipment-sharing/equipment-sharing.service.ts
- packages/core/src/equipment/equipment.controller.ts
- packages/core/src/equipment/equipment.entity.ts
- packages/core/src/language/language.controller.ts
> Fix/Equipment, Sharing & Policy Routes

- apps/gauzy/src/app/@core/services/expenses.service.ts
- apps/gauzy/src/app/@core/services/income.service.ts
- apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
- apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts
- apps/gauzy/src/app/pages/expenses/expense-categories/expense-categories.component.ts
- apps/gauzy/src/app/pages/expenses/expenses.component.ts
- apps/gauzy/src/app/pages/income/income.component.ts
- packages/contracts/src/employee.model.ts
- packages/contracts/src/expense-category.model.ts
- packages/contracts/src/expense.model.ts
- packages/contracts/src/income.model.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/expense-categories/expense-categories.controller.ts
- packages/core/src/expense-categories/expense-category.entity.ts
- packages/core/src/expense/commands/handlers/expense.create.handler.ts
- packages/core/src/expense/expense.controller.ts
- packages/core/src/expense/expense.entity.ts
- packages/core/src/expense/expense.module.ts
- packages/core/src/income/income.controller.ts
- packages/core/src/income/income.entity.ts
- packages/core/src/income/income.module.ts
- packages/core/src/organization-contact/organization-contact.entity.ts
- packages/core/src/organization-project/organization-project.entity.ts
- packages/core/src/organization-vendor/organization-vendor.entity.ts
> Fix/Expense, Expense Category & Income route and entity related fixes

- apps/gauzy-e2e/src/support/step_definitions/TimeTrackingTest/TimeTrackingTest.ts
> fix: time tracking e2e small fix

- apps/gauzy-e2e/src/support/Base/pagedata/AccountingTemplatesPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/AccountingTemplatesPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/AccountingTemplates.po.ts
- apps/gauzy-e2e/src/support/step_definitions/AccountingTemplatesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/AccountingTemplatesTest/AccountingTemplatesTest.ts
> feat: accounting templates e2e tests with gherkin

- apps/gauzy-e2e/src/support/Base/pagedata/ManageInterviewsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ManageInterviewsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/EditUser.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ManageInterviews.po.ts
- apps/gauzy-e2e/src/support/Base/pages/OrganizationTags.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/commands.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageInterviewsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ManageInterviewsTest/ManageInterviewsTest.ts
> Feat: extend coverage for ManageInterviewsTest

- apps/gauzy-e2e/src/support/Base/pagedata/ProposalsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ProposalsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Proposals.po.ts
- apps/gauzy-e2e/src/support/commands.ts
- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest/ProposalsTest.ts
> feat: proposals template e2e tests with gherkin

- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest/ProposalsTest.ts
> fix: proposal templates e2e small fix

- apps/gauzy/src/app/@core/services/employees.service.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts
- packages/contracts/src/employee.model.ts
- packages/core/src/core/crud/index.ts
- packages/core/src/employee-statistics/employee-statistics.service.ts
- packages/core/src/employee-statistics/queries/handlers/aggregate-employee-statistic.handler.ts
- packages/core/src/employee/commands/employee.update.command.ts
- packages/core/src/employee/commands/handlers/employee.update.handler.ts
- packages/core/src/employee/commands/handlers/index.ts
- packages/core/src/employee/commands/handlers/workig-employee.get.handler.ts
- packages/core/src/employee/commands/index.ts
- packages/core/src/employee/commands/working-employee.get.command.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/employee/employee.service.ts
- packages/core/src/employee/employee.subscriber.ts
> Fix/Employee API route order & tiny fixes

- apps/gauzy-e2e/src/support/Base/pagedata/ReportsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ReportsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Reports.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/commands.ts
- apps/gauzy-e2e/src/support/step_definitions/ReportsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ReportsTest/ReportsTest.ts
> feat: reports additional e2e tests with gherkin

- apps/gauzy-e2e/src/support/Base/pagedata/PaymentsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/PaymentsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Payments.po.ts
- apps/gauzy-e2e/src/support/step_definitions/PaymentsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/PaymentsTest/PaymentsTest.ts
> feat: payments additional e2e tests with gherkin

- apps/gauzy-e2e/src/support/Base/pagedata/ExpensesPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ExpensesPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Expenses.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ExpensesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ExpensesTest/ExpensesTest.ts
> feat: expenses additional e2e tests with gherkin

- apps/gauzy-e2e/src/support/Base/pagedata/OrganizationPublicPagePageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationPublicPagePageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/AddOrganization.po.ts
- apps/gauzy-e2e/src/support/Base/pages/OrganizationPublicPage.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/commands.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationPublicPageTest.feature
- apps/gauzy-e2e/src/support/step_definitions/OrganizationPublicPageTest/OrganizationPublicPageTest.ts
> Feat: Add organization public page test

- apps/gauzy/src/app/@core/services/feature/feature-store.service.ts
- apps/gauzy/src/app/@core/services/feature/feature.service.ts
- apps/gauzy/src/app/@shared/feature-toggle/feature-toggle.component.ts
- apps/gauzy/src/app/app.module.ts
- packages/core/src/core/crud/crud.service.ts
- packages/core/src/feature/commands/handlers/feature-toggle.update.handler.ts
- packages/core/src/feature/feature-organization.entity.ts
- packages/core/src/feature/feature-organization.service.ts
- packages/core/src/feature/feature-toggle.controller.ts
- packages/core/src/feature/feature.entity.ts
- packages/core/src/feature/feature.module.ts
- packages/core/src/feature/feature.service.ts
- packages/core/src/tenant/commands/handlers/tenant-feature-organization.create.handler.ts
- packages/core/src/user/user.controller.ts
> Fix/ User & feature toggle API routes & separate service fixes

- apps/gauzy/src/app/@core/services/appointment-employees.service.ts
- packages/contracts/src/appointment-employees.model.ts
- packages/core/src/appointment-employees/appointment-employees.controller.ts
- packages/core/src/appointment-employees/appointment-employees.entity.ts
- packages/core/src/employee-appointment/employee-appointment.controller.ts
- packages/core/src/employee-job-preset/employee-preset.controller.ts
- packages/core/src/employee-job-preset/job-search-category/job-search-category.controller.ts
- packages/core/src/employee-job-preset/job-search-category/job-search-category.entity.ts
- packages/core/src/employee-job-preset/job-search-occupation/job-search-occupation.controller.ts
- packages/core/src/employee-job-preset/job-search-occupation/job-search-occupation.entity.ts
- packages/core/src/employee-job-preset/job-search-preset.controller.ts
- packages/core/src/export-import/export/export-all.controller.ts
- packages/core/src/goal-kpi-template/goal-kpi-template.controller.ts
> Fix/Employee appointment route & entity fixes

- apps/gauzy-e2e/src/support/Base/pagedata/AppointmentsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/AppointmentsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Appointments.po.ts
- apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest/AppointmentsTest.ts
Extended functionality for adding a public appointment for a specific employee schedule.
> Feat: Extend appointments test

- apps/gauzy-e2e/src/support/Base/pagedata/OrganizationInventoryPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationInventoryPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/OrganizationInventory.po.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationInventoryTest.feature
- apps/gauzy-e2e/src/support/step_definitions/OrganizationInventoryTest/OrganizationInventoryTest.ts
---
Tests will be finished after below error is fixed
> feat: organization inventory e2e tests for merchant and warehouse

- apps/gauzy-e2e/src/support/Base/pagedata/OrganizationInventoryPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationInventoryPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/OrganizationInventory.po.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationInventoryTest.feature
- apps/gauzy-e2e/src/support/step_definitions/OrganizationInventoryTest/OrganizationInventoryTest.ts
> feat: organization inventory more e2e tests with gherkin

- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-table/merchant-table.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-table/merchant-table.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-table/warehouses-table.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-table/warehouses-table.component.scss
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-table/warehouses-table.component.ts
- packages/core/src/merchant/merchant.controller.ts
- packages/core/src/merchant/merchant.entity.ts
- packages/core/src/merchant/merchant.service.ts
- packages/core/src/warehouse/warehouse.controller.ts
- packages/core/src/warehouse/warehouse.entity.ts
> Fix/Added validation & grid view issue (Merchant & Warehouse)

- apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/index.ts
- apps/gauzy/src/app/@shared/timesheet/index.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/index.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal/view-time-log-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log/index.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.ts
- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-language-selector.component.ts
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
- apps/gauzy/src/assets/i18n/bg.json
- apps/gauzy/src/assets/i18n/en.json
- apps/gauzy/src/assets/i18n/he.json
- apps/gauzy/src/assets/i18n/ru.json
> Fix/Reset web timer after delete timesheet/timelog

- apps/desktop-timer/src/index.ts
- apps/desktop/src/index.ts
- apps/server/src/index.ts
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-menu.ts
- packages/desktop-libs/src/lib/desktop-store.ts
- packages/desktop-libs/src/lib/desktop-tray.ts
- packages/desktop-ui-lib/src/lib/settings/settings.component.html
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
- packages/desktop-ui-lib/src/lib/settings/settings.module.ts
> fix: add tab electron app setting api environtment

- apps/gauzy-e2e/src/support/Base/pagedata/MyTasksTrackedInTimesheetsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/MyTasksTrackedInTimesheetsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/MyTasksTrackedInTimesheets.po.ts
- apps/gauzy-e2e/src/support/step_definitions/MyTasksTrackedInTimesheetsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/MyTasksTrackedInTimesheetsTest/MyTasksTrackedInTimesheetsTest.ts
> Feat: My Tasks Tracked in Timesheets test

- apps/gauzy/src/app/@core/services/users.service.ts
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-language-selector.component.ts
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.ts
- packages/core/src/user/user.controller.ts
- packages/core/src/user/user.entity.ts
- packages/core/src/user/user.service.ts
> Fix/User preferred language/layout selection

- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.ts
- apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.ts
- packages/contracts/src/candidate.model.ts
- packages/core/src/candidate-source/candidate-source.entity.ts
- packages/core/src/candidate/candidate.controller.ts
- packages/core/src/candidate/candidate.subscriber.ts
- packages/core/src/tags/tag.controller.ts
> Fix/Cypress latest v8.3.1 e2e issue

- apps/gauzy-e2e/src/support/Base/pagedata/ProjectTrackedInTimesheetPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ProjectTrackedInTimesheetPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/ManageEmployees.po.ts
- apps/gauzy-e2e/src/support/Base/pages/MyTasksTrackedInTimesheets.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ProjectTrackedInTimesheet.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ProjectTrackedInTimesheetsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ProjectTrackedInTimesheetsTest/ProjectTrackedInTimesheetsTest.ts
> Feat: Project tracked in timesheets test

- packages/core/src/availability-slots/availability-slots.controller.ts
- packages/core/src/availability-slots/availability-slots.entity.ts
- packages/core/src/availability-slots/availability-slots.module.ts
- packages/core/src/availability-slots/availability-slots.service.ts
- packages/core/src/availability-slots/commands/handlers/availability-slots.bulk.create.handler.ts
- packages/core/src/availability-slots/commands/handlers/availability-slots.create.handler.ts
- packages/core/src/availability-slots/commands/handlers/get-conflict-availability-slots.handler.ts
> Fix/Availability slot bulk create issue (SQLite)

- apps/desktop/src/index.ts
- apps/server/src/index.ts
- packages/desktop-libs/src/lib/desktop-store.ts
> fix: use env from third party setting

- apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationInventoryPageObject.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationInventoryTest/OrganizationInventoryTest.ts
- apps/gauzy/src/app/@shared/product-mutation/index.ts
- apps/gauzy/src/app/@shared/product-mutation/product-category-mutation/product-category-mutation.component.html
- apps/gauzy/src/app/@shared/product-mutation/product-category-mutation/product-category-mutation.component.ts
- apps/gauzy/src/app/@shared/product-mutation/product-mutation.module.ts
- apps/gauzy/src/app/@shared/product-mutation/product-type-mutation/product-type-mutation.component.html
- apps/gauzy/src/app/@shared/product-mutation/product-type-mutation/product-type-mutation.component.ts
- apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories.component.scss
- apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-product-types/product-types.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-product-types/product-types.component.scss
- apps/gauzy/src/app/pages/inventory/components/manage-product-types/product-types.component.ts
- apps/gauzy/src/app/pages/inventory/components/table-inventory-items/table-inventory.component.ts
- packages/core/src/product-category/product-category.controller.ts
- packages/core/src/product-category/product-category.module.ts
- packages/core/src/product-category/product-category.service.ts
- packages/core/src/product-type/product-type.controller.ts
- packages/core/src/product-type/product-type.module.ts
- packages/core/src/product-type/product-type.service.ts
- packages/core/src/product/product.entity.ts
- packages/core/src/timesheet/screenshot/screenshot.entity.ts
> Fix/Product types & categories E2e failed issue

- apps/gauzy-e2e/src/support/Base/pagedata/TimeTrackingForClientPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/TimeTrackingForClientPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/TimeTrackingForClient.po.ts
- apps/gauzy-e2e/src/support/step_definitions/TimeTrackingForClientTest.feature
- apps/gauzy-e2e/src/support/step_definitions/TimeTrackingForClientTest/TimeTrackingForClientTest.ts
> Feat: time tracking for client test

- apps/gauzy-e2e/cypress.json
- apps/gauzy-e2e/src/support/Base/pageobjects/DashboardPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Dashboard.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Proposals.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest/ProposalsTest.ts
> fix: proposal test fix-new verification on dashboard for employees

- apps/server/src/index.ts
- packages/desktop-libs/src/lib/desktop-menu.ts
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
> fix: gauzy server menu

- apps/gauzy-e2e/src/support/Base/pages/ManageEmployees.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Proposals.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest/ProposalsTest.ts
> Fix: final fix on proposals test, employee dropdown wait xhr

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
> Fix/View change detection issue E2e

- apps/gauzy-e2e/src/support/Base/pagedata/TimeTracingWithPausePageData.ts
- apps/gauzy-e2e/src/support/Base/pagedata/TimeTrackingForClientPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/TimeTrackingForClientPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/TimeTrackingWithPausePageObjects.ts
- apps/gauzy-e2e/src/support/Base/pages/Estimates.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Logout.po.ts
- apps/gauzy-e2e/src/support/Base/pages/MyTasksTrackedInTimesheets.po.ts
- apps/gauzy-e2e/src/support/Base/pages/TimeOff.po.ts
- apps/gauzy-e2e/src/support/Base/pages/TimeTrackingForClient.po.ts
- apps/gauzy-e2e/src/support/Base/pages/TimeTrackingWithPause.po.ts
- apps/gauzy-e2e/src/support/step_definitions/MyTasksTrackedInTimesheetsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/MyTasksTrackedInTimesheetsTest/MyTasksTrackedInTimesheetsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/TimeOffTest/TimeOffTest.ts
- apps/gauzy-e2e/src/support/step_definitions/TimeTrackingForClientTest/TimeTrackingForClientTest.ts
- apps/gauzy-e2e/src/support/step_definitions/TimeTrackingWithPauseTest.feature
- apps/gauzy-e2e/src/support/step_definitions/TimeTrackingWithPauseTest/TimeTrackingWithPauseTest.ts
> Fix: fixing time-tracking tests and more! Added wait-for-xhr response.

- packages/core/src/equipment-sharing/equipment-sharing.service.ts
> Fix/Equipment sharing (SQLite) query

- apps/gauzy-e2e/src/support/Base/pagedata/ProjectTrackedInTimesheetPageData.ts
- apps/gauzy-e2e/src/support/Base/pagedata/TimeTrackingPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ManageInterviewsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ProjectTrackedInTimesheetPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/TimeTrackingPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/AddOrganization.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ManageInterviews.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ProjectTrackedInTimesheet.po.ts
- apps/gauzy-e2e/src/support/Base/pages/TimeOff.po.ts
- apps/gauzy-e2e/src/support/Base/pages/TimeTracking.po.ts
- apps/gauzy-e2e/src/support/step_definitions/FileStorageTest/FileStorageTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageInterviewsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ManageInterviewsTest/ManageInterviewsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/MyTasksTrackedInTimesheetsTest/MyTasksTrackedInTimesheetsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationEquipmentTest.feature
- apps/gauzy-e2e/src/support/step_definitions/OrganizationEquipmentTest/OrganizationEquipmentTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ProjectTrackedInTimesheetsTest/ProjectTrackedInTimesheetsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/TimeTrackingTest/TimeTrackingTest.ts
> Fix: gauzy e2e test fixing

- apps/gauzy-e2e/src/support/Base/pageobjects/AppointmentsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ClientsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/AddOrganization.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Appointments.po.ts
- apps/gauzy-e2e/src/support/Base/pages/CreateButton.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ManageCandidatesInvites.po.ts
- apps/gauzy-e2e/src/support/commands.ts
- apps/gauzy-e2e/src/support/step_definitions/AccountingTemplatesTest/AccountingTemplatesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/AddEmployeeLevelTest/AddEmployeeLevelTest.ts
- apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest/AppointmentsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/FileStorageTest/FileStorageTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest/ManageCandidatesInvitesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageInterviewsCriterionsTest/ManageInterviewsCriterionsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageInterviewsTest/ManageInterviewsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationPublicPageTest.feature
- apps/gauzy-e2e/src/support/step_definitions/OrganizationPublicPageTest/OrganizationPublicPageTest.ts
> Fix appointment test and more

- apps/gauzy/src/app/@core/services/role.service.ts
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.html
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/@theme/theme.module.ts
- apps/gauzy/src/app/pages/settings/edit-roles-permissions/edit-roles-permissions.component.html
- apps/gauzy/src/app/pages/settings/edit-roles-permissions/edit-roles-permissions.component.ts
- packages/contracts/src/role-permission.model.ts
- packages/core/src/role-permissions/role-permissions.controller.ts
- packages/core/src/role-permissions/role-permissions.module.ts
- packages/core/src/role-permissions/role-permissions.service.ts
- packages/core/src/role/role.controller.ts
- packages/core/src/role/role.seed.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-create.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-update.handler.ts
- packages/core/src/time-tracking/time-slot/utils.ts
- packages/core/src/time-tracking/timer/timer.controller.ts
- packages/core/src/time-tracking/timer/timer.module.ts
- packages/core/src/time-tracking/timer/timer.service.ts
> Fix/Time Tracker Permission & Role Permissions

- apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationPublicPagePageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/ApprovalRequest.po.ts
- apps/gauzy-e2e/src/support/Base/pages/OrganizationPublicPage.po.ts
- apps/gauzy-e2e/src/support/commands.ts
- apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest/AppointmentsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest/ApprovalRequestTest.ts
- apps/gauzy-e2e/src/support/step_definitions/AppsIntegrationsTest/AppsIntegrationsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationPublicPageTest.feature
- apps/gauzy-e2e/src/support/step_definitions/OrganizationPublicPageTest/OrganizationPublicPageTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ReportsTest/ReportsTest.ts
> Fix gauzy organization test and more

- apps/gauzy-e2e/src/support/Base/pages/ManageCandidatesInvites.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest/ManageCandidatesInvitesTest.ts
> fix: manage candidates test delete last step-Not correct use

- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
- apps/gauzy/src/assets/i18n/ru.json
- packages/core/src/core/seeds/seed-data.service.ts
> Fix/Employee Selector Clearable Option

- apps/server/src/index.ts
- packages/desktop-libs/src/lib/desktop-server.ts
- packages/desktop-ui-lib/src/lib/server-dashboard/server-dashboard.component.ts
- packages/desktop-ui-lib/src/lib/settings/settings.component.html
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
- packages/desktop-ui-lib/src/lib/settings/settings.module.ts
> fix: gauzy server restart after save config

- apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.ts
> feat: added default tenant file storage

- apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.html
- apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.ts
- apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.html
- apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts
- apps/gauzy/src/app/pages/tasks/tasks.module.ts
> feat: updated my task modal

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-language-selector.component.scss
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.scss
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.scss
> fix: selector text should not be truncate

- apps/gauzy-e2e/src/support/Base/pageobjects/ManageUserInvitesPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Appointments.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ApprovalRequest.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ManageUserInvites.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageUserInvitesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ManageUserInvitesTest/ManageUserInvitesTest.ts
> fix: manage users make it independent test and fix approval test

- apps/gauzy-e2e/src/support/Base/pages/Estimates.po.ts
- apps/gauzy-e2e/src/support/Base/pages/SalesInvoices.po.ts
- apps/gauzy-e2e/src/support/step_definitions/EstimatesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/EstimatesTest/EstimatesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/SalesEstimatesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/SalesEstimatesTest/SalesEstimatesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/SalesInvoicesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/SalesInvoicesTest/SalesInvoicesTest.ts
> fix: all estimates test changed verification for send email

- apps/gauzy-e2e/src/support/Base/pageobjects/MyTasksTrackedInTimesheetsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/TeamsTasksPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/ManageUserInvites.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Proposals.po.ts
- apps/gauzy-e2e/src/support/step_definitions/CandidatesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/CandidatesTest/CandidatesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/CreateButtonTest/CreateButtonTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageInterviewsTest/ManageInterviewsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/RolesPermissionsTest/RolesPermissionsTest.ts
> fix: problems in tests and selectors

- apps/gauzy-e2e/src/support/Base/pages/Appointments.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ApprovalRequest.po.ts
- apps/gauzy-e2e/src/support/step_definitions/RolesPermissionsTest/RolesPermissionsTest.ts
> fix: update roles permission

- apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.html
- apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.scss
- apps/gauzy/src/app/@shared/skills/skills-input/skills-input.component.html
- apps/gauzy/src/app/@shared/skills/skills-input/skills-input.component.scss
- apps/gauzy/src/app/share/organization/organization.component.html
- apps/gauzy/src/assets/i18n/ach.json
- apps/gauzy/src/assets/i18n/bg.json
- apps/gauzy/src/assets/i18n/en.json
- apps/gauzy/src/assets/i18n/he.json
- apps/gauzy/src/assets/i18n/ru.json
> feat: added main tab to organization public page

- packages/core/src/invite/invite.entity.ts
> fix: copy invitation link not working in invite user

- apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.html
- apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.module.ts
- apps/gauzy/src/app/share/employee/employee.component.html
- apps/gauzy/src/app/share/employee/employee.module.ts
- apps/gauzy/src/app/share/organization/organization.component.html
- apps/gauzy/src/app/share/organization/organization.module.ts
> feat: add ng tag in organization page

- apps/gauzy/src/app/@core/services/organization-employment-types.service.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.html
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.ts
- apps/gauzy/src/app/share/organization/organization-routing.module.ts
- apps/gauzy/src/app/share/organization/organization.component.html
- apps/gauzy/src/app/share/organization/organization.component.ts
- packages/common/src/utils/shared-utils.ts
- packages/contracts/src/employee.model.ts
- packages/core/package.json
- packages/core/src/core/utils.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/employee/employee.seed.ts
- packages/core/src/employee/employee.subscriber.ts
- yarn.lock
> fix: error of when click edit employee public page.

- apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.scss
> fix: fixed issue of invite email field always first letter capitalized

- apps/gauzy-e2e/src/support/Base/pageobjects/ApprovalRequestPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ManageEmployeesPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/ApprovalRequest.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ManageEmployees.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest/ApprovalRequestTest.ts
- apps/gauzy-e2e/src/support/step_definitions/RolesPermissionsTest/RolesPermissionsTest.ts
> fix: approval request test add tag select scenario

- apps/gauzy-e2e/src/support/Base/pageobjects/CandidatesPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ManageCandidatesInvitesPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ManageUserInvitesPageObject.ts
- apps/gauzy-e2e/src/support/step_definitions/CustomersTest/CustomersTest.ts
> fix: customers test add xhr to wait for res and more fixes

- package.json
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-ui-lib/package.json
- packages/desktop-ui-lib/src/lib/time-tracker/custom-render-cell.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.module.ts
> feat: added button to expand view on timer window

- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.html
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.ts
> fix: improvement subject based user organizations

- apps/gauzy/src/app/auth/login/login.component.html
- apps/gauzy/src/app/auth/register/register.component.html
> feat: add autocomplete input to login and register page

- apps/gauzy-e2e/src/support/Base/pageobjects/EditUserPageObject.ts
- apps/gauzy-e2e/src/support/step_definitions/CustomersTest/CustomersTest.ts
- apps/gauzy-e2e/src/support/step_definitions/EstimatesTest/EstimatesTest.ts
> Fix gauzy e2e test edit user and more

- apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.html
- apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.ts
- apps/gauzy/src/app/@shared/invite/invite-mutation/invite-mutation.component.ts
- apps/gauzy/src/app/@shared/invite/invites/invites.component.html
- apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
- apps/gauzy/src/app/auth/accept-invite/accept-invite.component.ts
- apps/gauzy/src/app/pages/candidates/candidates.component.ts
- apps/gauzy/src/app/pages/employees/employees.component.ts
- apps/gauzy/src/app/pages/users/users.component.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/invite.model.ts
- packages/core/src/invite/commands/handlers/index.ts
- packages/core/src/invite/commands/handlers/invite.bulk.create.handler.ts
- packages/core/src/invite/commands/index.ts
- packages/core/src/invite/commands/invite.bulk.create.command.ts
- packages/core/src/invite/invite.controller.ts
- packages/core/src/invite/invite.entity.ts
- packages/core/src/invite/invite.service.ts
> Feat: Invitation Expiration Field

- apps/gauzy/src/app/pages/employees/timesheet/daily/daily.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template.service.ts
- packages/core/src/employee-proposal-template/employee-proposal-template.module.ts
> Fix/#3561 proposal template API faling

- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
- apps/gauzy/src/app/pages/contacts/contact.component.ts
> fix: create contact button send to wrong URL and undefined Organization

- packages/core/src/core/crud/tenant-aware-crud.service.ts
- yarn.lock
> fix: multiple find conditions typescript issue

- apps/gauzy/src/app/pages/contacts/invite-contact/invite-contact.component.ts
> fix: application crash when send invite to contact

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
> fix: time tracking auto refresh default

- apps/gauzy/src/app/pages/contacts/contact.component.ts
> Fix: Default contact type

- apps/gauzy/src/app/@shared/gallery/gallery.component.html
- apps/gauzy/src/app/@shared/gallery/gallery.component.ts
- apps/gauzy/src/app/@shared/gallery/gallery.module.ts
- apps/gauzy/src/app/@shared/gallery/gallery.service.ts
> fix: screenshot download instead of open in new tab

- apps/gauzy-e2e/src/support/Base/pages/Estimates.po.ts
- apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/EstimatesTest/EstimatesTest.ts
> fix: appointments test scenario, estimates fix on xhr

- apps/gauzy/src/app/pages/invoices/invoices.component.ts
> Fix: Loading indicator after debounce time

- apps/gauzy-e2e/src/support/Base/pages/EmailHistory.po.ts
- apps/gauzy-e2e/src/support/Base/pages/FileStorage.po.ts
- apps/gauzy-e2e/src/support/step_definitions/EmailHistoryTest/EmailHistoryTest.ts
- apps/gauzy-e2e/src/support/step_definitions/EstimatesTest/EstimatesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/FileStorageTest/FileStorageTest.ts
- apps/gauzy-e2e/src/support/step_definitions/IncomeTest/IncomeTest.ts
- apps/gauzy-e2e/src/support/step_definitions/RecurringExpensesTest/RecurringExpensesTest.ts
> fix: remove problems, change scenarios on some tests, add wait for xhr

- apps/gauzy-e2e/src/support/Base/pagedata/ChangeLanguagePageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ChangeLanguagePageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/ChangeLanguage.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ChangeLanguageTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ChangeLanguageTest/ChangeLanguageTest.ts
> Feat: gauzy e2e change language test

- apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.html
- apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
- apps/gauzy/src/app/pages/payments/payments.component.ts
- packages/contracts/src/payment.model.ts
- packages/core/src/core/crud/crud.service.ts
- packages/core/src/organization-contact/organization-contact.entity.ts
- packages/core/src/payment/payment.entity.ts
- packages/core/src/payment/payment.map.service.ts
- packages/core/src/payment/payment.seed.ts
- packages/core/src/payment/payment.service.ts
> fix: payment backend API pagination issue

- packages/core/src/organization-project/organization-project.entity.ts
> fix: organization project delete API issue

- apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
- packages/core/src/core/crud/crud.service.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/organization-team/organization-team.entity.ts
- packages/core/src/tasks/task.entity.ts
> fix: #3580 SQLite task dashboard list/delete API issue

- packages/contracts/src/employee.model.ts
- packages/contracts/src/organization-team-model.ts
- packages/core/src/invoice/invoice.entity.ts
- packages/core/src/organization-team/organization-team.entity.ts
> Fix/#3583 invoice delete API issue

- apps/gauzy/src/app/@core/services/goal.service.ts
- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.html
- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.ts
- apps/gauzy/src/app/pages/teams/teams.component.html
- apps/gauzy/src/app/pages/teams/teams.component.ts
- apps/gauzy/src/app/pages/teams/teams.module.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/goal/goal.controller.ts
- packages/core/src/goal/goal.entity.ts
- packages/core/src/organization-team-employee/organization-team-employee.service.ts
- packages/core/src/organization-team/organization-team.entity.ts
- packages/core/src/organization-team/organization-team.service.ts
> Fix/#3693 Organization Team Mutation

- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest/ProposalsTest.ts
- apps/gauzy/src/app/pages/proposals/proposals.component.ts
> Fix: proposals statistics and test

- apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.html
- apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.ts
- apps/gauzy/src/app/@shared/table-components/contact-links/contact-links.component.ts
- apps/gauzy/src/app/@shared/table-components/employee-links/employee-links.component.ts
- apps/gauzy/src/app/@shared/table-components/index.ts
- apps/gauzy/src/app/@shared/table-components/table-components.module.ts
- apps/gauzy/src/app/pages/contacts/contact-routing.module.ts
- apps/gauzy/src/app/pages/contacts/contact-view/contact-view-routing.module.ts
- apps/gauzy/src/app/pages/contacts/contact-view/contact-view.component.html
- apps/gauzy/src/app/pages/contacts/contact-view/contact-view.component.scss
- apps/gauzy/src/app/pages/contacts/contact-view/contact-view.component.ts
- apps/gauzy/src/app/pages/contacts/contact-view/contact-view.module.ts
- apps/gauzy/src/app/pages/contacts/contact.component.html
- apps/gauzy/src/app/pages/contacts/contact.component.ts
- apps/gauzy/src/app/pages/income/income.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
- apps/gauzy/src/app/pages/projects/projects.component.ts
- apps/gauzy/src/app/pages/proposals/proposals.component.ts
> Feat/#2638 Integrate Contact View Page

- apps/gauzy-e2e/src/support/Base/pagedata/EmployeeDashboardPageData.ts
- apps/gauzy-e2e/src/support/Base/pagedata/ProposalsPageData.ts
- apps/gauzy-e2e/src/support/Base/pagedata/SettingsFeaturesPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/EmployeeDashboardPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/IncomePageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ProposalsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/EmployeeDashboardTest.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Proposals.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Timesheets.po.ts
- apps/gauzy-e2e/src/support/step_definitions/EmployeeDashboardTest.feature
- apps/gauzy-e2e/src/support/step_definitions/EmployeeDashboardTest/EmployeeDashboardTest.ts
- apps/gauzy-e2e/src/support/step_definitions/IncomeTest/IncomeTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ProposalsTest/ProposalsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/TimesheetsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/TimesheetsTest/TimesheetsTest.ts
> Fix-gauzy e2e test problems

- apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.ts
- packages/core/src/proposal/proposal.controller.ts
> Fix/Proposal Duplicate API route

- apps/gauzy-e2e/src/support/Base/pagedata/ClientsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ClientsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Clients.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ClientsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ClientsTest/ClientsTest.ts
> Fix: clients test css selectors, add search for clients scenario

- apps/gauzy-e2e/src/support/Base/pagedata/ClientsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ClientsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Clients.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ClientsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ClientsTest/ClientsTest.ts
- apps/gauzy/src/app/pages/contacts/contact-view/contact-view.component.html
- apps/gauzy/src/app/pages/contacts/contact-view/contact-view.component.scss
> Fix:clients test and add back button 

- apps/gauzy/src/app/pages/proposals/proposals.component.ts
> fix: Proposals table

- apps/gauzy-e2e/src/support/Base/pagedata/ContactsLeadsPageData.ts
- apps/gauzy-e2e/src/support/Base/pagedata/CustomersPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ContactsLeadsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/CustomersPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/ContactsLeads.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Customers.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ContactsLeadsTest/ContactsLeadsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/CustomersTest/CustomersTest.ts
> fix: customers and leads test css selectors

- apps/gauzy/src/app/pages/invoices/invoices.component.html
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
> Fix: invoice sent button, disable when no contact

- apps/gauzy-e2e/src/support/step_definitions/OrganizationPublicPageTest/OrganizationPublicPageTest.ts
- apps/gauzy-e2e/src/support/step_definitions/RolesPermissionsTest/RolesPermissionsTest.ts
> Fix: gauzy e2e problems tests

- apps/gauzy-e2e/src/support/Base/pagedata/ClientsPageData.ts
- apps/gauzy-e2e/src/support/Base/pagedata/HumanResourcesPageData.ts
- apps/gauzy-e2e/src/support/Base/pages/Clients.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ClientsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ClientsTest/ClientsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/HumanResourcesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/HumanResourcesTest/HumanResourcesTest.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
> Fix: gauzy e2e tests and pop options 

- apps/gauzy/src/app/pages/proposals/proposals.component.ts
> Fix: Proposals table job url verify if null

- apps/gauzy/src/app/@shared/expenses/recurring-expense-block/recurring-expense-block.component.html
- apps/gauzy/src/app/@shared/expenses/recurring-expense-block/recurring-expense-block.component.scss
> fix: Fixed Recurring Expenses table Edit Buttons

- apps/gauzy/src/app/pages/approvals/approvals.component.ts
- packages/core/src/request-approval/request-approval.service.ts
> feat:#2326 added employee name and client name in list

- apps/gauzy/src/app/auth/login/login.component.html
- apps/gauzy/src/app/auth/login/login.component.scss
- apps/gauzy/src/app/auth/login/login.component.ts
-   [v ] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [ v] Have you explained what your changes do, and why they add value?
---
> fix: Added button for collapse the demo credential box

- apps/gauzy/src/app/auth/register/register.component.html
-   [v] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [v] Have you explained what your changes do, and why they add value?
---
> fix: Display password not match message fixed

- apps/gauzy-e2e/src/support/Base/pagedata/ApprovalRequestPageData.ts
- apps/gauzy-e2e/src/support/Base/pagedata/PipelinesPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ApprovalRequestPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/ApprovalRequest.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ManageCandidatesInvites.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Payments.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Pipelines.po.ts
- apps/gauzy-e2e/src/support/Base/pages/RecurringExpenses.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest/ApprovalRequestTest.ts
- apps/gauzy-e2e/src/support/step_definitions/InvoicesTest/InvoicesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest/ManageCandidatesInvitesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/PaymentsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/PaymentsTest/PaymentsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/PipelinesTest/PipelinesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/RecurringExpensesTest/RecurringExpensesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/SalesInvoicesTest/SalesInvoicesTest.ts
- apps/gauzy/src/app/pages/payments/payments.component.ts
- apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.html
- apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.ts
- apps/gauzy/src/app/pages/proposals/proposal-edit/proposal-edit.component.ts
- apps/gauzy/src/app/pages/proposals/table-components/proposal-status/proposal-status.component.ts
- apps/gauzy/src/assets/i18n/bg.json
- apps/gauzy/src/assets/i18n/en.json
- apps/gauzy/src/assets/i18n/he.json
> Fix: gauzy e2e tests and more validations

- apps/gauzy/src/app/@core/auth/auth.guard.ts
- apps/gauzy/src/app/@core/guards/permission.guard.ts
- apps/gauzy/src/app/@core/guards/role.guard.ts
- apps/gauzy/src/app/@core/services/feature/feature.service.ts
- apps/gauzy/src/app/@core/services/goal-settings.service.ts
- apps/gauzy/src/app/@core/services/goal-templates.service.ts
- apps/gauzy/src/app/@core/services/keyresult-update.service.ts
- apps/gauzy/src/app/@core/services/keyresult.service.ts
- apps/gauzy/src/app/@core/services/service.ts
- apps/gauzy/src/app/@core/services/tasks.service.ts
- apps/gauzy/src/app/@core/utils/smart-table/server.data-source.ts
- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.ts
- apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.component.ts
- apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
- apps/gauzy/src/app/@shared/timesheet/activity.service.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts
- packages/contracts/src/timesheet.model.ts
> Fix/Deprecated code & timer position in gauzy store

- apps/gauzy/src/app/auth/login/login.component.html
- apps/gauzy/src/app/auth/login/login.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix/Time Tracking Dashboard Member Activity & Hide Demo Collapse Button

- packages/core/src/tasks/task.service.ts
> Fix/#3726 Employee my task list SQLite query

- apps/gauzy/src/app/pages/hubstaff/components/hubstaff-authorize/hubstaff-authorize.component.ts
- apps/gauzy/src/app/pages/upwork/components/upwork-authorize/upwork-authorize.component.html
- apps/gauzy/src/app/pages/upwork/components/upwork-authorize/upwork-authorize.component.ts
- packages/config/src/environments/environment.prod.ts
- packages/config/src/environments/environment.ts
- packages/core/src/hubstaff/hubstaff.controller.ts
- packages/core/src/upwork/upwork.controller.ts
> Fix/#2396 Upwork integration callback server side

- apps/gauzy/src/app/@core/services/hubstaff.service.ts
- apps/gauzy/src/app/pages/hubstaff/components/hubstaff/hubstaff.component.ts
- packages/contracts/src/integration.model.ts
- packages/core/src/hubstaff/hubstaff.controller.ts
- packages/core/src/hubstaff/hubstaff.module.ts
- packages/core/src/hubstaff/hubstaff.service.ts
- packages/core/src/time-tracking/screenshot/screenshot.module.ts
- packages/core/src/upwork/upwork.controller.ts
- packages/plugins/integration-hubstaff/src/hubstaff.config.ts
- packages/plugins/integration-hubstaff/src/index.ts
> Fix/#783 working on hubstaff sync 

- packages/desktop-libs/src/lib/desktop-timer.ts
- packages/desktop-ui-lib/src/lib/settings/settings.component.html
> feat: random screenshot desktop timer

- apps/gauzy/package.json
- yarn.lock
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-UGLIFYJS-1727251
---
> fix: apps/gauzy/package.json to reduce vulnerabilities

- packages/core/package.json
- packages/core/src/email/email.service.ts
- yarn.lock
> Fix/Email templates upgrade package & postmark configuration

- packages/core/src/core/interceptors/transform.interceptor.ts
- packages/core/src/custom-smtp/custom-smtp.controller.ts
- packages/core/src/custom-smtp/custom-smtp.entity.ts
- packages/core/src/custom-smtp/custom-smtp.service.ts
> Fix/Visibility hide for username & password for custom smtp

- packages/core/src/auth/auth.module.ts
- packages/core/src/custom-smtp/custom-smtp.entity.ts
- packages/core/src/custom-smtp/custom-smtp.module.ts
- packages/core/src/custom-smtp/custom-smtp.service.ts
- packages/core/src/email-template/email-template.module.ts
- packages/core/src/email/email.module.ts
- packages/core/src/email/email.service.ts
- packages/core/src/organization-contact/organization-contact.module.ts
- packages/core/src/pipeline/pipeline.module.ts
- packages/core/src/pipeline/pipeline.service.ts
> Fix/Custom smtp settings load from DB

- apps/gauzy-e2e/src/support/Base/pagedata/OrganizationTeamsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationTeamsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ReportsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/OrganizationTeams.po.ts
- apps/gauzy-e2e/src/support/Base/pages/Reports.po.ts
- apps/gauzy-e2e/src/support/commands.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationTeamsTest/OrganizationTeamsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ReportsTest/ReportsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/TeamsTasksTest/TeamsTasksTest.ts
> Fix gauzy e2e tests

- apps/gauzy-e2e/src/support/Base/pages/Estimates.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest/ManageCandidatesInvitesTest.ts
> fix: estimates, manage candidates tests

- apps/gauzy-e2e/src/support/Base/pagedata/PipelinesPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/PipelinesPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/Pipelines.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/step_definitions/PipelinesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/PipelinesTest/PipelinesTest.ts
> Fix: Pipelines test

- apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deal-form/pipeline-deal-form.component.ts
> Fix: pipeline deal form validation

- apps/gauzy-e2e/src/support/Base/pagedata/OrganizationHelpCenterPageData.ts
- apps/gauzy-e2e/src/support/Base/pagedata/OrganizationProjectsPageData.ts
- apps/gauzy-e2e/src/support/Base/pages/OrganizationHelpCenter.po.ts
- apps/gauzy-e2e/src/support/Base/pages/OrganizationProjects.po.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationHelpCenterTest/OrganizationHelpCenterTest.ts
- apps/gauzy-e2e/src/support/step_definitions/OrganizationProjectsTest/OrganizationProjectsTest.ts
> Fix: organization help and project tests

- apps/gauzy/src/app/pages/users/edit-user-mutation/edit-user-mutation.component.html
- apps/gauzy/src/app/pages/users/edit-user-mutation/edit-user-mutation.component.ts
> fix: add disable for button

- apps/gauzy/src/app/pages/users/edit-user-mutation/edit-user-mutation.component.html
- apps/gauzy/src/assets/i18n/en.json
> fix: add tooltip for user page

- .deploy/api/Dockerfile
> fix: some more Alpine related fixes

- .deploy/api/Dockerfile
> fix: ooopppsss

- apps/gauzy/src/app/pages/invoices/invoices.component.ts
> fix: hide popup settings

- .deploy/k8s/k8s-manifest.prod.yaml
- .github/workflows/deploy-do.yml
> fix: deployment to production

- apps/gauzy-e2e/src/support/Base/pagedata/GoalsKPIPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/GoalsKPIPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/GoalsKPI.po.ts
- apps/gauzy-e2e/src/support/step_definitions/GoalsSettingsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/GoalsSettingsTest/GoalsGeneralSettingsTest.ts
> fix: goals settings test

- apps/gauzy/src/app/@shared/image-uploader/image-uploader.component.ts
- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.html
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts
> Fix/#3846 User & Employee Avatar 

- packages/core/package.json
- yarn.lock
> fix: sh..t happens even for the best :)))

- apps/gauzy-e2e/src/support/Base/pagedata/ContactsLeadsPageData.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ContactsLeadsPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/ManageUserInvitesPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/ContactsLeads.po.ts
- apps/gauzy-e2e/src/support/Base/pages/ManageUserInvites.po.ts
- apps/gauzy-e2e/src/support/step_definitions/ContactsLeadsTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ContactsLeadsTest/ContactsLeadsTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest/ManageCandidatesInvitesTest.ts
- apps/gauzy-e2e/src/support/step_definitions/ManageUserInvitesTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ManageUserInvitesTest/ManageUserInvitesTest.ts
> Fix: gauzy e2e tests

- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/header.component.scss
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/pages/pages.component.ts
> Feat: header box for demo

- packages/core/src/feature/feature.seed.ts
- packages/core/src/organization-employment-type/organization-employment-type.seed.ts
- packages/core/src/warehouse/warehouse.seed.ts
> Fix/Seed Sqlite Await/Async Issue

- apps/gauzy-e2e/src/support/Base/pageobjects/ApprovalRequestPageObject.ts
- apps/gauzy-e2e/src/support/Base/pages/ApprovalRequest.po.ts
- apps/gauzy-e2e/src/support/Base/utils/util.ts
- apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest.feature
- apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest/ApprovalRequestTest.ts
> fix: approval request test

- apps/gauzy/src/app/auth/auth.module.ts
- apps/gauzy/src/app/auth/login/login.component.html
- apps/gauzy/src/app/auth/login/login.component.scss
---
Video: https://www.loom.com/share/85e91172d7e24ed3940180a28a8d3f76
> fix: update login page, new style, mobile responsive

- apps/gauzy/src/app/auth/login/login.component.html
- apps/gauzy/src/app/auth/login/login.component.scss
> fix: update login style for demo

- packages/contracts/src/role.model.ts
- packages/core/src/role/dto/create-role.dto.ts
- packages/core/src/role/dto/index.ts
- packages/core/src/role/role.controller.ts
- packages/core/src/shared/decorators/validations/index.ts
- packages/core/src/shared/decorators/validations/is-role-already.decorator.ts
> Feat/#3479 Role class create/update and duplicate validators

- apps/gauzy/src/app/@core/services/invoice-item.service.ts
- apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
- apps/gauzy/src/app/pages/approvals/approvals.component.ts
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.ts
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.ts
- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
- apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
- apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
- apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/variant-table/variant-table.component.ts
- apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
- packages/core/src/invoice-item/invoice-item.controller.ts
> Fix/Permissions & deprecated code fixes

- apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories.component.ts
- apps/gauzy/src/app/pages/inventory/components/table-components/image-row.component.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix/Time tracking divided by zero & product default SVG image

- apps/gauzy/src/app/@core/services/employee-store.service.ts
- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.ts
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
- apps/gauzy/src/app/pages/employees/employees.component.ts
- packages/contracts/src/employee.model.ts
- packages/core/src/employee/commands/handlers/employee.bulk.create.handler.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/employee/employee.service.ts
- packages/core/src/user-organization/user-organization.services.ts
> Fix/Employee bulk create async/await transactions sqlite issue

- apps/gauzy/src/app/pages/pages.component.scss
> fix: table filters in dark/cosmic mode

- apps/desktop-timer/src/index.ts
- apps/desktop/src/index.ts
- apps/server/src/index.ts
- packages/desktop-libs/src/lib/desktop-menu.ts
- packages/desktop-libs/src/lib/desktop-store.ts
- packages/desktop-libs/src/lib/desktop-tray.ts
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/custom-render-cell.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> fix: desktop timer different user name after logout

- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
- apps/gauzy/src/app/pages/settings/roles-permissions/roles-permissions.component.html
- apps/gauzy/src/app/pages/settings/roles-permissions/roles-permissions.component.ts
- packages/contracts/src/role-permission.model.ts
- packages/contracts/src/role.model.ts
- packages/contracts/src/user.model.ts
- packages/core/src/role-permission/dto/create-role-permission.dto.ts
- packages/core/src/role-permission/dto/index.ts
- packages/core/src/role-permission/dto/update-role-permission.dto.ts
- packages/core/src/role-permission/role-permission.controller.ts
- packages/core/src/role-permission/role-permission.service.ts
- packages/core/src/role/dto/index.ts
- packages/core/src/role/role.controller.ts
- packages/core/src/role/role.entity.ts
- packages/core/src/shared/decorators/validations/index.ts
- packages/core/src/shared/decorators/validations/is-role-already-exist.decorator.ts
- packages/core/src/shared/decorators/validations/is-role-should-exist.decorator.ts
- packages/core/src/user/dto/index.ts
- packages/core/src/user/dto/update-preferred-component-layout.dto.ts
- packages/core/src/user/dto/update-preferred-language.dto.ts
- packages/core/src/user/user.controller.ts
- packages/core/src/user/user.entity.ts
> Fix/Role Permissions DTO

- apps/gauzy/src/app/pages/settings/settings.module.ts
- packages/core/src/user/dto/create-user.dto.ts
- packages/core/src/user/dto/login-user.dto.ts
> Fix/Sms Gateway & String Triming

- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.html
- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.ts
- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.html
- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.ts
- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
- apps/gauzy/src/app/@shared/user/forms/user-forms.module.ts
- apps/gauzy/src/app/@shared/user/user-mutation/user-mutation.component.html
- apps/gauzy/src/app/@shared/user/user-mutation/user-mutation.component.ts
- packages/core/src/employee/commands/handlers/employee.create.handler.ts
> Fix/User page create candidate/employee as well

- apps/desktop-timer/src/index.ts
- apps/desktop/src/index.ts
- packages/desktop-libs/src/lib/desktop-database-migration.ts
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-timer-activity.ts
- tools/build/webpack.config.js
> fix: desktop timer knex timeout on collect activities from activitywatch

- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.scss
> fix: daily grid background color

- apps/gauzy-e2e/src/support/Base/pagedata/AddUserPageData.ts
- apps/gauzy-e2e/src/support/Base/pages/TimeOff.po.ts
- apps/gauzy-e2e/src/support/step_definitions/TimeOffTest.feature
- apps/gauzy-e2e/src/support/step_definitions/TimeOffTest/TimeOffTest.ts
> fix: add user and time off tests

- apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.html
- apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.ts
- apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.html
- apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.ts
- apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts
- apps/gauzy/src/app/pages/approval-policy/approval-policy.component.html
- apps/gauzy/src/app/pages/approval-policy/approval-policy.component.ts
---
VIDEO: 
https://www.loom.com/share/c0d27e60936e4759bcac38d8859b1d1d
> fix: approval request/policy duplicate when click faster

- packages/core/src/core/file-storage/providers/local.provider.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-delete.handler.ts
- packages/core/src/time-tracking/time-log/dto/delete-time-log.dto.ts
- packages/core/src/time-tracking/time-log/dto/index.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-range-delete.handler.ts
- packages/core/src/time-tracking/time-slot/time-slot.subscriber.ts
- packages/core/src/time-tracking/timesheet/commands/handlers/timesheet-recalculate.handler.ts
> Fix/Time Log Delete Permissions

- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
- packages/core/src/time-tracking/statistic/statistic.controller.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-log/commands/handlers/delete-time-span.handler.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-range-delete.handler.ts
- packages/core/src/time-tracking/time-slot/dto/delete-time-slot.dto.ts
- packages/core/src/time-tracking/time-slot/dto/index.ts
- packages/core/src/time-tracking/time-slot/time-slot.controller.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
> Fix/Displayed screenshot first  instead of no screenshots available for overlapping screenshots

- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal/view-time-log-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal/view-time-log-modal.component.scss
> Fix/View  time log overflow wrap for description & reason

- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-store.ts
- packages/desktop-libs/src/lib/desktop-timer.ts
- packages/desktop-ui-lib/src/lib/screen-capture/screen-capture.component.scss
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-window/src/lib/desktop-window-timer.ts
> fix: desktop timer smaller device display issue

- apps/gauzy/src/app/@core/services/auth.service.ts
- apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.ts
- apps/gauzy/src/app/@shared/invite/invite-mutation/invite-mutation.component.html
- apps/gauzy/src/app/@shared/invite/invite-mutation/invite-mutation.component.ts
- apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.ts
- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
- apps/gauzy/src/app/@shared/user/user-mutation/user-mutation.component.html
- apps/gauzy/src/app/@shared/user/user-mutation/user-mutation.component.ts
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.scss
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-data/edit-user-data.component.ts
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-profile.component.ts
- apps/gauzy/src/app/pages/users/users.component.ts
- packages/core/src/auth/auth.controller.ts
- packages/core/src/auth/auth.service.ts
> Fix/#3942 Invite expiration status & invitation roles only

- apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.ts
- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html
- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
- apps/gauzy/src/app/pages/contacts/contact.component.html
- apps/gauzy/src/app/pages/contacts/contact.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html
- apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.html
- apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
- apps/gauzy/src/app/pages/invoices/table-components/invoice-employees-selector.component.ts
> Fix/#3939 Removed deleted employees from dropdown selections

- apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.component.html
- apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.component.ts
- apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.module.ts
- packages/contracts/src/equipment-sharing.model.ts
> Fix/#3939 Equipment employee selection

- apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.html
- apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.ts
- apps/gauzy/src/app/pages/contacts/contact.component.html
- apps/gauzy/src/app/pages/departments/departments-mutation/departments-mutation.component.html
- apps/gauzy/src/app/pages/departments/departments-mutation/departments-mutation.component.ts
- apps/gauzy/src/app/pages/departments/departments.component.html
- apps/gauzy/src/app/pages/departments/departments.component.ts
> Fix/Department employee selection list & member card fixes

- apps/gauzy/src/app/@shared/components/date-range-title/date-range-title.component.ts
- apps/gauzy/src/app/@shared/components/date-range-title/date-range-title.module.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.html
- apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report.module.ts
- apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.html
- apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report.module.ts
- apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.html
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report.module.ts
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report.module.ts
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.html
- apps/gauzy/src/app/pages/reports/payment-report/payment-report.module.ts
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.html
- apps/gauzy/src/app/pages/reports/time-reports/time-reports.module.ts
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.html
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports.module.ts
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.html
- packages/core/src/time-tracking/activity/activity.map.service.ts
- packages/core/src/time-tracking/activity/activity.service.ts
> Fix/#3961 Rearrange statistic blocks

- packages/desktop-libs/src/lib/desktop-store.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> fix: added logger for screenshot result

- packages/config/src/environments/environment.prod.ts
- packages/config/src/environments/environment.ts
- packages/core/src/app.controller.ts
> Fix/Replace API & CLIENT base local/production environment variables

- apps/desktop-timer/src/app/app.component.ts
- apps/desktop-timer/src/index.ts
- apps/desktop-timer/src/package.json
- apps/desktop/src/app/app.component.ts
- apps/desktop/src/package.json
- packages/desktop-libs/package.json
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-notifier.ts
- packages/desktop-libs/src/lib/desktop-screenshot.ts
- packages/desktop-libs/src/lib/desktop-timer.ts
- packages/desktop-ui-lib/src/lib/screen-capture/screen-capture.component.html
- packages/desktop-ui-lib/src/lib/screen-capture/screen-capture.component.scss
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> Fix/3938 desktop timer don't make screenshot

- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.module.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal/view-time-log-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal/view-time-log-modal.component.scss
- apps/gauzy/src/assets/i18n/en.json
> Fix/Added warning message for edit/delete button disabled, if timer is runnig state

- packages/contracts/src/candidate.model.ts
- packages/contracts/src/employee.model.ts
- packages/core/src/app.controller.ts
- packages/core/src/candidate/candidate.entity.ts
- packages/core/src/database/migrations/1642411409517-AlterCandidateEmployeeTable.ts
- packages/core/src/employee/employee.entity.ts
---
- Candidate and Employee one to one relationship migration.
- Fixed numeric to integer column type for `billRateValue` column.
> Feature/#3979 Migrations & Interface changes

- apps/gauzy/src/app/@core/services/candidates.service.ts
- apps/gauzy/src/app/@shared/candidate/candidate-interview-feedback/candidate-interview-feedback.component.ts
- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.ts
- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
- apps/gauzy/src/app/pages/candidates/candidates.component.html
- apps/gauzy/src/app/pages/candidates/candidates.component.scss
- apps/gauzy/src/app/pages/candidates/candidates.component.ts
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.ts
- apps/gauzy/src/app/pages/candidates/table-components/candidate-status/candidate-status.component.scss
- apps/gauzy/src/app/pages/candidates/table-components/index.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/candidate.model.ts
- packages/core/src/candidate-feedbacks/candidate-feedbacks.entity.ts
- packages/core/src/candidate-feedbacks/candidate-feedbacks.seed.ts
- packages/core/src/candidate/candidate.controller.ts
- packages/core/src/candidate/candidate.entity.ts
- packages/core/src/candidate/candidate.module.ts
- packages/core/src/candidate/candidate.subscriber.ts
- packages/core/src/candidate/commands/candidate.hired.command.ts
- packages/core/src/candidate/commands/candidate.rejected.command.ts
- packages/core/src/candidate/commands/handlers/candidate.hired.handler.ts
- packages/core/src/candidate/commands/handlers/candidate.rejected.handler.ts
- packages/core/src/candidate/commands/handlers/index.ts
- packages/core/src/candidate/commands/index.ts
---
We have created commands to migrate "CANDIDATE" user to "EMPLOYEE" user. Please check below short video.
https://www.loom.com/share/80976deb051d40739fd80db732947116
> Feat/#3979 Migrate candidate to employee user

- packages/core/src/time-tracking/statistic/dto/index.ts
- packages/core/src/time-tracking/statistic/dto/statistic-counts.dto.ts
- packages/core/src/time-tracking/statistic/statistic.controller.ts
> Fix/#3961 Statistic counts DTO validation (Time Tracking Dashboard)

- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.ts
Fixed Edit current user email bug
Fix #3937
> Fix/#3937 Edit User Profile (fixed email edit)

- package.json
> Feat/Added command to run core package API from root folder

- apps/gauzy-e2e/src/support/Base/pageobjects/TimeTrackingForClientPageObject.ts
- apps/gauzy-e2e/src/support/Base/pageobjects/TimeTrackingPageObject.ts
> fix: some tests css selectors

- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
> fix: Remaining column width for client budget table

- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.html
- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.ts
- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.module.ts
> Fix/#4018 Candidate modal & removed unused import

- packages/core/src/tenant/tenant.controller.ts
> Fix/#3479 Tenant Swagger Docs Update

- packages/core/src/employee/dto/create-employee.dto.ts
- packages/core/src/employee/dto/employee-input.dto.ts
- packages/core/src/employee/dto/update-employee.dto.ts
- packages/core/src/employee/dto/user-input-dto.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/employee/pipes/employee-transformer.pipe.ts
Added validations for mutation endpoints (post, put)
> Feat / Implemented data dto validations for employee endpoints 

- packages/core/src/employee/dto/create-employee.dto.ts
- packages/core/src/employee/dto/employee-input.dto.ts
- packages/core/src/employee/dto/index.ts
- packages/core/src/employee/dto/rates.dto.ts
- packages/core/src/employee/dto/update-employee.dto.ts
- packages/core/src/employee/dto/update-profile.dto.ts
- packages/core/src/employee/dto/user-input-dto.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/user/dto/create-user.dto.ts
> Fix/Employee update and other DTO related fixes

- packages/core/src/user/dto/create-user.dto.ts
- packages/core/src/user/dto/index.ts
- packages/core/src/user/dto/register-user.dto.ts
- packages/core/src/user/dto/update-user.dto.ts
- packages/core/src/user/user.controller.ts
> Feat / Improved data dto validations for user endpoints

- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
- apps/gauzy/src/app/@shared/user/forms/fields/password/password.component.html
- apps/gauzy/src/app/@shared/user/forms/fields/password/password.component.ts
---
You can see the [demo](https://www.loom.com/share/fc52076a694d491a8874f4a3652a84c4)
> Fix:/Autofill password field

- apps/gauzy/src/app/@core/validators/match.validator.ts
- apps/gauzy/src/app/@shared/user/forms/fields/password/password.component.html
- apps/gauzy/src/app/@shared/user/forms/fields/password/password.component.ts
> Fix/#3937 Autofill password field auto match validator

- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/core/src/time-tracking/time-log/commands/handlers/delete-time-span.handler.ts
> Fix/#3977 Screenshot Split & Remove Entries

- packages/core/src/email/dto/index.ts
- packages/core/src/email/dto/update-email.dto.ts
- packages/core/src/email/email.controller.ts
I implemented dto validations for updating an email
> Feat / Implemented dto validation for updating email

- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.scss
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-log/commands/handlers/delete-time-span.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/delete-time-slot.handler.ts
---
https://www.loom.com/share/175d627f1a6341fa87855cc7a1c7b83e
> Fix/#3977 Multiple screenshot removed functionality

- apps/gauzy/src/app/@shared/expenses/recurring-expense-block/recurring-expense-block.component.html
- apps/gauzy/src/app/@shared/expenses/recurring-expense-block/recurring-expense-block.component.scss
- apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.html
- apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.scss
---
https://www.loom.com/share/2b6d37a3617a4cae850d5adf73cc523b)
> Bug/ Resolve recurring expenses table records issue #3740

- apps/gauzy/src/app/@core/services/invite.service.ts
- apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
- packages/contracts/src/invite.model.ts
- packages/core/src/invite/commands/handlers/invite.bulk.create.handler.ts
- packages/core/src/invite/commands/handlers/invite.resend.handler.ts
- packages/core/src/invite/commands/invite.resend.command.ts
- packages/core/src/invite/invite.controller.ts
- packages/core/src/invite/invite.service.ts
> #3975 fix email resend

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-language-selector.component.scss
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.scss
---
https://www.loom.com/share/ea6ffc9fc23f43f2b5b2141ff2416987
> fix: theme side bar selectors width

- apps/gauzy/src/app/@shared/image-asset/image-asset.component.html
- apps/gauzy/src/app/pages/inventory/components/table-components/item-img-tags-row.component.ts
- apps/gauzy/src/app/pages/inventory/components/table-inventory-items/table-inventory.component.html
- apps/gauzy/src/assets/images/others/no-image-placeholder.svg
---
I update a broken link with a new one.
> fix: change source for no image file

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- apps/gauzy/src/assets/i18n/en.json
---
Issue: #3964 
Video: https://www.loom.com/share/d83d8e719ec343ea90412e13977d8fe2
> Feat: "View all" button for screenshot block in time tracking

- packages/core/src/organization/dto/update-organization.dto.ts
---
Organization update validation was broken.
> Urgent fix for update organization DTOs

- apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
- apps/gauzy/src/app/auth/login/login.component.ts
- package.json
> Fix/#4049 Cookie password field security issue

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
> Fix/#3964 button size & typo error (Time Tracking Dashboard)

- apps/gauzy/src/app/@shared/time-off/time-off-holiday-mutation/time-off-holiday-mutation.component.ts
- apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts
- apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.ts
---
@rahul-rathore-576
If there is others pages i left, please mention it @dokata99
> Fix/ Proposals timezone problem

- packages/contracts/src/role-permission.model.ts
- packages/core/src/database/migrations/1643807301083-AlterRolePermissionTable.ts
- packages/core/src/database/migrations/1643809486960-MigrateEmailTemplatesData.ts
- packages/core/src/role-permission/role-permission.entity.ts
- packages/core/src/role-permission/role-permission.service.ts
> Fix/#3976 Email templates & Role Permission migration

- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.html
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.scss
- apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.scss
- apps/gauzy/src/app/pages/email-templates/email-templates.component.html
- apps/gauzy/src/app/pages/email-templates/email-templates.component.scss
- apps/gauzy/src/app/pages/settings/email-history/email-history.component.html
- apps/gauzy/src/app/pages/settings/email-history/email-history.component.scss
> Fix/Language UI translate issue

- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.html
- apps/gauzy/src/app/pages/employees/activity/time-and-activities/time-and-activities/time-and-activities.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
- packages/core/src/time-tracking/activity/activity.service.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-client.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-date.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-employee.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-project.handler.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
> Fix/Time & Activities & Screenshots Pages

- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.html
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.scss
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
> Fix/Web timer theme (dark/cosmic)

- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.html
---
To finish this task, i applied matrix transform in order to set stored position.
Take a look on [demo](https://www.loom.com/share/2a1be2a6d7a446a1a2802442d2872855)
> Feature/ Remember timer position

- apps/desktop-timer/src/app/app.component.ts
- apps/desktop-timer/src/index.ts
- packages/desktop-libs/src/lib/desktop-database-migration.ts
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-screenshot.ts
- packages/desktop-libs/src/lib/desktop-timer.ts
- packages/desktop-ui-lib/src/lib/screen-capture/screen-capture.component.html
- packages/desktop-ui-lib/src/lib/screen-capture/screen-capture.component.scss
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> fix: bug sqlite busy and database is locked

- packages/core/src/feature/dto/create-feature-toggle.dto.ts
- packages/core/src/feature/dto/index.ts
- packages/core/src/feature/feature-toggle.controller.ts
---
Implemented dto validations for feature - toggle
> Feat / Implemented feature-toggle dto validations

- packages/core/src/core/dto/tenant-base.dto.ts
- packages/core/src/core/dto/tenant-organization-base.dto.ts
- packages/core/src/feature/dto/create-feature-toggle.dto.ts
---
Make organization DTO optional.
> Feat/#3479 Class validator feature toggle

- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/arrow/strategies/arrow-strategy.interface.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/arrow/strategies/concrete/index.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/arrow/strategies/concrete/next.strategy.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/arrow/strategies/concrete/previous.strategy.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.component.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.module.ts
- apps/gauzy/src/app/app.module.ts
- apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report.module.ts
- apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report.module.ts
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report.module.ts
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report.module.ts
- apps/gauzy/src/app/pages/reports/manual-time/manual-time.module.ts
- apps/gauzy/src/app/pages/reports/payment-report/payment-report.module.ts
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report.module.ts
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report.module.ts
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.html
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports.module.ts
- yarn.lock
> Feat/#4092 Updated yarn & more indentation code structure 

- packages/core/src/expense/dto/create-expense.dto.ts
- packages/core/src/expense/dto/expense.dto.ts
- packages/core/src/expense/dto/index.ts
- packages/core/src/expense/dto/update-expense.dto.ts
- packages/core/src/expense/expense.controller.ts
---
Implemented dto validation for creating new and updating existing expense
> Feature/ Implemented dto validation for expense

- apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
- apps/gauzy/src/app/pages/approval-policy/approval-policy.component.ts
- apps/gauzy/src/app/pages/approvals/approvals.component.ts
- apps/gauzy/src/app/pages/candidates/candidates.component.ts
- apps/gauzy/src/app/pages/employees/employees.component.ts
- apps/gauzy/src/app/pages/equipment-sharing-policy/equipment-sharing-policy.component.ts
- apps/gauzy/src/app/pages/equipment-sharing/equipment-sharing.component.ts
- apps/gauzy/src/app/pages/equipment/equipment.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories.component.ts
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts
- apps/gauzy/src/app/pages/tags/tags.component.ts
> #4109 fix close cancel refresh

- packages/core/src/role-permission/role-permission.seed.ts
> Fixed :: Migration Exception

- packages/core/src/payment/dto/create-payment.dto.ts
- packages/core/src/payment/dto/index.ts
- packages/core/src/payment/dto/payment.dto.ts
- packages/core/src/payment/dto/update-payment.dto.ts
- packages/core/src/payment/payment.controller.ts
---
Implemented and enabled dto validation for creating new and updating existed payment
> Feature / Implemented dto validation for payments

- packages/core/src/goal/dto/create-goal.dto.ts
- packages/core/src/goal/dto/goal.dto.ts
- packages/core/src/goal/dto/index.ts
- packages/core/src/goal/dto/update-goal.dto.ts
- packages/core/src/goal/goal.controller.ts
---
Implemented and enabled dto validation for creating new and updating existed goal
> Feature / Implemented dto validation for goal

- packages/core/src/goal-general-setting/dto/create-goal-general-setting.dto.ts
- packages/core/src/goal-general-setting/dto/goal-general-setting.dto.ts
- packages/core/src/goal-general-setting/dto/index.ts
- packages/core/src/goal-general-setting/dto/update-goal-general-setting.dto.ts
- packages/core/src/goal-general-setting/goal-general-setting.controller.ts
---
I implemented dto validations for creating new or updating existed goal general setting
> Feature / Implemented dto validation for goal general setting

- packages/core/src/keyresult/dto/create-keyresult.dto.ts
- packages/core/src/keyresult/dto/index.ts
- packages/core/src/keyresult/dto/keyresult-bulk-input.dto.ts
- packages/core/src/keyresult/dto/keyresult.dto.ts
- packages/core/src/keyresult/dto/update-keyresult.dto.ts
- packages/core/src/keyresult/keyresult.controller.ts
---
Implemented and enabled dto validations for bulk, creating new and updating existed keyresult
> Feature / Implemented dto validitions for keyresult

- packages/core/src/proposal/dto/create-proposal.dto.ts
- packages/core/src/proposal/dto/index.ts
- packages/core/src/proposal/dto/proposal.dto.ts
- packages/core/src/proposal/dto/update-proposal.dto.ts
- packages/core/src/proposal/proposal.controller.ts
---
Implemented dto validation for creating new and updating existed proposal.
> Feature / Implemented dto validation for proposal routes

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
- packages/core/src/database/migrations/1644491785525-AdjustTimeLogStopDate.ts
- packages/core/src/time-tracking/statistic/statistic.controller.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
> Fix/#4120 Time Tracking Adjust Old Entires

- apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
- apps/gauzy/src/app/app.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view-routing.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view.resolver.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.ts
> Fix/Timesheet View (Cannot read properties of undefined)

- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.component.html
- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.component.ts
---
Take a look on [demo](https://www.loom.com/share/4a4ff2ead28e494db6df57569e116b5e)
> Feat/ Disallow switching to future periods in reports

- packages/core/src/organization-team/dto/create-organization-team.dto.ts
- packages/core/src/organization-team/dto/index.ts
- packages/core/src/organization-team/dto/organization-team.dto.ts
- packages/core/src/organization-team/dto/update-organization-team.dto.ts
- packages/core/src/organization-team/organization-team.controller.ts
---
I implemented and enabled dto validation for creating and updating organization team routes
Here you can get the [Test Video : https://www.loom.com/share/f7d540d436804e9bb0654538a2156ad0](https://www.loom.com/share/f7d540d436804e9bb0654538a2156ad0)
> Feature / Implemented dto validations for organization team

- apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.scss
- apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.scss
- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.scss
- apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.scss
- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.scss
- apps/gauzy/src/app/@theme/styles/report.scss
- apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.html
- apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.scss
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.scss
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.scss
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.scss
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.scss
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.scss
- packages/core/src/core/seeds/data/default-accounting-templates/estimate/bg/estimate.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/estimate/en/estimate.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/estimate/he/estimate.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/estimate/ru/estimate.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/invoice/bg/invoice.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/invoice/en/invoice.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/invoice/he/invoice.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/invoice/ru/invoice.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/receipt/bg/receipt.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/receipt/en/receipt.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/receipt/he/receipt.mjml
- packages/core/src/core/seeds/data/default-accounting-templates/receipt/ru/receipt.mjml
> Fix/ Dark theme should work fine

- apps/desktop-timer/src/index.ts
- apps/desktop/src/index.ts
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-tray.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> Fix/gauzy desktop timer doesn't start

- packages/core/src/invoice-item/dto/index.ts
- packages/core/src/invoice-item/dto/invoice-item-bulk-input.dto.ts
- packages/core/src/invoice-item/invoice-item.controller.ts
---
Implemented dto validations for creating new invoice items (bulk)
> Feature / Implemented dto validations for invoice items

- packages/core/src/invoice/dto/invoice.dto.ts
---
Improved dto validation for creating new invoice. Made at least one of fromOrganization and fromOrganizationId required in the request.
Take a look for a quick [demo](https://www.loom.com/share/10aa02d41d314e04aaef580931267458)
> Feature / Improved dto validations for invoice

- apps/gauzy/src/app/pages/goals/edit-objective/edit-objective.component.html
- apps/gauzy/src/app/pages/goals/edit-objective/edit-objective.component.ts
---
Fixed goal required when creating a new Goal.
Watch For a quick [demo](https://www.loom.com/share/2ed59f2eaeb845cc8a7759a6d610f878)
Fix #4123
> Bug / Fixed name required for Goal creation

- apps/gauzy/src/app/@shared/goal/goal-level-select/goal-level-select.component.html
- apps/gauzy/src/app/@shared/goal/goal-level-select/goal-level-select.component.ts
- apps/gauzy/src/app/@shared/goal/goal-level-select/goal-level-select.module.ts
- apps/gauzy/src/app/@shared/goal/goal-template-select/goal-template-select.component.html
- apps/gauzy/src/app/@shared/goal/goal-template-select/goal-template-select.component.ts
- apps/gauzy/src/app/pages/goals/edit-objective/edit-objective.component.html
- apps/gauzy/src/app/pages/goals/edit-objective/edit-objective.component.ts
- packages/core/src/goal/dto/goal.dto.ts
> Fix/Goal Objective Create Issue

- apps/gauzy/src/app/@core/services/keyresult-update.service.ts
- packages/contracts/src/goals.model.ts
- packages/core/src/keyresult-update/dto/create-keyresult-update.dto.ts
- packages/core/src/keyresult-update/dto/index.ts
- packages/core/src/keyresult-update/dto/keyresult-update.dto.ts
- packages/core/src/keyresult-update/dto/update-keyresult-update.dto.ts
- packages/core/src/keyresult-update/keyresult-update.controller.ts
- packages/core/src/keyresult-update/keyresult-update.entity.ts
---
Implemented dto validations for creating and updating keyresult update
> NOT MERGE YET : Feature / Implemented dto validation for keyresult update

- apps/gauzy/src/app/@core/services/invoices.service.ts
- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
- packages/core/src/invoice/dto/index.ts
- packages/core/src/invoice/dto/update-estimate-invoice.dto.ts
- packages/core/src/invoice/invoice.controller.ts
---
I have created new endpoint to accept and reject estimates and called this endpoint from the endpoints
Fix #4168
> Bug / Created and Implemented new endpoint to Accept and Reject Estimates

- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/arrow/strategies/concrete/future.strategy.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/arrow/strategies/concrete/index.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.module.ts
- packages/contracts/src/timesheet-statistics.model.ts
---
For this task, i have replaced the old DateRangePicker with the new GauzyDateRangePicker.
> Feat/Improve date range selector (Time Tracking Dashboard)

- packages/core/src/payment/dto/payment.dto.ts
---
I have modified the payment dto validator class to make a payment method to be a valid enum value
Fix #4176
> Bug / Made payment method to be a valid enum value

- packages/contracts/src/payment.model.ts
- packages/core/src/core/dto/tenant-organization-base.dto.ts
- packages/core/src/database/migrations/1645012749640-AlterPaymentTable.ts
- packages/core/src/payment/dto/create-payment.dto.ts
- packages/core/src/payment/dto/payment.dto.ts
- packages/core/src/payment/dto/update-payment.dto.ts
- packages/core/src/payment/payment.entity.ts
- packages/core/src/payment/payment.seed.ts
> Fix/Payment migration & DTOs fixes

- apps/gauzy/src/app/@shared/employee/employee-location/employee-location.component.ts
- apps/gauzy/src/app/@shared/employee/employee-rates/employee-rates.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-employment/edit-employee-employment.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-hiring/edit-employee-hiring.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-networks/edit-employee-networks.component.ts
- apps/gauzy/src/app/pages/settings/roles-permissions/roles-permissions.component.html
- apps/gauzy/src/app/pages/settings/roles-permissions/roles-permissions.component.scss
- apps/gauzy/src/app/pages/settings/roles-permissions/roles-permissions.component.ts
- packages/core/src/candidate/dto/create-candidate.dto.ts
- packages/core/src/employee/dto/create-employee.dto.ts
- packages/core/src/employee/dto/employment.dto.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/organization/dto/create-organization.dto.ts
- packages/core/src/organization/dto/organization-bonus.dto.ts
- packages/core/src/organization/dto/organization-setting.dto.ts
- packages/core/src/organization/dto/update-organization.dto.ts
- packages/core/src/role-permission/role-permission.service.ts
- packages/core/src/tenant/tenant.controller.ts
> Fix/#4182 Cloud Business Management Solution

- apps/gauzy/src/app/pages/invoices/invoices.component.ts
- apps/gauzy/src/app/pages/settings/email-history/email-history.component.ts
- packages/core/src/email/dto/update-email.dto.ts
---
New validation require email of selected email object.
[demo](https://www.loom.com/share/f7ede751fe5b42dda54131b2f8089940)
> Fix/ Archived email history

- packages/contracts/src/organization-positions.model.ts
- packages/core/src/organization-position/dto/create-organization-position.dto.ts
- packages/core/src/organization-position/dto/index.ts
- packages/core/src/organization-position/dto/organization-position.dto.ts
- packages/core/src/organization-position/dto/update-organization-position.dto.ts
- packages/core/src/organization-position/organization-position.controller.ts
- packages/core/src/organization-position/organization-position.entity.ts
---
Implemented and enabled dto validation for updating existed organization position
> Feature / Implemented dto validations for organization position

- apps/gauzy/src/app/@core/services/invoices.service.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
- packages/core/src/invoice/dto/index.ts
- packages/core/src/invoice/dto/update-estimate-status.dto.ts
- packages/core/src/invoice/invoice.controller.ts
---
I have created new endpoint `api/invoice/${id}/status ` for updating estimate's status
Quick [demo](https://www.loom.com/share/a234e821b9b24a8ebb5b32a091b7eef7)
Fix #4189
> Bug/ Fixed estimate changing status

- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
> Fixed :: Organization update setting validation issue

- packages/core/src/database/migrations/1645179275947-AlterInvoiceTable.ts
> Fix :: Invoice migration for PostgreSQL/SQLite

- apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts
- packages/core/src/invoice/dto/update-invoice-action.dto.ts
---
I have fixed bug issue by adding additional properties into invoice action class 
Fix #4197
> Bug / Fixed payment issue

- apps/gauzy/src/app/@shared/card-grid/card-grid.component.scss
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.scss
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.scss
- apps/gauzy/src/app/@theme/styles/report.scss
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.scss
- apps/gauzy/src/app/pages/invoices/invoices.component.scss
---
Take a look on [demo](https://www.loom.com/share/13972063b56d41c884903e1f2b799f63)
> fix screenshot dark theme issue

- packages/core/src/invoice/dto/invoice.dto.ts
> Fix:: #4203 extends more invoice/estimate enum status type

- apps/gauzy/src/app/pages/income/income.component.ts
- packages/contracts/src/income.model.ts
> Fix/#4206 Income mutation DTO validation

- apps/gauzy/src/app/@shared/card-grid/card-grid.component.html
- apps/gauzy/src/app/@shared/card-grid/card-grid.component.scss
- apps/gauzy/src/app/@shared/card-grid/card-grid.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.html
---
Quick [demo](https://www.loom.com/share/c84b0dddea2546debc5037720b5cf6c5)
> Bug/ Selection of invoice or estimate

- apps/gauzy/src/app/pages/expenses/expenses.component.ts
- packages/contracts/src/expense.model.ts
---
I currently fixed the issue of updating expense but doing expense mutation dto validation
Fix #4209 
Watch for quick [demo](https://www.loom.com/share/95ffc6c38ca44ac0a8a9c2f695818c9e)
> Bug : Fixed Expense update Bug

- apps/gauzy/src/app/pages/proposals/proposal-edit/proposal-edit.component.ts
---
I have fixed edit proposal issue by adding extra fields into the body request 
Fix #4219 
Watch quick [demo](https://www.loom.com/share/c2ffeb37d9b649ccaee347f66d96b51d)
> Bug / Solved edit proposal bug

- apps/gauzy/src/app/@core/services/employees.service.ts
- apps/gauzy/src/app/pages/employees/employees.component.html
- apps/gauzy/src/app/pages/employees/employees.component.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/employee.model.ts
- packages/core/src/employee/dto/update-employee.dto.ts
---
https://loom.com/share/017ca4261da64dc2ba8270fc52dc752f
> Feat/#4213 Enabled/Disabled time tracking actions

- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts
---
Did a quick fix of edit main organization
Fix #4224
> Bug / Fix edit main organization

- apps/gauzy/src/app/@core/services/navigation-builder/navigation-builder.service.ts
- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts
- packages/core/src/time-tracking/timer/timer.service.ts
---
https://www.loom.com/share/8c44c0c033b648ba95e1f0e96b365ca7
> Fix/#4213 Enable/Disable time tracking API

- apps/gauzy/src/app/@shared/project-select/project/project.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
> Fix/#4120 Organization future allowed date range issue for today's work

- apps/gauzy/src/app/@shared/pipes/currency-position.pipe.ts
- apps/gauzy/src/app/@shared/pipes/index.ts
- apps/gauzy/src/app/@shared/pipes/replace.pipe.ts
- apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.html
- apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.html
- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.html
- apps/gauzy/src/app/@shared/table-components/income-amount/income-amount.component.ts
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.html
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.ts
- apps/gauzy/src/app/pages/dashboard/dashboard.module.ts
- apps/gauzy/src/app/pages/dashboard/human-resources/human-resources.component.html
- apps/gauzy/src/app/pages/invoices/table-components/invoice-total-value.component.ts
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.html
- packages/core/src/organization/organization.entity.ts
---
Take a look on [demo](https://www.loom.com/share/3d47045b8c0644318ce26c910b004c44)
> Fix/#4214 Currency position not working

- apps/gauzy/src/app/pages/invoices/invoices.component.html
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
---
Take a look on this [demo](https://www.loom.com/share/5aad1f37ae9e495f941ca990281208d1)
> Bug/ Button add not disabled

- packages/core/src/core/utils.ts
- packages/core/src/time-tracking/statistic/statistic.controller.ts
- packages/core/src/time-tracking/time-log/time-log.seed.ts
> Fix/Disabled Time Tracking seed for future dates

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- packages/core/src/core/utils.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix/#4120 More accurate date range selection (Time Tracking Dashboard)

- apps/gauzy/src/app/@shared/pagination/pagination.component.scss
- apps/gauzy/src/app/pages/invoices/invoices.component.scss
- apps/gauzy/src/app/pages/pages.component.scss
> Fix/ Estimate-invoice page UI

- apps/gauzy/src/app/pages/invoices/invoice-view/inner-component/invoice-view-inner.component.html
- apps/gauzy/src/app/pages/invoices/invoice-view/inner-component/invoice-view-inner.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.module.ts
> Fix/ Estimate-Invoice view download organization currency position

- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-profile.component.ts
---
I have adjusted the edit candidate request payload buy adding the organizationId
Watch for quick [demo](https://www.loom.com/share/716e76d7f20c40e79301d6ae641c2cec)
Fix #4248
> Fixed / Adjusted edit candidate request payload to new validated endpoints

- apps/gauzy/src/app/@shared/status-badge/status-badge.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.html
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view.resolver.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.html
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-update.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
- packages/core/src/time-tracking/time-slot/commands/time-slot-merge.command.ts
- packages/core/src/time-tracking/timesheet/timesheet.controller.ts
- packages/core/src/time-tracking/timesheet/timesheet.service.ts
> Fix/#4120 Timesheet Improvement

- apps/desktop/package.json
- apps/gauzy/package.json
- apps/server/package.json
- package.json
- yarn.lock
> Fix/Upgrade @angular/cdk to the @angular/material compatibility version

- packages/core/src/candidate-skill/candidate-skill.controller.ts
- packages/core/src/candidate-skill/dto/create-candidate-skill.dto.ts
- packages/core/src/candidate-skill/dto/index.ts
- packages/core/src/candidate-source/dto/create-candidate-source.dto.ts
- packages/core/src/candidate/dto/candidate-feature.dto.ts
- packages/core/src/candidate/dto/index.ts
---
Implemented dto validation for creating candidate skill
Watch For quick [demo](https://www.loom.com/share/f4a2523351d847f3bfd7cd30d633b29d)
> Feature / Implemented dto validation for candidate skill

- packages/core/src/candidate-skill/candidate-skill.module.ts
> Fix :: Missing user module for candidate skill routes permission

- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/role-permission.model.ts
> Fix/Missing permission translation & default group permission

- apps/gauzy/src/app/@shared/expenses/recurring-expense-block/recurring-expense-block.component.html
- apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.module.ts
- apps/gauzy/src/app/pages/contacts/contact-view/contact-view.component.html
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.html
- packages/core/src/time-tracking/time-log/commands/handlers/delete-time-span.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/delete-time-slot.handler.ts
> Fix/#4160 View time log info & Employee Avatar

- .deploy/api/Dockerfile
- .deploy/desktop-timer/Dockerfile.linux
- .deploy/desktop-timer/Dockerfile.win
- .deploy/desktop/Dockerfile.linux
- .deploy/desktop/Dockerfile.win
- .deploy/webapp/Dockerfile
- .github/workflows/desktop-app.yml
- .github/workflows/desktop-timer-app.yml
- .github/workflows/server.yml
> chore: update node version and install latest node-gyp

- .github/workflows/desktop-app.yml
- .github/workflows/desktop-timer-app.yml
- .github/workflows/server.yml
> fix: ops, node-gyp should be global

- .github/workflows/desktop-app.yml
- .github/workflows/desktop-timer-app.yml
- .github/workflows/server.yml
> fix: there is no sudo on Windows :)

- .github/workflows/desktop-app.yml
- .github/workflows/desktop-timer-app.yml
- .github/workflows/server.yml
> fix: setup Windows Build Tools

- .github/workflows/desktop-app.yml
- .github/workflows/desktop-timer-app.yml
- .github/workflows/server.yml
> fix: switch to Windows 2022

- .github/workflows/desktop-app.yml
- .github/workflows/desktop-timer-app.yml
- .github/workflows/server.yml
> fix: and switch temporary to Windows 2019 :)

- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/pages.component.ts
---
I have implemented recurring expense sub-menu from organization into accounting menu
Fixed #4282 
Watch for quick [demo](https://www.loom.com/share/ac53d369bd5741dfb4439a8c316928cb)
> Fixed / Duplicated recurring expense sub menu into accounting

- apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html
- apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.scss
- apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
- packages/core/src/database/migrations/1646206946845-AlterExpenseTable.ts
- packages/core/src/expense/commands/handlers/expense.update.handler.ts
- packages/core/src/expense/dto/create-expense.dto.ts
- packages/core/src/expense/dto/expense.dto.ts
- packages/core/src/expense/dto/update-expense.dto.ts
- packages/core/src/expense/expense.entity.ts
- packages/core/src/organization-vendor/dto/index.ts
- packages/core/src/organization-vendor/dto/organization-vendor-feature.dto.ts
> Fixed :: Expense Mutation & Validation

- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts
---
Take a look on [demo](https://www.loom.com/share/75e0fb6436ba4a8c8b83490a7a33d48b)
> Bug/ Loading expense categories list

- apps/gauzy/src/app/@core/services/file-storage.service.ts
- apps/gauzy/src/app/@core/services/index.ts
- apps/gauzy/src/app/pages/settings/file-storage/file-storage-routing.module.ts
- apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.html
- apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.ts
- apps/gauzy/src/app/pages/settings/file-storage/file-storage.module.ts
- apps/gauzy/src/app/pages/settings/settings-routing.module.ts
- apps/gauzy/src/app/pages/settings/settings.module.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/core/src/core/file-storage/file-storage.ts
- packages/core/src/tenant/tenant-setting/dto/aws-s3-provider-config.dto.ts
- packages/core/src/tenant/tenant-setting/dto/index.ts
- packages/core/src/tenant/tenant-setting/dto/wasabi-s3-provider-config.dto.ts
- packages/core/src/tenant/tenant-setting/tenant-setting.controller.ts
- packages/core/src/tenant/tenant-setting/tenant-setting.service.ts
> Feat/#4279 Wasabi Storage Credentials Verify Before Save

- apps/desktop-timer/src/app/app.component.ts
- apps/desktop-timer/src/app/app.module.guards.ts
- apps/desktop-timer/src/app/auth/auth.guard.ts
- apps/desktop-timer/src/app/auth/services/server-connection.service.ts
- apps/desktop-timer/src/app/server-down/server-down.page.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.module.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
time tracking is disable on desktop timer
desktop timer load view on offline mode
---
> fix: last screenshot date

- packages/core/src/core/decorators/index.ts
- packages/core/src/core/decorators/is-secret.ts
- packages/core/src/tenant/tenant-setting/commands/handlers/tenant-setting.get.handler.ts
- packages/core/src/tenant/tenant-setting/dto/aws-s3-provider-config.dto.ts
- packages/core/src/tenant/tenant-setting/dto/index.ts
- packages/core/src/tenant/tenant-setting/dto/wasabi-s3-provider-config.dto.ts
- packages/core/src/tenant/tenant-setting/tenant-setting.service.ts
> Feat :: Wrapped Secrets Keys

- apps/gauzy/src/app/@shared/regex/regex-patterns.const.ts
- apps/gauzy/src/app/@shared/smtp/smtp.component.ts
- packages/core/src/core/decorators/is-secret.ts
- packages/core/src/custom-smtp/commands/handlers/custom-smtp.create.handler.ts
- packages/core/src/custom-smtp/commands/handlers/custom-smtp.update.handler.ts
- packages/core/src/custom-smtp/custom-smtp.controller.ts
- packages/core/src/custom-smtp/custom-smtp.entity.ts
- packages/core/src/custom-smtp/custom-smtp.service.ts
- packages/core/src/custom-smtp/dto/custom-smtp.ts
- packages/core/src/custom-smtp/dto/index.ts
> Feat :: Wrapped SMTP Secrets 

- apps/gauzy/src/app/@shared/gallery/gallery.component.ts
- apps/gauzy/src/app/@shared/gallery/gallery.directive.ts
- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix :: Display employee relevant screenshots inside footer gallery

- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix/Missing distinct on query issue for SQLite

- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix/Recent Activities Query (Time Tracking Dashboard)

- yarn.lock
> Fix :: Updated yarn.lock file

- apps/gauzy/src/app/@shared/card-grid/card-grid.component.html
- apps/gauzy/src/app/@shared/card-grid/card-grid.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
- packages/contracts/src/invoice.model.ts
- packages/core/src/invoice/dto/invoice.dto.ts
- packages/core/src/invoice/dto/update-estimate-invoice.dto.ts
- packages/core/src/invoice/dto/update-invoice-action.dto.ts
- packages/core/src/invoice/invoice.controller.ts
- packages/core/src/invoice/invoice.entity.ts
- packages/core/src/invoice/invoice.seed.ts
> Fix/Invoice Estimate Sorting & Other Fixes

- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix :: Recent activities query group by fixes

- apps/gauzy/src/app/@shared/card-grid/card-grid.component.html
- apps/gauzy/src/app/@shared/pagination/pagination-filter-base.component.ts
- apps/gauzy/src/app/@shared/pagination/pagination.component.html
- apps/gauzy/src/app/@shared/pagination/pagination.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.html
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
> Fix :: Multiple Pagination API call

- apps/gauzy/src/app/pages/invoices/invoices.component.html
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
> Fix :: Invoice/Estimate Button Actions

- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> feat: added button refresh on desktop timer

- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.component.html
- apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.component.scss
- apps/gauzy/src/app/@theme/styles/_overrides.scss
- apps/gauzy/src/app/@theme/styles/themes.scss
- apps/gauzy/src/app/pages/dashboard/dashboard.component.html
- apps/gauzy/src/app/pages/dashboard/dashboard.component.scss
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
> Feat/Resize elements on dashboard/tracking 

- apps/gauzy/src/app/@core/services/store.service.ts
- apps/gauzy/src/app/@shared/card-grid/card-grid.component.scss
- apps/gauzy/src/app/@shared/components/avatar/avatar.component.scss
- apps/gauzy/src/app/@shared/pagination/pagination.component.html
- apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.ts
- apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.scss
- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/@theme/components/layout-selector/layout-selector.component.html
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.ts
- apps/gauzy/src/app/@theme/styles/_overrides.scss
- apps/gauzy/src/app/@theme/styles/site-menu.scss
- apps/gauzy/src/app/@theme/styles/themes.scss
- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.html
- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.html
- apps/gauzy/src/app/pages/invoices/invoices.component.scss
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
- apps/gauzy/src/app/pages/invoices/table-components/invoice-paid.component.ts
- packages/core/src/core/crud/pagination-params.ts
---
Take a look on [demo](https://www.loom.com/share/37972eb8951c419295d56f6202617b32)
> Fix/ Invoice/ Estimate/ Theme

- apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.module.ts
- apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-log/commands/handlers/schedule-time-log-entries.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-delete.handler.ts
- packages/core/src/time-tracking/time-log/dto/delete-time-log.dto.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
- packages/core/src/time-tracking/time-slot/dto/delete-time-slot.dto.ts
- packages/core/src/time-tracking/timer/timer.service.ts
> Fix/Time Tracking Actions

- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.html
- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.ts
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.ts
- packages/common-angular/src/utils/shared-utils.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/database/migrations/1647417832147-AlterActivityTable.ts
- packages/core/src/time-tracking/activity/activity.entity.ts
- packages/core/src/time-tracking/activity/commands/handlers/bulk-activities-save.handler.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-bulk-create.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
- packages/core/src/time-tracking/timer/timer.service.ts
- packages/desktop-libs/src/lib/desktop-timer.ts
> Fix :: Timeslot start time before get set activity for current time slot

- packages/core/src/time-tracking/activity/activity.seed.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/timesheet/timesheet.seed.ts
> Fix :: Rename Activity Seed File

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/activity/activity.seed.ts
- packages/core/src/time-tracking/time-log/commands/delete-time-span.command.ts
- packages/core/src/time-tracking/time-log/commands/handlers/delete-time-span.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-conflict-time-log.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-delete.handler.ts
- packages/core/src/time-tracking/time-log/dto/delete-time-log.dto.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
- packages/core/src/time-tracking/time-slot/commands/delete-time-slot.command.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/delete-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/index.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-bulk-delete.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-range-delete.handler.ts
- packages/core/src/time-tracking/time-slot/commands/index.ts
- packages/core/src/time-tracking/time-slot/commands/time-slot-bulk-delete.command.ts
- packages/core/src/time-tracking/time-slot/commands/time-slot-range-delete.command.ts
- packages/core/src/time-tracking/time-slot/dto/delete-time-slot.dto.ts
- packages/core/src/time-tracking/time-slot/time-slot.controller.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
- packages/core/src/time-tracking/timer/timer.service.ts
- packages/desktop-libs/src/lib/desktop-timer.ts
> Fix :: Time Logs & Slots Delete

- apps/gauzy/src/app/app-routing.module.ts
- apps/gauzy/src/app/app.module.ts
- apps/gauzy/src/app/auth/auth-routing.module.ts
- apps/gauzy/src/app/auth/auth.module.ts
- apps/gauzy/src/assets/i18n/ru.json
- packages/core/src/home/home.controller.ts
> Fix :: Auth Routes Redirection

- apps/desktop-timer/src/app/app-routing.module.ts
- apps/desktop-timer/src/app/app.module.ts
- apps/desktop-timer/src/app/auth/auth-strategy.service.ts
- packages/desktop-ui-lib/src/index.ts
- packages/desktop-ui-lib/src/lib/login/index.ts
- packages/desktop-ui-lib/src/lib/login/login.component.html
- packages/desktop-ui-lib/src/lib/login/login.component.scss
- packages/desktop-ui-lib/src/lib/login/login.component.ts
- packages/desktop-ui-lib/src/lib/login/login.module.ts
> Fix :: Desktop Timer Login Component

- apps/gauzy/src/assets/i18n/ru.json
> fix: updated ru.json

- apps/gauzy/src/app/pages/settings/roles-permissions/roles-permissions.component.ts
- packages/contracts/src/role-permission.model.ts
- packages/core/src/role-permission/dto/create-role-permission.dto.ts
- packages/core/src/role-permission/dto/update-role-permission.dto.ts
- packages/core/src/role-permission/role-permission.controller.ts
- packages/core/src/shared/decorators/validations/is-role-should-exist.decorator.ts
> Fix :: Updated role permissions mutation

- apps/gauzy/src/app/@shared/pagination/pagination-filter-base.component.ts
- apps/gauzy/src/app/pages/pipelines/pipelines.component.html
- apps/gauzy/src/app/pages/pipelines/pipelines.component.ts
- apps/gauzy/src/app/pages/pipelines/pipelines.routing.ts
- packages/core/src/pipeline/pipeline.controller.ts
> Fixed :: Sales Pipeline Permission & Routes Fixes

- apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.html
- apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.scss
- apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date/date.component.scss
- apps/gauzy/src/app/@theme/components/index.ts
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-selector/switch-theme/switch-theme.component.html
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-selector/switch-theme/switch-theme.component.scss
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-selector/switch-theme/switch-theme.component.ts
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.module.ts
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-sidebar.module.ts
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.scss
- apps/gauzy/src/app/@theme/styles/themes.scss
- apps/gauzy/src/app/auth/_reusable.scss
- apps/gauzy/src/app/auth/auth.module.ts
- apps/gauzy/src/app/auth/forgot-password/forgot-password.component.html
- apps/gauzy/src/app/auth/forgot-password/forgot-password.component.scss
- apps/gauzy/src/app/auth/login/login.component.html
- apps/gauzy/src/app/auth/login/login.component.scss
- apps/gauzy/src/app/auth/login/whats-new/whats-new.component.scss
- apps/gauzy/src/app/auth/register/register.component.html
- apps/gauzy/src/app/auth/register/register.component.scss
- apps/gauzy/src/app/auth/theme-switch/theme-switch.component.html
> Fix/#4342 theme UI

- apps/desktop-timer/src/app/auth/auth-strategy.service.ts
> Fix :: Desktop timer build failed issue

- apps/desktop-timer/src/index.ts
- apps/desktop/src/index.ts
- packages/desktop-libs/src/lib/desktop-tray.ts
> fix: tray icon double click event open main window

- apps/gauzy/src/app/@shared/workspaces/workspaces.component.html
- apps/gauzy/src/app/@shared/workspaces/workspaces.component.scss
- apps/gauzy/src/app/@shared/workspaces/workspaces.component.ts
- apps/gauzy/src/app/@shared/workspaces/workspaces.module.ts
- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/header.component.scss
- apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.html
- apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.scss
- apps/gauzy/src/app/@theme/components/user/user.component.html
- apps/gauzy/src/app/@theme/components/user/user.component.ts
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.html
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts
- apps/gauzy/src/app/@theme/styles/_overrides.scss
- apps/gauzy/src/app/@theme/theme.module.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/tenant.model.ts
- packages/core/src/core/entities/internal.ts
- packages/core/src/core/entities/subscribers.ts
- packages/core/src/core/utils.ts
- packages/core/src/database/migrations/1648899149818-AlterTenantTable.ts
- packages/core/src/organization/organization.subscriber.ts
- packages/core/src/tenant/tenant.entity.ts
- packages/core/src/tenant/tenant.subscriber.ts
> Feat/Workspace Component

- packages/plugins/changelog/package.json
- packages/plugins/changelog/src/changelog.controller.ts
- yarn.lock
> Fix :: Change log/What's new routes made public

- apps/gauzy/src/app/@theme/styles/report.scss
> fixed class

- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.scss
> Feat: Gauzy Range Picker UI

- apps/gauzy/src/app/@core/services/employee-recurring-expense.service.ts
- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/index.ts
- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html
- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts
- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense.setting.ts
- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.html
- apps/gauzy/src/app/pages/expense-recurring/expense-recurring.component.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.html
- apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.ts
- apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.module.ts
- packages/contracts/src/employee-recurring-expense.model.ts
> Fix :: Employee/Organization recurring expense mutation fixes

- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
> Fix :: Date range picker locale config as per organization

- apps/gauzy/src/app/@shared/components/date-range-title/date-range-title.component.ts
- apps/gauzy/src/app/@shared/components/date-range-title/index.ts
- apps/gauzy/src/app/@shared/pipes/date-format.pipe.ts
- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.html
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.module.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/payments/payments.module.ts
- apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.html
- apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.html
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.html
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.html
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.html
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.html
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.html
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.html
> Fix :: Date Range Picker Minor Fixes

- apps/gauzy/src/app/@shared/directives/autocomplete-off.directive.ts
> Fix :: Prevent cannot read property (querySelectorAll) issue

- apps/gauzy/src/app/@shared/report/report-base/report-base.component.ts
- apps/gauzy/src/app/@shared/table-filters/index.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.setting.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/index.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
- apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.ts
- apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.ts
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.ts
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.ts
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.ts
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.ts
- packages/core/src/invoice/invoice.service.ts
> Fix :: Invoice/Estimates Using Date Range Picker

- apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.ts
- apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.ts
- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.ts
- apps/gauzy/src/app/@shared/report/daily-statistics/daily-statistics/daily-statistics.component.ts
- apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.ts
- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/base-selector-filter/base-selector-filter.component.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.ts
- apps/gauzy/src/app/pages/employees/activity/activity-routing.module.ts
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity.module.ts
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot.module.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
- apps/gauzy/src/app/pages/employees/activity/time-and-activities/time-and-activities.module.ts
- apps/gauzy/src/app/pages/employees/activity/time-and-activities/time-and-activities/time-and-activities.component.html
- apps/gauzy/src/app/pages/employees/activity/time-and-activities/time-and-activities/time-and-activities.component.ts
- apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.ts
- apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.ts
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.ts
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.ts
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.ts
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.ts
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.ts
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.ts
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.ts
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.ts
> Fix :: Integrated header date range selector for Time Activity menu

- apps/gauzy/src/app/@shared/timesheet/view-time-log/index.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
> Fix :: Daily/Weekly Timesheet Employee Activity

- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/base-selector-filter/base-selector-filter.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.html
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
- packages/contracts/src/timesheet.model.ts
> Fix :: Approvals timesheet header date range selector applied

- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
> Fix :: Screenshots/Apps/Urls activities date range picker selection (next/previous)

- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.scss
> Fix :: Date range picker width

- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.ts
> Fix :: Accounting date range filter

- angular.json
- apps/desktop-timer/package.json
- apps/desktop-timer/src/app/app.module.ts
- apps/desktop/package.json
- packages/desktop-ui-lib/src/lib/tasks/tasks.component.html
- packages/desktop-ui-lib/src/lib/tasks/tasks.component.scss
- packages/desktop-ui-lib/src/lib/tasks/tasks.component.ts
- packages/desktop-ui-lib/src/lib/tasks/tasks.module.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.module.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> feat: add new task from desktop timer

- apps/gauzy/src/app/@shared/project-select/project/project.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/organization/organization.component.html
> Fix/Disabled selectors auto focus on select project/employee/organization

- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix :: Statistic for time tracking members

- apps/gauzy/src/app/pages/dashboard/dashboard.module.ts
- apps/gauzy/src/app/pages/dashboard/project-management/project-management.component.html
- apps/gauzy/src/app/pages/dashboard/project-management/project-management.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.html
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.scss
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.ts
> Fix :: Edit Employee Main Section

- packages/core/src/core/seeds/seed-data.service.ts
- packages/core/src/organization-project/organization-project.seed.ts
> Fix :: Default organization projects seeder

- apps/gauzy/src/app/@shared/single-statistic/single-statistic.component.scss
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.html
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.scss
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.html
> Feat: Improve Dashboard Accounting Page 

- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
> Fix :: Replace profile role name

- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.scss
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
- packages/core/src/organization/organization.seed.ts
> Fix :: Organization Settings & Date Picker Size

- apps/gauzy/src/app/@shared/pagination/pagination-filter-base.component.ts
- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.html
- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.html
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
- apps/gauzy/src/app/pages/income/income.component.ts
- apps/gauzy/src/app/pages/payments/payments.component.html
- apps/gauzy/src/app/pages/payments/payments.component.ts
- apps/gauzy/src/app/pages/time-off/time-off.component.ts
> Fix :: Some Tiny Issues

- apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.html
- apps/gauzy/src/app/@shared/table-components/document-date/document-date.component.ts
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-documents/edit-candidate-documents.component.html
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-documents/edit-candidate-documents.component.ts
- apps/gauzy/src/app/pages/documents/documents.component.html
- apps/gauzy/src/app/pages/documents/documents.component.ts
- apps/gauzy/src/app/pages/projects/projects.component.html
- apps/gauzy/src/app/pages/projects/projects.component.ts
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.html
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.html
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.html
> Fix :: Date Format For Organization Menu

- apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.html
- apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.html
- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.html
> Fix :: Change date format for other report pages

- apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.html
- apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/arrow/strategies/concrete/next.strategy.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/arrow/strategies/concrete/previous.strategy.ts
- apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.ts
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.html
- packages/core/src/core/utils.ts
- packages/core/src/payment/payment.controller.ts
- packages/core/src/payment/payment.service.ts
- packages/core/src/time-tracking/activity/activity.controller.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
> Fixed :: Time & Activity Report Displayed Wrong Dates

- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
- packages/contracts/src/organization-contact.model.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/employee/employee.seed.ts
- packages/core/src/organization-contact/organization-contact.seed.ts
- packages/core/src/organization-project/organization-project.seed.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-log/time-log.module.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
> Fix :: Client Budget Report

- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.html
- packages/core/src/organization-project/organization-project.seed.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
> Fix :: Project Budget Report

- apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts
> Fix :: Bad Request - Record Full Payment

- apps/gauzy/src/app/@shared/pipes/duration-format.pipe.ts
> Fix :: Duration format pipe for minus values

- apps/gauzy/src/app/@shared/invite/invites/invites.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/app.component.ts
- apps/gauzy/src/app/pages/contacts/contact-routing.module.ts
- apps/gauzy/src/app/pages/employee-levels/employee-level.component.ts
- apps/gauzy/src/app/pages/employees/employees-routing.module.ts
- apps/gauzy/src/app/pages/jobs/jobs-routing.module.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/pages.component.ts
- apps/gauzy/src/app/pages/positions/positions.component.ts
- apps/gauzy/src/app/pages/time-off/time-off-routing.module.ts
> Fix :: Selectors Visibility & Date Range Picker Handler

- apps/gauzy/src/app/@core/services/selector-builder/date-range-picker-builder.service.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.scss
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/app.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/pages.component.ts
> Fix :: Locking Weekly Date Range

- apps/gauzy/src/app/@shared/components/header-title/header-title.component.html
- apps/gauzy/src/app/@shared/components/header-title/header-title.component.ts
- apps/gauzy/src/app/@shared/single-statistic/single-statistic.component.html
- apps/gauzy/src/app/@shared/single-statistic/single-statistic.component.ts
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.html
> Feat/Header Title Typography

- apps/gauzy/src/app/@core/services/selector-builder/date-range-picker-builder.service.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/employees/activity/activity-routing.module.ts
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.html
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
- apps/gauzy/src/app/pages/employees/activity/time-and-activities/time-and-activities/time-and-activities.component.html
- apps/gauzy/src/app/pages/employees/activity/time-and-activities/time-and-activities/time-and-activities.component.ts
- packages/contracts/src/timesheet.model.ts
> Fix :: Save Date Range Filter Improvement

- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-screenshot.ts
- packages/desktop-libs/src/lib/desktop-timer.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> fix: desktop timer screenshot notification

- apps/gauzy/src/app/@shared/user/forms/action-confirmation/action-confirmation.component.ts
- apps/gauzy/src/app/@shared/user/forms/delete-confirmation/delete-confirmation.component.ts
- apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.html
- apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.scss
- apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.ts
- apps/gauzy/src/app/pages/proposals/proposal-edit/proposal-edit.component.html
- apps/gauzy/src/app/pages/proposals/proposal-edit/proposal-edit.component.scss
- apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.html
- apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.scss
- apps/gauzy/src/app/pages/proposals/proposals.component.html
- apps/gauzy/src/app/pages/proposals/proposals.component.scss
- apps/gauzy/src/app/pages/reports/all-report/all-report/all-report.component.html
- apps/gauzy/src/app/pages/reports/all-report/all-report/all-report.component.scss
> Feat:: Improve proposal UI

- apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.scss
- apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.html
- apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.scss
- apps/gauzy/src/app/@shared/report/daily-statistics/daily-statistics/daily-statistics.component.html
- apps/gauzy/src/app/@shared/report/daily-statistics/daily-statistics/daily-statistics.component.scss
- apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.scss
---
https://user-images.githubusercontent.com/10062202/163972185-1bb26497-07cf-4421-965d-b4a50e1d4c41.mp4
> Feat/#4359: new update amount design + fixes in daily statistics grid

- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.html
- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.scss
- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.module.ts
- apps/gauzy/src/app/@theme/styles/report.scss
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.scss
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.html
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.scss
---
https://user-images.githubusercontent.com/10062202/164023887-bf5b5aa3-a622-4321-aabf-03df5cca4f18.mp4
> feat: updated payment report page

- apps/gauzy/src/app/@shared/progress-status/progress-status/progress-status.component.html
- apps/gauzy/src/app/@shared/progress-status/progress-status/progress-status.component.scss
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report.module.ts
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.html
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.scss
---
https://user-images.githubusercontent.com/10062202/164053222-a3eb4e93-1c3e-41d5-a0f6-433bba7587aa.mp4
> feat: update weekly limit-report

- apps/gauzy/src/app/@shared/status-badge/status-badge.component.scss
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-overrides.scss
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-table.scss
- apps/gauzy/src/app/@theme/styles/themes.scss
- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
- apps/gauzy/src/app/pages/jobs/employees/employees.module.ts
- apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.html
- apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.scss
- apps/gauzy/src/app/pages/jobs/search/search.module.ts
- apps/gauzy/src/app/pages/jobs/search/search/search.component.html
- apps/gauzy/src/app/pages/jobs/search/search/search.component.scss
- apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
- apps/gauzy/src/app/pages/payments/payments.component.html
- apps/gauzy/src/app/pages/payments/payments.component.scss
- apps/gauzy/src/app/pages/pipelines/pipeline-form/pipeline-form.component.html
- apps/gauzy/src/app/pages/pipelines/pipeline-form/pipeline-form.component.scss
- apps/gauzy/src/app/pages/pipelines/pipeline-form/pipeline-form.component.ts
- apps/gauzy/src/app/pages/pipelines/pipelines.component.html
- apps/gauzy/src/app/pages/pipelines/pipelines.component.scss
- apps/gauzy/src/app/pages/pipelines/pipelines.component.ts
- apps/gauzy/src/app/pages/pipelines/pipelines.module.ts
- apps/gauzy/src/assets/i18n/en.json
> Feat::Pipeline Job UI Upgrade

- apps/gauzy/src/app/@theme/styles/report.scss
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.html
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.scss
---
https://user-images.githubusercontent.com/10062202/164194853-76adad92-be19-4b3f-bf1c-c09d1a8d4531.mp4
> feat: update daily limit design

- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report.module.ts
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.scss
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.ts
- apps/gauzy/src/assets/i18n/en.json
---
https://user-images.githubusercontent.com/10062202/164267267-3e60e3b4-c477-426e-a404-168c155a6eef.mp4
> feat: update project budget design

- packages/core/src/organization-project/organization-project.seed.ts
> Fix :: SQLite query alias issue for project members count

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- packages/core/src/time-tracking/activity/activity.service.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix :: Time tracking daily/weekly statistic activity

- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.setting.ts
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.html
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.scss
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.ts
- packages/contracts/src/organization.model.ts
- packages/core/src/organization/organization.entity.ts
> Fix :: Timesheet Calendar Page

- apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.html
- apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.scss
- apps/gauzy/src/app/pages/jobs/proposal-template/add-edit-proposal-template/add-edit-proposal-template.component.html
- apps/gauzy/src/app/pages/jobs/proposal-template/add-edit-proposal-template/add-edit-proposal-template.component.scss
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template.module.ts
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.html
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.scss
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts
- apps/gauzy/src/app/pages/jobs/search/search/search.component.scss
> Feat/Upgrade Jobs Matching/Proposals

- packages/core/src/database/migrations/1650704972412-AlterChangelogTable.ts
> Fix :: SQLite changelog migration issue

- apps/gauzy/src/app/@shared/card-grid/card-grid.component.html
- apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.html
- apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.scss
- apps/gauzy/src/app/@shared/invite/invite-mutation/invite-mutation.component.html
- apps/gauzy/src/app/@shared/invite/invite-mutation/invite-mutation.component.scss
- apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.scss
- apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.ts
- apps/gauzy/src/app/@shared/table-components/tags-only/tags-only.component.html
- apps/gauzy/src/app/@shared/table-components/tags-only/tags-only.component.ts
- apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.html
- apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.scss
- apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.scss
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.scss
- apps/gauzy/src/app/@theme/styles/_overrides.scss
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-table.scss
- apps/gauzy/src/app/pages/employees/employees.component.html
- apps/gauzy/src/app/pages/employees/employees.component.scss
- apps/gauzy/src/app/pages/employees/employees.component.ts
- apps/gauzy/src/app/pages/employees/employees.module.ts
- apps/gauzy/src/app/pages/employees/table-components/employee-work-status/employee-work-status.component.scss
- apps/gauzy/src/app/pages/jobs/search/search/search.component.html
- apps/gauzy/src/app/pages/jobs/search/search/search.component.scss
- apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
---
On employee component
On invite component
> Feat: Employee Manage

- apps/gauzy/src/app/@shared/invite/invites/client-names/client-names.component.scss
- apps/gauzy/src/app/@shared/invite/invites/client-names/client-names.component.ts
- apps/gauzy/src/app/@shared/invite/invites/invites.component.html
- apps/gauzy/src/app/@shared/invite/invites/invites.component.scss
- apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
- apps/gauzy/src/app/@shared/invite/invites/invites.module.ts
- apps/gauzy/src/app/@shared/invite/invites/resend-confirmation/resend-confirmation.component.scss
- apps/gauzy/src/app/@shared/invite/invites/resend-confirmation/resend-confirmation.component.ts
> Feat: Employee Manage Invite

- packages/core/src/database/migrations/1650704972412-AlterChangelogTable.ts
> Fix :: Default changelog seeder migration insert query not working

- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.html
- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.scss
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.scss
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.html
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.scss
- apps/gauzy/src/app/pages/employees/activity/layout/layout.component.html
- apps/gauzy/src/app/pages/employees/activity/layout/layout.component.scss
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.scss
- apps/gauzy/src/app/pages/employees/activity/time-and-activities/time-and-activities/time-and-activities.component.html
- apps/gauzy/src/app/pages/employees/activity/time-and-activities/time-and-activities/time-and-activities.component.scss
> Feat/Employee Time Activity

- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
- apps/gauzy/src/assets/i18n/en.json
> Fix :: Activity column translation

- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.html
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
> Fix :: Date Range Picker Save Filter

- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.html
- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.scss
- apps/gauzy/src/app/@shared/file-uploader-input/file-uploader-input.component.html
- apps/gauzy/src/app/@shared/file-uploader-input/file-uploader-input.component.scss
- apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.scss
- apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.ts
- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.scss
- apps/gauzy/src/app/@shared/user/forms/user-forms.module.ts
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-dialogs.scss
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-overrides.scss
- apps/gauzy/src/app/pages/employees/table-components/employee-work-status/employee-work-status.component.scss
> Feat/Upgrade UI Employees Add Mutation

- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.html
- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.scss
- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.ts
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.html
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.scss
- apps/gauzy/src/assets/i18n/en.json
> Fix: Visited Sites Element Alignment

- packages/core/src/organization-position/organization-position.controller.ts
> Fix :: Employee position DTO whitelist payload

- apps/gauzy/src/app/@shared/card-grid/card-grid.component.scss
- apps/gauzy/src/app/pages/employee-levels/employee-level.component.html
- apps/gauzy/src/app/pages/employee-levels/employee-level.component.scss
- apps/gauzy/src/app/pages/employee-levels/employee-level.component.ts
- apps/gauzy/src/app/pages/employee-levels/employee-level.module.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.scss
- apps/gauzy/src/app/pages/expenses/expense-categories/expense-categories.component.html
- apps/gauzy/src/app/pages/expenses/expense-categories/expense-categories.component.scss
> Feat/Upgrade Employee Level

- apps/gauzy/src/app/@shared/time-off/settings-mutation/time-off-settings-mutation.component.html
- apps/gauzy/src/app/@shared/time-off/time-off-holiday-mutation/time-off-holiday-mutation.component.html
- apps/gauzy/src/app/@shared/time-off/time-off-mutation.components.scss
- apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.html
- apps/gauzy/src/app/pages/time-off/table-components/index.ts
- apps/gauzy/src/app/pages/time-off/table-components/paid-icon.scss
- apps/gauzy/src/app/pages/time-off/table-components/request-approval-icon.scss
- apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.html
- apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.scss
- apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.ts
- apps/gauzy/src/app/pages/time-off/time-off.module.ts
> Feat/Upgrade UI employee time off settings

- apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.ts
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-table.scss
- apps/gauzy/src/app/pages/time-off/time-off.component.html
- apps/gauzy/src/app/pages/time-off/time-off.component.scss
- apps/gauzy/src/app/pages/time-off/time-off.component.ts
- apps/gauzy/src/app/pages/time-off/time-off.module.ts
> Feat/Upgrade Employee Time Off

- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.html
- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.scss
- apps/gauzy/src/app/pages/candidates/candidates.component.html
- apps/gauzy/src/app/pages/candidates/candidates.component.scss
- apps/gauzy/src/app/pages/candidates/candidates.component.ts
- apps/gauzy/src/app/pages/candidates/candidates.module.ts
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-employment/edit-candidate-employment.component.html
- apps/gauzy/src/app/pages/candidates/table-components/candidate-status/candidate-status.component.scss
> Feat/Upgrade Employee Manage Candidate

- apps/gauzy/src/app/pages/candidates/candidate-statistic/candidate-statistic.component.scss
- apps/gauzy/src/app/pages/candidates/candidate-statistic/candidate-statistic.component.ts
> Feat/Candidate Manage Statistic

- apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-interview-form/candidate-interview-form.component.html
- apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-interview-form/candidate-interview-form.component.scss
- apps/gauzy/src/app/@shared/user/forms/archive-confirmation/archive-confirmation.component.ts
- apps/gauzy/src/app/@shared/user/forms/delete-confirmation/delete-confirmation.component.scss
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-overrides.scss
- apps/gauzy/src/app/@theme/styles/themes.scss
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-calendar/interview-calendar.component.html
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-calendar/interview-calendar.component.scss
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-criterions/candidate-personal-qualities/candidate-personal-qualities.component.html
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-criterions/candidate-personal-qualities/candidate-personal-qualities.component.scss
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-criterions/candidate-technologies/candidate-technologies.component.html
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-criterions/candidate-technologies/candidate-technologies.component.scss
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-criterions/interview-criterions.component.scss
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.html
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.scss
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.ts
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/table-components/index.ts
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.html
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.scss
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.ts
> Feat/Upgrade UI Candidate Manage Interviews

- apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.scss
- apps/gauzy/src/app/pages/employees/appointment/appointment.component.html
- apps/gauzy/src/app/pages/employees/appointment/appointment.component.scss
- apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html
- apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.scss
- apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.html
- apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.scss
- apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.ts
- apps/gauzy/src/app/pages/employees/schedules/layout/layout.component.html
- apps/gauzy/src/app/pages/employees/schedules/layout/layout.component.scss
> Feat/Upgrade UI Employees Appointments

- apps/gauzy/src/app/@shared/invite/invites/invites.component.html
- apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
- apps/gauzy/src/app/pages/approval-policy/approval-policy.component.ts
> Fix ::  Missing actions buttons for GRID view & better package import

- apps/gauzy/src/app/@theme/styles/_overrides.scss
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-documents/edit-candidate-documents.component.scss
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-employment/edit-candidate-employment.component.scss
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-experience/edit-candidate-experience.component.scss
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.scss
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-hiring/edit-candidate-hiring.component.scss
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-interview/edit-candidate-interview.component.scss
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-location/edit-candidate-location.component.ts
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-main/edit-candidate-main.component.ts
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-rates/edit-candidate-rates.component.ts
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-calendar/interview-calendar.component.scss
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-criterions/interview-criterions.component.scss
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.scss
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.scss
- apps/gauzy/src/app/pages/dashboard/human-resources/human-resources.component.scss
- apps/gauzy/src/app/pages/dashboard/project-management/project-management.component.scss
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-contact/edit-employee-contact.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-employment/edit-employee-employment.component.scss
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-hiring/edit-employee-hiring.component.scss
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-location/edit-employee-location.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.scss
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-networks/edit-employee-networks.component.scss
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-projects/edit-employee-projects.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-rate/edit-employee-rate.component.ts
- apps/gauzy/src/app/pages/jobs/search/search/search.component.scss
---
> Chrome ✔️
Safari ✔️
Edge ✔️
Firefox ✔️
> Fix::Cards scrollbar for Firefox browser

- apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.html
- apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.ts
- packages/core/src/core/file-storage/file-storage.ts
- packages/core/src/organization-project/organization-project.seed.ts
- packages/core/src/tenant/tenant-setting/dto/create-tenant-setting.dto.ts
- packages/core/src/tenant/tenant-setting/tenant-setting.seed.ts
- packages/core/src/tenant/tenant.service.ts
- packages/core/src/time-tracking/screenshot/screenshot.controller.ts
> Fix :: File Provider Storage

- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.ts
- apps/gauzy/src/app/pages/candidates/candidates.component.html
- apps/gauzy/src/app/pages/candidates/candidates.component.ts
- packages/core/src/candidate-source/candidate-source.entity.ts
> Fix :: Candidate GRID and TABLE view & candidate mutation

- apps/gauzy/src/app/@core/utils/smart-table/index.ts
- apps/gauzy/src/app/@core/utils/smart-table/server-source.conf.ts
- apps/gauzy/src/app/@core/utils/smart-table/server.data-source.ts
- apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.setting.ts
- apps/gauzy/src/app/pages/approvals/table-components/index.ts
- apps/gauzy/src/app/pages/time-off/time-off.component.html
- apps/gauzy/src/app/pages/time-off/time-off.component.ts
- packages/core/src/database/migrations/1652270907163-AlterTimeOffRequestTable.ts
- packages/core/src/time-off-request/time-off-request.controller.ts
- packages/core/src/time-off-request/time-off-request.entity.ts
- packages/core/src/time-off-request/time-off-request.seed.ts
- packages/core/src/time-off-request/time-off-request.service.ts
> Fix/#4513 Time Off Pagination

- apps/gauzy/src/app/@shared/time-off/settings-mutation/time-off-settings-mutation.component.ts
- apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.html
- apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.ts
- apps/gauzy/src/app/pages/time-off/time-off.component.html
- packages/contracts/src/time-off.model.ts
- packages/core/src/time-off-policy/time-off-policy.controller.ts
> Fix/#4513 Time Off Policy Pagination

- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-employment/edit-candidate-employment.component.html
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-employment/edit-candidate-employment.component.ts
- packages/core/src/candidate/candidate.controller.ts
- packages/core/src/candidate/dto/update-candidate.dto.ts
> Fix/Candidate Empployment Update Profile

- apps/gauzy/src/app/@shared/employee/employee-location/employee-location.component.html
- apps/gauzy/src/app/@shared/employee/employee-location/employee-location.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.html
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
> Fix/Invoice Pagination Multiple API calls

- apps/gauzy/src/app/@shared/table-components/created-at/created-at.component.html
- apps/gauzy/src/app/@shared/table-components/created-at/created-at.component.scss
- apps/gauzy/src/app/@shared/table-components/created-at/created-at.component.ts
- apps/gauzy/src/app/@shared/table-components/employees-merged-teams/employees-merged-teams.component.scss
- apps/gauzy/src/app/@shared/table-components/table-components.module.ts
- apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
- apps/gauzy/src/assets/i18n/en.json
> Feat/ Tasks Page improvement

- apps/gauzy/src/app/@core/validators/at-least-one-field.validator.ts
- apps/gauzy/src/app/@core/validators/index.ts
- apps/gauzy/src/app/pages/pipelines/pipelines.component.html
- apps/gauzy/src/app/pages/pipelines/pipelines.component.ts
- packages/contracts/src/pipeline.model.ts
- packages/core/src/core/crud/query-builder.ts
- packages/core/src/pipeline/pipeline.service.ts
> Fix/#4480 Pipeline pagination & search  filters

- packages/core/src/database/migrations/1644491785525-AdjustTimeLogStopDate.ts
- packages/core/src/organization-project/organization-project.seed.ts
> Fix :: Trying to fix migration to run successfully on production

- packages/core/src/income/income.seed.ts
> Fix :: #4544 Applied tags on income seeder

- apps/gauzy/package.json
- yarn.lock
> chore: updated ngx-daterangepicker-material package

- apps/gauzy/src/app/@shared/table-components/employee-links/employee-links.component.scss
- apps/gauzy/src/app/@shared/table-components/employee-links/employee-links.component.ts
- apps/gauzy/src/app/pages/income/income.component.html
- apps/gauzy/src/app/pages/income/income.component.scss
- apps/gauzy/src/app/pages/income/income.component.ts
- yarn.lock
> Fix/Income Page Improvement

- apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html
- apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts
- packages/core/src/income/dto/create-income.dto.ts
- packages/core/src/income/dto/income.dto.ts
> Fix/Income Mutation

- apps/gauzy/src/app/pages/jobs/employees/employees.module.ts
- apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.html
- apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.scss
- apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.ts
- packages/core/src/employee/commands/handlers/get-employee-job-statistics.handler.ts
- packages/core/src/employee/employee.controller.ts
> Fix :: #4480 Server side pagination for job employees

- apps/gauzy/src/app/pages/invoices/invoices.component.ts
- apps/gauzy/src/app/pages/jobs/search/search.module.ts
- apps/gauzy/src/app/pages/jobs/search/search/search.component.html
- apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
- apps/gauzy/src/app/pages/pipelines/pipelines.component.ts
- packages/contracts/src/employee-job.model.ts
> Fix/Job Search Pagination

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-language-selector.component.ts
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-selector/theme-selector-image/theme-selector-image.component.html
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-selector/theme-selector-image/theme-selector-image.component.scss
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.html
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.scss
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.ts
- apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.html
- apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.scss
- apps/gauzy/src/app/@theme/components/user/user.component.scss
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.html
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.scss
- apps/gauzy/src/assets/images/logos/logo_Gauzy.svg
> Fix/Theme language Hebrew

- apps/gauzy/src/app/@core/services/tasks.service.ts
- apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.component.html
- apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.component.ts
- apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.module.ts
- apps/gauzy/src/app/@shared/tasks/task-number/task-number-field.component.html
- apps/gauzy/src/app/@shared/tasks/task-number/task-number-field.component.ts
- apps/gauzy/src/app/@shared/tasks/task-number/task-number-field.module.ts
- apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.html
- apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.ts
- apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
- apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.html
- apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts
- apps/gauzy/src/app/pages/tasks/tasks.module.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/task-entity.model.ts
- packages/core/src/core/entities/internal.ts
- packages/core/src/core/entities/subscribers.ts
- packages/core/src/database/migrations/1652703299052-AlterTaskTableColumns.ts
- packages/core/src/tasks/commands/handlers/task-create.handler.ts
- packages/core/src/tasks/dto/create-task.dto.ts
- packages/core/src/tasks/dto/task.dto.ts
- packages/core/src/tasks/task.controller.ts
- packages/core/src/tasks/task.entity.ts
- packages/core/src/tasks/task.seed.ts
- packages/core/src/tasks/task.service.ts
- packages/core/src/tasks/task.subscriber.ts
> Fix/#4536 Task Page & Modal Improvement

- packages/core/src/database/migrations/1652936174625-ReportTableIconSeed.ts
> Fix :: Default reports icon class seed migration

- apps/gauzy/src/app/@shared/equipment/equipment-mutation.component.html
- apps/gauzy/src/app/@shared/equipment/equipment-mutation.component.ts
- apps/gauzy/src/app/pages/equipment/equipment.component.html
- apps/gauzy/src/app/pages/equipment/equipment.component.scss
- apps/gauzy/src/app/pages/equipment/equipment.component.ts
- apps/gauzy/src/app/pages/equipment/equipment.module.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/core/src/equipment/dto/create-equipment.dto.ts
- packages/core/src/equipment/dto/equipment.dto.ts
- packages/core/src/equipment/equipment.controller.ts
> Fix/#4480 Equipment Server Side Pagination

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-language-selector.component.html
- apps/gauzy/src/assets/i18n/bg.json
- apps/gauzy/src/assets/i18n/en.json
- apps/gauzy/src/assets/i18n/he.json
- apps/gauzy/src/assets/i18n/ru.json
> Fix :: Removed unused translation

- apps/gauzy/src/app/@shared/time-off/time-off-holiday-mutation/time-off-holiday-mutation.component.html
- apps/gauzy/src/app/@shared/time-off/time-off-holiday-mutation/time-off-holiday-mutation.component.ts
- apps/gauzy/src/app/@shared/time-off/time-off-policy-select/time-off-policy-select.component.html
- apps/gauzy/src/app/@shared/time-off/time-off-policy-select/time-off-policy-select.component.ts
- apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.html
- apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts
- packages/contracts/src/time-off.model.ts
> Fix/#4507 Time Off Request Mutation

- apps/gauzy/src/app/@shared/gauzy-button-action/gauzy-button-action.component.html
- apps/gauzy/src/app/@shared/gauzy-button-action/gauzy-button-action.component.ts
- apps/gauzy/src/app/@shared/pagination/pagination-filter-base.component.ts
- apps/gauzy/src/app/@shared/table-filters/task-status-filter.component.ts
- apps/gauzy/src/app/@shared/tasks/task-status-select/task-status-select.component.html
- apps/gauzy/src/app/@shared/tasks/task-status-select/task-status-select.component.ts
- apps/gauzy/src/app/pages/employees/employees.component.html
- apps/gauzy/src/app/pages/employees/employees.component.ts
- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
- apps/gauzy/src/app/pages/payments/payments.component.ts
- apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
- packages/common-angular/src/utils/shared-utils.ts
- packages/core/src/employee/dto/employment.dto.ts
- packages/core/src/employee/dto/hiring.dto.ts
- packages/core/src/employee/dto/network.dto.ts
- packages/core/src/employee/dto/rates.dto.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/employee/employee.service.ts
- packages/core/src/organization-department/dto/create-organization-department.dto.ts
- packages/core/src/organization-employment-type/dto/create-organization-employment-type.dto.ts
- packages/core/src/payment/payment.service.ts
- packages/core/src/tags/dto/relational-tag.dto.ts
- packages/core/src/tasks/commands/handlers/task-create.handler.ts
- packages/core/src/tasks/commands/handlers/task-update.handler.ts
- packages/core/src/tasks/commands/task-create.command.ts
- packages/core/src/tasks/commands/task-update.command.ts
- packages/core/src/tasks/dto/update-task.dto.ts
- packages/core/src/tasks/task.controller.ts
- packages/core/src/tasks/task.service.ts
- packages/core/src/tasks/task.subscriber.ts
> Fix/#4480 Pagination Improvement & Other Major Fixes

- apps/gauzy/src/app/@shared/back-navigation/back-navigation.component.ts
- apps/gauzy/src/app/@shared/forms/location/location-form.component.html
- apps/gauzy/src/app/@shared/forms/maps/leaflet/leaflet.component.scss
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/menu-item/menu-item.component.scss
- apps/gauzy/src/app/@shared/table-components/contact-with-tags/contact-with-tags.component.html
- apps/gauzy/src/app/@shared/table-components/contact-with-tags/contact-with-tags.component.scss
- apps/gauzy/src/app/@shared/table-components/contact-with-tags/contact-with-tags.component.ts
- apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.ts
- apps/gauzy/src/app/@shared/table-components/project/project.component.html
- apps/gauzy/src/app/@shared/table-components/project/project.component.ts
- apps/gauzy/src/app/@shared/table-components/table-components.module.ts
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-dialogs.scss
- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html
- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.scss
- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
- apps/gauzy/src/app/pages/contacts/contact.component.html
- apps/gauzy/src/app/pages/contacts/contact.component.scss
- apps/gauzy/src/app/pages/contacts/contact.component.ts
- apps/gauzy/src/app/pages/contacts/contact.module.ts
- apps/gauzy/src/app/pages/contacts/invite-contact/invite-contact.component.html
- apps/gauzy/src/app/pages/contacts/invite-contact/invite-contact.component.scss
- apps/gauzy/src/app/pages/contacts/table-components/contact-action/contact-action.component.html
- apps/gauzy/src/app/pages/contacts/table-components/contact-action/contact-action.component.ts
- apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
- apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.ts
- packages/contracts/src/index.ts
- packages/contracts/src/project.model.ts
---
> [demo link](https://www.loom.com/share/3fd97f64d38444fbb617a871b8a50eb4)
> Feat/Upgrade UI Contacts Pages

- apps/gauzy/src/app/@shared/card-grid/card-grid.component.html
- apps/gauzy/src/app/@shared/card-grid/card-grid.component.scss
- apps/gauzy/src/app/@shared/equipment/equipment-mutation.component.html
- apps/gauzy/src/app/@shared/equipment/equipment-mutation.component.scss
- apps/gauzy/src/app/@shared/select-asset-modal/img-asset/img-asset.component.scss
- apps/gauzy/src/app/@shared/select-asset-modal/img-preview/img-preview.component.html
- apps/gauzy/src/app/@shared/select-asset-modal/img-preview/img-preview.component.scss
- apps/gauzy/src/app/@shared/select-asset-modal/select-asset.component.html
- apps/gauzy/src/app/@shared/select-asset-modal/select-asset.component.scss
- apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.ts
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.scss
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-dialogs.scss
- apps/gauzy/src/app/pages/equipment/auto-approve/auto-approve.component.html
- apps/gauzy/src/app/pages/equipment/equipment.component.html
- apps/gauzy/src/app/pages/equipment/equipment.component.scss
- apps/gauzy/src/app/pages/equipment/equipment.component.ts
- apps/gauzy/src/app/pages/inventory/components/table-components/image-row.component.ts
> Feat/Upgrade UI equipment page

- packages/core/src/core/seeds/seed-data.service.ts
- packages/core/src/organization-project/organization-project.seed.ts
> Fix :: Organization project member count seeder

- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
> Fix :: Lock date range picker selection

- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/base-selector-filter/base-selector-filter.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
> Fix :: Minor filter fixes

- apps/gauzy/src/app/@shared/currency/currency.component.html
- apps/gauzy/src/app/@shared/currency/currency.component.ts
- apps/gauzy/src/app/@shared/currency/currency.module.ts
- apps/gauzy/src/app/pages/employees/employees.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html
> Fix/#4591 Currency Autocomplete

- apps/gauzy/src/app/@shared/project-select/project/project.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/organization/organization.component.html
- apps/gauzy/src/assets/i18n/en.json
> Fix :: #4583 Added translation for tag text of header selectors

- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
> Fix :: Disabled max dates for date range picker

- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
> fix: desktop timer missing footer

- apps/gauzy/src/app/@theme/components/header/header.component.scss
> Fix: Increase employee selector size

- apps/gauzy/src/app/@shared/report/daily-statistics/daily-statistics/daily-statistics.component.scss
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot.module.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.scss
> Fix/#4608 Add Statistics Block To Screenshots Page

- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.ts
- apps/gauzy/src/app/@shared/report/daily-statistics/daily-statistics/daily-statistics.component.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/base-selector-filter/base-selector-filter.component.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.ts
- apps/gauzy/src/app/@shared/timesheet/timesheet-filter.service.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
- apps/gauzy/src/app/pages/employees/activity/time-and-activities/time-and-activities/time-and-activities.component.html
> Fix/#4610 Prevent Multiple API call for Time & Activities pages

- apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.component.html
- apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.html
- apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.ts
- apps/gauzy/src/app/onboarding/tenant-details/tenant-details.component.html
- apps/gauzy/src/app/onboarding/tenant-details/tenant-details.component.scss
- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html
- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.scss
> Fix/Organization & Contact issues

- apps/gauzy/src/app/@shared/pipes/text.pipe.ts
- apps/gauzy/src/app/@shared/project-select/project-select.module.ts
- apps/gauzy/src/app/@shared/project-select/project/project.component.html
- apps/gauzy/src/app/@shared/project-select/project/project.component.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
---
**What we have before:**
**What we fixed after:**
> Fix :: Project Selector Width

- apps/gauzy/src/app/@shared/report/charts/line-chart/line-chart.component.ts
- apps/gauzy/src/app/@theme/styles/report.scss
- apps/gauzy/src/app/@theme/styles/themes.scss
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-main/edit-candidate-main.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.scss
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-location/edit-organization-location.component.scss
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.html
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.scss
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.scss
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.scss
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.scss
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.ts
---
> Actually on `demo.gauzy.co`
> Figma design
> PR result
> Fix/Organization Settings Issue

- apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.ts
- apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.html
- apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.ts
- apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.html
- apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.ts
- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.html
- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.ts
- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
- apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.html
- apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.ts
- apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.html
- apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.ts
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.ts
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.html
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.ts
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.html
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.ts
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.html
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.ts
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.ts
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.html
- apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.ts
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.html
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.ts
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.html
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.ts
> Fix/ Time & Activity and Apps  & URLs Reports

- apps/gauzy/src/app/@shared/feature-toggle/feature-toggle.component.html
- apps/gauzy/src/app/@shared/feature-toggle/feature-toggle.component.scss
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.scss
- apps/gauzy/src/app/@theme/styles/themes.scss
- apps/gauzy/src/app/pages/settings/feature/feature.component.html
- apps/gauzy/src/app/pages/settings/feature/feature.component.scss
---
> Figma Design
> On server `demo.gauzy.co`
> <img width="1440" alt="image" src="https://user-images.githubusercontent.com/45813955/171882818-f4bb9b70-65ab-4106-a637-c641e91946e1.png">
> <img width="1440" alt="image" src="https://user-images.githubusercontent.com/45813955/171882775-3776a7a7-a2ee-496a-bed8-84cfb0441891.png">
> <img width="1440" alt="Screen Shot 2022-06-03 at 5 16 55 PM" src="https://user-images.githubusercontent.com/45813955/171883043-78ef332b-564 …
> Feat/Settings Features

- apps/gauzy/src/app/@shared/components/header-title/header-title.component.html
- apps/gauzy/src/app/@shared/components/header-title/header-title.module.ts
- apps/gauzy/src/app/pages/dashboard/human-resources/human-resources.component.html
---
> What was the issue.
> How now it's look like in this PR.
> How actually look like on [demo.gauzy.co](https://demo.gauzy.co/).
> feat:#4629 made sort name of emp in header title

- apps/gauzy/src/app/@shared/card-grid/card-grid.component.html
- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.scss
- apps/gauzy/src/app/@shared/user/forms/fields/password/password.component.html
- apps/gauzy/src/app/@shared/user/user-mutation/user-mutation.component.html
- apps/gauzy/src/app/@shared/user/user-mutation/user-mutation.component.scss
- apps/gauzy/src/app/pages/employees/table-components/employee-work-status/employee-work-status.component.scss
- apps/gauzy/src/app/pages/users/edit-user-mutation/edit-user-mutation.component.html
- apps/gauzy/src/app/pages/users/edit-user-mutation/edit-user-mutation.component.scss
- apps/gauzy/src/app/pages/users/edit-user-mutation/edit-user-mutation.component.ts
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-data/edit-user-data.component.scss
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-data/edit-user-data.component.ts
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations-mutation/edit-user-organizations-mutation.component.html
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations-mutation/edit-user-organizations-mutation.component.ts
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.html
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.scss
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.ts
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-profile.component.html
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-profile.component.scss
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-profile.component.ts
- apps/gauzy/src/app/pages/users/users.component.html
- apps/gauzy/src/app/pages/users/users.component.scss
- apps/gauzy/src/app/pages/users/users.component.ts
- apps/gauzy/src/app/pages/users/users.module.ts
- apps/gauzy/src/assets/i18n/en.json
---
> State on [demo.gauzy.co](https://demo.gauzy.co/#/pages/users)
> Figma Design
> PR content
> Feat/Upgrade UI Manage User's Pages

- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.scss
> fix: #4632 View Time Log UI when timer on

- apps/gauzy/src/app/@shared/country/country.component.html
- apps/gauzy/src/app/@shared/country/country.component.scss
- apps/gauzy/src/app/@shared/country/country.component.ts
- apps/gauzy/src/app/@shared/country/country.module.ts
- apps/gauzy/src/app/@shared/forms/location/location-form.component.html
- apps/gauzy/src/app/@shared/forms/location/location-form.component.ts
> Fix: #4595 Country selector should be Combo box (Searchable)

- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.html
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
> Fix/#4643 Use date range for calendar

- apps/gauzy/src/app/@shared/project-select/project/project.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.module.ts
> Fix/#4629 Emplyee & Project Selector Shorter Naming

- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.scss
---
> Actually on server
> PR
> <img width="1440" alt="image" src="https://user-images.githubusercontent.com/45813955/171998767-0345fa3b-6283-43cb-9ef3-f2a4c8b090dd.png">
> Fix: View Screenshots Modal background 

- apps/gauzy/src/app/@shared/table-components/role/role.component.scss
> fix: Import

- apps/desktop-timer/src/index.html
- apps/desktop/src/index.html
> feat: added loading indicators to desktop apps

- apps/gauzy/src/app/pages/settings/email-history/email-history.component.html
- apps/gauzy/src/app/pages/settings/email-history/email-history.component.scss
---
`Server` ❌
`Figma` 👀
`PR` ✔️
> Feat/Upgrade UI Settings Email History

- packages/core/src/time-tracking/timer/timer.service.ts
> Fix :: #4642 start/stop web timer fixes

- apps/gauzy/src/app/@core/services/store.service.ts
- apps/gauzy/src/app/@shared/directives/index.ts
- apps/gauzy/src/app/@shared/directives/time-tracking-authorized-directive.ts
- apps/gauzy/src/app/@shared/directives/timer-authorized-directive.ts
- apps/gauzy/src/app/@shared/pipes/date-format.pipe.ts
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.html
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
- apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.html
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.html
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
- packages/contracts/src/role-permission.model.ts
> Fix :: Time Tracking Permissions (Timesheet Pages)

- apps/gauzy/src/app/@shared/table-components/contact-links/contact-links.component.scss
- apps/gauzy/src/app/@shared/table-components/contact-links/contact-links.component.ts
> fix: #4584 contact name should displaying inline

- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
- apps/gauzy/src/app/pages/contacts/contacts.component.ts
- packages/core/src/organization-contact/organization-contact.controller.ts
- packages/core/src/organization-contact/organization-contact.service.ts
- packages/core/src/organization-project/organization-project.subscriber.ts
> Fix :: #4666 Organization Contact

- apps/gauzy/src/app/auth/login/whats-new/whats-new.component.html
- apps/gauzy/src/app/auth/login/whats-new/whats-new.component.ts
- apps/gauzy/src/app/auth/register/register-side-features/register-side-features.component.html
- apps/gauzy/src/app/auth/register/register-side-features/register-side-features.component.ts
- apps/gauzy/src/assets/i18n/bg.json
- apps/gauzy/src/assets/i18n/en.json
- apps/gauzy/src/assets/i18n/he.json
- apps/gauzy/src/assets/i18n/ru.json
- packages/contracts/src/changelog.model.ts
- packages/core/src/database/migrations/1654675304373-SeedChangeLogFeature.ts
> Fix :: Login/Register Sidebar Changelog

- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/children-menu-item/children-menu-item.component.html
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/children-menu-item/children-menu-item.component.ts
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/menu-item/menu-item.component.html
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/menu-item/menu-item.component.scss
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/menu-item/menu-item.component.ts
- apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.html
- apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.scss
- apps/gauzy/src/app/@theme/components/header/header.component.scss
- apps/gauzy/src/app/@theme/components/header/selectors/organization/organization.component.scss
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.scss
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-overrides.scss
- apps/gauzy/src/app/@theme/theme.module.ts
---
Demo [Link](https://www.loom.com/share/0339cd35113f4db2a58a276fe6ebb2cd)
`Figma`
`server`
`PR`
`On server`
`PR`
> Fix/Improve Sidebar Menu

- apps/gauzy/src/app/@theme/components/header/selectors/organization/organization.component.html
> Fix :: Organization searchable/create only when selector is bigger

- apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.html
- apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.scss
- apps/gauzy/src/app/onboarding/tenant-details/tenant-details.component.scss
> Fix/Tenant Onboarding UI

- apps/gauzy/src/app/@shared/table-components/employee-links/employee-links.component.ts
- apps/gauzy/src/app/pages/proposals/proposals.component.ts
> fix: #4542 author column redirect to wrong page

- apps/gauzy/src/app/@shared/pipes/text.pipe.ts
- apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.html
- apps/gauzy/src/app/pages/projects/projects.component.html
> fix:#4670 fix description text and truncate 50 character

- apps/gauzy/src/app/@shared/table-components/employee-links/employee-links.component.ts
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.scss
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.module.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
- apps/gauzy/src/assets/i18n/en.json
> Feat/#4269 Multiple Screenshots View

- apps/gauzy/src/app/@shared/card-grid/card-grid.component.scss
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/children-menu-item/children-menu-item.component.html
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/children-menu-item/children-menu-item.component.scss
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/children-menu-item/children-menu-item.component.ts
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/concrete/menu-item/menu-item.component.scss
- apps/gauzy/src/app/@shared/sidebar-menu/menu-items/interface/menu-item.interface.ts
- apps/gauzy/src/app/@shared/sidebar-menu/sidebar-menu.module.ts
- apps/gauzy/src/app/@theme/components/header/header.component.scss
- apps/gauzy/src/app/@theme/styles/_overrides.scss
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-overrides.scss
- apps/gauzy/src/app/pages/approvals/approvals.component.ts
- apps/gauzy/src/app/pages/departments/departments.component.ts
- apps/gauzy/src/app/pages/documents/documents.component.ts
- apps/gauzy/src/app/pages/employment-types/employment-types.component.ts
- apps/gauzy/src/app/pages/equipment/equipment.component.ts
- apps/gauzy/src/app/pages/expense-recurring/expense-recurring.component.ts
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts
- apps/gauzy/src/app/pages/pages.component.ts
- apps/gauzy/src/app/pages/pipelines/pipelines.component.ts
- apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.ts
- apps/gauzy/src/app/pages/tags/tags.component.ts
- apps/gauzy/src/app/pages/time-off/time-off.component.ts
- apps/gauzy/src/app/pages/vendors/vendors.component.ts
> Feat/Add Icon plus near sub menus

- apps/gauzy/src/app/@shared/product-mutation/product-type-mutation/product-type-mutation.component.html
- apps/gauzy/src/app/@shared/product-mutation/product-type-mutation/product-type-mutation.component.ts
- packages/core/src/product-type/dto/index.ts
- packages/core/src/product-type/dto/product-type-translation.dto.ts
- packages/core/src/product-type/dto/product-type.dto.ts
- packages/core/src/product-type/product-type.controller.ts
- packages/core/src/product-type/product-type.service.ts
> Fix/#4671 Inventory Product Type Mutation

- apps/gauzy/src/app/pages/reports/manual-time/manual-time.module.ts
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.html
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.scss
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/time-log/time-log.entity.ts
> Fix :: #4696 Manual Edit Report

- apps/gauzy/src/app/@shared/product-mutation/product-category-mutation/product-category-mutation.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories-routing.module.ts
- apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-product-types/product-types-routing.module.ts
- apps/gauzy/src/app/pages/inventory/components/manage-product-types/product-types.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-product-types/product-types.component.ts
- packages/core/src/core/dto/index.ts
- packages/core/src/core/dto/translate-base-dto.ts
- packages/core/src/product-category/dto/index.ts
- packages/core/src/product-category/dto/product-category.dto.ts
- packages/core/src/product-category/product-category.controller.ts
- packages/core/src/product-category/product-category.service.ts
- packages/core/src/product-type/dto/index.ts
- packages/core/src/product-type/dto/product-type-translation.dto.ts
- packages/core/src/product-type/dto/product-type.dto.ts
> Fix/#4671 Inventory Product Category Mutation

- apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.html
- apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.html
- apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.ts
> Fix :: Create tenant level tags on create organization

- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
- apps/gauzy/src/app/pages/contacts/contacts.component.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
> Fix :: Contact & Time Logs Listing

- packages/core/src/time-tracking/time-log/commands/handlers/schedule-time-log-entries.handler.ts
> Fix :: Updated time log maintain time entries (schedule time log)

- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix :: Time Tracking Dashboard

- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.html
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.ts
- apps/gauzy/src/assets/i18n/en.json
> Feat/ Show Weekly Total Worked Hours

- apps/gauzy/src/app/@core/services/selector-builder/date-range-picker-builder.service.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.scss
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/employees/activity/activity-routing.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
> Fix/#4731 Single Date Picker

- apps/gauzy/src/app/pages/documents/documents.component.html
- apps/gauzy/src/app/pages/documents/documents.component.scss
- apps/gauzy/src/app/pages/documents/documents.component.ts
- apps/gauzy/src/app/pages/documents/documents.module.ts
- apps/gauzy/src/app/pages/documents/upload-document/upload-document.component.html
---
`Server` ❌
`Figma` 👀
`PR` ✔️
> Feat/#4686 organization documents UI upgrade

- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.html
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.ts
- packages/contracts/src/report.model.ts
- packages/core/src/shared/decorators/validations/index.ts
- packages/core/src/shared/decorators/validations/is-between-activity.decorator.ts
- packages/core/src/shared/dto/date-range-query.dto.ts
- packages/core/src/shared/dto/filters-query.dto.ts
- packages/core/src/shared/dto/index.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-log/dto/query/index.ts
- packages/core/src/time-tracking/time-log/dto/query/time-log-report-query.dto.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
> Fix/#4732 Weekly Report

- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
> Fix/#4733 Time Tracking / Screenshots

- apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.html
- apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.scss
- apps/gauzy/src/app/@shared/table-components/table-components.module.ts
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-table.scss
- apps/gauzy/src/app/@theme/styles/themes.scss
- apps/gauzy/src/app/share/organization/organization.component.html
- apps/gauzy/src/app/share/organization/organization.component.scss
- apps/gauzy/src/app/share/organization/organization.component.ts
- apps/gauzy/src/app/share/organization/organization.module.ts
- apps/gauzy/src/assets/i18n/en.json
---
`Expected` ---> see issue #4691 ✔️
`Server` ---> please visit [public page](https://demo.gauzy.co/#/share/organization/ever-technologies-ltd) ❌
`PR` ✅
> Feat/Organization Public Pages

- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.scss
> Fix/ Time Tracking Filter Selectors

- apps/gauzy/src/app/pages/integrations/components/integrations-list/integrations-list.component.html
- apps/gauzy/src/app/pages/integrations/components/integrations-list/integrations-list.component.scss
- apps/gauzy/src/app/share/organization/organization.component.ts
> Fix: Available App Integration Selector

- apps/gauzy/src/app/@shared/components/header-title/header-title.component.ts
- apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.scss
- apps/gauzy/src/app/pages/employees/employees.component.html
- apps/gauzy/src/app/pages/employees/employees.component.scss
- apps/gauzy/src/app/pages/expenses/expenses.component.html
- apps/gauzy/src/app/pages/expenses/expenses.component.scss
- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.html
- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.scss
- apps/gauzy/src/app/pages/invoices/invoices.component.html
- apps/gauzy/src/app/pages/invoices/invoices.component.scss
- apps/gauzy/src/app/pages/payments/payments.component.html
- apps/gauzy/src/app/pages/payments/payments.component.scss
- apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.scss
- apps/gauzy/src/app/pages/tasks/components/task/task.component.html
- apps/gauzy/src/app/pages/tasks/components/task/task.component.scss
- apps/gauzy/src/app/pages/users/users.component.scss
> Fix/Double Scrollbar

- apps/gauzy/src/app/@shared/pagination/pagination-filter-base.component.ts
- apps/gauzy/src/app/pages/approval-policy/approval-policy.component.html
- apps/gauzy/src/app/pages/approvals/approvals.component.html
- apps/gauzy/src/app/pages/candidates/candidates.component.html
- apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.html
- apps/gauzy/src/app/pages/contacts/contacts.component.html
- apps/gauzy/src/app/pages/departments/departments.component.html
- apps/gauzy/src/app/pages/employees/employees.component.html
- apps/gauzy/src/app/pages/employees/event-types/event-type.component.html
- apps/gauzy/src/app/pages/equipment/equipment.component.html
- apps/gauzy/src/app/pages/expenses/expenses.component.html
- apps/gauzy/src/app/pages/income/income.component.html
- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.html
- apps/gauzy/src/app/pages/invoices/invoices.component.html
- apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.html
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.html
- apps/gauzy/src/app/pages/jobs/search/search/search.component.html
- apps/gauzy/src/app/pages/payments/payments.component.html
- apps/gauzy/src/app/pages/pipelines/pipelines.component.html
- apps/gauzy/src/app/pages/proposals/proposals.component.html
- apps/gauzy/src/app/pages/tags/tags.component.html
- apps/gauzy/src/app/pages/tasks/components/task/task.component.html
- apps/gauzy/src/app/pages/teams/teams.component.html
- apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.html
- apps/gauzy/src/app/pages/time-off/time-off.component.html
- apps/gauzy/src/app/pages/users/users.component.html
> Fix/ Pagination Not Showing

- apps/gauzy/src/app/@core/services/selector-builder/date-range-picker-builder.service.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.html
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/employees/activity/activity-routing.module.ts
- packages/core/src/shared/dto/date-range-query.dto.ts
> Fix/#4734 Screenshots Date Picker Future Disability

- packages/core/src/time-tracking/screenshot/screenshot.subscriber.ts
> Fix :: #4763 Missing required key 'Key' in params (Wasabi Provider)

- packages/core/src/time-tracking/time-log/commands/handlers/schedule-time-log-entries.handler.ts
> Fix :: #4733 Calculate time duration difference for old malicious time log entries

- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.html
- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.ts
- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.module.ts
- apps/gauzy/src/app/@theme/styles/report.scss
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-client.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-date.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-employee.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-project.handler.ts
> Fix/#4736 Time and Activity Report

- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.html
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-date.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-employee.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-project.handler.ts
> Fix/#4736 Time Activity Client Column Grid

- packages/core/src/time-tracking/screenshot/screenshot.controller.ts
- packages/core/src/time-tracking/time-log/commands/handlers/schedule-time-log-entries.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-create.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-update.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-bulk-create.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
- packages/core/src/time-tracking/timer/timer.service.ts
> Fix :: Added logger for time tracker request

- packages/core/src/core/dto/translate-base-dto.ts
> Fix :: #4775 Language validation

- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.html
- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.ts
- apps/gauzy/src/app/pages/teams/teams.component.html
- apps/gauzy/src/app/pages/teams/teams.component.scss
- apps/gauzy/src/app/pages/teams/teams.component.ts
---
`Server` ❌
`PR` ✔️
@rahul-rathore-576 as you mentioned in this pr https://github.com/ever-co/ever-gauzy/pull/4746, I have added modal for add/edit team
> feat: added dialog for add/edit team

- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
- packages/core/src/time-tracking/time-slot/utils.ts
> Fix :: Time Tracking Dashboard Statistics Query

- packages/core/src/organization-contact/organization-contact.entity.ts
> fix: client simultaneously with project

- packages/core/src/time-tracking/activity/activity.service.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
> Fix :: Time Slot Merger Command

- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
> Fix :: Daily screenshots employee relations eager default false

- apps/gauzy/src/app/@shared/components/editable-grid/gauzy-editable-grid.component.css
- apps/gauzy/src/app/@shared/components/editable-grid/gauzy-editable-grid.component.html
- apps/gauzy/src/app/@shared/components/editable-grid/gauzy-editable-grid.component.scss
- apps/gauzy/src/app/@shared/components/editable-grid/gauzy-editable-grid.component.ts
- apps/gauzy/src/app/@shared/components/editable-grid/gauzy-editable-grid.module.ts
- apps/gauzy/src/app/@shared/tasks-sprint-settings-view/sprint-dialog/sprint-dialog.component.css
- apps/gauzy/src/app/@shared/tasks-sprint-settings-view/sprint-dialog/sprint-dialog.component.html
- apps/gauzy/src/app/@shared/tasks-sprint-settings-view/sprint-dialog/sprint-dialog.component.scss
- apps/gauzy/src/app/@shared/tasks-sprint-settings-view/sprint-dialog/sprint-dialog.component.ts
- apps/gauzy/src/app/@shared/tasks-sprint-settings-view/tasks-sprint-settings-view.component.html
- apps/gauzy/src/app/@shared/tasks-sprint-settings-view/tasks-sprint-settings-view.component.scss
- apps/gauzy/src/app/@shared/tasks-sprint-settings-view/tasks-sprint-settings-view.component.ts
- apps/gauzy/src/app/@shared/tasks-sprint-settings-view/tasks-sprint-settings-view.module.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
- apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.html
- apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/project-view.component.html
- apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/project-view.component.scss
- apps/gauzy/src/app/pages/tasks/components/task/task-settings/task-settings.component.html
- apps/gauzy/src/app/pages/tasks/components/task/task-settings/task-settings.component.scss
- apps/gauzy/src/assets/i18n/en.json
> Feat/ Add new tab to manage sprint view mode

- apps/gauzy/src/app/@shared/project-select/project/project.component.html
- apps/gauzy/src/app/@shared/project-select/project/project.component.scss
- packages/contracts/src/organization-projects.model.ts
- packages/core/src/database/migrations/1655885355508-OrganizationProjectAlterTable.ts
- packages/core/src/organization-project/organization-project.entity.ts
- packages/core/src/organization-project/organization-project.subscriber.ts
> Feat :: #4805 Project Image Migration & Subscriber

- packages/core/src/equipment/equipment.controller.ts
- packages/core/src/equipment/equipment.service.ts
> fix: Organization equipment table filter

- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/time-log/commands/handlers/delete-time-span.handler.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
> Fix :: Screenshot Removed

- packages/desktop-libs/src/lib/desktop-screenshot.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> fix: desktop timer today duration and sound screenshot

- packages/contracts/src/timesheet-statistics.model.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
> Fix/Time Tracking Dashboard Projects/Tasks Statistics

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-language-selector.component.ts
---
👀 [demo ](https://www.loom.com/share/a964a51bdd454994925e914bd1ffc885)
> Fix/ Bug Automatically switch language

- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/time-log/dto/query/index.ts
- packages/core/src/time-tracking/time-log/dto/query/time-log-limit-query.dto.ts
- packages/core/src/time-tracking/time-log/dto/query/time-log-query.dto.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/timesheet/dto/query/index.ts
- packages/core/src/time-tracking/timesheet/dto/query/timesheet-query.dto.ts
- packages/core/src/time-tracking/timesheet/timesheet.controller.ts
- packages/core/src/time-tracking/timesheet/timesheet.service.ts
> Fix :: Approval Timesheets 

- apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.ts
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report.module.ts
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.html
- apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.ts
- packages/core/src/expense/dto/query/expense-report-query.dto.ts
- packages/core/src/expense/dto/query/index.ts
- packages/core/src/expense/expense.controller.ts
- packages/core/src/expense/expense.map.service.ts
- packages/core/src/expense/expense.service.ts
> Fix :: Expense Report

- apps/gauzy/src/app/@shared/legal/privacy-policy/privacy-policy.component.scss
- apps/gauzy/src/app/@shared/legal/terms-and-conditions/terms-and-conditions.component.scss
- apps/gauzy/src/app/legal/legal-routing.module.ts
- apps/gauzy/src/app/pages/legal/legal-routing.module.ts
---
👀 [demo](https://www.loom.com/share/e3bee97440654103860ead9ecf4aeb69)
> `PR` ✔️
>
> <img width="1440" alt="image" src="https://user-images.githubusercontent.com/45813955/176243040-3aac574f-2270-4ccc-910d-f1cc33f76a5b.png">
>
> <img width="1440" alt="image" src="https://user-images.githubusercontent.com/45813955/176243183-008cf037-3d86-43a4-9164-3f5d12327675.png">
> Fix/ Terms & Conditions and Privacy Policy

- apps/gauzy/src/app/@theme/theme.module.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.html
- apps/gauzy/src/app/pages/invoices/invoices.component.scss
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
> Fix/UI Estimate Page

- apps/gauzy/src/app/@shared/table-components/contact-links/contact-links.component.ts
- apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report.module.ts
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.html
- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
> Fix :: Budget Reports

- apps/gauzy/src/app/pages/employees/employees.component.ts
- packages/core/src/employee/employee.service.ts
> Fix :: #4807 Incorrect Employee Pagination

- apps/gauzy/src/app/pages/goals/goals.component.html
- apps/gauzy/src/app/pages/goals/key-result-parameters/key-result-parameters.component.html
- apps/gauzy/src/assets/i18n/en.json
---
**Task : #4836**
I have applied translation for mentioned points.
> fix: #4836 apply translation for goal module

- apps/gauzy/src/app/pages/contacts/contacts.component.ts
- packages/core/src/organization-contact/organization-contact.service.ts
> Fix :: #4857 Client pagination relational query

- packages/core/src/product-category/product-category.service.ts
- packages/core/src/product-type/product-type.service.ts
> Fix :: #4775 NOT NULL constraint failed

- apps/gauzy/src/app/@shared/currency/currency.component.html
- apps/gauzy/src/app/@shared/currency/currency.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.html
- apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.module.ts
- apps/gauzy/src/app/pages/reports/payment-report/payment-report.module.ts
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.html
- apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.ts
- packages/contracts/src/payment.model.ts
- packages/core/src/payment/dto/query/index.ts
- packages/core/src/payment/dto/query/payment-report-query.dto.ts
- packages/core/src/payment/payment.controller.ts
- packages/core/src/payment/payment.map.service.ts
- packages/core/src/payment/payment.service.ts
> Fix :: Payment Report & Invoice Payments 

- apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.html
- apps/gauzy/src/app/pages/expenses/expenses.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
- packages/core/src/expense/expense.service.ts
> Fix :: Expense Report & Expense Mutation

- apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
- packages/core/src/core/utils.ts
- packages/core/src/expense/expense.seed.ts
- packages/core/src/expense/expense.service.ts
- packages/core/src/income/income.seed.ts
- packages/core/src/invoice/invoice.seed.ts
- packages/core/src/invoice/invoice.service.ts
- packages/core/src/payment/payment.seed.ts
- packages/core/src/payment/payment.service.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-log/time-log.seed.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-bulk-create.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
- packages/core/src/time-tracking/timesheet/commands/handlers/timesheet-recalculate.handler.ts
- packages/core/src/time-tracking/timesheet/timesheet.service.ts
> Fix :: Convert dates into UTC format

- apps/gauzy/src/app/pages/equipment-sharing-policy/equipment-sharing-policy.routing.module.ts
- apps/gauzy/src/app/pages/equipment-sharing/equipment-sharing.component.html
- apps/gauzy/src/app/pages/equipment-sharing/equipment-sharing.component.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/pages.component.ts
- packages/contracts/src/equipment-sharing.model.ts
- packages/core/src/equipment-sharing/equipment-sharing.controller.ts
- packages/core/src/equipment-sharing/equipment-sharing.seed.ts
- packages/core/src/equipment-sharing/equipment-sharing.service.ts
> Fix/#4814 Equipment Sharing Pagination

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-selector/switch-theme/switch-theme.component.ts
---
👀 [Demo](https://www.loom.com/share/dafecf7faaef44f9a9c8cd7da502c200)
> Feat/Switching to OS theme color

- apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
- apps/gauzy/src/app/@core/services/auth.service.ts
- apps/gauzy/src/app/@core/services/store.service.ts
- apps/gauzy/src/app/@shared/currency/currency.component.ts
- apps/gauzy/src/app/onboarding/tenant-details/tenant-details.component.ts
- packages/config/src/environments/environment.prod.ts
- packages/config/src/environments/environment.ts
- packages/config/src/environments/ienvironment.ts
- packages/contracts/src/user.model.ts
- packages/core/src/auth/auth.controller.ts
- packages/core/src/auth/auth.module.ts
- packages/core/src/auth/auth.service.ts
- packages/core/src/auth/dto/index.ts
- packages/core/src/auth/dto/refresh-token.dto.ts
- packages/core/src/auth/strategies/index.ts
- packages/core/src/auth/strategies/jwt-refresh-token.strategy.ts
- packages/core/src/auth/strategies/jwt.strategy.ts
- packages/core/src/database/migrations/1656833636109-AlterUserTable.ts
- packages/core/src/shared/guards/auth-refresh.guard.ts
- packages/core/src/shared/guards/index.ts
- packages/core/src/user/user.entity.ts
- packages/core/src/user/user.service.ts
> Fix/#4720 Refresh token after onboarding process

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-selector/switch-theme/switch-theme.component.ts
- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-selector/switch-theme/switch-theme.service.ts
> Fix/#3984 preferred color theme OS/LocalStorage

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/layout-selector/layout-selector.component.ts
- packages/contracts/src/user.model.ts
- packages/core/src/auth/auth.service.ts
- packages/core/src/database/migrations/1656833636109-AlterUserTable.ts
- packages/core/src/user/dto/update-user.dto.ts
- packages/core/src/user/user.controller.ts
- packages/core/src/user/user.entity.ts
> Fix :: #4085 Disbled login if user is inactive

- apps/gauzy/src/app/@core/services/selector-builder/date-range-picker-builder.service.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.resolver.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/index.ts
- apps/gauzy/src/app/app.component.ts
- apps/gauzy/src/app/pages/dashboard/dashboard-routing.module.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- apps/gauzy/src/app/pages/employees/activity/activity-routing.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
- apps/gauzy/src/app/pages/expenses/expenses.component.ts
- apps/gauzy/src/app/pages/income/income.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
- apps/gauzy/src/app/pages/invoices/invoices.component.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/time-off/time-off-routing.module.ts
- packages/core/src/time-tracking/time-log/commands/handlers/schedule-time-log-entries.handler.ts
> Fix :: #4737 Date range selector route resolver

- packages/plugin/package.json
- yarn.lock
> Chore :: @nestjs/core similar version for plugin

- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.ts
- apps/gauzy/src/app/pages/proposals/proposals-routing.module.ts
> Fix :: #4737 Date range picker selected recently added date for proposals

- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
> Fix :: #4737 date range picker selected recently added date for timesheet pages

- apps/gauzy/src/app/pages/invoices/invoices-routing.module.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
> Fix :: #4737 date range picker selected recently added date for invoices

- apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.html
- apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.scss
> fix: #4910 My task page add modal UI fixed

- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.scss
- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/header.component.scss
- apps/gauzy/src/app/@theme/components/theme-sidebar/changelog/changelog.component.html
- apps/gauzy/src/app/@theme/components/theme-sidebar/changelog/changelog.component.scss
- apps/gauzy/src/app/@theme/components/theme-sidebar/changelog/changelog.component.ts
- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.scss
- apps/gauzy/src/app/auth/login/whats-new/whats-new.component.scss
> Fix/Header menu UI issue

- apps/gauzy/src/app/@shared/report/charts/line-chart/chart-utils.ts
- apps/gauzy/src/app/@shared/report/charts/line-chart/line-chart.component.ts
- apps/gauzy/src/app/@shared/single-statistic/single-statistic.component.scss
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.html
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.scss
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.ts
- apps/gauzy/src/app/pages/dashboard/dashboard-routing.module.ts
- apps/gauzy/src/app/pages/dashboard/dashboard.module.ts
- apps/gauzy/src/assets/i18n/en.json
---
👀 [demo](https://www.loom.com/share/17a73f74d2c2427a82ee1b5d76b614cc)
`PR` ✔️
`Server` ❌
> Feat/Improve UI dashboard accounting

- apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.html
- apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.html
- apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.html
- apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
- apps/gauzy/src/app/pages/contacts/contacts.component.ts
- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.html
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
- apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.html
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.ts
- apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.html
- apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.html
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.html
- apps/gauzy/src/assets/i18n/en.json
> Fix :: #4914 Empty Message Translations 

- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-timer.ts
> fix: desktop timer stop button does not work

- apps/desktop-timer/src/index.ts
- apps/desktop/src/index.ts
- packages/desktop-libs/src/index.ts
- packages/desktop-libs/src/lib/desktop-notifier.ts
- packages/desktop-libs/src/lib/desktop-updater.ts
> feat: desktop app update notify

- apps/gauzy/src/app/@shared/table-components/project-organization/project-organization.component.ts
- apps/gauzy/src/app/@shared/table-components/role/role.component.ts
- apps/gauzy/src/app/@theme/layouts/public/public.layout.ts
- apps/gauzy/src/app/pages/projects/projects.component.ts
> Fix :: Wrong workspace packages import path

- apps/gauzy/src/app/pages/import-export/import-export.component.ts
- packages/core/src/gauzy-cloud/gauzy-cloud.controller.ts
- packages/core/src/gauzy-cloud/gauzy-cloud.service.ts
- packages/core/src/organization/commands/handlers/organization.create.handler.ts
> Fix :: Cloud Migration

- apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.component.scss
- apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.component.ts
- apps/gauzy/src/app/pages/organizations/organizations.component.scss
> Fix/Organization modal UI

- apps/gauzy/package.json
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.module.ts
- package.json
- tsconfig.json
- yarn.lock
> Feature :: Integrate Swiper Angular Module

- apps/desktop-timer/src/package.json
- apps/desktop/package.json
- apps/desktop/src/package.json
- packages/core/package.json
- yarn.lock
> chore: node fetch downgrade from v3.2.9 to v2.6.7

- apps/gauzy/src/app/@shared/table-components/contact-with-tags/contact-with-tags.component.html
- apps/gauzy/src/app/@shared/table-components/contact-with-tags/contact-with-tags.component.scss
- apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.html
- apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.scss
- apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.ts
- apps/gauzy/src/app/@shared/table-components/organization-with-tags/organization-with-tags.component.html
- apps/gauzy/src/app/@shared/table-components/organization-with-tags/organization-with-tags.component.scss
- apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.ts
- apps/gauzy/src/app/@shared/table-components/tags-only/tags-only.component.html
- apps/gauzy/src/app/@shared/table-components/tags-only/tags-only.component.scss
- apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.html
- apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.scss
- apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.ts
- apps/gauzy/src/app/pages/tags/tags-color/tags-color.component.html
> Fix/Tags/Badges bg & text color

- apps/api/package.json
- apps/api/src/pm2bootstrap.ts
- apps/gauzy/src/pm2bootstrap.ts
- package.json
- packages/auth/package.json
- packages/config/package.json
- packages/config/src/default-configuration.ts
- packages/config/src/environments/environment.prod.ts
- packages/config/src/environments/environment.ts
- packages/core/package.json
> chore: dotenv from v8.2.0 to v16.0.0

- packages/core/src/product-variant/product-variant.seed.ts
> Fix :: Too many sqlite variables seeder issue

- apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.html
- apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.scss
- apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.ts
- apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.module.ts
- apps/gauzy/src/app/@shared/dashboard/records-history/records-history.component.html
- apps/gauzy/src/app/@shared/dashboard/records-history/records-history.component.scss
- apps/gauzy/src/app/@shared/dashboard/records-history/records-history.component.ts
- apps/gauzy/src/app/@shared/dashboard/records-history/records-history.module.ts
- apps/gauzy/src/app/@shared/pagination/pagination-filter-base.component.ts
- apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-dialogs.scss
> Feat/Upgrade UI dialogs hr

- packages/common/src/constants.ts
- packages/core/src/core/core.module.ts
- packages/core/src/core/seeds/seed-data.service.ts
- packages/core/src/core/seeds/seeder.module.ts
- packages/core/src/database/database-helper.ts
- packages/core/src/database/database.module.ts
> Fix/#4973 Db Seeder Logs

- packages/core/src/export-import/export/export-all.module.ts
- packages/core/src/export-import/export/export-all.service.ts
- packages/core/src/export-import/import/import-all.module.ts
> Fix :: Attempt to dependency injection for data source provider 

- packages/core/src/export-import/export/export-all.controller.ts
- packages/core/src/export-import/export/export-all.module.ts
- packages/core/src/export-import/export/export-all.service.ts
- packages/core/src/export-import/import-history/import-history.service.ts
- packages/core/src/export-import/import/import-all.controller.ts
- packages/core/src/export-import/import/import-all.module.ts
- packages/core/src/export-import/import/import-all.service.ts
> Fix :: Attempt to dependency injection for data source provider

- packages/core/src/database/database.module.ts
- packages/core/src/database/database.providers.ts
- packages/core/src/database/index.ts
- packages/core/src/export-import/export/export-all.module.ts
- packages/core/src/export-import/import/import-all.module.ts
> feat: common API connection data source providers

- apps/gauzy/src/app/@core/services/accounting-template.service.ts
- apps/gauzy/src/app/@shared/employee/employee-rates/employee-rates.component.html
- apps/gauzy/src/app/@shared/employee/employee-rates/employee-rates.component.ts
- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html
- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts
- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense.setting.ts
- apps/gauzy/src/app/pages/expense-recurring/expense-recurring.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
- apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.ts
- packages/contracts/src/recurring-expense.model.ts
- packages/core/src/accounting-template/accounting-template.controller.ts
- packages/core/src/database/database.module.ts
- packages/core/src/database/database.providers.ts
> Fix/#4981 Server Error

- packages/core/src/database/migration.ts
> Fix :: Database migration connection initialize

- apps/gauzy/src/app/@shared/dashboard/window-layout/window-layout.component.scss
- apps/gauzy/src/app/@theme/styles/styles.scss
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- packages/core/src/database/migration.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
> Feat/Add slider screenshots 

- apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
- packages/core/src/core/crud/pagination-params.ts
- packages/core/src/core/dto/tenant-base.dto.ts
- packages/core/src/core/dto/tenant-organization-base.dto.ts
- packages/core/src/database/migrations/1659618978087-AlterInvoiceEstimateHistory.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/employee/employee.service.ts
- packages/core/src/invoice-estimate-history/invoice-estimate-history.entity.ts
- packages/core/src/shared/decorators/index.ts
- packages/core/src/shared/decorators/user.decorator.ts
- packages/core/src/shared/validators/constraints/index.ts
- packages/core/src/shared/validators/constraints/is-organization-should-belongs-to.constraint.ts
- packages/core/src/shared/validators/index.ts
- packages/core/src/shared/validators/is-organization-should-belongs-to.decorator.ts
- packages/core/src/shared/validators/validator.module.ts
- packages/core/src/user-organization/user-organization.controller.ts
> Fix :: Employee Pagination & Access only belongs to organization

- apps/gauzy/src/app/pages/contacts/contacts.component.ts
> Fix :: Organization contacts pagination alias typo

- apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
> fix: bad import

- packages/core/src/contact/contact.entity.ts
- packages/core/src/database/migration.ts
- packages/core/src/database/migrations/1659618978087-AlterInvoiceEstimateHistory.ts
- packages/core/src/database/migrations/1659684413063-AlterContactTable.ts
- packages/core/src/database/migrations/1659696180759-AlterTenantTable.ts
- packages/core/src/organization-contact/organization-contact.subscriber.ts
- packages/core/src/tenant/tenant.entity.ts
> Fix :: #3841 Inappropriate Migration Detection

- packages/core/src/auth/auth.module.ts
- packages/core/src/auth/auth.service.ts
> Fix :: Used injected repository method instead of data source

- apps/gauzy/src/app/pages/employees/employees.component.ts
---
take a look 👀
https://www.loom.com/share/02f5831b45c4421da1fd2aff8dd43030
> fix: bad behavior on paginate employees

- apps/gauzy/src/app/@core/utils/smart-table/server-source.conf.ts
- apps/gauzy/src/app/@core/utils/smart-table/server.data-source.ts
- apps/gauzy/src/app/pages/time-off/time-off.component.ts
- packages/core/src/time-off-request/time-off-request.controller.ts
- packages/core/src/time-off-request/time-off-request.service.ts
> Fix :: Timeoff Request Pagination Customization

- apps/gauzy/src/app/pages/departments/departments.component.ts
- apps/gauzy/src/app/pages/projects/projects.component.ts
- apps/gauzy/src/app/pages/teams/teams.component.ts
> Fix/ Jointure Alias 👾

- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
> Fix :: Create time slot handler query optimization

- packages/core/src/time-tracking/timesheet/commands/handlers/timesheet-first-or-create.handler.ts
> Fix :: Timesheet find or create alternative timesheet

- packages/core/src/user/user.service.ts
> Fix :: Hidden password field for update user API

- apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
- packages/core/src/auth/auth.controller.ts
- packages/core/src/auth/auth.service.ts
Password Reset token returned in Response. Account takeover.
---
> Fix :: Password reset token returned in response

- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
- packages/core/src/core/file-storage/providers/wasabi-s3.provider.ts
- packages/core/src/time-tracking/screenshot/screenshot.subscriber.ts
> Fix :: #4765 Delete Screenshots Wasabi

- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> Fix :: Desktop timer request failed

- apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts
- apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.html
- apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.ts
> fix: hide proposal author for employee login

- apps/gauzy/src/app/@core/services/email-template.service.ts
- apps/gauzy/src/app/pages/settings/email-history/email-filters/email-filters.component.html
- apps/gauzy/src/app/pages/settings/email-history/email-filters/email-filters.component.ts
- apps/gauzy/src/app/pages/settings/email-history/email-history.component.html
- apps/gauzy/src/app/pages/settings/email-history/email-history.component.ts
- packages/core/src/email/email.controller.ts
- packages/core/src/email/email.entity.ts
> Fix :: Get all email template API & removed email crud controller

- packages/core/src/core/utils.ts
- packages/core/src/export-import/import/import-all.service.ts
> Fix :: timestamp column & organization missing for self  import

- apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html
- apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
- apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.html
- apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
> Fix :: Invoice items first row selected in the table

- packages/core/src/organization/commands/handlers/organization.create.handler.ts
- packages/core/src/role-permission/role-permission.controller.ts
- packages/core/src/role-permission/role-permission.service.ts
- packages/core/src/role/role.service.ts
- packages/core/src/tenant/tenant.service.ts
> Fix :: Removed deprecated get manage & used repository metadata

- packages/core/src/user/user.service.ts
> fix: refresh token query modified

- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-experience/edit-candidate-education/edit-candidate-education.component.ts
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.ts
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/table-components/index.ts
- apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-interview/edit-candidate-interview.component.ts
> Fix :: Disabled first row auto selected for candidate tables

- apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
- apps/gauzy/src/app/@core/services/auth.service.ts
- packages/core/src/user/user.service.ts
> fix: server side logout (removed refresh token)

- apps/gauzy/src/app/@core/services/warehouse.service.ts
- apps/gauzy/src/app/@shared/forms/helpers.ts
- apps/gauzy/src/app/@shared/forms/location/location-form.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/select-product-form/select-product-form.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-form/warehouse-form.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-form/warehouse-form.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-form/warehouse-form.resolver.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-products-table/warehouse-products-table.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-products-table/warehouse-products-table.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-routing.module.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses.module.ts
- packages/core/src/contact/dto/index.ts
- packages/core/src/contact/dto/relational-contact.dto.ts
- packages/core/src/database/migrations/1660988196279-AlterWarehouseProductTable.ts
- packages/core/src/tags/dto/relational-tag.dto.ts
- packages/core/src/warehouse/dto/create-warehouse.dto.ts
- packages/core/src/warehouse/dto/index.ts
- packages/core/src/warehouse/dto/update-warehouse.dto.ts
- packages/core/src/warehouse/dto/warehouse.dto.ts
- packages/core/src/warehouse/warehouse-product-service.ts
- packages/core/src/warehouse/warehouse-product-variant.entity.ts
- packages/core/src/warehouse/warehouse-product.entity.ts
- packages/core/src/warehouse/warehouse.controller.ts
- packages/core/src/warehouse/warehouse.seed.ts
> Fix :: Inventory Warehouse API

- packages/desktop-libs/src/lib/desktop-timer.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> fix: duration overall timeslot update desktop timer

- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-products-table/warehouse-products-table.component.ts
- apps/gauzy/src/assets/i18n/en.json
> Fix :: #5039 Changed empty message for warehouse products

- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-table/warehouses-table.component.ts
> Fix :: #5039 Display code column inside TABLE/GRID view 2nd point

- packages/core/src/core/crud/crud.service.ts
- packages/core/src/invite/commands/handlers/invite.accept-employee.handler.ts
- packages/core/src/invite/invite.service.ts
> Fix :: Employee/User Invitation

- apps/gauzy/src/app/@core/services/merchant.service.ts
- apps/gauzy/src/app/@core/services/warehouse.service.ts
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-form/merchant-form.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-form/merchant-form.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-form/merchant-form.resolver.ts
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-routing.module.ts
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-table/merchant-table.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant.module.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-form/warehouse-form.component.ts
- packages/contracts/src/product.model.ts
- packages/core/src/merchant/dto/create-merchant.dto.ts
- packages/core/src/merchant/dto/index.ts
- packages/core/src/merchant/dto/merchant.dto.ts
- packages/core/src/merchant/dto/update-merchant.dto.ts
- packages/core/src/merchant/merchant.controller.ts
- packages/core/src/merchant/merchant.entity.ts
- packages/core/src/warehouse/dto/index.ts
- packages/core/src/warehouse/dto/relational-warehouse.dto.ts
- packages/core/src/warehouse/warehouse.controller.ts
- packages/core/src/warehouse/warehouse.entity.ts
> Fix :: Merchant/Warehouse DTO Validation's 

- apps/gauzy/package.json
- apps/gauzy/src/app/@shared/invite/invites/invites.component.html
- apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
- apps/gauzy/src/app/@shared/invite/invites/invites.module.ts
- packages/contracts/src/invite.model.ts
- packages/core/src/invite/invite.controller.ts
- packages/core/src/invite/invite.entity.ts
- packages/core/src/merchant/merchant.entity.ts
- packages/core/src/warehouse/warehouse.entity.ts
- yarn.lock
> Fix :: Invite Copy Link

- apps/gauzy/src/app/pages/contacts/invite-contact/invite-contact.component.ts
- packages/core/src/invite/commands/handlers/invite.accept-organization-contact.handler.ts
- packages/core/src/invite/commands/handlers/invite.organization-contact.handler.ts
- packages/core/src/invite/invite.service.ts
- packages/core/src/user/commands/handlers/user.delete.handler.ts
- packages/core/src/user/commands/index.ts
- packages/core/src/user/user.controller.ts
- packages/core/src/user/user.service.ts
> Fix :: Contact invite mutation email already exist validation

- apps/gauzy/src/app/pages/expenses/expense-categories/expense-categories.component.ts
> Fix :: Jointure Alias (Expense Categories)

- apps/gauzy/src/app/@shared/expenses/recurring-expense-block/recurring-expense-block.component.html
- apps/gauzy/src/app/@shared/expenses/recurring-expense-history/recurring-expense-history.component.html
- apps/gauzy/src/app/@shared/expenses/recurring-expense-history/recurring-expense-history.component.ts
- apps/gauzy/src/app/@shared/expenses/recurring-expense-history/recurring-expense-history.module.ts
- apps/gauzy/src/app/pages/expense-recurring/expense-recurring-routing.module.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee-routing.module.ts
- apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.ts
- packages/core/src/employee-recurring-expense/employee-recurring-expense.controller.ts
> Fix :: #5063 Recurring Expense For Employee

- apps/gauzy/src/app/@shared/smtp/smtp.component.html
- apps/gauzy/src/app/@shared/smtp/smtp.component.ts
- apps/gauzy/src/app/@shared/smtp/smtp.module.ts
- apps/gauzy/src/app/pages/settings/custom-smtp/custom-smtp.component.ts
- packages/common/src/constants.ts
- packages/core/src/core/context/request-context.ts
- packages/core/src/custom-smtp/custom-smtp.controller.ts
- packages/core/src/custom-smtp/custom-smtp.entity.ts
- packages/core/src/custom-smtp/custom-smtp.module.ts
- packages/core/src/custom-smtp/custom-smtp.service.ts
- packages/core/src/custom-smtp/dto/custom-smtp.dto.ts
- packages/core/src/custom-smtp/dto/custom-smtp.query.dto.ts
- packages/core/src/custom-smtp/dto/index.ts
- packages/core/src/shared/decorators/index.ts
- packages/core/src/shared/decorators/permissions.decorator.ts
- packages/core/src/shared/decorators/permissions.ts
- packages/core/src/shared/decorators/roles.decorator.ts
- packages/core/src/shared/decorators/roles.ts
- packages/core/src/shared/decorators/user.decorator.ts
- packages/core/src/shared/guards/organization-permission.guard.ts
- packages/core/src/shared/guards/permission.guard.ts
- packages/core/src/shared/guards/role.guard.ts
- packages/core/src/shared/guards/tenant-permission.guard.ts
- packages/core/src/time-tracking/timer/timer.controller.ts
> Fix :: Roles/Permissions on controller level

- packages/core/src/database/migrations/1661599336316-AlterWarehouseMerchant.ts
> Fix :: Warehouse & Merchant many to many relation migration

- packages/contracts/src/tenant.model.ts
- packages/core/src/auth/auth.controller.ts
- packages/core/src/tenant/dto/create-tenant.dto.ts
- packages/core/src/tenant/dto/index.ts
- packages/core/src/tenant/dto/tenant.dto.ts
- packages/core/src/tenant/dto/update-tenant.dto.ts
- packages/core/src/tenant/tenant.controller.ts
- packages/core/src/tenant/tenant.entity.ts
- packages/core/src/tenant/tenant.subscriber.ts
> Fix :: Tenant controller class level permission & refactor tenant routes

- apps/desktop-timer/src/app/app.component.ts
- apps/desktop-timer/src/app/app.service.ts
- apps/desktop-timer/src/index.ts
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> fix: social login desktop timer

- packages/core/src/core/context/request-context.ts
- packages/core/src/export-import/import-record/commands/handlers/import-record-update-or-create.handler.ts
- packages/core/src/gauzy-cloud/gauzy-cloud.controller.ts
> Fix :: (Gauzy Cloud) - tenant/organization migrations fixes

- apps/gauzy/src/app/@core/services/accounting-template.service.ts
- apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.ts
- packages/contracts/src/accounting-template.model.ts
- packages/core/src/accounting-template/accounting-template.controller.ts
- packages/core/src/accounting-template/accounting-template.entity.ts
- packages/core/src/accounting-template/accounting-template.service.ts
- packages/core/src/accounting-template/dto/accounting-template-query.dto.ts
- packages/core/src/accounting-template/dto/index.ts
- packages/core/src/accounting-template/dto/save-accounting-template.dto.ts
> Fix :: Accounting Template Validation

- apps/gauzy/src/app/@core/services/email-template.service.ts
- apps/gauzy/src/app/pages/email-templates/email-templates.component.ts
- packages/core/src/accounting-template/dto/accounting-template-query.dto.ts
- packages/core/src/accounting-template/dto/save-accounting-template.dto.ts
- packages/core/src/email-template/commands/email-template.save.command.ts
- packages/core/src/email-template/dto/email-template-query.dto.ts
- packages/core/src/email-template/dto/index.ts
- packages/core/src/email-template/dto/save-email-template.dto.ts
- packages/core/src/email-template/email-template.controller.ts
- packages/core/src/email-template/email-template.entity.ts
- packages/core/src/email-template/email-template.module.ts
- packages/core/src/email-template/email-template.service.ts
> Fix :: Email Template Validation

- apps/gauzy/src/app/@core/services/role.service.ts
- apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.ts
- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.ts
- apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.ts
- apps/gauzy/src/app/@shared/invite/invite-mutation/invite-mutation.component.ts
- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.ts
- apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
- apps/gauzy/src/app/pages/settings/roles-permissions/roles-permissions.component.ts
- packages/contracts/src/role.model.ts
- packages/core/src/role/dto/index.ts
- packages/core/src/role/dto/role-feature.dto.ts
- packages/core/src/role/role.controller.ts
> Fix :: Roles API Validation

- apps/gauzy/src/app/pages/candidates/candidates.component.ts
- packages/core/src/candidate/candidate.controller.ts
- packages/core/src/candidate/candidate.entity.ts
- packages/core/src/candidate/candidate.service.ts
- packages/core/src/candidate/candidate.subscriber.ts
- packages/core/src/candidate/commands/candidate.create.command.ts
- packages/core/src/candidate/commands/candidate.update.command.ts
- packages/core/src/candidate/commands/handlers/candidate.create.handler.ts
- packages/core/src/candidate/commands/handlers/candidate.hired.handler.ts
- packages/core/src/candidate/commands/handlers/candidate.rejected.handler.ts
- packages/core/src/candidate/commands/handlers/candidate.update.handler.ts
- packages/core/src/candidate/dto/candidate-bulk-input.dto.ts
- packages/core/src/candidate/dto/create-candidate.dto.ts
- packages/core/src/employee/dto/employment.dto.ts
> Fix :: Candidate Routes Permissions

- apps/gauzy/src/app/@shared/invite/invites/invites.component.html
- apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
- apps/gauzy/src/app/@shared/table-components/index.ts
- apps/gauzy/src/app/@shared/table-components/role/role.component.html
- apps/gauzy/src/app/@shared/table-components/role/role.component.ts
- apps/gauzy/src/app/pages/users/users.component.ts
- packages/core/src/invite/dto/create-invite.dto.ts
- packages/core/src/invite/dto/find-invite-query.dto.ts
- packages/core/src/invite/dto/invite.dto.ts
- packages/core/src/invite/invite.controller.ts
- packages/core/src/invite/invite.seed.ts
- packages/core/src/invite/invite.service.ts
- packages/core/src/invite/queries/find-public-invite-by-email-token.query.ts
- packages/core/src/invite/queries/handlers/find-public-invite-by-email-token.handler.ts
> Fix :: Invite Component Pagination / Routes Validation

- packages/core/src/organization-project/organization-project.seed.ts
- packages/core/src/warehouse/warehouse.seed.ts
> Fix :: Warehouse random seeder (NOT NULL constraint failed)

- apps/gauzy/src/app/@core/services/expense-categories-store.service.ts
- apps/gauzy/src/app/@core/services/expense-categories.service.ts
- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html
- apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts
- apps/gauzy/src/app/pages/expenses/expense-categories/expense-categories.component.ts
- apps/gauzy/src/app/pages/expenses/expense-categories/expense-category-mutation/expense-category-mutation.component.ts
- packages/contracts/src/expense-category.model.ts
- packages/core/src/expense-categories/commands/expense-category-create.command.ts
- packages/core/src/expense-categories/commands/expense-category-update.command.ts
- packages/core/src/expense-categories/commands/handlers/expense-category-create.handler.ts
- packages/core/src/expense-categories/commands/handlers/expense-category-first-or-create.handler.ts
- packages/core/src/expense-categories/commands/handlers/expense-category-update.handler.ts
- packages/core/src/expense-categories/commands/handlers/index.ts
- packages/core/src/expense-categories/commands/index.ts
- packages/core/src/expense-categories/dto/create-expense-category.dto.ts
- packages/core/src/expense-categories/dto/expense-category.dto.ts
- packages/core/src/expense-categories/dto/update-expense-category.dto.ts
- packages/core/src/expense-categories/expense-categories.controller.ts
- packages/core/src/expense-categories/expense-categories.module.ts
- packages/core/src/shared/validators/constraints/index.ts
- packages/core/src/shared/validators/constraints/is-expense-category-already-exist.constraint.ts
- packages/core/src/shared/validators/index.ts
- packages/core/src/shared/validators/is-expense-category-exist.decorator.ts
- packages/core/src/shared/validators/validator.module.ts
> Fix :: Expense Category Routes Validation

- apps/gauzy/src/app/@core/services/approval-policy.service.ts
- apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.ts
- apps/gauzy/src/app/pages/approval-policy/approval-policy.component.html
- apps/gauzy/src/app/pages/approval-policy/approval-policy.component.ts
- packages/contracts/src/approval-policy.model.ts
- packages/core/src/approval-policy/approval-policy.controller.ts
- packages/core/src/approval-policy/approval-policy.entity.ts
- packages/core/src/approval-policy/approval-policy.module.ts
- packages/core/src/approval-policy/approval-policy.service.ts
- packages/core/src/approval-policy/commands/approval-policy.create.command.ts
- packages/core/src/approval-policy/commands/approval-policy.get.command.ts
- packages/core/src/approval-policy/commands/approval-policy.update.command.ts
- packages/core/src/approval-policy/commands/dto/approval-policy.dto.ts
- packages/core/src/approval-policy/commands/dto/create-approval-policy.dto.ts
- packages/core/src/approval-policy/commands/dto/index.ts
- packages/core/src/approval-policy/commands/dto/update-approval-policy.dto.ts
- packages/core/src/approval-policy/commands/handlers/approval-policy.create.handler.ts
- packages/core/src/approval-policy/commands/handlers/approval-policy.get.handler.ts
- packages/core/src/approval-policy/commands/handlers/approval-policy.update.handler.ts
- packages/core/src/core/crud/crud.controller.ts
- packages/core/src/core/crud/crud.service.ts
- packages/core/src/core/crud/pagination-params.ts
> Fix :: Approval Policy Routes Validation

- apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.ts
> Fix :: #5052 Product Type & Product Category fields are optional now (1st point)

- apps/gauzy/src/app/@core/services/product-type.service.ts
- apps/gauzy/src/app/@shared/product-type-selector/product-type-selector.component.html
- apps/gauzy/src/app/@shared/product-type-selector/product-type-selector.component.ts
- apps/gauzy/src/app/@shared/product-type-selector/product-type-selector.module.ts
- apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.html
- apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.ts
- apps/gauzy/src/app/pages/inventory/inventory.module.ts
- packages/contracts/src/product.model.ts
- packages/core/src/product-type/commands/handlers/index.ts
- packages/core/src/product-type/commands/handlers/product-type.create.handler.ts
- packages/core/src/product-type/commands/index.ts
- packages/core/src/product-type/commands/product-type.create.command.ts
- packages/core/src/product-type/product-type-translation.entity.ts
- packages/core/src/product-type/product-type.controller.ts
- packages/core/src/product-type/product-type.entity.ts
- packages/core/src/product-type/product-type.module.ts
- packages/core/src/product-type/product-type.service.ts
> Fix :: #5052 product type separate selector

- apps/gauzy/src/app/@core/services/product-category.service.ts
- apps/gauzy/src/app/@shared/product-category-selector/product-category-selector.component.html
- apps/gauzy/src/app/@shared/product-category-selector/product-category-selector.component.ts
- apps/gauzy/src/app/@shared/product-category-selector/product-category-selector.module.ts
- apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.html
- apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-product-types/product-types.component.ts
- apps/gauzy/src/app/pages/inventory/inventory.module.ts
- packages/contracts/src/product.model.ts
- packages/core/src/product-category/commands/handlers/index.ts
- packages/core/src/product-category/commands/handlers/product-category.create.handler.ts
- packages/core/src/product-category/commands/index.ts
- packages/core/src/product-category/commands/product-category.create.command.ts
- packages/core/src/product-category/product-category-translation.entity.ts
- packages/core/src/product-category/product-category.controller.ts
- packages/core/src/product-category/product-category.entity.ts
- packages/core/src/product-category/product-category.module.ts
- packages/core/src/product-category/product-category.service.ts
- packages/core/src/product-type/commands/handlers/product-type.create.handler.ts
- packages/core/src/product-type/commands/product-type.create.command.ts
- packages/core/src/product-type/product-type-translation.entity.ts
- packages/core/src/product-type/product-type.service.ts
- packages/core/src/product/product.entity.ts
> Fix :: #5052 Product Category Selector

- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/statistic/statistic.service.ts
- packages/core/src/time-tracking/time-slot/time-slot.entity.ts
- packages/core/src/time-tracking/time-slot/time-slot.subscriber.ts
> Fix :: Calculate Mouse/Keyboard activity percentage

- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.html
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.scss
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
> Fix/Weekly Timesheet

- apps/gauzy/src/app/@core/services/employees.service.ts
- apps/gauzy/src/app/@core/services/users.service.ts
- apps/gauzy/src/app/@theme/components/header/header.component.html
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/onboarding/tenant-details/tenant-details.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- apps/gauzy/src/app/pages/employees/employees.component.ts
- apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.html
- apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.ts
- apps/gauzy/src/app/pages/jobs/search/search/search.component.html
- apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/employee.model.ts
- packages/core/src/core/crud/crud.service.ts
- packages/core/src/employee/commands/get-employee-job-statistics.command.ts
- packages/core/src/employee/commands/handlers/get-employee-job-statistics.handler.ts
- packages/core/src/employee/commands/handlers/update-employee-job-search-status.handler.ts
- packages/core/src/employee/dto/employee-job-statistic.dto.ts
- packages/core/src/employee/dto/index.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/employee/employee.service.ts
- packages/core/src/user/dto/find-me-query.dto.ts
- packages/core/src/user/user.controller.ts
> WIP :: Employee Controller Level Permissions

- apps/gauzy/src/app/@core/services/employees.service.ts
- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.html
- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.ts
- apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.module.ts
- apps/gauzy/src/app/pages/employees/employees.component.ts
- apps/gauzy/src/app/pages/pages.component.ts
- packages/core/src/employee/commands/employee.bulk.create.command.ts
- packages/core/src/employee/commands/employee.create.command.ts
- packages/core/src/employee/commands/employee.get.command.ts
- packages/core/src/employee/commands/handlers/employee.bulk.create.handler.ts
- packages/core/src/employee/commands/handlers/employee.create.handler.ts
- packages/core/src/employee/dto/employment.dto.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/employee/employee.module.ts
- packages/core/src/employee/employee.service.ts
- packages/core/src/user-organization/user-organization.services.ts
> Fix :: Employee API Routes Validate Permissions

- .editorconfig
- apps/gauzy/src/app/pages/inventory/components/inventory-table-components/description/description.component.css
- apps/gauzy/src/app/pages/inventory/components/inventory-table-components/description/description.component.html
- apps/gauzy/src/app/pages/inventory/components/inventory-table-components/description/description.component.ts
- apps/gauzy/src/app/pages/inventory/components/inventory-table-components/inventory-table-components.module.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/manage-variants-quantity-form/manage-variants-quantity-form.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/manage-variants-quantity-form/manage-variants-quantity-form.component.scss
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/manage-variants-quantity/manage-variants-quantity.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/manage-variants-quantity/manage-variants-quantity.component.scss
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/manage-variants-quantity/manage-variants-quantity.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/select-product-form/select-product-form.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/select-product-form/select-product-form.component.scss
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/select-product-form/select-product-form.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-form/warehouse-form.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-form/warehouse-form.component.scss
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-products-table/warehouse-products-table.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-products-table/warehouse-products-table.component.scss
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouse-products-table/warehouse-products-table.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-table/warehouses-table.component.ts
---
Take a look on [demo](https://www.loom.com/share/81fb8a906f314a0b84fa7805525c7f47)
`PR`
`Server`
> Fix/#5039 UI inventory warehouse

- apps/gauzy/src/app/pages/employees/employees.component.html
> Fix: Bad behaviour on scrolling employee grid card layout

- packages/desktop-libs/src/lib/desktop-ipc.ts
---
[Screencast from 09-15-2022 11:43:34 AM.webm](https://user-images.githubusercontent.com/45813955/190372413-5d6a2c36-5684-4690-b5c7-ab27e93f0e37.webm)
> fix: linux bug on expand windows

- apps/gauzy/src/app/@core/services/organizations.service.ts
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-location/edit-organization-location.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.resolver.ts
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations-mutation/edit-user-organizations-mutation.component.ts
- apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.ts
> Fix :: Broken Organization Routes

- apps/gauzy/src/app/@shared/forms/maps/leaflet/leaflet.component.ts
> Fix :: Map not found (leaflet map)

- apps/gauzy/src/app/@core/resolvers/employee-count.resolver.ts
- apps/gauzy/src/app/@core/resolvers/index.ts
- apps/gauzy/src/app/@core/services/employees.service.ts
- apps/gauzy/src/app/@shared/report/daily-statistics/daily-statistics/daily-statistics.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/organization/organization.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-routing.module.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-location/edit-organization-location.component.html
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-location/edit-organization-location.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.html
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.html
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.html
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.module.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.resolver.ts
- apps/gauzy/src/app/pages/organizations/organizations-routing.module.ts
- apps/gauzy/src/app/pages/organizations/organizations.module.ts
> Fix :: Organization (Route Resolver)

- apps/gauzy/src/app/@shared/table-components/role/role.component.html
- apps/gauzy/src/app/@shared/table-components/role/role.component.ts
- apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
> Fix :: Displayed missing role badge

- packages/core/src/employee/employee.controller.ts
- packages/core/src/employee/employee.service.ts
- packages/core/src/employee/employee.subscriber.ts
- packages/core/src/organization/organization.controller.ts
- packages/core/src/organization/organization.entity.ts
- packages/core/src/organization/organization.seed.ts
> Fix  :: Employee Entity Subscriber

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
> Fix :: Time tracking dashboard title when there is no employee

- apps/desktop-timer/src/app/app.module.ts
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-notifier.ts
- packages/desktop-ui-lib/src/index.ts
- packages/desktop-ui-lib/src/lib/electron/services/electron/electron.service.ts
- packages/desktop-ui-lib/src/lib/image-viewer/image-viewer.component.ts
- packages/desktop-ui-lib/src/lib/screen-capture/screen-capture.component.ts
- packages/desktop-ui-lib/src/lib/server-dashboard/server-dashboard.component.ts
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
- packages/desktop-ui-lib/src/lib/setup/setup.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/updater/updater.component.ts
> Fix/Screen Permission On macOS

- apps/gauzy/src/app/pages/settings/feature/feature-routing.module.ts
- apps/gauzy/src/app/pages/settings/settings-routing.module.ts
> Fix :: Feature menu component missing routes permissions

- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
- apps/gauzy/src/app/pages/jobs/jobs-routing.module.ts
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template-routing.module.ts
- packages/core/src/employee/employee.service.ts
> Fix :: Proposal Template missing employee selector

- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.scss
> fix: show arrow on recent activity  window for employee

- apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.html
- apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.scss
> fix: truncate name of company in sidebar

- apps/gauzy/src/app/@core/services/email.service.ts
- apps/gauzy/src/app/pages/settings/email-history/email-history.component.ts
- packages/core/src/email/dto/update-email.dto.ts
- packages/core/src/email/email.controller.ts
- packages/core/src/email/email.entity.ts
- packages/core/src/email/email.module.ts
- packages/core/src/email/email.service.ts
- packages/core/src/user-organization/user-organization.services.ts
> Fix :: Email History (Permissions)

- apps/gauzy/src/app/@core/services/employee-award.service.ts
- apps/gauzy/src/app/@shared/employee/public-page-employee-mutation/public-page-employee-mutation.component.ts
- apps/gauzy/src/app/share/employee/employee.component.ts
- apps/gauzy/src/app/share/employee/public-employee.resolver.ts
- packages/contracts/src/employee-award.model.ts
- packages/contracts/src/employee.model.ts
- packages/core/src/core/dto/tenant-base.dto.ts
- packages/core/src/core/dto/tenant-organization-base.dto.ts
- packages/core/src/employee-award/dto/create-employee-award.dto.ts
- packages/core/src/employee-award/dto/index.ts
- packages/core/src/employee-award/dto/update-employee-award.dto.ts
- packages/core/src/employee-award/employee-award.controller.ts
- packages/core/src/employee-award/employee-award.entity.ts
- packages/core/src/employee-award/employee-award.module.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/public-share/employee/dto/public-employee-query.dto.ts
- packages/core/src/public-share/employee/public-employee.service.ts
> Fix :: Employee Award routes validation

- apps/gauzy/src/app/@core/services/candidate-documents.service.ts
- packages/core/src/candidate-documents/candidate-documents.controller.ts
> Fix :: Candidate documents permissions

- apps/desktop-timer/src/package.json
- packages/desktop-libs/package.json
- packages/desktop-libs/src/lib/contexts/current-application.ts
- packages/desktop-libs/src/lib/contexts/data-application.ts
- packages/desktop-libs/src/lib/desktop-active-window.ts
- packages/desktop-libs/src/lib/desktop-event-counter.ts
- packages/desktop-libs/src/lib/desktop-timer.ts
- packages/desktop-libs/src/lib/interfaces/i-current-application.ts
- packages/desktop-libs/src/lib/interfaces/i-data-application.ts
- packages/desktop-libs/src/lib/interfaces/serializable.ts
- yarn.lock
> Fix/Desktop Timer Activities

- packages/core/src/core/context/request-context.ts
- packages/core/src/core/crud/tenant-aware-crud.service.ts
> Fixed :: Failed Registration 

- apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.scss
> Fix: Tooltip Position

- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.html
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.ts
> Fix :: Accouting dashboard

- apps/gauzy/src/app/@core/services/candidate-skills.service.ts
- packages/contracts/src/candidate-skill.model.ts
- packages/contracts/src/candidate.model.ts
- packages/core/src/candidate-skill/candidate-skill.controller.ts
- packages/core/src/candidate-skill/candidate-skill.entity.ts
- packages/core/src/candidate-skill/dto/create-candidate-skill.dto.ts
- packages/core/src/candidate-skill/dto/index.ts
- packages/core/src/candidate-skill/dto/update-candidate-skill.dto.ts
- packages/core/src/candidate/dto/candidate-feature.dto.ts
- packages/core/src/candidate/dto/index.ts
> Fix :: Candidate skill routes validation DTO's

- apps/desktop-timer/src/index.ts
- packages/desktop-libs/src/lib/desktop-updater.ts
> Fix: Error on Update

- apps/gauzy/src/app/@core/services/candidate-source.service.ts
- packages/contracts/src/candidate-source.model.ts
- packages/core/src/candidate-skill/candidate-skill.controller.ts
- packages/core/src/candidate-source/candidate-source.controller.ts
- packages/core/src/candidate-source/candidate-source.entity.ts
- packages/core/src/candidate-source/candidate-source.service.ts
- packages/core/src/candidate-source/dto/candidate-source-bulk-input.dto.ts
- packages/core/src/candidate-source/dto/create-candidate-source.dto.ts
- packages/core/src/candidate-source/dto/index.ts
- packages/core/src/candidate-source/dto/update-candidate-source.dto.ts
> Fix :: Candidate source routes validation DTO's

- apps/gauzy/src/app/@core/services/candidate-educations.service.ts
- packages/core/src/candidate-documents/candidate-documents.controller.ts
- packages/core/src/candidate-education/candidate-education.controller.ts
- packages/core/src/candidate-education/candidate-education.entity.ts
- packages/core/src/candidate-education/candidate-education.module.ts
- packages/core/src/candidate-education/dto/create-candidate-education.dto.ts
- packages/core/src/candidate-education/dto/index.ts
- packages/core/src/candidate-education/dto/update-candidate-education.dto.ts
> Fix :: Candidate education routes validation DTO's

- apps/gauzy/src/app/@core/services/candidate-experience.service.ts
- packages/core/src/candidate-education/candidate-education.controller.ts
- packages/core/src/candidate-experience/candidate-experience.controller.ts
- packages/core/src/candidate-experience/candidate-experience.entity.ts
- packages/core/src/candidate-experience/candidate-experience.service.ts
- packages/core/src/candidate-experience/dto/create-candidate-experience.dto.ts
- packages/core/src/candidate-experience/dto/index.ts
- packages/core/src/candidate-experience/dto/update-candidate-experience.dto.ts
- packages/core/src/core/crud/crud.service.ts
> Fix :: Candidate experience routes validation DTO's

- apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-criterions-form/candidate-criterions-form.component.scss
> fix: ui dark theme color issue

- packages/contracts/src/candidate-feedback.model.ts
- packages/contracts/src/candidate-interview.model.ts
- packages/contracts/src/candidate-interviewers.model.ts
- packages/core/src/candidate-feedbacks/candidate-feedbacks.entity.ts
- packages/core/src/candidate-feedbacks/dto/create-candidate-feedback.dto.ts
- packages/core/src/candidate-feedbacks/dto/index.ts
- packages/core/src/candidate-feedbacks/dto/update-candidate-feedback.dto.ts
- packages/core/src/candidate-interview/dto/candidate-interview-feature.dto.ts
- packages/core/src/candidate-interview/dto/index.ts
- packages/core/src/candidate-interviewers/dto/candidate-interviewer-feature.dto.ts
- packages/core/src/candidate-interviewers/dto/index.ts
- packages/core/src/candidate-interviewers/dto/interviewer-feature.dto.ts
- packages/core/src/database/migrations/1664869127437-AlterCandidateFeedbackTable.ts
---
Note: Integrate DTOs into the controller in next PR.
> Wip :: Candidate Feedback (Routes Validation)

- packages/core/src/candidate-interview/candidate-interview.entity.ts
- packages/core/src/candidate-interview/dto/create-candidate-interview.dto.ts
- packages/core/src/candidate-interview/dto/index.ts
- packages/core/src/candidate-interview/dto/update-candidate-interview.dto.ts
- packages/core/src/database/migrations/1665044607000-AlterCandidateInterviewTable.ts
> Fix :: Candidate Interview DTO's  

- apps/gauzy/src/app/@core/services/candidate-interview.service.ts
- apps/gauzy/src/app/@shared/candidate/candidate-calendar-info/candidate-calendar-info.component.html
- apps/gauzy/src/app/@shared/candidate/candidate-calendar-info/candidate-calendar-info.component.ts
- packages/core/src/candidate-interview/candidate-interview.controller.ts
- packages/core/src/candidate-interview/candidate-interview.service.ts
> Fix :: Candidate Interview Permissions

- packages/desktop-libs/src/lib/desktop-notifier.ts
> refactor: desktop-notifier with better organization code

- apps/gauzy/src/app/pages/dashboard/human-resources/employee-charts/employee-charts.component.scss
> Fix :: Align Chart Type dropdown with text

- packages/core/src/email/email.module.ts
- packages/core/src/invoice/invoice.module.ts
- packages/core/src/payment/payment.module.ts
- packages/core/src/time-tracking/time-log/time-log.module.ts
> Fixed :: Failed Seeder Commands 

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/layout-selector/layout-selector.component.scss
Fixes #5194 
https://user-images.githubusercontent.com/76220055/194603567-00a4bc16-e2f6-41eb-bf74-86ec29da7661.mp4
https://user-images.githubusercontent.com/76220055/194603629-69eab694-1b12-4cf0-89bc-1a8073ac5066.mp4
---
> Fix:: Layout dropdown Cards Grid is in two rows

- apps/gauzy/src/app/@core/services/merchant.service.ts
- apps/gauzy/src/app/pages/inventory/components/inventory-table-components/index.ts
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-routing.module.ts
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-table/merchant-table.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-table/merchant-table.component.ts
- apps/gauzy/src/app/pages/inventory/components/table-inventory-items/table-inventory.component.html
- apps/gauzy/src/app/pages/inventory/components/table-inventory-items/table-inventory.component.ts
- packages/contracts/src/contact.model.ts
- packages/contracts/src/image-asset.model.ts
- packages/contracts/src/index.ts
- packages/contracts/src/product.model.ts
- packages/core/src/core/crud/crud.controller.ts
- packages/core/src/image-asset/image-asset.entity.ts
- packages/core/src/merchant/dto/create-merchant.dto.ts
- packages/core/src/merchant/dto/merchant.dto.ts
- packages/core/src/merchant/dto/update-merchant.dto.ts
- packages/core/src/merchant/merchant.controller.ts
- packages/core/src/merchant/merchant.entity.ts
- packages/core/src/merchant/merchant.module.ts
- packages/core/src/merchant/merchant.service.ts
> Fix :: Merchants Routes (Validations/Permissions)

- apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/components/theme-selector/theme-selector.component.scss
Fixes #5209 
https://user-images.githubusercontent.com/76220055/194699759-03e19378-f754-4941-ad02-df4e755cadb0.mp4
https://user-images.githubusercontent.com/76220055/194699763-ff5fa4e4-afb5-4248-9656-59944d134664.mp4
---
> feat: Theme is showing in one row

- apps/gauzy/src/app/@core/services/warehouse.service.ts
- apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-form/merchant-form.component.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-routing.module.ts
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-table/warehouses-table.component.html
- apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-table/warehouses-table.component.ts
- packages/contracts/src/product.model.ts
- packages/core/src/contact/dto/relational-contact.dto.ts
- packages/core/src/database/migrations/1665388204010-AlterWarehouseTable.ts
- packages/core/src/warehouse/dto/create-warehouse.dto.ts
- packages/core/src/warehouse/dto/update-warehouse.dto.ts
- packages/core/src/warehouse/dto/warehouse.dto.ts
- packages/core/src/warehouse/warehouse.controller.ts
- packages/core/src/warehouse/warehouse.entity.ts
- packages/core/src/warehouse/warehouse.service.ts
> Fix :: Product Warehouse Routes (Permission Level)

- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/organization.model.ts
- packages/core/src/database/migrations/1665399395983-AlterOrganizationTable.ts
- packages/core/src/organization/organization.entity.ts
> Feat/#5217 Gauzy Timer Settings

- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
---
🍂 Employee should not launch timer if he is not allowed.
> Fix: Starting Desktop Timer Issue

- packages/core/src/gauzy-cloud/gauzy-cloud.module.ts
- packages/core/src/organization/commands/handlers/organization.create.handler.ts
- packages/core/src/organization/organization.module.ts
- packages/core/src/role/role.module.ts
- packages/core/src/tenant/tenant.controller.ts
- packages/core/src/tenant/tenant.module.ts
- packages/core/src/tenant/tenant.service.ts
- packages/core/src/user-organization/user-organization.services.ts
> Fix :: Organization Create

- packages/desktop-libs/src/lib/decorators/concretes/power-manager-detect-inactivity.ts
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-os-inactivity-handler.ts
- packages/desktop-libs/src/lib/desktop-store.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> Fix/Desktop Timer Managed By Gauzy UI

- apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.html
- apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.ts
- apps/gauzy/src/app/onboarding/tenant-details/tenant-details.component.html
- apps/gauzy/src/app/onboarding/tenant-details/tenant-details.component.ts
- apps/gauzy/src/assets/i18n/en.json
---
@evereq This is incomplete PR, but still stable code. So i am going to merge this PR. We will do the rest code in next PR.
> WIP :: Register as employee

- apps/gauzy/src/app/@core/services/organization-teams.service.ts
- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.html
- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.ts
- apps/gauzy/src/app/pages/teams/teams.component.ts
- packages/contracts/src/role.model.ts
- packages/core/src/organization-team/dto/create-organization-team.dto.ts
- packages/core/src/organization-team/dto/index.ts
- packages/core/src/organization-team/dto/organization-team.dto.ts
- packages/core/src/organization-team/dto/update-organization-team.dto.ts
- packages/core/src/organization-team/organization-team.controller.ts
- packages/core/src/organization-team/organization-team.entity.ts
- packages/core/src/organization-team/organization-team.service.ts
> Fix :: Organization Team Routes

- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.ts
> Fix :: Create Team (Mutation Required Validation)

- packages/core/src/time-tracking/timer/dto/index.ts
- packages/core/src/time-tracking/timer/dto/stop-timer.dto.ts
- packages/core/src/time-tracking/timer/timer.controller.ts
- packages/core/src/time-tracking/timer/timer.service.ts
> Fix :: Stop Time Tracking (Request Validation) 

- apps/gauzy/src/app/pages/dashboard/team/chart/chart.component.ts
> Fix: Translation Issue On Change Language Team Chart

- apps/gauzy/src/app/onboarding/onboarding-complete/onboarding-complete.component.html
- apps/gauzy/src/app/onboarding/onboarding-complete/onboarding-complete.component.scss
> feat: improve onboarding complete component

- apps/gauzy/src/app/@shared/components/avatar/avatar.component.scss
- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.html
- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.scss
- apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.ts
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
---
`PR ✔️`
`Server ❌`
Closes #5228
> Fix/Dashboard Avatars

- apps/gauzy/src/app/@shared/components/avatar/avatar.component.scss
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
> fix: avatar ui on time tracking activity

- packages/core/src/tenant/tenant.controller.ts
> Fix :: Tenant controller removed tenant permission guard

- apps/desktop-timer/src/index.ts
> Fix: multiple instance for windows and linux OS

- packages/contracts/src/organization.model.ts
- packages/core/src/core/dto/tenant-organization-base.dto.ts
- packages/core/src/database/migrations/1666181221327-AlterOrganizationTable.ts
- packages/core/src/organization/dto/create-organization.dto.ts
- packages/core/src/organization/dto/organization-bonuses.dto.ts
- packages/core/src/organization/dto/organization-find-query.dto.ts
- packages/core/src/organization/dto/organization-public-setting.dto.ts
- packages/core/src/organization/dto/organization-setting.dto.ts
- packages/core/src/organization/dto/update-organization.dto.ts
- packages/core/src/organization/organization.controller.ts
- packages/core/src/organization/organization.entity.ts
> Fix :: Organization for swagger documentation (dto validation)

- packages/contracts/src/tenant.model.ts
- packages/core/src/tenant/dto/create-tenant.dto.ts
- packages/core/src/tenant/dto/tenant.dto.ts
- packages/core/src/tenant/tenant.controller.ts
> Fix :: Tenant swagger create/update request DTO validation

- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-location/edit-organization-location.component.ts
> Fix :: Empty organization location undefined property

- packages/desktop-libs/src/lib/desktop-timer.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> Fix/Desktop Timer Counter

- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/time-log/dto/query/time-log-query.dto.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
> Fix :: Timelog Team Filters

- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> fix: time format and absolute error

- packages/contracts/src/base-entity.model.ts
- packages/contracts/src/employee.model.ts
- packages/contracts/src/index.ts
- packages/core/src/database/migrations/1666780716428-AlterEmployeeTable.ts
- packages/core/src/employee/dto/employment.dto.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/employee/employee.service.ts
- packages/core/src/employee/employee.subscriber.ts
> Fix :: Employee Time Tracking Setting (Enabled/Disabled)

- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
> fix: bad hours computation

- apps/gauzy/src/app/pages/dashboard/team/all-team/all-team.component.html
- apps/gauzy/src/app/pages/dashboard/team/all-team/all-team.component.scss
- apps/gauzy/src/app/pages/dashboard/team/all-team/all-team.component.ts
- apps/gauzy/src/app/pages/dashboard/team/chart/chart.component.ts
- apps/gauzy/src/app/pages/dashboard/team/team-card/team-card.component.html
- apps/gauzy/src/app/pages/dashboard/team/team-card/team-card.component.scss
- apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.html
- apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.scss
- apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.ts
- apps/gauzy/src/app/pages/dashboard/team/team.component.html
- apps/gauzy/src/app/pages/dashboard/team/team.component.scss
- apps/gauzy/src/app/pages/dashboard/team/team.component.ts
- apps/gauzy/src/app/pages/dashboard/team/team.module.ts
- apps/gauzy/src/assets/i18n/en.json
> feat: Improve teams dashboard

- apps/gauzy/src/app/@theme/styles/_overrides.scss
- apps/gauzy/src/app/@theme/styles/themes.scss
> feat: create color for table border

- apps/desktop-timer/package.json
- apps/desktop/package.json
- package.json
- yarn.lock
> Fix/#5295 Upgrade Electron Builder

- apps/gauzy/src/assets/i18n/en.json
- packages/core/src/organization/organization.entity.ts
> Fix/Timer Settings

- packages/common/src/utils/shared-utils.ts
- packages/core/src/core/utils.ts
- packages/core/src/employee/employee.subscriber.ts
> Feat :: Generate invite code method

- .github/workflows/desktop-app.yml
- .github/workflows/desktop-timer-app.yml
- .github/workflows/server.yml
> chore: update to Windows 2022 + latest node

- apps/gauzy/src/app/@shared/smtp/smtp.component.html
- apps/gauzy/src/app/@shared/smtp/smtp.component.ts
- apps/gauzy/src/app/pages/settings/custom-smtp/custom-smtp.component.ts
- packages/core/src/core/decorators/is-secret.ts
- packages/core/src/custom-smtp/commands/custom-smtp.create.command.ts
- packages/core/src/custom-smtp/commands/custom-smtp.update.command.ts
- packages/core/src/custom-smtp/commands/handlers/custom-smtp.create.handler.ts
- packages/core/src/custom-smtp/commands/handlers/custom-smtp.update.handler.ts
- packages/core/src/custom-smtp/custom-smtp.controller.ts
- packages/core/src/custom-smtp/custom-smtp.service.ts
- packages/core/src/custom-smtp/dto/custom-smtp.dto.ts
- packages/core/src/custom-smtp/dto/custom-smtp.query.dto.ts
> Fix :: Custom Smtp Secret

- apps/gauzy/src/app/@shared/smtp/smtp.component.html
- apps/gauzy/src/app/@shared/smtp/smtp.component.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/common/src/interfaces/ISMTPConfig.ts
- packages/config/src/environments/environment.prod.ts
- packages/config/src/environments/environment.ts
- packages/contracts/src/custom-smtp.model.ts
- packages/core/src/custom-smtp/custom-smtp.entity.ts
- packages/core/src/custom-smtp/custom-smtp.service.ts
- packages/core/src/custom-smtp/dto/custom-smtp.dto.ts
- packages/core/src/database/migrations/1668256889786-AlterCustomSmtpTable.ts
- packages/core/src/email/email.service.ts
> Fix :: Custom Smtp (From Email Address)

- apps/desktop-timer/src/package.json
- apps/desktop/src/package.json
- apps/server/src/package.json
> chore: let's try array as publish target in Electron apps

- apps/gauzy/src/app/onboarding/tenant-details/tenant-details.component.ts
- packages/core/src/employee/employee.service.ts
> Fix :: Employee Selector Visibility (Register As Employee)

- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.html
- apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.ts
- apps/gauzy/src/assets/i18n/bg.json
> Fix :: Dashboard (Accouting/HR) Tab

- apps/gauzy/src/app/pages/employees/event-types/event-type.component.ts
- apps/gauzy/src/app/pages/expenses/expenses.component.ts
- apps/gauzy/src/app/pages/income/income.component.ts
- apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts
- apps/gauzy/src/app/pages/proposals/proposals.component.ts
> Fixx :: Missing employee column for register as employee feature

- apps/gauzy/src/app/@shared/pipes/date-format.pipe.ts
- apps/gauzy/src/app/@shared/table-components/date-view/date-view.component.ts
- apps/gauzy/src/app/pages/dashboard/project-management/project-management-details/project-management-details.component.html
- apps/gauzy/src/app/pages/dashboard/project-management/project-management-details/project-management-details.component.ts
- apps/gauzy/src/app/pages/income/income.component.ts
> Fix :: Project Management Details

- apps/desktop-timer/src/index.ts
- packages/desktop-window/src/lib/desktop-window-image-viewer.ts
- packages/desktop-window/src/lib/desktop-window-server.ts
- packages/desktop-window/src/lib/desktop-window-setting.ts
- packages/desktop-window/src/lib/desktop-window-setup.ts
- packages/desktop-window/src/lib/desktop-window-timer.ts
- packages/desktop-window/src/lib/desktop-window-updater.ts
- packages/desktop-window/src/lib/desktop-window.ts
---
https://www.electronjs.org/blog/electron-20-0
> fix: windows app automayically close after clicked on start

- apps/desktop-timer/src/index.ts
- apps/desktop-timer/src/sentry.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
---
https://sentry.io/organizations/ever-co/issues/3741324016/?project=4397292&query=is%3Aunresolved&referrer=issue-stream
> fix: configure and catch electron errors with sentry

- apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.ts
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/employee/dto/employee-feature.dto.ts
- packages/core/src/shared/dto/relations-query.dto.ts
- packages/core/src/time-tracking/timer/dto/index.ts
- packages/core/src/time-tracking/timer/dto/timer-status-query.dto.ts
- packages/core/src/time-tracking/timer/timer.controller.ts
- packages/core/src/time-tracking/timer/timer.service.ts
> Fix :: Time Tracker Status (Active Task & Project)

- packages/core/src/app.module.ts
- packages/core/src/auth/auth.controller.ts
- packages/core/src/candidate/candidate.controller.ts
- packages/core/src/core/interceptors/transform.interceptor.ts
- packages/core/src/custom-smtp/custom-smtp.controller.ts
- packages/core/src/email/email.controller.ts
- packages/core/src/employee-statistics/employee-statistics.controller.ts
- packages/core/src/employee/employee.controller.ts
- packages/core/src/export-import/import/import-all.controller.ts
- packages/core/src/health-indicator/health.controller.ts
- packages/core/src/home/home.controller.ts
- packages/core/src/invite/invite.controller.ts
- packages/core/src/organization-team-employee/organization-team-employee.controller.ts
- packages/core/src/organization-team/organization-team.controller.ts
- packages/core/src/password-reset/dto/reset-password-request.dto.ts
- packages/core/src/role/role.controller.ts
- packages/core/src/tasks/task.controller.ts
- packages/core/src/time-tracking/screenshot/screenshot.controller.ts
- packages/core/src/time-tracking/statistic/statistic.controller.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-slot/time-slot.controller.ts
- packages/core/src/time-tracking/timer/timer.controller.ts
- packages/core/src/time-tracking/timesheet/timesheet.controller.ts
- packages/core/src/user-organization/user-organization.controller.ts
- packages/core/src/user/commands/handlers/user.create.handler.ts
- packages/core/src/user/commands/user.create.command.ts
- packages/core/src/user/commands/user.delete.command.ts
- packages/core/src/user/dto/create-user.dto.ts
- packages/core/src/user/user.controller.ts
> Fix :: Global transform interceptor (exclude fields from response)

- apps/desktop-timer/src/index.ts
- packages/desktop-libs/src/lib/decorators/concretes/power-manager-detect-inactivity.ts
---
https://www.loom.com/share/4989df691b964113ad33922735a75b1a
> Fix/Remove Dialog When Second Instance Triggered

- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.html
- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.ts
- apps/gauzy/src/app/pages/teams/teams.component.ts
- packages/contracts/src/organization-team-model.ts
- packages/core/src/organization-team/dto/create-organization-team.dto.ts
- packages/core/src/organization-team/dto/organization-team.dto.ts
- packages/core/src/organization-team/dto/update-organization-team.dto.ts
- packages/core/src/organization-team/organization-team.controller.ts
- packages/core/src/organization-team/organization-team.service.ts
- packages/core/src/shared/validators/constraints/index.ts
- packages/core/src/shared/validators/constraints/is-team-already-exist.constraint.ts
- packages/core/src/shared/validators/index.ts
- packages/core/src/shared/validators/is-team-already-exist.decorator.ts
- packages/core/src/shared/validators/validator.module.ts
> Fix :: Prevent duplicate organization team

- apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.html
- packages/contracts/src/base-entity.model.ts
- packages/contracts/src/index.ts
- packages/contracts/src/organization-team-employee-model.ts
- packages/contracts/src/organization-team-model.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/organization-team/dto/index.ts
- packages/core/src/organization-team/dto/organization-team-statistic.dto.ts
- packages/core/src/organization-team/organization-team.controller.ts
- packages/core/src/organization-team/organization-team.module.ts
- packages/core/src/organization-team/queries/get-organization-team-statistic.query.ts
- packages/core/src/organization-team/queries/handlers/get-organization-team-statistic.handler.ts
- packages/core/src/organization-team/queries/handlers/index.ts
- packages/core/src/organization-team/queries/index.ts
- packages/core/src/shared/dto/relations-query.dto.ts
- packages/core/src/time-tracking/timer/timer.controller.ts
- packages/core/src/time-tracking/timer/timer.service.ts
> Fix :: Organization team timer status statistics

- packages/core/src/tasks/task.entity.ts
> Fix (Column) :: Exposed Task Prefix

- apps/desktop-timer/src/index.ts
- packages/desktop-libs/src/index.ts
- packages/desktop-libs/src/lib/contexts/index.ts
- packages/desktop-libs/src/lib/contexts/sleep-tracking.ts
- packages/desktop-libs/src/lib/contexts/update-context.ts
- packages/desktop-libs/src/lib/decorators/abstracts/base-cdn-decorator.ts
- packages/desktop-libs/src/lib/decorators/concretes/digital-ocean-cdn.ts
- packages/desktop-libs/src/lib/decorators/concretes/github-cdn.ts
- packages/desktop-libs/src/lib/decorators/index.ts
- packages/desktop-libs/src/lib/interfaces/i-desktop-cdn-update.ts
- packages/desktop-libs/src/lib/interfaces/i-desktop-update.ts
- packages/desktop-libs/src/lib/interfaces/i-updater-config.ts
- packages/desktop-libs/src/lib/interfaces/index.ts
- packages/desktop-libs/src/lib/strategies/abstracts/sleep-tracking-strategy.ts
- packages/desktop-libs/src/lib/strategies/abstracts/update-strategy.ts
- packages/desktop-libs/src/lib/strategies/concretes/cdn-update.ts
- packages/desktop-libs/src/lib/strategies/concretes/local-update.ts
- packages/desktop-libs/src/lib/strategies/index.ts
- packages/desktop-ui-lib/src/lib/settings/settings.component.html
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
---
> This PR adds many options for updating the application.
> It offers the possibility to implement new CDN download servers as much as we want without modifying the existing code.  it also offers the possibility of updating the application locally.
> In the next PR I will update the UI to allow to configure CDN servers for download, Github or Digital Ocean and/or locally and i will remove duplicated code for Gauzy Desktop and Gauzy Server
> Feat/switch GitHub CDN to Digital Ocean CDN

- packages/core/src/invite/invite.controller.ts
- packages/core/src/invite/invite.service.ts
> Fix :: Get Team Memebers Invite

- apps/gauzy/src/app/auth/accept-invite/accept-invite.component.ts
- packages/contracts/src/invite.model.ts
- packages/contracts/src/user.model.ts
- packages/core/src/auth/auth.service.ts
- packages/core/src/invite/commands/handlers/invite-accept.handler.ts
- packages/core/src/invite/commands/handlers/invite.accept-user.handler.ts
- packages/core/src/invite/invite.controller.ts
- packages/core/src/invite/invite.service.ts
> Fix :: Improved Invite Flow (Gauzy UI)

- packages/core/src/time-tracking/activity/commands/handlers/bulk-activities-save.handler.ts
> Fix :: Removed Blank (Timer Activities)

- packages/contracts/src/user.model.ts
- packages/core/src/auth/auth.service.ts
- packages/core/src/database/migrations/1669366070058-AlterUserInviteTable.ts
- packages/core/src/invite/invite.entity.ts
- packages/core/src/user/user.entity.ts
> Feat :: User Invite Relationship (Tables)

- packages/contracts/src/invite.model.ts
- packages/core/src/core/seeds/data/default-email-templates/invite-gauzy-teams/bg/html.mjml
- packages/core/src/core/seeds/data/default-email-templates/invite-gauzy-teams/en/html.mjml
- packages/core/src/core/seeds/data/default-email-templates/invite-gauzy-teams/he/html.mjml
- packages/core/src/core/seeds/data/default-email-templates/invite-gauzy-teams/ru/html.mjml
- packages/core/src/email/email.service.ts
- packages/core/src/invite/dto/invite.dto.ts
- packages/core/src/invite/invite.service.ts
> Fix :: Dynamic Invite Link (Gauzy Teams Invite)  

- apps/desktop-timer/package.json
- apps/desktop-timer/src/index.ts
- apps/desktop/src/index.ts
- apps/server/src/index.ts
- packages/desktop-libs/package.json
- packages/desktop-libs/src/index.ts
- packages/desktop-libs/src/lib/config/index.ts
- packages/desktop-libs/src/lib/config/local-server-update-config.ts
- packages/desktop-libs/src/lib/decorators/abstracts/base-desktop-dialog-decorator.ts
- packages/desktop-libs/src/lib/decorators/concretes/dialog-local-update.ts
- packages/desktop-libs/src/lib/decorators/concretes/digital-ocean-cdn.ts
- packages/desktop-libs/src/lib/decorators/concretes/github-cdn.ts
- packages/desktop-libs/src/lib/decorators/index.ts
- packages/desktop-libs/src/lib/desktop-dialog.ts
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-store.ts
- packages/desktop-libs/src/lib/desktop-updater.ts
- packages/desktop-libs/src/lib/interfaces/i-desktop-dialog.ts
- packages/desktop-libs/src/lib/interfaces/i-desktop-open-dialog.ts
- packages/desktop-libs/src/lib/interfaces/i-local-update-server.ts
- packages/desktop-libs/src/lib/interfaces/index.ts
- packages/desktop-libs/src/lib/strategies/concretes/local-update.ts
- packages/desktop-libs/src/lib/update-server/desktop-local-update-server.ts
- packages/desktop-libs/src/lib/update-server/static-server.ts
- packages/desktop-ui-lib/src/lib/settings/settings.component.html
- packages/desktop-ui-lib/src/lib/settings/settings.component.scss
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
- packages/desktop-ui-lib/src/lib/settings/settings.module.ts
- yarn.lock
---
👀 https://www.loom.com/share/15a6875761dc43c98069f3d2706a3a27
> Feat/local update & code refactoring

- packages/core/src/email-template/email-template-reader.service.ts
- packages/core/src/email-template/email-template.controller.ts
- packages/core/src/email-template/email-template.module.ts
- packages/core/src/email-template/email-template.seed.ts
- packages/core/src/email-template/email-template.service.ts
- packages/core/src/email-template/queries/handlers/email-template.find.handler.ts
> Fix :: Get/Save missing email templates (Production Environment)

- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.scss
> fix: broken buttons UI

- packages/core/src/app.module.ts
> feat: Using the sentry interceptor globally

- angular.json
- apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
- apps/gauzy/src/app/@shared/time-tracker/time-tracker.worker.ts
- apps/gauzy/tsconfig.json
- apps/gauzy/tsconfig.worker.json
- nx.json
---
👀 https://www.loom.com/share/b43a322731dd460292611fb30e96b2d6
> Feat/Implement webworker for Web Timer

- apps/gauzy/src/app/@shared/invite/invites/invites.component.html
- apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/invite.model.ts
- packages/core/src/core/entities/internal.ts
- packages/core/src/core/entities/subscribers.ts
- packages/core/src/invite/commands/handlers/invite.resend.handler.ts
- packages/core/src/invite/commands/invite.resend.command.ts
- packages/core/src/invite/dto/index.ts
- packages/core/src/invite/dto/resend-invite.dto.ts
- packages/core/src/invite/invite.controller.ts
- packages/core/src/invite/invite.entity.ts
- packages/core/src/invite/invite.service.ts
- packages/core/src/invite/invite.subscriber.ts
> Fix :: Resend Invite Expired

- packages/core/src/invite/invite.service.ts
> Fix :: Send invite issues for same role

- angular.json
> fix: allowed commonJs dependencies

- apps/gauzy/src/app/@core/services/organization-projects.service.ts
- apps/gauzy/src/app/@shared/project-select/project/project.component.ts
- apps/gauzy/src/app/@theme/components/header/header.component.html
- packages/core/src/organization-project/organization-project.controller.ts
- packages/core/src/organization-project/organization-project.service.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> Fix :: #5376 Project By Employee

- packages/contracts/src/payment.model.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/core/dto/tenant-base.dto.ts
- packages/core/src/core/dto/tenant-organization-base.dto.ts
- packages/core/src/payment/dto/query/payment-report-query.dto.ts
- packages/core/src/shared/dto/date-range-query.dto.ts
- packages/core/src/shared/dto/filters-query.dto.ts
- packages/core/src/shared/dto/relations-query.dto.ts
- packages/core/src/shared/dto/selectors-query.dto.ts
- packages/core/src/time-tracking/activity/dto/query/activity-query.dto.ts
- packages/core/src/time-tracking/statistic/dto/statistic-counts-query.dto.ts
- packages/core/src/time-tracking/statistic/statistic.controller.ts
- packages/core/src/time-tracking/time-log/dto/query/time-log-limit-query.dto.ts
- packages/core/src/time-tracking/time-log/dto/query/time-log-query.dto.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-slot/dto/query/time-slot-query.dto.ts
- packages/core/src/time-tracking/time-slot/time-slot.controller.ts
- packages/core/src/time-tracking/timesheet/dto/query/timesheet-query.dto.ts
- packages/core/src/time-tracking/timesheet/dto/query/update-timesheet-status.dto.ts
- packages/core/src/time-tracking/timesheet/timesheet.controller.ts
- packages/core/src/time-tracking/timesheet/timesheet.service.ts
> Fix :: Swagger Documentation

- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts
- packages/core/src/employee/employee.controller.ts
> Fix :: Edit employee page (stay on selected tab)

- packages/core/src/core/seeds/seed-data.service.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/equipment-sharing-policy/equipment-sharing-policy.seed.ts
- packages/core/src/equipment-sharing/equipment-sharing.entity.ts
- packages/core/src/equipment-sharing/equipment-sharing.seed.ts
- packages/core/src/organization-team/organization-team.entity.ts
- packages/core/src/time-off-request/time-off-request.seed.ts
> Fix :: SQLITE_CONSTRAINT: UNIQUE constraint failed

- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> Fix/ Api status relations

- apps/gauzy/src/app/@core/services/organization-contact.service.ts
- apps/gauzy/src/app/pages/contacts/contacts.component.ts
- apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
- packages/contracts/src/organization-contact.model.ts
- packages/core/src/employee/employee.entity.ts
- packages/core/src/organization-contact/commands/handlers/index.ts
- packages/core/src/organization-contact/commands/handlers/organization-contact-update.handler.ts
- packages/core/src/organization-contact/commands/index.ts
- packages/core/src/organization-contact/commands/organization-contact-update.command.ts
- packages/core/src/organization-contact/dto/create-organization-contact.dto.ts
- packages/core/src/organization-contact/dto/index.ts
- packages/core/src/organization-contact/dto/organization-contact.dto.ts
- packages/core/src/organization-contact/dto/update-organization-contact.dto.ts
- packages/core/src/organization-contact/organization-contact.controller.ts
- packages/core/src/organization-contact/organization-contact.entity.ts
- packages/core/src/organization-contact/organization-contact.service.ts
- packages/core/src/organization-contact/organization-contact.subscriber.ts
> Fix :: #5432 Organization Contact (Mutation)

- packages/core/src/candidate/candidate.subscriber.ts
- packages/core/src/email-template/email-template.subscriber.ts
- packages/core/src/employee/employee.subscriber.ts
- packages/core/src/export-import/import-history/import-history.subscriber.ts
- packages/core/src/feature/feature.subscriber.ts
- packages/core/src/invite/invite.subscriber.ts
- packages/core/src/invoice/invoice.subscriber.ts
- packages/core/src/organization-contact/organization-contact.subscriber.ts
- packages/core/src/organization-project/organization-project.subscriber.ts
- packages/core/src/organization-team/organization-team.subscriber.ts
- packages/core/src/organization/organization.subscriber.ts
- packages/core/src/payment/payment.subscriber.ts
- packages/core/src/reports/report.subscriber.ts
- packages/core/src/tasks/task.subscriber.ts
- packages/core/src/tenant/tenant.subscriber.ts
- packages/core/src/time-tracking/activity/activity.subscriber.ts
- packages/core/src/time-tracking/screenshot/screenshot.subscriber.ts
- packages/core/src/time-tracking/time-slot/time-slot.subscriber.ts
- packages/core/src/user/user.subscriber.ts
> Fix :: Try/Catch block to prevent query failed in subscribers

- packages/contracts/src/employee.model.ts
- packages/contracts/src/goals.model.ts
- packages/contracts/src/index.ts
- packages/contracts/src/invoice-item.model.ts
- packages/contracts/src/organization-projects.model.ts
- packages/contracts/src/organization-sprint.model.ts
- packages/contracts/src/organization-team-model.ts
- packages/contracts/src/task.model.ts
- packages/contracts/src/timesheet-statistics.model.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/integration-map/commands/handlers/integration-map.sync-task.handler.ts
- packages/core/src/tasks/commands/handlers/task-create.handler.ts
- packages/core/src/tasks/commands/handlers/task-update.handler.ts
- packages/core/src/tasks/commands/task-update.command.ts
- packages/core/src/tasks/dto/index.ts
- packages/core/src/tasks/dto/task.dto.ts
- packages/core/src/tasks/task.controller.ts
- packages/core/src/tasks/task.entity.ts
- packages/core/src/tasks/task.service.ts
- packages/core/src/tasks/task.subscriber.ts
> Fix :: Event Subscriber (Task Creator)

- packages/core/src/employee/employee.subscriber.ts
> Fix :: Restore Employee Work

- apps/gauzy/src/app/pages/employees/employees.component.ts
> Fix :: Employee work status

- apps/gauzy/src/app/@core/constants/timesheet.constants.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.html
- apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.ts
- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
> Fix :: Timelog Filters

- apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.ts
- packages/core/src/tasks/task.subscriber.ts
- packages/core/src/time-tracking/time-log/time-log.service.ts
- packages/core/src/time-tracking/time-slot/time-slot.subscriber.ts
---
`Before`
`After`
`Local Before`
`Local After`
> Fix :: Time Logs APIs Performance

- packages/core/src/database/migrations/1671107860058-AlterInviteAllowedOrganizationTable.ts
- packages/core/src/invite/commands/handlers/invite-accept.handler.ts
- packages/core/src/invite/invite.service.ts
- packages/core/src/invite/invite.subscriber.ts
- packages/core/src/organization/organization.entity.ts
> Fix ::  Default invite allowed for organization

- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.html
- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.ts
- apps/gauzy/src/assets/i18n/en.json
---
```
"Web Timer"
"Desktop Timer App",
"Mobile Timer App"
"Upwork"
"HubStaff"
```
> Fix :: Timelog Source selectors displayed order

- apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
- apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
- apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log/view-time-log.component.ts
- apps/gauzy/src/app/@theme/components/header/header.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/contracts/src/timesheet.model.ts
- packages/core/src/time-tracking/activity/activity.entity.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-create.handler.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-update.handler.ts
- packages/core/src/time-tracking/time-log/dto/create-time-log.dto.ts
- packages/core/src/time-tracking/time-log/time-log.entity.ts
- packages/core/src/time-tracking/time-log/time-log.seed.ts
- packages/core/src/time-tracking/timer/timer.service.ts
> Fix :: Browser to Web Timer enum value renamed

- packages/desktop-window/src/lib/desktop-window-about.ts
---
@evereq 
I forgot to remove devtools,
Please merge
> fix: instantly open devtools

- apps/gauzy/src/app/@core/services/candidates.service.ts
- packages/contracts/src/candidate.model.ts
- packages/core/src/candidate/candidate.controller.ts
- packages/core/src/candidate/candidate.entity.ts
- packages/core/src/candidate/commands/candidate.bulk.create.command.ts
- packages/core/src/candidate/commands/candidate.create.command.ts
- packages/core/src/candidate/commands/candidate.hired.command.ts
- packages/core/src/candidate/commands/candidate.rejected.command.ts
- packages/core/src/candidate/commands/handlers/candidate.bulk.create.handler.ts
- packages/core/src/candidate/commands/handlers/candidate.create.handler.ts
- packages/core/src/candidate/commands/handlers/candidate.hired.handler.ts
- packages/core/src/candidate/commands/handlers/candidate.rejected.handler.ts
- packages/core/src/candidate/dto/create-candidate.dto.ts
- packages/core/src/employee/commands/employee.bulk.create.command.ts
- packages/core/src/employee/commands/handlers/employee.bulk.create.handler.ts
> Fix :: Candidate Hire/Reject Action

- packages/core/src/organization-team/organization-team.controller.ts
- packages/core/src/organization-team/organization-team.service.ts
> Fix :: Find organization teams by employee

- packages/core/src/organization-team/organization-team.service.ts
> Fix :: Retrieve organization teams without members for ADMIN roles

- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/teams/teams.component.ts
- packages/core/src/organization-team/organization-team.service.ts
> Fix :: Teams filter by employee

- apps/gauzy/src/app/@core/utils/smart-table/server.data-source.ts
- packages/core/src/organization-team/organization-team.service.ts
> fix: teams pagination skip/take parameters

- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
- packages/core/src/organization/dto/organization-setting.dto.ts
- packages/core/src/organization/organization.controller.ts
> Fix :: Update organization settings

- apps/gauzy/src/app/@core/services/organization-projects.service.ts
- apps/gauzy/src/app/@shared/employee/edit-employee-membership-form/edit-employee-membership-form.component.html
- apps/gauzy/src/app/@shared/employee/edit-employee-membership-form/edit-employee-membership-form.component.ts
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-contact/edit-employee-contact.component.html
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-projects/edit-employee-projects.component.html
- apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-projects/edit-employee-projects.component.ts
- packages/contracts/src/entity-with-members.model.ts
- packages/core/src/organization-contact/commands/handlers/organization-contact.edit-by-employee.handler.ts
- packages/core/src/organization-department/commands/handlers/organization-department.edit-by-employee.handler.ts
- packages/core/src/organization-project/commands/handlers/organization-project.edit-by-employee.handler.ts
- packages/core/src/shared/handlers/update-entity.by-member.handler.ts
> Fix :: Organization Projects Assigned Members

- apps/gauzy/src/app/pages/pages-routing.module.ts
- apps/gauzy/src/app/pages/projects/projects.component.ts
> Fix :: Missing smployee selector for projects page

- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
- packages/core/src/time-tracking/screenshot/dto/delete-query.dto.ts
- packages/core/src/time-tracking/screenshot/dto/index.ts
- packages/core/src/time-tracking/screenshot/screenshot.controller.ts
- packages/core/src/time-tracking/screenshot/screenshot.service.ts
> Fix :: Self Screenshot Delete By Employee

- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
> Fix :: Fullcalender Timesheet

- apps/gauzy/src/app/auth/confirm-email/confirm-email.component.ts
- apps/gauzy/src/app/auth/confirm-email/confirm-email.resolver.ts
- apps/gauzy/src/assets/i18n/en.json
- packages/core/src/user/dto/user-email.dto.ts
- packages/core/src/user/dto/user-token.dto.ts
> fix: email verification validate API request & translation

- packages/core/src/invite/invite.service.ts
> Fix :: #5480 invited candidate is able to receive invite email

- packages/core/src/time-tracking/activity/commands/bulk-activities-save.command.ts
- packages/core/src/time-tracking/activity/commands/handlers/bulk-activities-save.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/time-slot.controller.ts
> Fix :: Bulk Empty Activities

- packages/desktop-ui-lib/src/lib/settings/settings.component.html
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
---
https://www.loom.com/share/62b6e2659ef54ae1afec166080b26ab1
> fix: download/check update button behaviour

- packages/core/src/time-tracking/activity/commands/handlers/bulk-activities-save.handler.ts
- packages/core/src/time-tracking/screenshot/screenshot.controller.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
> Fix :: Revert back permission based code

- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-bulk-create-or-update.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-bulk-create.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
- packages/core/src/time-tracking/time-slot/commands/time-slot-bulk-create-or-update.command.ts
- packages/core/src/time-tracking/time-slot/commands/time-slot-bulk-create.command.ts
- packages/core/src/time-tracking/time-slot/commands/time-slot-merge.command.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
> Fix :: Missing organization query for time slot merge command handler

- packages/core/src/time-tracking/activity/commands/handlers/bulk-activities-save.handler.ts
- packages/core/src/time-tracking/screenshot/screenshot.controller.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-bulk-create-or-update.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-bulk-create.handler.ts
- packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
- packages/core/src/time-tracking/time-slot/commands/time-slot-bulk-create-or-update.command.ts
- packages/core/src/time-tracking/time-slot/commands/time-slot-bulk-create.command.ts
- packages/core/src/time-tracking/time-slot/commands/time-slot-merge.command.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
- packages/desktop-ui-lib/src/lib/settings/settings.component.html
- packages/desktop-ui-lib/src/lib/settings/settings.component.ts
> Release to Demo

- packages/desktop-libs/src/lib/decorators/concretes/dialog-acknowledge-inactivity.ts
- packages/desktop-libs/src/lib/decorators/index.ts
- packages/desktop-libs/src/lib/desktop-ipc.ts
- packages/desktop-libs/src/lib/desktop-os-inactivity-handler.ts
- packages/desktop-ui-lib/src/lib/tasks/tasks.component.html
- packages/desktop-ui-lib/src/lib/tasks/tasks.component.scss
- packages/desktop-ui-lib/src/lib/tasks/tasks.component.ts
- packages/desktop-ui-lib/src/lib/tasks/tasks.module.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> Feat/improve tags selector/ 

- apps/gauzy/src/app/@core/services/selector-builder/date-range-picker-builder.service.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
---
@evereq BehaviorSubject always emit old value before emit new value cause  it call API multiple time with different date.
https://www.loom.com/share/129e27b546b64cf296a5cd3cefe18c66
> Fix :: Date Range Picker (Emit latest date range value)

- apps/gauzy/src/app/@shared/directives/time-tracking-authorized-directive.ts
- apps/gauzy/src/app/pages/employees/activity/activity-routing.module.ts
- apps/gauzy/src/app/pages/employees/activity/activity.module.ts
- apps/gauzy/src/app/pages/employees/activity/layout/layout.component.spec.ts
- apps/gauzy/src/app/pages/employees/activity/layout/layout.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
- apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.spec.ts
- apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
- apps/gauzy/src/app/pages/employees/timesheet/timesheet.module.ts
- packages/core/src/time-tracking/activity/activity.controller.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-slot/commands/update-time-slot.command.ts
- packages/core/src/time-tracking/time-slot/dto/delete-time-slot.dto.ts
- packages/core/src/time-tracking/time-slot/time-slot.controller.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
> Fix :: #5489 Candidate Permissions API

- apps/gauzy/src/app/@shared/timesheet/gauzy-filters/base-selector-filter/base-selector-filter.component.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
> Fix :: Refetched calendar events on organization change

- apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.ts
- apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
- packages/core/src/time-tracking/time-slot/time-slot.service.ts
> Fix :: Employee time & activities pages performace

- apps/desktop-timer/src/index.ts
- apps/desktop/src/index.ts
- apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
- apps/gauzy/src/assets/i18n/en.json
- apps/server/src/index.ts
- packages/desktop-libs/src/lib/decorators/concretes/dialog-acknowledge-inactivity.ts
- packages/desktop-libs/src/lib/decorators/concretes/github-cdn.ts
- packages/desktop-libs/src/lib/decorators/concretes/power-manager-detect-inactivity.ts
- packages/desktop-libs/src/lib/desktop-os-inactivity-handler.ts
- packages/desktop-libs/src/lib/interfaces/i-desktop-cdn-update.ts
- packages/desktop-libs/src/lib/interfaces/i-updater-config.ts
- packages/desktop-libs/src/lib/strategies/concretes/cdn-update.ts
> Fix/Download Link from GitHub releases

- apps/gauzy/src/app/pages/projects/projects.component.html
- apps/gauzy/src/app/pages/projects/projects.component.ts
> Fix :: #5483 Organization Project

- apps/gauzy/src/app/@core/services/selector-builder/date-range-picker-builder.service.ts
- apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
> Fix :: Header employee selector does not displayed employee on load page

- packages/core/src/time-tracking/statistic/statistic.controller.ts
- packages/core/src/time-tracking/time-log/time-log.controller.ts
- packages/core/src/time-tracking/time-slot/time-slot.controller.ts
> Fix :: Time Tracking Statistics Permissions

- packages/core/src/auth/auth.service.ts
- packages/core/src/auth/email-confirmation.service.ts
- packages/core/src/auth/email-verification.controller.ts
- packages/core/src/core/seeds/data/default-email-templates/email-verification/bg/html.mjml
- packages/core/src/core/seeds/data/default-email-templates/email-verification/en/html.mjml
- packages/core/src/core/seeds/data/default-email-templates/email-verification/he/html.mjml
- packages/core/src/core/seeds/data/default-email-templates/email-verification/ru/html.mjml
- packages/core/src/email/email.service.ts
- packages/core/src/user/user.service.ts
> Fix :: Email Verification Code

- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.html
- apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
- apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.ts
> Fix :: Timesheet Hidden Tabs

- apps/gauzy/src/app/pages/dashboard/dashboard.component.ts
- packages/core/src/auth/auth.controller.ts
- packages/core/src/auth/auth.service.ts
- packages/core/src/auth/dto/confirm-email.dto.ts
- packages/core/src/auth/dto/two-factor-dto.ts
- packages/core/src/auth/email-confirmation.service.ts
- packages/core/src/auth/email-verification.controller.ts
- packages/core/src/invite/dto/validate-invite-by-code-query.dto.ts
- packages/core/src/user/dto/index.ts
- packages/core/src/user/dto/user-code.dto.ts
- packages/core/src/user/user.controller.ts
- packages/core/src/user/user.entity.ts
- packages/core/src/user/user.service.ts
> Fix :: Email Verification (By Code)

- apps/gauzy/src/app/pages/settings/roles-permissions/roles-permissions.component.ts
- packages/core/src/core/interceptors/transform.interceptor.ts
> Fix :: Displayed toaster error messaage (Roles delete)

- apps/gauzy/src/app/@shared/components/label/label.module.ts
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.html
- packages/contracts/src/timesheet.model.ts
- packages/core/src/database/migrations/1673005639130-AlterTimeLogTable.ts
- packages/core/src/time-tracking/time-log/commands/handlers/time-log-create.handler.ts
- packages/core/src/time-tracking/time-log/time-log.entity.ts
- packages/core/src/time-tracking/timer/dto/start-timer.dto.ts
- packages/core/src/time-tracking/timer/timer.service.ts
---
Note: @adkif You have to send version from desktop timer side inside `Start Timer` request.
`i.e.` version = 'v0.222.2'
> Fix :: View Time Log Modal

- packages/desktop-libs/src/lib/desktop-timer.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
- packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
> feat: send app desktop timer version via api

- apps/gauzy/src/app/@shared/components/avatar/avatar.component.html
- apps/gauzy/src/app/@shared/components/avatar/avatar.component.ts
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
- apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.scss
- apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.scss
- apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.html
- apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
- apps/gauzy/src/assets/i18n/bg.json
- apps/gauzy/src/assets/i18n/en.json
- apps/gauzy/src/assets/i18n/he.json
- apps/gauzy/src/assets/i18n/ru.json
> Fix :: #5532 Dashboard Improvement

- apps/gauzy/src/app/pages/contacts/contacts-routing.module.ts
- apps/gauzy/src/app/pages/pages-routing.module.ts
> Fix :: Date Picker Visibility (Contacts Pages) 

- apps/desktop-timer/src/package.json
- apps/desktop/package.json
- apps/desktop/src/package.json
- apps/server/package.json
- apps/server/src/package.json
- yarn.lock
> chore: upgrade knex.js 0.21.5 -> 2.4.0
