ever-co/ever-gauzy

apps/gauzy/src/app/pages/about/about-routing.module.ts
apps/gauzy/src/app/pages/about/about.component.html
apps/gauzy/src/app/pages/about/about.component.ts
apps/gauzy/src/app/pages/about/about.module.ts
apps/gauzy/src/app/pages/help/help-routing.module.ts
apps/gauzy/src/app/pages/help/help.component.html
apps/gauzy/src/app/pages/help/help.component.ts
apps/gauzy/src/app/pages/help/help.module.ts
apps/gauzy/src/app/pages/pages-menu.ts
apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/pages.module.ts

This is how help page looks. About page looks similar

added help and about pages

---

apps/gauzy/src/app/@theme/components/footer/footer.component.html
apps/gauzy/src/app/@theme/components/footer/footer.component.ts
apps/gauzy/src/environments/environment.ts

enhance footer text

---

apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
apps/gauzy/src/app/@shared/user/forms/user-forms.module.ts
libs/models/src/lib/user.model.ts

added 'Started work on' field

---

apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html

added the recommended text changes for date and image input fields and switched their place so that image input is larger and date field is smaller

added small text and styling changes

---

apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/employees/employees.module.ts
apps/gauzy/src/app/pages/employees/table-components/employee-bonus/employee-bonus.component.html
apps/gauzy/src/app/pages/employees/table-components/employee-bonus/employee-bonus.component.ts

Improved Bonus column on Employees table.

feat: improved bonus column on Employees table

---

apps/gauzy/src/app/@theme/components/theme-settings/theme-settings.component.html
apps/gauzy/src/app/@theme/components/theme-settings/theme-settings.component.scss
apps/gauzy/src/app/@theme/components/theme-settings/theme-settings.component.ts
apps/gauzy/src/app/@theme/theme.module.ts
apps/gauzy/src/app/app.module.ts
apps/gauzy/src/app/pages/dashboard/dashboard.component.html
apps/gauzy/src/app/pages/dashboard/dashboard.module.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
package.json
yarn.lock

We can merge it. I added ngx-translate:

feat: install ngx-translate

---

apps/gauzy/src/app/@core/services/organizations.service.ts
apps/gauzy/src/app/@core/utils/date.ts
apps/gauzy/src/app/@theme/components/header/selectors/date/date.component.ts
apps/gauzy/src/app/pages/dashboard/employee-chart/employee-chart.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/employees/table-components/employee-bonus/employee-bonus.component.html

I did fixing described in ticket #8

feat: improvements on Employees page

---

apps/gauzy/src/app/@theme/components/header/header.component.html
apps/gauzy/src/app/@theme/components/header/header.component.ts

feat: support button added to the header

---

apps/gauzy/src/app/pages/dashboard/dashboard.component.html
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

feat: add translates to developer info on dashboard page

---

apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.html
apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
libs/models/src/lib/employee.model.ts

https://github.com/ever-co/gauzy/issues/131
Done

feat: only employees who are part of selected organization are listed

---

apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts

Fix on issue
https://github.com/ever-co/gauzy/issues/188
Feature on issue
https://github.com/ever-co/gauzy/issues/86
https://www.screencast.com/t/dJuJWKUxyE

fix: popups on income and expenses page work when no date is selected

---

apps/gauzy/src/app/pages/pages.component.ts

Tested on current versions of Chrome, Firefox and Edge with cleared cache and cookies.

fix: the admin panel in main menu is fixed

---

apps/gauzy/src/app/pages/employees/employees.component.ts

feat: added average income and expense for every employee

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-departments/edit-organization-departments.component.html
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

@AlishMekliov931 Please take a look at the translation of:
edit-organization-main.component.html, line 18.
The syntax is changed from: [placeholder] to: placeholder, which has potential effect, unknown to me.

feat: organization edit departments translated

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects.component.html
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

feat: organization projects page translated

---

apps/gauzy/src/app/pages/dashboard/dashboard.component.ts
apps/gauzy/src/app/pages/employees/employees.component.html
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/employees/employees.module.ts
apps/gauzy/src/app/pages/expenses/expenses.component.html
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/expenses/expenses.module.ts
apps/gauzy/src/app/pages/income/income.component.html
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/income/income.module.ts
apps/gauzy/src/app/pages/organizations/organizations.component.html
apps/gauzy/src/app/pages/organizations/organizations.component.ts
apps/gauzy/src/app/pages/organizations/organizations.module.ts
apps/gauzy/src/app/pages/pages.module.ts

https://www.screencast.com/t/zUUxLyDnarD

feat: loading indicators added to all main pages

---

apps/gauzy/src/app/pages/employees/employees.component.ts

Two cases:
- when employee full name (first and last) is not entered or
- only first or last name is presented in the DB
are fully covered

feat: improvements on employee add/delete notifications

---

apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.html
apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.scss
apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts

Video for review: https://www.screencast.com/t/UDrffa7F0HIB

feat: change sidebar direction on select Hebrew

---

apps/gauzy/src/app/@theme/styles/_overrides.scss

https://www.screencast.com/t/JpI9Kppwf

fix: css overwritten and overflow: hidden removed for all pages

---

apps/gauzy/src/index.html

https://www.screencast.com/t/94Pvv2DXtuA

feat: app loading indicator implemented in index.html

---

apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

feat: bg, ru and he translations added to header

---

apps/api/src/app/app.module.ts
apps/api/src/app/core/core.module.ts
apps/api/src/app/employee/employee.entity.ts
apps/api/src/app/organization-projects/organization-projects.entity.ts
apps/api/src/app/organization-teams/index.ts
apps/api/src/app/organization-teams/organization-teams.controller.ts
apps/api/src/app/organization-teams/organization-teams.entity.ts
apps/api/src/app/organization-teams/organization-teams.module.ts
apps/api/src/app/organization-teams/organization-teams.service.ts
apps/gauzy/src/app/@core/services/organization-teams.service.ts
apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.module.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.ts
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/environments/environment.ts
libs/models/src/index.ts
libs/models/src/lib/organization-projects.model.ts
libs/models/src/lib/organization-teams-model.ts

This branch contains some draft code which is not validated or tested. It could introduce errors in the app. Please do not delete this branch and do not merge it with the develop branch.

feat: organization-teams functionality initial commit

---

apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/app/pages/proposals/proposals-routing.module.ts
apps/gauzy/src/app/pages/proposals/proposals.component.html
apps/gauzy/src/app/pages/proposals/proposals.component.spec.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts
apps/gauzy/src/app/pages/proposals/proposals.module.ts
apps/gauzy/src/assets/i18n/en.json

feat: initial commit on proposals page

---

apps/api/src/app/core/crud/crud.service.ts

fix: auth service removed from crud service

---

apps/gauzy/src/app/pages/proposals/proposals.module.ts
apps/gauzy/src/app/pages/proposals/register/proposal-register.component.html
apps/gauzy/src/app/pages/proposals/register/proposal-register.component.scss
apps/gauzy/src/app/pages/proposals/register/proposal-register.component.ts
libs/models/src/index.ts
libs/models/src/lib/proposal.model.ts

Initial commit. Proposal interface, component and template created

feat: initial commit on register proposal

---

apps/api/src/app/app.module.ts
apps/api/src/app/core/core.module.ts
apps/api/src/app/organization-projects/organization-projects.entity.ts
apps/api/src/app/proposal/index.ts
apps/api/src/app/proposal/proposal.controller.ts
apps/api/src/app/proposal/proposal.entity.ts
apps/api/src/app/proposal/proposal.module.ts
apps/api/src/app/proposal/proposal.service.ts
apps/gauzy/src/app/@core/services/proposals.service.ts
apps/gauzy/src/app/pages/proposals/proposals.module.ts
apps/gauzy/src/app/pages/proposals/register/proposal-register.component.html
apps/gauzy/src/app/pages/proposals/register/proposal-register.component.ts
libs/models/src/lib/proposal.model.ts

feat: register proposal implemented

---

apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.html
apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.scss
apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts
apps/gauzy/src/app/pages/proposals/proposals.module.ts
apps/gauzy/src/app/pages/proposals/table-components/proposal-status/proposal-status.component.scss
apps/gauzy/src/app/pages/proposals/table-components/proposal-status/proposal-status.component.ts

Demo on current progress on Proposals related pages:
Register proposal page: 
https://www.screencast.com/t/VjFSSQwu18h
Proposals Management Page and Proposal Details:
https://www.screencast.com/t/YmW5LQ5MEJOE

feat: improvements on proposals management and details pages

---

apps/gauzy/src/app/@core/services/proposals.service.ts
apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.html
apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.scss
apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.ts
apps/gauzy/src/app/pages/proposals/proposal-edit/proposal-edit.component.html
apps/gauzy/src/app/pages/proposals/proposal-edit/proposal-edit.component.ts
apps/gauzy/src/app/pages/proposals/proposals-routing.module.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts
apps/gauzy/src/app/pages/proposals/proposals.module.ts

Edit proposal page created and update functionality implemented;
Improvements on Details page in terms of responsive design and visualization of Job post and Proposal content

feat: edit proposal functionality implemented

---

apps/gauzy/src/app/@shared/user/forms/action-confirmation/action-confirmation.component.ts
apps/gauzy/src/app/@shared/user/forms/user-forms.module.ts
apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.scss
apps/gauzy/src/app/pages/proposals/proposals.component.html
apps/gauzy/src/app/pages/proposals/proposals.component.ts

https://www.screencast.com/t/hnTOu4nbq1

feat: proposal status change implemented

---

apps/gauzy/src/app/pages/dashboard/employee-chart/employee-chart.component.ts
apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.ts
apps/gauzy/src/app/pages/proposals/proposals-pie-chart/proposals-pie-chart.component.scss
apps/gauzy/src/app/pages/proposals/proposals-pie-chart/proposals-pie-chart.component.ts
apps/gauzy/src/app/pages/proposals/proposals.component.html
apps/gauzy/src/app/pages/proposals/proposals.component.ts
apps/gauzy/src/app/pages/proposals/proposals.module.ts

feat: statistics on accepted- sent proposals displayed on proposals page

---

apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.html
apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.scss
apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.ts
apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.module.ts

feat: mini cards added on profit report popup

---

apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.ts
apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.module.ts
apps/gauzy/src/app/@shared/dashboard/profit-history/table-components/expense-table.component.ts
apps/gauzy/src/app/@shared/dashboard/profit-history/table-components/income-table.component.ts

feat: profit report popup completed

---

apps/gauzy/src/app/@theme/components/header/header.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.module.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.ts

https://www.screencast.com/t/NWrMQVXovC5f

feat: on teams page spinner implemented, path from header improved

---

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.html

Fixed #326 and #327 
Added optional chaining for user and organization
(PS: Really sorry for the console bug)

fix: console issue in organization and user edit pages

---

apps/api/src/app/app.module.ts
apps/api/src/app/core/core.module.ts
apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/countries/countries.controller.ts
apps/api/src/app/countries/countries.entity.ts
apps/api/src/app/countries/countries.module.ts
apps/api/src/app/countries/countries.seed.ts
apps/api/src/app/countries/countries.service.ts
apps/api/src/app/countries/index.ts
apps/api/src/app/organization/organization.entity.ts
apps/gauzy/src/app/@core/services/countries.service.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/index.ts
libs/models/src/lib/countries.model.ts
libs/models/src/lib/organization.model.ts

Please review the following points if it's ok:
1. I've created a new **countries** module in API. The module, entity, database table, etc are all called "countries" - should they be called "country" instead?
2. Organization stores the country **isoCode** field instead of the Postgres `id` field of the Country table. Is that OK?
3. Please see if the position of all fields is ok in the attached screenshot
4. Do the Address fields need to multi-line text areas instead of inputs?

feat: add more fields to organization

---

apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts

Fixes: #345 for
1. Employees
2. Expenses
3. Income
4. Proposals

fix: remove selected if filters changed #345

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/core/seeds/index.ts
apps/api/src/app/country/country.seed.ts
apps/api/src/app/employee/employee.entity.ts
apps/api/src/app/organization-teams/organization-teams.entity.ts
libs/models/src/lib/employee.model.ts

Fixes: #329 
Looks like there were multiple issues
1. process.exit(0) did not wait for the seed to end
2. typescript issues in teams
3. getConnection() is not an async function & throws an exception if the connection is not present
4. all entities which are being modified needed to be imported

fix: yarn seed

---

apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts

fix: console errors on proposals page cleaned

---

apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.ts
libs/models/src/lib/proposal.model.ts

fix: no employee selected case covered

---

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts

Fixes made:
- await response from the server before message is displayed;
- in case of error, more appropriate and understandable by the user error message is displayed

fix: on employee update if username exists an error is displayed

---

apps/api/src/app/employee-recurring-expense/employee-recurring-expense.entity.ts
apps/api/src/app/expense/expense.entity.ts
apps/api/src/app/income/income.entity.ts
apps/api/src/app/organization-recurring-expense/organization-recurring-expense.entity.ts

Fixes: #365 
---
- changed all currency fields to numeric
```
Please note:
After this fix, if you face the below error you run the application, 
please reset (nuke) your database and start again.
error: error: column "value" contains null values
```

fix: allow decimal input in currency

---

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.scss

fix: employee recurring expenses fixed on dark theme

---

apps/gauzy/src/app/pages/proposals/proposals.component.ts
apps/gauzy/src/app/pages/proposals/proposals.module.ts
apps/gauzy/src/app/pages/proposals/table-components/job-title/job-title.component.ts

Improved showing of job post url and title on Proposals management page and Details page

fix: cosmetic changes on proposals pages

---

apps/gauzy/src/app/@core/services/error-handling.service.ts
apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.ts
apps/gauzy/src/app/pages/auth/profile/profile.component.ts
apps/gauzy/src/app/pages/dashboard/employee-chart/employee-chart.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/organizations/organizations.component.ts
apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts

The error handling service is implemented in order to translate back-end (NestJS/TypeORM) error messages to the end user in more clear and understandable way. In the future, the service will catch more and more possible errors and will guide the user how to proceed. All cases, which are not covered are handled as before.
Some examples:

feat: error handling service implemented

---

apps/api/src/app/auth/auth.service.ts

feat: nodemailer implemented and sends fake emails to etheral

---

apps/gauzy/src/app/pages/dashboard/dashboard.component.ts

Fixes #399 
Added a conditional statement to only call the API if selectedDate is not null

fix: #399 dashboard console error if date is null

---

apps/api/src/app/expense/commands/handlers/expense.create.handler.ts
apps/api/src/app/expense/expense.seed.ts
apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.html
apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.ts
apps/gauzy/src/app/pages/dashboard/dashboard.component.html

When user input for expense is a negative number, the profit calculation is wrong. Fix: absolute value is taken

fix: dashboard calculations with negative numbers input

---

apps/api/src/app/expense/commands/handlers/expense.create.handler.ts
apps/api/src/app/expense/expense.entity.ts
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/expense.model.ts

feat: optional field purpose implemented on all expenses related pages

---

apps/api/src/app/expense/expense.entity.ts
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.html

On expenses pages "Include Taxes" feature implemented.

feat: on expenses pages calculation of taxes implemented

---

apps/gauzy/src/app/@core/auth/auth.module.ts
apps/gauzy/src/app/@core/auth/no-auth.guard.ts
apps/gauzy/src/app/app-routing.module.ts

Fixes #431 
---
Created a NoAuthGuard which returns true if the user is logged out.

fix: #431 auth pages should not open if user is logged in

---

apps/gauzy/src/app/pages/employees/employees.component.ts

fix: on employees page the bonus for last month header fixed

---

apps/api/src/app/app.module.ts
apps/api/src/app/auth/auth.module.ts
apps/api/src/app/core/core.module.ts
apps/api/src/app/email-templates/email.entity.ts
apps/api/src/app/email-templates/email.module.ts
apps/api/src/app/email-templates/email.service.ts
apps/api/src/app/email-templates/index.ts
apps/api/src/app/employee/employee.module.ts
apps/api/src/app/organization/organization.module.ts
libs/models/src/index.ts
libs/models/src/lib/email-template.model.ts
yarn.lock

This branch is a work in progress and contains untested code, which could cause errors. Please do not merge or delete the branch.

feat: db model created for email templates

---

apps/api/src/app/income/commands/handlers/income.create.handler.ts
apps/api/src/app/income/income.entity.ts
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.scss
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.module.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/income.model.ts

#231 
As per our discussion, this only adds a boolean flag `isBonus` to the table **`income`**
1. Now we will need a way to show bonus incomes (maybe we can add it to the table ?) 
2. We need to finalize & implement the calculations

feat: #231 bonus flag in income

---

apps/gauzy/src/app/@shared/table-components/income-amount/income-amount.component.ts
apps/gauzy/src/app/@shared/table-components/table-components.module.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/assets/i18n/en.json

Added a bonus indicator in the income table

feat: #231 bonus income indicator

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
libs/models/src/lib/organization.model.ts

feat: added date format in relation with selected region

---

apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts

High memory usage was noted and to fix it, ngOnDestroy lifecycle method and pipe operator is implemented in expense- mutation and organization-settings components.

fix: ngOnDestroy implemented in expense and organization settings pages

---

apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/app/pages/time-off/time-off-routing.module.ts
apps/gauzy/src/app/pages/time-off/time-off.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.ts
apps/gauzy/src/app/pages/time-off/time-off.module.ts
apps/gauzy/src/assets/i18n/en.json

feat: time-off page base front-end implementation

---

.scripts/env.ts
apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
apps/gauzy/src/app/@core/services/income.service.ts

fix: #500 Remove deepscan issues like unused imports, variables

---

apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.html

Fixes one error in circle ci build

fix: circle ci build

---

apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-profile.component.html
apps/gauzy/src/assets/i18n/en.json

The heading in the edit user profile referred to the employee heading. Updated en.json file to include a heading for edit user and updated the edit user profile reference.

fix(#506): updated edit user profile component to use user heading

---

apps/gauzy/src/app/@shared/invite/invite-mutation/invite-mutation.component.ts
apps/gauzy/src/app/pages/time-off/table-components/paid-icon.html
apps/gauzy/src/app/pages/time-off/table-components/paid-icon.scss
apps/gauzy/src/app/pages/time-off/table-components/paid-icon.ts
apps/gauzy/src/app/pages/time-off/table-components/request-approval-icon.html
apps/gauzy/src/app/pages/time-off/table-components/request-approval-icon.scss
apps/gauzy/src/app/pages/time-off/table-components/request-approval-icon.ts
apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.ts
apps/gauzy/src/app/pages/time-off/time-off.module.ts

feat: time off policy improvements in grid

---

apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.ts
apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.ts
apps/gauzy/src/assets/i18n/en.json

on income, expenses, proposal, policy and user

fix: removed static toastr messages

---

apps/gauzy/src/app/@core/services/store.service.ts
apps/gauzy/src/app/@theme/components/header/header.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-clients/edit-organization-clients-mutation/edit-organization-clients-mutation.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-clients/edit-organization-clients-mutation/edit-organization-clients-mutation.component.ts

Added validators to the form fields: name, email, phone

feat: on organization clients page email validation implemented

---

apps/gauzy/src/app/@core/services/store.service.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-clients/edit-organization-clients-mutation/edit-organization-clients-mutation.component.ts

fix: small correction (removed unused code)

---

apps/gauzy/src/app/@theme/components/header/header.component.ts

Added subscription to userRolePermissions$ in @theme/components/header/header.component.ts

feat: options are only seen in create button only if the user has perm

---

apps/api/src/app/employee-statistics/employee-statistics.service.ts

fix: #555 employee page not loading

---

apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/assets/i18n/en.json
package.json
yarn.lock

The "download all data" button is added.

feat: added the download all button

---

apps/api/src/app/proposal/proposal.controller.ts
apps/api/src/app/proposal/proposal.module.ts
apps/api/src/app/time-off-policy/time-off-policy.controller.ts
apps/api/src/app/time-off-policy/time-off-policy.module.ts

Added guards for time off and proposal backend. Still remains the guards in the user.controller   to be added.

feat: added guards for time off proposal

---

apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts

fix: removed console warning in add income

---

apps/api/src/app/proposal/proposal.controller.ts
apps/api/src/app/shared/guards/auth/permission.guard.ts
apps/api/src/app/time-off-policy/time-off-policy.controller.ts
apps/api/src/app/user/user.controller.ts
apps/api/src/app/user/user.module.ts

Added guards for the user.controller. Still adding user/me endpoint remains

feat: 559-added-guards-for-user-controller

---

apps/api/src/app/user/commands/handlers/index.ts
apps/api/src/app/user/commands/handlers/user.create.handler.ts
apps/api/src/app/user/commands/index.ts
apps/api/src/app/user/commands/user.create.command.ts
apps/api/src/app/user/user.controller.ts
apps/api/src/app/user/user.module.ts

Added Get('/me') and Post() endpoint in user controller.

feat: added get me and post endpoint in user controller

---

apps/gauzy/src/app/@shared/settings/danger-zone-mutation/danger-zone-mutation.component.ts
apps/gauzy/src/app/@shared/translation-base/translation-base.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-clients/edit-organization-clients.component.ts
apps/gauzy/src/app/pages/settings/edit-roles-permissions/edit-roles-permissions.component.ts

Abstract Translation Base Component for #527

feat: #527 translation base component

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-clients/edit-organization-clients-mutation/edit-organization-clients-mutation.component.html

Added red border and text if email, name, phone are invalid in organization =>clients.

feat: added-red-border-and-validation-text

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-clients/edit-organization-clients-mutation/edit-organization-clients-mutation.component.html
apps/gauzy/src/assets/i18n/en.json

feat: added-translation-pipes

---

apps/api/src/app/organization/organization.entity.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts

Added two input fields with type date
fiscalYearStart and fiscalYearEnd

feat: added-fiscal-year-start-and-year-end

---

apps/api/src/app/user/user.controller.ts
apps/gauzy/src/app/@core/services/users.service.ts
apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts

---
Modified the findAll call to findMe so that users without view all permissions can at least get their own data.
Fixes #621 
Fixes #623

fix: #621 #623 non admin dashboard page keeps loading

---

apps/api/src/app/organization/organization.seed.ts
apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.component.html
apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.component.scss
apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.component.ts
apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.html
apps/gauzy/src/app/pages/dashboard/organization-employees/organization-employees.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/organization.model.ts

---
What is new?
1. Bonus type and percentage in organization seed. Ever Technologies always gets seeded with Revenue Based Bonus with 10% bonus percentage. All other organizations get randomly seeded with either Revenue Based Bonus (with bonus percentages between 5-10%) or Profit Based Bonus (with bonus percentages between 65-75%)
2. By default, organization is created with Profit Based Bonus with 75% bonus percentage.
3. Allow creation of an organization with no …

Feat/ #401 bonuses

---

apps/api/src/app/expense/expense.controller.ts
apps/api/src/app/expense/expense.module.ts
apps/api/src/app/expense/queries/expense.find-split-expense.query.ts
apps/api/src/app/expense/queries/handlers/expense.find-split-expense.handler.ts
apps/api/src/app/expense/queries/handlers/index.ts
apps/api/src/app/organization-recurring-expense/organization-recurring-expense.controller.ts
apps/api/src/app/organization-recurring-expense/organization-recurring-expense.module.ts
apps/api/src/app/organization-recurring-expense/queries/handlers/index.ts
apps/api/src/app/organization-recurring-expense/queries/handlers/organization-recurring-expense.by-month.handler.ts
apps/api/src/app/organization-recurring-expense/queries/handlers/organization-recurring-expense.find-split-expense.handler.ts
apps/api/src/app/organization-recurring-expense/queries/organization-recurring-expense.find-split-expense.query.ts
apps/gauzy/src/app/@core/services/expenses.service.ts
apps/gauzy/src/app/@core/services/organization-recurring-expense.service.ts
apps/gauzy/src/app/@shared/dashboard/info-block/info-block.component.html
apps/gauzy/src/app/@shared/dashboard/info-block/info-block.component.scss
apps/gauzy/src/app/@shared/dashboard/info-block/info-block.component.ts
apps/gauzy/src/app/@shared/dashboard/info-block/info-block.module.ts
apps/gauzy/src/app/@shared/dashboard/records-history/records-history.component.ts
apps/gauzy/src/app/@shared/table-components/income-amount/income-amount.component.ts
apps/gauzy/src/app/@shared/table-components/table-components.module.ts
apps/gauzy/src/app/pages/dashboard/dashboard.module.ts
apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.html
apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.scss
apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/expense.model.ts
libs/models/src/lib/organization-recurring-expense.model.ts

Just the first part, I have currently modified the calculation code in the UI itself since that's where things were happening earlier. I suggest once we are sure of what we want that we shift all major calculations to the backend and don't do much in the UI as such. This will also solve #558 when completed.
@evereq Please see this video, just to show how it's coming up: https://www.screencast.com/t/EARd2RSKI

feat: #467 bonus enhancements

---

apps/api/src/app/download-all/download-all.service.ts

-   [X ] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [X ] Have you explained what your changes do, and why they add value?
---

fix: deep-scan-error-correct

---

apps/gauzy/src/app/@core/services/error-handling.service.ts
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts

fix: #645 and #652 add or edit expense dialog

---

apps/api/src/app/organization-projects/organization-projects.entity.ts
apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.html
apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.scss
apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects-mutation/edit-organization-projects-mutation.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects-mutation/edit-organization-projects-mutation.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects.component.scss
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/organization-projects.model.ts

---
Still need to work on validating users to see only public projects and one that they are assigned to, and for admin to see whole projects either private or public.

feat: added toggle button for private or public projects

---

apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.component.html
apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.component.scss
apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.component.ts
apps/gauzy/src/app/@shared/organizations/organizations-mutation/organizations-mutation.module.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/organization.model.ts

---
What is new?
1. Additional fields such as Official Name, Tax ID, Address, Fiscal year start and end dates, Invite features have been added as part of Organization creation wizard.
2. Each step in the wizard is an independent form, which can be extended or modified in future.
Organization creation flow:
Known issues:
Nebular Stepper has an open issue which shows `Form submission cancelled because the form is not connected` warning message in the browser dev …

feat: #638 organization creation wizard

---

apps/gauzy/src/app/@theme/components/footer/footer.component.html
apps/gauzy/src/assets/i18n/en.json

-   [ x] Have you explained what your changes do, and why they add value?
---
I changed to the **year 2019** in the footer to be **2019-present**

feat: #649 updated footer copyright text

---

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts

---
Cause of error:
recurringExpenseMutation component is used to create and update both Organization Recurring Expenses and Employee Recurring expenses. 
`splitExpense` field is only applicable for organization recurring expense but backend API for updating employee recurring expense received this field, which resulted in an error.
Applied Fix:
Extracted only the applicable inputs received from recurring expense mutation before making the update call to backend …

fix: #668 transform recurringExpenseMutation result to employee Expense

---

apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html
apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts

---
Recurring Expense Mutation component form showed warning messages on browser console. 
This issue has also been fixed.

fix: #668 reactive forms browser console warning messages fixed

---

apps/gauzy/src/app/@shared/tags/tags-mutation.component.html
apps/gauzy/src/app/@shared/tags/tags-mutation.component.ts

---
@sunk0 check these changes out & let me know what was the issue :)

feat: #545 changed color values

---

apps/gauzy/src/app/@shared/dashboard/info-block/info-block.component.html
apps/gauzy/src/app/@shared/dashboard/info-block/info-block.component.scss
apps/gauzy/src/app/@shared/dashboard/info-block/info-block.component.ts
apps/gauzy/src/app/@shared/dashboard/info-block/info-block.module.ts
apps/gauzy/src/app/@shared/dashboard/records-history/records-history.component.ts
apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.html
apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.scss
apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.ts
apps/gauzy/src/assets/i18n/en.json

---
Currently, I've used the Nebular accordion, so if we click on the header it opens up the child items. 
If we click on the 'attach' button then the history pop up appears.

feat: #467 total income accordion

---

apps/gauzy/src/app/pages/dashboard/organization-employees/organization-employees.component.html
apps/gauzy/src/app/pages/dashboard/organization-employees/organization-employees.component.ts

feat: click on employee dashboard card selects employee in the header

---

apps/gauzy/src/app/@core/services/validation.service.ts
apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.ts
apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
apps/gauzy/src/app/@shared/user/user-mutation/user-mutation.module.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-hiring/edit-employee-hiring.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-hiring/edit-employee-hiring.component.ts

-   [x ] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
---

Feat#665/accept offer dates employees

---

apps/api/src/app/employee-statistics/employee-statistics.controller.ts
apps/api/src/app/employee-statistics/employee-statistics.module.ts
apps/api/src/app/employee-statistics/employee-statistics.service.ts
apps/api/src/app/employee-statistics/queries/handlers/index.ts
apps/api/src/app/employee-statistics/queries/handlers/month-aggregated-employee-statistics.handler.ts
apps/api/src/app/employee-statistics/queries/month-aggregated-employee-statistics.query.ts
apps/api/src/app/expense/queries/handlers/expense.find-split-expense.handler.ts
apps/gauzy/src/app/@core/services/employee-statistics.serivce.ts
apps/gauzy/src/app/pages/dashboard/employee-chart/employee-chart.component.ts
libs/models/src/lib/employee-statistics.model.ts

---
What got fixed?
1. Employee chart expenses and bonus values.
2. Update chart when the selected month is changed.
Sample Screenshots:
1.The chart displays statistics for past 12 months starting from March 2020, because the selected date is Mar 2020
2. The chart displays statistics for past 12 months starting from February 2020, because the selected date is Feb 2020
Values in the chart match the values displayed in the adjacent component.
What was added?
1. The …

fix: #660 employee statistics chart

---

apps/api/src/app/employee/employee.controller.ts
apps/api/src/app/user-organization/user-organization.controller.ts
apps/api/src/app/user-organization/user-organization.module.ts

fix: #557 fixed backend guards so user can see his own statistics

---

apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts

---
When selecting clients in add income page, the values are not hardcoded but they come from the database

feat: load-real-clients

---

apps/api/src/app/core/entities/location-base.ts
apps/api/src/app/employee/employee.entity.ts
apps/api/src/app/location/location-base.entity.ts
apps/api/src/app/organization/organization.entity.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-location/edit-employee-location.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-location/edit-employee-location.component.scss
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-location/edit-employee-location.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
apps/gauzy/src/app/pages/employees/employees-routing.module.ts
apps/gauzy/src/app/pages/employees/employees.module.ts
apps/gauzy/tslint.json
libs/models/src/index.ts
libs/models/src/lib/employee.model.ts
libs/models/src/lib/location.model.ts
libs/models/src/lib/organization.model.ts

-   [ x] Have you explained what your changes do, and why they add value?
[https://www.screencast.com/t/jLcopX2BQWo](https://www.screencast.com/t/jLcopX2BQWo)

feat: add location tab in employees edit page

---

apps/api/src/app/employee/employee.entity.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
libs/models/src/lib/employee.model.ts
libs/models/src/lib/user.model.ts

---
I have made changes for issues#726 (Show real departments in employee settings edit page & store selected department)

feat: show real departments in employee

---

apps/api/src/app/employee/employee.entity.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts
libs/models/src/lib/employee.model.ts
libs/models/src/lib/user.model.ts

---
I have made changes to show real positions in employee settings edit page & store selected position. #725

Feat#725/show real positions

---

apps/api/src/app/expense/expense.entity.ts
apps/api/src/app/income/income.entity.ts
apps/api/src/app/organization/organization.entity.ts
apps/api/src/app/user/user.entity.ts
apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
apps/gauzy/src/app/@shared/tags/tags-mutation.module.ts
apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
apps/gauzy/src/app/@shared/user/forms/user-forms.module.ts
apps/gauzy/src/app/auth/accept-invite/accept-invite-form/accept-invite-form.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.scss
apps/gauzy/src/app/pages/tags/tags-color/tags-color.component.html
apps/gauzy/src/app/pages/tags/tags-color/tags-color.component.scss
apps/gauzy/src/app/pages/tags/tags.component.ts
libs/models/src/lib/expense.model.ts
libs/models/src/lib/income.model.ts
libs/models/src/lib/organization.model.ts
libs/models/src/lib/user.model.ts
package.json
yarn.lock

the badge needs to be styled better

feat: added badge to tags page and removed 3-rd section

---

apps/api/src/app/organization_employeeLevel/organization-employee-level.controller.ts
apps/api/src/app/organization_employeeLevel/organization-employee-level.entity.ts
apps/api/src/app/organization_employeeLevel/organization-employee-level.seed.ts
apps/gauzy/src/app/@core/services/employee-level.service.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employee-levels/edit-organization-employee-level.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employee-levels/edit-organization-employee-levle.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.ts
apps/gauzy/src/app/pages/organizations/organizations-routing.module.ts
apps/gauzy/src/app/pages/organizations/organizations.module.ts

---
On organization settings i added a new tab called Employee Levels
In it you can add/edit/delete employee levels per current organization

feat: #724-added-add-delete-edit-buttons

---

apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts

feat: fixes

---

apps/api/package.json
apps/api/src/app/app.module.ts
apps/api/src/environments/environment.prod.ts
apps/api/src/environments/environment.ts
apps/api/src/environments/ienvironment.ts
apps/api/src/main.ts
apps/gauzy/src/app/@core/sentry-error.handler.ts
apps/gauzy/src/app/app.module.ts
apps/gauzy/src/environments/environment.ts
apps/gauzy/src/environments/model.ts
package.json
yarn.lock

---
Integrated sentry in api and frontend

Feat#402 integrate sentry

---

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts

---
Removed if condition so it will update null value in the database.

fix: solve the remove department and position issue

---

yarn.lock

fix: yarn.lock file updated to prevent front-end build error

---

.scripts/configure.ts

bring latest from develop

---

apps/api/src/app/equipment/equipment.entity.ts
apps/gauzy/src/app/@shared/equipment/equipment-mutation.component.html
apps/gauzy/src/app/@shared/equipment/equipment-mutation.component.ts
apps/gauzy/src/environments/environment.ts
libs/models/src/lib/equipment.model.ts
yarn.lock

fix#487: follow equipment entity constraints

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-vendors/edit-organization-vendors.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-vendors/edit-organization-vendors.component.ts
apps/gauzy/src/environments/environment.ts

Added functionality about editing organization vendors names
---

feat: added-edit-functionality-on-vendor-names

---

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.html

---
Fixed employee level input width

fix: fixed-employee-level-input-width

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/core/seeds/data/default-email-templates/invite-employee/bg/html.mjml
apps/api/src/app/core/seeds/data/default-email-templates/invite-employee/en/html.mjml
apps/api/src/app/core/seeds/data/default-email-templates/invite-employee/he/html.mjml
apps/api/src/app/core/seeds/data/default-email-templates/invite-employee/ru/html.mjml
apps/api/src/app/country/country.entity.ts
apps/api/src/app/email-template/email-template.seed.ts
apps/api/src/app/employee/employee.entity.ts
apps/api/src/app/employment-types/employment-types.entity.ts
apps/api/src/app/expense/expense.entity.ts
apps/api/src/app/income/income.entity.ts
apps/api/src/app/invite/invite.entity.ts
apps/api/src/app/organization-clients/organization-clients.entity.ts
apps/api/src/app/organization-clients/organization-clients.service.ts
apps/api/src/app/organization-positions/organization-positions.entity.ts
apps/api/src/app/organization-projects/organization-projects.entity.ts
apps/api/src/app/organization-teams/organization-teams.entity.ts
apps/api/src/app/organization-vendors/organization-vendors.entity.ts
apps/api/src/app/organization/organization.entity.ts
apps/api/src/app/role-permissions/role-permissions.entity.ts
apps/api/src/app/tags/tag.entity.ts
apps/api/src/app/tasks/task.entity.ts
apps/api/src/app/tenant/tenant.entity.ts
apps/api/src/app/user/user.controller.ts
apps/api/src/app/user/user.entity.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-profile.component.html
apps/gauzy/src/environments/environment.ts

getting latest changes

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-positions/edit-organization-positions.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-positions/edit-organization-positions.component.ts

---
Added edit functionality on organizaton settings positions.
The positions are also shown on employee settings main page.

feat: added-organization-edit-positions

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/time-off-policy/time-off-policy.seed.ts

feat: default time-off policy seeded in the db

---

apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.html
apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.scss
apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.ts

feat: added edit icon to near the employee's name

---

apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html

@evereq I re arranged the input fileds on edit users page.
See the screenshot and the video below
You can close ticket I think
---
Video Link: https://vimeo.com/397393348

feat: strange-input-locations-fixed

---

apps/api/src/app/country/country.controller.ts
apps/api/src/app/country/country.service.ts
apps/api/src/app/export_import/export-all.controller.ts
apps/api/src/app/export_import/export-all.module.ts
apps/api/src/app/export_import/export-all.service.ts
package.json
yarn.lock

-   [ X] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [X
] Have you explained what your changes do, and why they add value?
---
I am creating csv folder in the export folder on the server. Then I create csv file(country.csv) and download the country table in it. Then the csv file is archived and downloaded to the user pc with the name export.zip.

feat: download-country-table

---

apps/gauzy/src/app/@shared/back-navigation/back-navigation.component.html
apps/gauzy/src/app/@shared/back-navigation/back-navigation.component.scss
apps/gauzy/src/app/@shared/back-navigation/back-navigation.component.spec.ts
apps/gauzy/src/app/@shared/back-navigation/back-navigation.component.ts
apps/gauzy/src/app/@shared/back-navigation/back-navigation.module.ts
apps/gauzy/src/app/@shared/back-navigation/index.ts
apps/gauzy/src/app/@shared/invite/invites/invites.component.html
apps/gauzy/src/app/@shared/invite/invites/invites.module.ts
apps/gauzy/src/app/@shared/shared.module.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
apps/gauzy/src/app/pages/employees/employees.module.ts
apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.html
apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.html
apps/gauzy/src/app/pages/proposals/proposals.module.ts
apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.html
apps/gauzy/src/app/pages/time-off/time-off.module.ts

Added the the button in `Employees > Edit`, `Employees > Manage Invites`, `Users > Manage Invites`, `Time Off Settings Page`, `Register Proposal` and `Proposal Details Page` page.
---
@rmagon @evereq 
Added the the button in `Employees > Edit`, `Employees > Manage Invites`, `Users > Manage Invites`, `Time Off Settings Page`, `Register Proposal` and `Proposal Details Page` page.
Please check the video https://www.loom.com/share/e6fd23c3fe4b4f4bad2e3549e0819cb1

feat: added back button

---

apps/api/src/app/country/country.controller.ts
apps/api/src/app/export_import/export-all.controller.ts
apps/api/src/app/export_import/export-all.service.ts

-   [ X] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [ X] Have you explained what your changes do, and why they add value?
---
I converted everything to promise in export-all.controller.

feat: converted-everything-to-promise-in-export-all-controller

---

apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.html
apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.module.ts
apps/gauzy/src/app/@shared/tags/tags-mutation.component.html
apps/gauzy/src/app/@shared/tags/tags-mutation.component.scss
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-employment/edit-employee-employment.component.html
apps/gauzy/src/app/pages/employees/employees.module.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-departments/edit-organization-departments-mutation/edit-organization-departments-mutation.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-departments/edit-organization-departments-mutation/edit-organization-departments-mutation.component.scss
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-departments/edit-organization-departments-mutation/edit-organization-departments-mutation.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.module.ts
apps/gauzy/src/assets/i18n/en.json

Feat#545/tags employee edit

---

apps/api/src/app/equipment-sharing/equipment-sharing.entity.ts
apps/api/src/app/equipment/equipment.controller.ts
apps/api/src/app/equipment/equipment.entity.ts
apps/api/src/app/equipment/equipment.service.ts
apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.component.html
apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.component.scss
apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/equipment.model.ts

-   [x ] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
[https://www.screencast.com/t/dg36IuWW](https://www.screencast.com/t/dg36IuWW)

Feat#487/equipment sharing

---

apps/gauzy/src/app/@core/services/tasks.service.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts

---
[2020-03-19 00-10-36.zip](https://github.com/ever-co/gauzy/files/4351802/2020-03-19.00-10-36.zip)

improvement: load translations for tasks

---

apps/api/src/app/core/seeds/data/default-email-templates/invite-employee/bg/html.mjml
apps/api/src/app/core/seeds/data/default-email-templates/invite-employee/en/html.mjml
apps/api/src/app/core/seeds/data/default-email-templates/invite-employee/he/html.mjml
apps/api/src/app/core/seeds/data/default-email-templates/invite-employee/ru/html.mjml
apps/api/src/app/email/email.service.ts
apps/api/src/app/invite/invite.controller.ts
apps/api/src/app/invite/invite.service.ts

---
Fixed the email service for users and employees.

fix: #823 invite user and employee email

---

apps/api/src/app/timesheet/screenshot.entity.ts
apps/api/src/app/timesheet/time-log.entity.ts
apps/api/src/app/timesheet/time-slot.entity.ts
apps/api/src/app/timesheet/timer/timer.service.ts
apps/api/src/app/timesheet/timesheet.entity.ts
apps/gauzy/src/app/@core/services/toastr.service.ts
apps/gauzy/src/app/@shared/time-tracker/project/project.component.html
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/utils.ts

Feat#489/time tracking 

---

apps/gauzy/src/app/@core/services/users-organizations.service.ts
apps/gauzy/src/app/pages/users/users.component.html
apps/gauzy/src/app/pages/users/users.component.ts
apps/gauzy/src/assets/i18n/en.json

---
Part 2 of the task which was to implement adding users to multiple organizations! Here I implemented feature of removing existing users and if user is no longer part of any organization his record is deleted from database!

feat: remove user from org and delete his data if it is his last entry

---

apps/api/src/app/export_import/export-all.controller.ts
apps/api/src/app/export_import/export-all.module.ts
apps/api/src/app/export_import/export-all.service.ts

---
Created download option for the user and user_organization table.  So now countries, users and user_organization tables can be downloaded. I also converted exportTables() function in export-all.service to Promise so now everything that is called in export-all.controller are Promises and the code can run asynchronous correctly with await. I also adjusted getAsCsv() in export-all.service so it can be used for all tables not only for countries.

feat: added-download-option-for-users-user-organization

---

apps/api/src/app/employee-statistics/employee-statistics.controller.ts
apps/api/src/app/employee-statistics/employee-statistics.service.ts
apps/api/src/app/employee-statistics/queries/handlers/aggregate-employee-statistic.handler.ts
apps/api/src/app/employee-statistics/queries/handlers/month-aggregated-employee-statistics.handler.ts

---
All employee's dashboard page shows income, expense, profit and bonus for each employee and at the total for the organization. These calculations now include direct income bonus, employee recurring expenses, organization split expenses, organization recurring split expenses.
These calculations match up to the values displayed in the human resources page and employee chart.
> Scenario 1: Date specified using period selector in the header …

feat: #459 added split and recurring expenses in dashboard calculation

---

apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.scss
apps/gauzy/src/app/pages/dashboard/employee-charts/employee-horizontal-bar-chart/employee-horizontal-bar-chart.component.ts
apps/gauzy/src/app/pages/dashboard/employee-charts/employee-stacked-bar-chart/employee-stacked-bar-chart.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.scss

fix: dark theme and charts legend changed [ref: #853]

---

apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.scss
apps/gauzy/src/app/@shared/user/user-organizations-multi-select/user-organizations-multi-select.component.html
apps/gauzy/src/app/@shared/user/user-organizations-multi-select/user-organizations-multi-select.component.ts
apps/gauzy/src/app/@shared/user/user-organizations-multi-select/user-organizations-multi-select.module.ts
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-data/edit-user-data.component.html
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-data/edit-user-data.component.ts
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.html
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.ts
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-profile.component.html
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-profile.component.ts
apps/gauzy/src/app/pages/users/users-routing.module.ts
apps/gauzy/src/app/pages/users/users.module.ts
apps/gauzy/src/assets/i18n/en.json

---
User edit page now have two tabs a main one and organizations where all organizations are listeed in multiple dropdown. I will continue working on implementing a feature to add many organizations to user, to list them with an option of removing.

feat: on edit user added second page with all orgs multiple dropdown

---

apps/gauzy/src/app/@core/services/edit-user-data.service.ts
apps/gauzy/src/app/@shared/user/user-organizations-multi-select/user-organizations-multi-select.component.html
apps/gauzy/src/app/pages/users/edit-user-mutation/edit-user-mutation.component.ts
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-data/edit-user-data.component.ts
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations-mutation/edit-user-organizations-mutation.component.html
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations-mutation/edit-user-organizations-mutation.component.ts
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.html
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.ts
apps/gauzy/src/app/pages/users/users.module.ts
apps/gauzy/src/assets/i18n/en.json

---
Finished Part 3 of the task which was to add second section in user profile and list all the organizations that he is part of, with fetaure of addin user to multiple organizations from a multiselect dropdown holding organizations that the user is not part of.

feat: finished task adding multiple organizations to user

---

apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/pages.component.ts

---
Reorganized candidates into employees

feat: #850 reorganize canditates

---

apps/api/src/app/export_import/export-all.module.ts
apps/api/src/app/export_import/export-all.service.ts

-   [ X] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [X ] Have you explained what your changes do, and why they add value?
---
I added option to download tables only if there is data inside(if the table is empty it gives me 'undefined' if I try to get the data). I also added option for download of the following tables: (email, user_organization, email, email_template, employee, employee_recurring_expense, employee_setting, equipment, equipment_sharing, expense, 'expense_category, income, invite ).

feat: #130-added-download-option-only-if-the table-is-not-empty

---

apps/api/src/app/export_import/export-all.module.ts
apps/api/src/app/export_import/export-all.service.ts
apps/api/src/app/timesheet/activity.service.ts
apps/api/src/app/timesheet/index.ts
apps/api/src/app/timesheet/screenshot.service.ts
apps/api/src/app/timesheet/time_log.service.ts
apps/api/src/app/timesheet/time_slot.service.ts
apps/api/src/app/timesheet/timesheet.module.ts
apps/api/src/app/timesheet/timesheet.service.ts

---
I added download option for the following tables(invite, invoice, invoice_item, organization, organization_employee_level, organization_client,organization_department,organization_employment_type, organization_position,  organization_project, organization_recurring_expense, organization_team, organization_vendor, proposal, role, role_permission, tag, task, tenant, time-off-policy, timesheet, activity, screenshot, time_log, time_slot).  I filled the empty tables …

feat: #130-added-download-option-for-a-couple-of-tables

---

apps/api/src/app/tenant/tenant.controller.ts

feat: #717 only super admin can delete tenant

---

apps/api/src/app/organization_employeeLevel/organization-employee-level.controller.ts
apps/gauzy/src/app/@core/services/employee-level.service.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-employment/edit-employee-employment.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employee-levels/edit-organization-employee-level.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employee-levels/edit-organization-employee-level.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/employee.model.ts

---
1. Employee Level Organization setting was modified to behave like other organization settings such as Vendors, Positions and Expense Categories.
2. Added appropriate toaster messages for Employee Level Add, Update, Cancel and Error events.
3. Added `Employee Level` Type to getAll API call.
**Demo Before change**
https://www.loom.com/share/a1ee770e181e44dcb79d0786512134f3
**Demo After change** …

feat: #724 employee level organizaiton setting enhancement

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add-tasks.component.ts
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/invoices/invoices.module.ts

The invoice add page now has a drop down list of invoice types which are used to generate invoice items based on the invoice type.
Video: https://www.loom.com/share/1dfcc539c076455ba43352d3ab1535a3

feat: added invoice types

---

apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.html
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.ts

---
Fixed feature issues of removing selected organization from user as it was working only for the last organization in the list and not for the selected one!

fix: fixed removing selected organization from user

---

apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html
apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts

fix: category combo-box improved [ref: #859]

---

apps/api/src/app/tasks/task.controller.ts
apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.html
apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts

---
https://www.loom.com/share/3bf117ce15e1485f926be390e0977e2b

fix: changed task controller edit to support many to many

---

.vscode/launch.json
apps/api/src/app/user/user.controller.ts
apps/gauzy/src/app/@core/services/users.service.ts
apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.ts
apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.module.ts
apps/gauzy/src/app/pages/tags/tags.component.ts
apps/gauzy/src/app/pages/users/edit-user-mutation/edit-user-mutation.component.ts
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-data/edit-user-data.component.ts
apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-profile.component.ts
apps/gauzy/src/app/pages/users/users.component.ts
libs/models/src/lib/user.model.ts

Not finished on the backend yet would like help from @rmagon

feat: implemented user-edit-tag 

---

apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts

---
Fixed client label binding in income and expense mutation components.
https://www.loom.com/share/e0e4ddd71c114923990646451c8e92e9

fix: #996 fixed client name in income expense pop ups

---

apps/api/src/app/invite/commands/handlers/invite.accept-employee.handler.ts
apps/api/src/app/invite/commands/handlers/invite.accept-user.handler.ts

---
Added tenant id in user and employee accept invite handlers.
https://www.loom.com/share/c33d7b1f889b45e587d3ba8f912048da

fix: #982 issue with user onboarding on invite

---

apps/gauzy/src/app/@theme/components/header/header.component.html
apps/gauzy/src/app/@theme/components/header/header.component.scss
apps/gauzy/src/app/@theme/components/header/header.component.ts

---
Instead of using angular conditions on window.width (which was causing the issue) we're now using simple CSS classes for making the header responsive.
Since width changes outside of Angular, we can't do things like ***ngIf="winndow.width > XYZ"** etc.
Also changed _*ngIf_ to [hidden] (hidden just adds a **'display:none'** whereas ngIf removes the element from the DOM completely)
Video of the fix:
https://www.loom.com/share/17b2d4993c5041ab93064dffc55ec8d8

fix: #913 header responsive issue with selectors

---

apps/api/src/app/app.module.ts
apps/api/src/app/export_import/import/import-all.controller.ts
apps/api/src/app/export_import/import/import-all.module.ts
apps/api/src/app/export_import/import/import-all.service.ts
apps/api/src/app/export_import/import/index.ts
apps/gauzy/src/app/@core/services/exportAll.service.ts
apps/gauzy/src/app/pages/import-export/export/export-routing.module.ts
apps/gauzy/src/app/pages/import-export/export/export.component.html
apps/gauzy/src/app/pages/import-export/export/export.component.scss
apps/gauzy/src/app/pages/import-export/export/export.component.ts
apps/gauzy/src/app/pages/import-export/export/export.module.ts
apps/gauzy/src/app/pages/import-export/import-export-routing.module.ts
apps/gauzy/src/app/pages/import-export/import-export.component.ts
apps/gauzy/src/app/pages/import-export/import-export.html
apps/gauzy/src/app/pages/import-export/import-export.module.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/app/pages/settings/settings-routing.module.ts
apps/gauzy/src/assets/i18n/en.json
package.json
yarn.lock

-   [ X] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [X ] Have you explained what your changes do, and why they add value?
---
I added a new look for the export/import section. Now export and import are two separate buttons and lead to different pages(still haven't done it for the import button). I also added option for uploading of files(so far only for the back end). I tested with postman and it uploads files to the folder import, which is generated on the server. Every file is given the name export.zip. Than when you call the backend(http://localhost:3000/api/import)  it unzips …

feat: #130-new-look-for-the-import-export-option

---

apps/api/src/app/auth/commands/handlers/auth.register.handler.ts
apps/api/src/app/invite/commands/invite.accept-employee.command.ts
apps/api/src/app/invite/commands/invite.accept-user.command.ts
apps/api/src/app/invite/commands/invite.resend.command.ts
apps/api/src/app/invite/invite.controller.ts
apps/api/src/app/invite/invite.service.ts
apps/gauzy/src/app/@core/services/invite.service.ts
apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.ts
libs/models/src/lib/invite.model.ts

---
Fixed 
1. Welcome user email
2. Welcome employee email
3. Few interface names

fix: #1004 gauzy logo in email templates

---

apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts

---
Fixed
1. Duplicate API calls with employee component
2. Issue when date not selected in employee component
3. Income mutation component was sending employeeId=null for the first time
4. Expense mutation component was sending employeeId=null for the first time
5. Toastr messages were incorrect.
6. Fixed extra updates in employee.component
Video:
https://www.loom.com/share/1ec22b49fb784a5e8ddffbd9fe653dff

fix: #1007 error in adding income and expense

---

apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts

---
Fixed page load
https://www.loom.com/share/e767d8157ba245799ea2b2e20fd66908

fix: #1021 income expense page load bug

---

apps/gauzy/src/app/pages/users/users.component.ts

---
Fixed removing selected user instead of last one.

fix: remove selected user from org

---

apps/api/src/app/candidate/candidate.seed.ts
apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/employee/employee.seed.ts
apps/api/src/app/organization/organization.seed.ts
apps/api/src/app/tenant/tenant.seed.ts
apps/api/src/app/user/user.seed.ts

---
Fixed seed so that everything falls under one single tenant.
Also fixed issue with `yarn run seed`

fix: #1006 tenant hierarchy in seed

---

apps/gauzy/src/app/pages/pages.component.ts

fix: small fix on permission

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.html
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-employees-selector.component.ts
apps/gauzy/src/assets/i18n/en.json

Invoice Number can not be a negative number or zero.
Discount Value and Tax can not be a negative number.
Invoices cannot be added without Invoice Items.
Invoice Items cannot be added  without price, quantity, description and employee/project/task.
Due Date cannot be before Invoice Date.
Video: https://www.loom.com/share/e1c0f620fda14ce183c518407c214bf7

feat: added validations for invoices and invoice items

---

apps/gauzy/src/app/pages/invoices/invoices.component.html
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/assets/i18n/en.json

Added Duplicate button in Invoices page.
It adds a copy of the selected invoice to the database with a different invoice number.
Video: https://www.loom.com/share/46ff6b78a36f4cf8b6871e3f128a0514

feat: added invoice duplication feature

---

apps/gauzy/src/app/@theme/styles/_overrides.scss

feat: scrollbar is removed, but scroll functionality is preserved

---

apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.ts
apps/gauzy/src/app/pages/proposals/proposal-edit/proposal-edit.component.ts
apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts

fix: navigation to all proposals pages is fixed

---

apps/api/src/app/app.module.ts
apps/api/src/app/product-option/product-option.entity.ts
apps/api/src/app/product-option/product-option.service.ts
apps/api/src/app/product-variant/product-variant.controller.ts
apps/api/src/app/product-variant/product-variant.entity.ts
apps/api/src/app/product-variant/product-variant.service.ts
apps/api/src/app/product/commands/handlers/product.create.handler.ts
apps/api/src/app/product/commands/handlers/product.update.handler.ts
apps/api/src/app/product/commands/product.update.command.ts
apps/api/src/app/product/product.controller.ts
apps/api/src/app/product/product.entity.ts
apps/api/src/app/product/product.module.ts
apps/api/src/app/product/product.service.ts
apps/gauzy/src/app/@core/services/product-variant-price.service.ts
apps/gauzy/src/app/@core/services/product-variant-settings.service.ts
apps/gauzy/src/app/@core/services/product-variant.service.ts
apps/gauzy/src/app/@shared/product-mutation/product-form/product-form.component.html
apps/gauzy/src/app/@shared/product-mutation/product-form/product-form.component.ts
apps/gauzy/src/app/@shared/product-mutation/product-mutation.component.html
apps/gauzy/src/app/@shared/product-mutation/product-mutation.component.ts
apps/gauzy/src/app/@shared/product-mutation/product-mutation.module.ts
apps/gauzy/src/app/@shared/product-mutation/product-variant-form/product-variant-form.component.ts
apps/gauzy/src/app/pages/inventory/inventory-table/inventory.component.ts
apps/gauzy/src/app/pages/inventory/inventory.module.ts
apps/gauzy/src/assets/i18n/en.json

**User can update Product and Product Variants** --> [https://www.screencast.com/t/G3nhUrK9Dd](https://www.screencast.com/t/G3nhUrK9Dd)

feat: #841/update product and variants

---

apps/api/src/app/invoice/invoice.controller.ts
apps/api/src/app/invoice/invoice.module.ts
apps/api/src/app/invoice/invoice.service.ts
apps/gauzy/src/assets/i18n/en.json

Added translations for invoice permissions.
Added backend api checks.

feat: added translations and backend api checks

---

apps/api/src/app/product-type/product-type.controller.ts
apps/api/src/app/product-type/product-type.entity.ts
apps/api/src/app/product-type/product-type.seed.ts
apps/gauzy/src/app/@core/services/product-type.service.ts
apps/gauzy/src/app/@shared/product-mutation/product-form/product-form.component.ts
apps/gauzy/src/app/@shared/product-mutation/product-mutation.module.ts
apps/gauzy/src/app/@shared/product-mutation/product-type-mutation/product-type-mutation.component.html
apps/gauzy/src/app/@shared/product-mutation/product-type-mutation/product-type-mutation.component.scss
apps/gauzy/src/app/@shared/product-mutation/product-type-mutation/product-type-mutation.component.ts
apps/gauzy/src/app/pages/inventory/inventory-routing.module.ts
apps/gauzy/src/app/pages/inventory/inventory-table/inventory.component.scss
apps/gauzy/src/app/pages/inventory/inventory-table/inventory.component.ts
apps/gauzy/src/app/pages/inventory/inventory.module.ts
apps/gauzy/src/app/pages/inventory/product-type/org-row/organization-row.component.ts
apps/gauzy/src/app/pages/inventory/product-type/product-types.component.html
apps/gauzy/src/app/pages/inventory/product-type/product-types.component.scss
apps/gauzy/src/app/pages/inventory/product-type/product-types.component.spec.ts
apps/gauzy/src/app/pages/inventory/product-type/product-types.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/product.model.ts

Added CRUD operations for Product Types --> [https://www.screencast.com/t/O9AQTvXM8](https://www.screencast.com/t/O9AQTvXM8)

Feat#841/inventory

---

apps/gauzy/src/app/@theme/styles/_overrides.scss

https://www.loom.com/share/6d0584ac2f2f430e8e7814aa47df3594
---

add dark theme css

---

apps/api/src/app/invoice/invoice.controller.ts
apps/api/src/app/shared/index.ts
apps/api/src/app/shared/pipes/index.ts
apps/api/src/app/shared/pipes/parse-json.pipe.ts

---
New Pipe to process JSON Parser, Safely...

Feat/#1130 New ParseJsonPipe and Fix the Invoice API

---

apps/api/src/app/core/crud/tenant-aware-crud.service.ts
apps/api/src/app/organization/commands/handlers/organization.create.handler.ts
apps/api/src/app/organization/organization.controller.ts

fix(api): tenantId is not saved when creating organization
---

feat/#1103: Apply AuthGuard on Create Organization Endpoint, and Fix TenantId on TenantAware CRUD

---

apps/api/src/app/candidate/candidate.entity.ts
apps/api/src/app/candidate/candidate.seed.ts
apps/gauzy/src/app/@core/services/candidates.service.ts
apps/gauzy/src/app/pages/candidates/candidates.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-profile.component.ts
apps/gauzy/src/app/pages/candidates/table-components/candidate-status/candidate-status.component.html
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/candidate.model.ts

---
- fixed updating candidate profile
- also fixed "include deleted candidates" button in main table 
https://www.loom.com/share/9a70527b9e8a421ca29eb85c2cbfd383

fix: fix updating candidate profile [ref:#1144]

---

apps/api/src/app/candidate/candidate.entity.ts
apps/api/src/app/candidate/candidate.seed.ts
apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/email-template/email-template.seed.ts
apps/gauzy/src/app/@core/services/candidates.service.ts
apps/gauzy/src/app/@shared/user/forms/archive-confirmation/archive-confirmation.component.ts
apps/gauzy/src/app/@shared/user/forms/user-forms.module.ts
apps/gauzy/src/app/pages/candidates/candidates.component.html
apps/gauzy/src/app/pages/candidates/candidates.component.ts
apps/gauzy/src/app/pages/candidates/table-components/candidate-status/candidate-status.component.html
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/candidate.model.ts

---
- "include archived" checkbox displayed archived candidates with status "Archived"
https://www.loom.com/share/d3ad53bbb3094c3a900b199fd08e495b

feat: include archive [ref:#1147]

---

apps/api/src/app/invoice/invoice.controller.ts
apps/api/src/app/invoice/invoice.service.ts
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts

Fixed various issues with editing invoices.

feat: fixed issues with invoice editing

---

apps/api/src/app/candidate-documents/candidate-documents.controller.ts
apps/api/src/app/candidate-experience/candidate-experience.controller.ts
apps/api/src/app/candidate-feedbacks/candidate-feedbacks.controller.ts
apps/api/src/app/candidate-skill/candidate-skill.controller.ts
apps/api/src/app/employee-setting/employee-setting.controller.ts
apps/api/src/app/employee-statistics/employee-statistics.controller.ts
apps/api/src/app/expense-categories/expense-categories.controller.ts
apps/api/src/app/export_import/export-all.controller.ts
apps/api/src/app/integration-entity-setting-tied-entity/integration-entity-setting-tied-entitiy.controller.ts
apps/api/src/app/integration-entity-setting/integration-entity-setting.controller.ts
apps/api/src/app/integration-map/integration-map.controller.ts
apps/api/src/app/integration-setting/integration-setting.controller.ts
apps/api/src/app/integration/integration.controller.ts
apps/api/src/app/invite/invite.controller.ts
apps/api/src/app/organization-employment-type/organization-employment-type.controller.ts
apps/api/src/app/product-category/product-category.controller.ts
apps/api/src/app/product-option/product-option.controller.ts
apps/api/src/app/product-settings/product-settings.controller.ts
apps/api/src/app/product-variant-price/product-variant-price.controller.ts
apps/api/src/app/product-variant/product-variant.controller.ts
apps/api/src/app/product/product.controller.ts
apps/api/src/app/role/role.controller.ts
apps/api/src/app/skills/skill.controller.ts
apps/api/src/app/tasks/task.controller.ts
apps/api/src/app/upwork/upwork.controller.ts

- added guard in some nestjs controller

feat: added guard for some controller

---

apps/api/src/app/app.module.ts
apps/api/src/app/appointment-employees/appointment-employees.entity.ts
apps/api/src/app/appointment-employees/appointment-employees.module.ts
apps/api/src/app/core/core.module.ts
apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/employee-appointment/commands/employee-appointment.create.command.ts
apps/api/src/app/employee-appointment/commands/employee-appointment.update.command.ts
apps/api/src/app/employee-appointment/commands/handlers/employee-appointment.create.handler.ts
apps/api/src/app/employee-appointment/commands/handlers/employee-appointment.update.handler.ts
apps/api/src/app/employee-appointment/commands/handlers/index.ts
apps/api/src/app/employee-appointment/commands/index.ts
apps/api/src/app/employee-appointment/employee-appointment.controller.ts
apps/api/src/app/employee-appointment/employee-appointment.entity.ts
apps/api/src/app/employee-appointment/employee-appointment.module.ts
apps/api/src/app/employee-appointment/employee-appointment.service.ts
apps/api/src/app/employee-appointment/index.ts
apps/gauzy/src/app/@core/services/employee-appointment.service.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.module.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
libs/models/src/index.ts
libs/models/src/lib/appointment-employees.model.ts
libs/models/src/lib/employee-appointment.model.ts

This PR adds backend for appointment schedule creation for employees. We can now create new appointments and the same will be rendered on the appointment calendar. The appointment invitees are still not getting saved, so work is in progress.
---

feat(appointment_scheduling): basic backend for appointment create

---

apps/api/package.json
apps/api/src/app/email-template/email-template.seed.ts
yarn.lock

---
Fixed email template seed by removing the readdirp library and writing my own function to recursively fetch directories using the nodejs 'fs' module.
Need to test on Windows & Ubuntu for compatibility.

fix: #1158 email template seed

---

apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/api/src/app/timesheet/timesheet.controller.spec.ts
apps/api/src/app/timesheet/timesheet.controller.ts
apps/api/src/app/timesheet/timesheet.entity.ts
apps/api/src/app/timesheet/timesheet.module.ts
apps/api/src/app/timesheet/timesheet.service.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals.module.ts
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.html
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.scss
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/timesheet.model.ts

---
- Create api for get timesheet and update status
- Set layout of the timesheet approval.

Feat#489/time tracking 3

---

apps/api/src/app/app.module.ts
apps/api/src/app/appointment-employees/appointment-employees.controller.ts
apps/api/src/app/appointment-employees/appointment-employees.entity.ts
apps/api/src/app/appointment-employees/appointment-employees.module.ts
apps/api/src/app/appointment-employees/appointment-employees.service.ts
apps/api/src/app/core/core.module.ts
apps/api/src/app/employee-appointment/employee-appointment.controller.ts
apps/api/src/app/employee-appointment/employee-appointment.entity.ts
apps/gauzy/src/app/@core/services/appointment-employees.service.ts
apps/gauzy/src/app/@core/services/employee-appointment.service.ts
apps/gauzy/src/app/pages/employees/appointment/appointment-routing.module.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.module.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
libs/models/src/lib/employee-appointment.model.ts

This PR adds update appointment handling in frontend and backend. On click of an appointment in calendar, user can edit the appointment. Also, added appointment employees apis to store invitees.
---

feat(appointment_scheduling): update appointment and store invitees

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/skills/skill.seed.ts
apps/gauzy/src/app/share/organization/organization.component.ts

#946 Public Page - Part 3
- Added skill seed
- Cleaned existing code

feat(#946-public page): added skill seed and cleaned existing code

---

apps/api/src/app/employee-appointment/employee-appointment.entity.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.module.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/employee-appointment.model.ts

This PR adds buffer time and break time for appointment schedules, See screenshots:
---

feat(appointment_scheduling): added buffer time and breaktime

---

apps/api/src/app/tasks/task.entity.ts
apps/gauzy/src/app/@core/services/tasks-store.service.ts
apps/gauzy/src/app/@core/services/tasks.service.ts
apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.html
apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
apps/gauzy/src/app/pages/tasks/tasks.module.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
libs/models/src/lib/task-entity.model.ts

feat(context): #992 Assign Tasks to Employees

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employment-types/edit-organization-employment-types.component.html
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/he.json

---
Added translations and fixed broken translation reference on epmloyment type header.
https://www.loom.com/share/05b70930b06646f0a2da1c97ec6a0640

fix: added translation to employment types header

---

apps/gauzy/src/app/@core/services/tasks-store.service.ts
apps/gauzy/src/app/@shared/table-components/employee-with-links/employee-with-links.component.html
apps/gauzy/src/app/@shared/table-components/employee-with-links/employee-with-links.component.ts
apps/gauzy/src/app/@shared/table-components/table-components.module.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.html
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts

feat(assign emp to task): added employee link, duplicate button

---

apps/api/src/app/tasks/task.entity.ts
apps/gauzy/src/app/@core/services/tasks.service.ts
apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.component.ts
apps/gauzy/src/app/@shared/table-components/table-components.module.ts
apps/gauzy/src/app/@shared/table-components/task-teams/task-teams.component.html
apps/gauzy/src/app/@shared/table-components/task-teams/task-teams.component.ts
apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.html
apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.scss
apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
apps/gauzy/src/app/pages/tasks/tasks.module.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
libs/models/src/lib/task-entity.model.ts

feat(assign teams to task): assign teams to task and add it to list

---

apps/api/src/app/app.module.ts
apps/api/src/app/core/core.module.ts
apps/api/src/app/event-types/commands/event-type.create.command.ts
apps/api/src/app/event-types/commands/handlers/event-type.create.handler.ts
apps/api/src/app/event-types/commands/handlers/index.ts
apps/api/src/app/event-types/event-type.controller.ts
apps/api/src/app/event-types/event-type.entity.ts
apps/api/src/app/event-types/event-type.module.ts
apps/api/src/app/event-types/event-type.service.ts
apps/gauzy/src/app/@core/services/event-type.service.ts
apps/gauzy/src/app/pages/employees/event-types/event-type-mutation/event-type-mutation.component.html
apps/gauzy/src/app/pages/employees/event-types/event-type-mutation/event-type-mutation.component.ts
apps/gauzy/src/app/pages/employees/event-types/event-type.component.html
apps/gauzy/src/app/pages/employees/event-types/event-type.component.ts
apps/gauzy/src/app/pages/employees/event-types/event-type.module.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/event-type.model.ts

This PR completes implementation of event types for appointment scheduling
---

feat(appointment_scheduling): event types completed

---

apps/api/src/app/organization-team/organization-team.controller.ts
apps/api/src/app/organization-team/organization-team.module.ts
apps/api/src/app/organization-team/organization-team.service.ts
apps/api/src/app/tasks/task.controller.ts
apps/api/src/app/tasks/task.service.ts
apps/gauzy/src/app/@core/services/organization-teams.service.ts
apps/gauzy/src/app/@core/services/tasks.service.ts
apps/gauzy/src/app/@core/services/team-tasks-store.service.ts
apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/team-tasks/components/team-task-dialog/team-task-dialog.component.html
apps/gauzy/src/app/pages/team-tasks/components/team-task-dialog/team-task-dialog.component.scss
apps/gauzy/src/app/pages/team-tasks/components/team-task-dialog/team-task-dialog.component.ts
apps/gauzy/src/app/pages/team-tasks/components/team-task/team-task.component.html
apps/gauzy/src/app/pages/team-tasks/components/team-task/team-task.component.ts
apps/gauzy/src/app/pages/team-tasks/team-tasks-routing.module.ts
apps/gauzy/src/app/pages/team-tasks/team-tasks.module.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

feat(team's task): teams task list and add/edit/remove

---

apps/gauzy/src/app/@shared/sidebar/sidebar.component.html
apps/gauzy/src/app/@shared/sidebar/sidebar.component.scss
apps/gauzy/src/app/@shared/sidebar/sidebar.component.ts
apps/gauzy/src/assets/i18n/en.json

added deleting nodes
added adding public/private
https://www.loom.com/share/fe406bbec21f459c8b8a7e21dd95fc4a
---

feat: added deleting nodes, adding public/private[ref:#1112]

---

apps/api/src/app/candidate-interview/candidate-interview.controller.ts
apps/api/src/app/candidate-interview/candidate-interview.service.ts
apps/gauzy/src/app/@core/services/candidate-interview.service.ts
apps/gauzy/src/app/@shared/candidate/candidate-interview-info/candidate-interview-info.component.html
apps/gauzy/src/app/@shared/candidate/candidate-interview-info/candidate-interview-info.component.scss
apps/gauzy/src/app/@shared/candidate/candidate-interview-info/candidate-interview-info.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.ts
apps/gauzy/src/assets/i18n/en.json

---
- displayed interview data in pop-up
- added query findByCandidateId for interview
https://www.loom.com/share/1a12c7b65e1f46559d5f38d727fa5209

Feature: candidate interview pop-up [ref:#1156]

---

apps/gauzy/src/app/@shared/sidebar/sidebar.component.html
apps/gauzy/src/app/@shared/sidebar/sidebar.component.scss
apps/gauzy/src/app/@shared/sidebar/sidebar.component.ts
apps/gauzy/src/assets/i18n/en.json

added icons remove-add-change
added editing articles&categories
https://www.loom.com/share/f2af469f377747e2aa1d88092c797949
---

feat: added icons remove-add-change, editing articles[ref:#1112]

---

apps/gauzy/src/app/@core/services/availability-slots.service.ts
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.html
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.ts
apps/gauzy/src/assets/i18n/en.json

This PR completes the Availability module, We can add create new availability slots, recurring slots will be automatically adjusted as per current dates. Date specific availability will have priority over recurring availability.
---

feat(appointment_scheduling): completed availability slots module

---

apps/gauzy/src/app/@shared/candidate/candidate-interview-form/candidate-interview-form.component.scss
apps/gauzy/src/app/@shared/candidate/candidate-interview-info/candidate-interview-info.component.html
apps/gauzy/src/app/@shared/candidate/candidate-interview-info/candidate-interview-info.component.ts
apps/gauzy/src/app/@shared/candidate/candidate-interview-info/candidate-interview-info.module.ts
apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-interview-mutation.component.ts
apps/gauzy/src/app/pages/candidates/candidates.module.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.html
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.scss
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.ts
apps/gauzy/src/assets/i18n/en.json

---
- added ability to edit interview from calendar page
- added multi-select for candidates and employees to filter interviews
https://www.loom.com/share/9a3d9ffb91f94cae8affed7419c869b0

Feature: candidate interview [ref:#1156]

---

apps/api/src/app/organization-team/organization-team.controller.ts
apps/api/src/app/organization-team/organization-team.module.ts
apps/api/src/app/tasks/task.controller.ts
apps/api/src/app/tasks/task.module.ts
apps/api/src/app/tasks/task.service.ts
apps/gauzy/src/app/@core/services/organization-teams.service.ts
apps/gauzy/src/app/@core/services/tasks.service.ts
apps/gauzy/src/app/@core/services/team-tasks-store.service.ts
apps/gauzy/src/app/@shared/table-components/assigned-to/assigned-to.component.ts
apps/gauzy/src/app/@shared/table-components/task-teams/task-teams.component.html
apps/gauzy/src/app/pages/team-tasks/components/team-task/team-task.component.ts
apps/gauzy/src/app/pages/team-tasks/team-tasks.module.ts

Feature  tasks minor enhancements

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.scss

-   [✔] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [✔ ] Have you explained what your changes do, and why they add value?
---

fix/#1301 Organization settings responsiveness fix

---

apps/api/src/app/export_import/export-all.module.ts
apps/api/src/app/export_import/export-all.service.ts

-   [x ] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [ x] Have you explained what your changes do, and why they add value?
---
Added download possibility for appointment_employees, approval_policy,  candidate

feat: #130 added download possibility for new tables

---

apps/api/src/app/event-types/event-type.entity.ts
apps/api/src/app/organization-team/organization-team.entity.ts
apps/api/src/app/organization-team/organization-team.service.ts
apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.html
apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.ts
apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.ts
apps/gauzy/src/app/@shared/table-components/table-components.module.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.module.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams-mutation/edit-organization-teams-mutation.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams-mutation/edit-organization-teams-mutation.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.scss
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.ts
apps/gauzy/src/assets/i18n/bg.json
libs/models/src/lib/employee.model.ts
libs/models/src/lib/organization-team-model.ts

Tags implemented to orgTeams but the stylings needs to be done better

feat: added tags to organization teams

---

apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.html
apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.module.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.html
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.ts
apps/gauzy/src/app/share/public-appointments/appointment-form/appointment-form.component.html
apps/gauzy/src/app/share/public-appointments/appointment-form/appointment-form.component.ts
apps/gauzy/src/app/share/public-appointments/appointment-form/appointment-form.module.ts
apps/gauzy/src/app/share/public-appointments/appointment-form/appointment-form.routing.module.ts
apps/gauzy/src/app/share/public-appointments/create-appointment/create-appointment.component.html
apps/gauzy/src/app/share/public-appointments/create-appointment/create-appointment.component.ts
apps/gauzy/src/app/share/share-routing.module.ts
apps/gauzy/src/assets/i18n/en.json

This PR prevents header dropdown change as requested in https://github.com/ever-co/gauzy/pull/1264
Also, the PR adds appointment form for public appointment booking.
The user can select only valid duration in calendar which is equal to the event type duration.
---

feat(appointment_scheduling): added appointment form for public appointments

---

.prettierrc
apps/api/src/app/candidate-interview/candidate-interview.entity.ts

---
**What got changed?**
Trailing comma setting in .prettierrc changed to "none" from its default value of "es5"
**Code Formatting Post change**
```
@JoinTable({
name: 'candidate_interviewers'
})
```

chore: #1326 updated prettier config to avoid trailing commas

---

apps/api/src/app/invite/invite.controller.ts

---
Removed jwt guard that was applied globally to invite controller as it blocked invite validate endpoint which is supposed to be accessed without authorization.
**Demo**
https://www.loom.com/share/06c52a9fe58e4346bacaa21f4b3ab9be

fix: #1280 removed jwt guard for public endpoint

---

apps/gauzy/src/app/@shared/candidate/candidate-calendar-info/candidate-calendar-info.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-documents/edit-candidate-documents.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-experience/edit-candidate-education/edit-candidate-education.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-experience/edit-candidate-experience/edit-candidate-experience-form.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-experience/edit-candidate-skills/edit-candidate-skills.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.scss
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-interview/edit-candidate-interview.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-interview/edit-candidate-interview.component.scss
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-interview/edit-candidate-interview.component.ts
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
apps/gauzy/src/assets/i18n/en.json

---
https://www.loom.com/share/d5da47322e7845b7bd133a31e5c81486
- fixed filter for feedbacks
- added mark "Past" for interview
- we can not edit/delete past interviews (because feedback contain interviewId and interviewers)
- we can not leave a feedback before  interview happens
- added button "Hide past interviews"
- started working on selecting time in calendar

Feature:  interview feedbacks  [ref:#1156]

---

apps/gauzy/src/app/@shared/candidate/candidate-calendar-info/candidate-calendar-info.component.html
apps/gauzy/src/app/@shared/candidate/candidate-calendar-info/candidate-calendar-info.component.scss
apps/gauzy/src/app/@shared/candidate/candidate-calendar-info/candidate-calendar-info.component.ts
apps/gauzy/src/app/@shared/candidate/candidate-interview-info/candidate-interview-info.component.html
apps/gauzy/src/app/@shared/candidate/candidate-interview-info/candidate-interview-info.component.scss
apps/gauzy/src/app/@shared/candidate/candidate-interview-info/candidate-interview-info.component.ts
apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-interview-form/candidate-interview-form.component.html
apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-interview-form/candidate-interview-form.component.scss
apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-interview-form/candidate-interview-form.component.ts
apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-interview-mutation.component.html
apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-interview-mutation.component.ts
apps/gauzy/src/app/@shared/candidate/candidate-select/candidate-select.component.html
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.html
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.ts
apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.html
apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-interview/edit-candidate-interview.component.scss
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.html
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.ts
apps/gauzy/src/assets/i18n/en.json

---
https://www.loom.com/share/91242e607a5b4b2aad5621be58c74274
1. fixed calendar  in interview (we can pick time and it create interview with it)
2. added minDate in data-range-picker (for disabling past dates)
3. added validation in calendar (we cannot pick the past date/time )
4. bugfix

Feat/#1156 candidate interview 

---

.vscode/launch.json
apps/api/src/app/organization-clients/organization-clients.controller.ts
apps/api/src/app/organization_employeeLevel/organization-employee-level.controller.ts
apps/api/src/app/organization_employeeLevel/organization-employee-level.entity.ts
apps/gauzy/src/app/@core/services/employee-level.service.ts
apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employee-levels/edit-organization-employee-level.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employee-levels/edit-organization-employee-level.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.module.ts
apps/gauzy/src/app/pages/organizations/organizations.module.ts
libs/models/src/lib/employee.model.ts

feat: added tags to org => positions

---

apps/gauzy/src/app/pages/candidates/candidate-statistic/candidate-statistic-charts/interviewer-assessment-chart/interviewer-assessment-chart.component.html
apps/gauzy/src/app/pages/candidates/candidate-statistic/candidate-statistic-charts/interviewer-assessment-chart/interviewer-assessment-chart.component.scss
apps/gauzy/src/app/pages/candidates/candidate-statistic/candidate-statistic-charts/interviewer-assessment-chart/interviewer-assessment-chart.component.ts
apps/gauzy/src/assets/i18n/en.json
yarn.lock

---
- added placeholder "No data", when no interview is selected
- fixed styles

Feature: candidate-statistic [ref:#1366]

---

apps/api/src/app/auth/auth.service.ts
apps/api/src/app/core/context/request-context.ts
apps/api/src/app/shared/decorators/permissions.ts
apps/api/src/app/timesheet/time-log/time-log.controller.ts
apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/api/src/app/timesheet/timesheet/timesheet.controller.ts
apps/api/src/app/timesheet/timesheet/timesheet.service.ts
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.ts
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.html
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.scss
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.ts
apps/gauzy/src/app/@shared/timesheet/filters/filters.module.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
apps/gauzy/src/assets/i18n/en.json
yarn.lock

Feat#489/time tracking 7

---

apps/api/src/app/organization/organization.entity.ts
apps/api/src/app/payment/payment.entity.ts
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts
apps/gauzy/src/app/pages/invoices/invoices-routing.module.ts
apps/gauzy/src/app/pages/invoices/invoices.module.ts
apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/payments/payments-routing.module.ts
apps/gauzy/src/app/pages/payments/payments.component.html
apps/gauzy/src/app/pages/payments/payments.component.ts
apps/gauzy/src/app/pages/payments/payments.module.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/payment.model.ts

Added a page where you can view all payments to an invoice made by your organization.
Video: https://www.loom.com/share/3e2e253f12c340629266ffafa5ff992f

feat: added organization level payments view page

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
apps/gauzy/src/app/pages/invoices/invoices.module.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-tasks-selector.component.ts

Fixed the api error in the invoice add page.
Video: https://www.loom.com/share/402f3d536abc4dca88dcc7cdbb71c618

feat: fixed api error in invoice add page

---

apps/gauzy/src/app/@core/role/permission.guard.ts
apps/gauzy/src/app/@core/services/approval-policy.service.ts
apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.html
apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.ts
apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.module.ts
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.html
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.ts
apps/gauzy/src/app/@shared/approvals/approvals-mutation.module.ts
apps/gauzy/src/app/pages/approval-policy/approval-policy-routing.module.ts
apps/gauzy/src/app/pages/approval-policy/approval-policy-status/approval-policy-status.component.html
apps/gauzy/src/app/pages/approval-policy/approval-policy-status/approval-policy-status.component.ts
apps/gauzy/src/app/pages/approval-policy/approval-policy.component.html
apps/gauzy/src/app/pages/approval-policy/approval-policy.component.ts
apps/gauzy/src/app/pages/approval-policy/approval-policy.module.ts
apps/gauzy/src/app/pages/approvals/approvals.component.ts
apps/gauzy/src/app/pages/approvals/table-components/approval-policy/approval-policy.component.html
apps/gauzy/src/app/pages/approvals/table-components/approval-policy/approval-policy.component.ts
apps/gauzy/src/app/pages/approvals/table-components/request-approval-status/request-approval-status.component.html
apps/gauzy/src/app/pages/approvals/table-components/request-approval-status/request-approval-status.component.ts
apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
libs/models/src/lib/approval-policy.model.ts
libs/models/src/lib/request-approval.model.ts

feat: #1132 approval-policy, request-approval form

---

apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/gauzy/src/app/@core/api.interceptor.ts
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.html
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.ts
apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.ts
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.module.ts
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.html
apps/gauzy/src/app/@theme/styles/includes/_dialog.scss
apps/gauzy/src/app/@theme/styles/styles.scss
apps/gauzy/src/app/app.module.ts
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals.module.ts
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.html
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar.module.ts
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.html
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily.module.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly.module.ts
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
libs/models/src/lib/timesheet.model.ts
libs/utils.ts

---
- Implement spinner when loading,
- Implement future date functionality,
- Disable Sentry logs when development, because not getting proper file name in console

feat: spinner and future date functionality

---

apps/api/src/app/event-types/event-type.controller.ts
apps/api/src/app/event-types/event-type.entity.ts

---
fixed event types page load
https://www.loom.com/share/f49ab2e360104174b4ba3d1626480495

fix: event types page load

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employee-levels/edit-organization-employee-level.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-positions/edit-organization-positions.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-vendors/edit-organization-vendors.component.html

fix: Add and Update without blank name in position-employelevel-vendor

---

apps/gauzy/src/app/pages/pipelines/pipelines.module.ts
apps/gauzy/src/app/pages/pipelines/stage-form/stage-form.component.html
apps/gauzy/src/app/pages/pipelines/stage-form/stage-form.component.ts

We can now reorder stages by drag&drop.
https://www.loom.com/share/a482c7ce2b3b44efa7a932254ef01a0c

feat: change stage order

---

apps/gauzy/src/app/pages/tags/tags.component.html
apps/gauzy/src/app/pages/tags/tags.component.scss
apps/gauzy/src/app/pages/tags/tags.component.ts
apps/gauzy/src/app/pages/tags/tags.module.ts

feat: implemented tags types

---

apps/api/src/app/organization/organization.entity.ts
apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.html
apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.ts
apps/gauzy/src/app/share/organization/organization.component.html
apps/gauzy/src/app/share/organization/organization.component.scss
apps/gauzy/src/app/share/organization/organization.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/organization.model.ts

- Company bonuses(bonus amount total) paid so far.
- Clients Count - total organization clients
- Public page translation data
The following one is the public page screenshot for the latest changes.

Public page

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects-mutation/edit-organization-projects-mutation.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects-mutation/edit-organization-projects-mutation.component.ts

feat:add client from dropdown in organization projects

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-employees-selector.component.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-product-selector.component.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-project-selector.component.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-tasks-selector.component.ts

Moved the drop down list in the invoice item table to edit mode.
Video: https://www.loom.com/share/98aed0ed31134e2a9d2cd98cb7071860

feat: moved drop down list to edit mode

---

apps/api/src/app/invoice/invoice.entity.ts
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-email/invoice-email-mutation.component.ts
apps/gauzy/src/app/pages/invoices/invoice-send/invoice-send-mutation.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/invoices/invoices.module.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-sent-status.component.ts
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/environments/environment.ts
libs/models/src/lib/invoice.model.ts
yarn.lock

Added sent status to the invoice table.
An invoice is considered sent if it is sent via email or the "Send" option in the invoice page.

feat: added sent status to invoice table

---

apps/gauzy/src/app/pages/goals/keyresult-details/keyresult-details.component.ts
apps/gauzy/src/app/pages/goals/keyresult-progress-chart/keyresult-progress-chart.component.ts

fix: keyResult details chart update

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.ts

---
fix: positions and employee level switch
https://www.loom.com/share/2783585a2cca4f2fbfdd0e4a15df7743

fix: positions and employee level switch

---

apps/gauzy/src/app/@shared/remove-lodash/remove-lodash.pipe.ts

---
fix: projects page crashing
https://www.loom.com/share/f6d2e325621a47a5aab3b596ea58bea9

fix: projects page crashing

---

apps/api/src/app/expense-categories/expense-categories.seed.ts
apps/api/src/app/expense-categories/expense-category.entity.ts
libs/models/src/lib/expense-category.model.ts

---
fix: expense-categories-page
https://www.loom.com/share/367970f6f856491581f039789f9bb05a

fix: expense-categories-page

---

.vscode/launch.json
angular.json
gauzy.code-workspace

---
1. Using [nrwl Issue](https://github.com/nrwl/nx/issues/1175#issuecomment-641320982) as a reference, configured gauzy API to enable inspection on port 9229 and added vscode launch.json configuration to attach to this port for debugging.
**Demo**
https://www.loom.com/share/9527b7c7d1ec4377891f53310b964801
@rmagon Please check if this works in Mac OS as well

fix: #1354 debugger config for backend

---

apps/api/src/app/employee/employee.service.ts
apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.ts

---
**What got changed?**
1.Added a fix to prevent sending empty string when no start date was selected. This used to cause the DB to throw errors for being incompatible data types(String and Date).
2. Newly added employee and the associated user had missing tenant information. Added a fix to populate both user and employee table with tenantId.
3. Tags selected in the user form were not a part of POST request payload, so tags were not linked to the newly added …

fix: #1283 fixed employee add feature and tags link to new employee

---

apps/api/src/app/timesheet/activity.entity.ts
apps/api/src/app/timesheet/screenshot.entity.ts
apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/api/src/app/timesheet/time-slot.service.ts
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal/view-time-log-modal.component.html
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts

---
@evereq @rmagon 
- Fix update time issue
- Display overlapping logs when add or edit time
- Use Translations
- Update/delete overlapping timelogs
- Delete time slots when update/delete timelogs
Video for demo 
https://www.loom.com/share/40ad1f3cf2d54021ba2580490f7efdd2

Feat#489/timesheet

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-clients/edit-organization-clients-mutation/edit-organization-clients-mutation.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-clients/edit-organization-clients-mutation/edit-organization-clients-mutation.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects-mutation/edit-organization-projects-mutation.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects-mutation/edit-organization-projects-mutation.component.ts

fixing bug for creating new project and client in dropdown

---

apps/gauzy/src/app/@shared/timer-picker/timer-picker/timer-picker.component.ts
apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment-routing.module.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts

This PR adds support for appointment booking for employees through Appointments page in Employees
---

feat(appointment-scheduling): changes for appointment booking for employees

---

apps/gauzy/src/app/pages/users/edit-user-profile/edit-user-organizations/edit-user-organizations.component.ts

---
fix : If user first or last name doesn't exist shows blank instead of null
https://www.loom.com/share/6069b8b0897e4476976cf66a3f995c8a

fix: user first and last name

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-departments/edit-organization-departments-mutation/edit-organization-departments-mutation.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employee-levels/edit-organization-employee-level.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-employment-types/edit-organization-employment-types.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-expense-categories/edit-organization-expense-categories.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-location/edit-organization-location.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-positions/edit-organization-positions.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-vendors/edit-organization-vendors.component.html

---
feat: improve functionality of organization fields like main, location, department, employee level, positions, vendors, expense categories and employment types
https://www.loom.com/share/c24fc83c2349451a9f20819fe7f8f8e7
https://www.loom.com/share/d4efbc76b54744b889ae1f81e770e69a

feat: improve functionality of organization

---

apps/api/src/app/appointment-employees/appointment-employees.controller.ts
apps/api/src/app/appointment-employees/appointment-employees.entity.ts
apps/api/src/app/employee-appointment/commands/employee-appointment.update.command.ts
apps/api/src/app/employee-appointment/commands/handlers/employee-appointment.update.handler.ts
apps/api/src/app/employee-appointment/employee-appointment.entity.ts
apps/gauzy/src/app/@core/services/appointment-employees.service.ts
apps/gauzy/src/app/@core/services/employee-appointment.service.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
apps/gauzy/src/app/share/public-appointments/confirm-appointment/confirm-appointment.component.html
apps/gauzy/src/app/share/public-appointments/confirm-appointment/confirm-appointment.component.ts
apps/gauzy/src/app/share/public-appointments/confirm-appointment/confirm-appointment.module.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/appointment-employees.model.ts
libs/models/src/lib/employee-appointment.model.ts

This PR adds support to cancel public appointment bookings, also when booking an appointment between employees within an organization, it will show appointment on calendar for all the attendees of that meeting.
---

feat(appointment_scheduling): support for cancel appointment and render appointment for all employees

---

apps/gauzy/src/app/share/organization/organization.component.scss
libs/models/src/lib/employee.model.ts

feat(public-page): gauzy companies public pages #515 - style and model

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-contacts/edit-organization-contact.component.scss
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-contacts/invite-contact/invite-contact.component.scss
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-contacts/invite-contact/invite-contact.component.ts

feat: #1111 scss files issue

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/employee/employee.service.ts
apps/api/src/app/language/language.service.ts
apps/api/src/app/skills/skill.service.ts
apps/api/src/app/tags/tag.service.ts
apps/api/src/app/upwork/upwork-transaction.service.ts
apps/gauzy/src/app/@shared/user/user-mutation/user-mutation.component.ts

fix: sonar qube critical issues fixed

---

.env.sample
.scripts/configure.ts
apps/gauzy/src/environments/environment.ts

feat: small improvements in generator of environment.ts

---

apps/api/src/app/request-approval-team/request-approval-team.entity.ts
apps/api/src/app/request-approval/request-approval.controller.ts
apps/api/src/app/request-approval/request-approval.entity.ts
apps/api/src/app/request-approval/request-approval.module.ts
apps/api/src/app/request-approval/request-approval.service.ts
apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.html
apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.scss
apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.ts
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.html
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.scss
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.ts
apps/gauzy/src/app/pages/approvals/approvals.component.html
apps/gauzy/src/app/pages/approvals/approvals.component.ts
apps/gauzy/src/app/pages/approvals/table-components/request-approval-type/request-approval-type.component.html
apps/gauzy/src/app/pages/approvals/table-components/request-approval-type/request-approval-type.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
libs/models/src/lib/request-approval-team.model.ts
libs/models/src/lib/request-approval.model.ts

- https://www.loom.com/share/644b44affcec4bb79ce1c7025f18c887 --> RequestApproval
---

feat: #1132  add team approval for request approval

---

apps/gauzy/src/app/pages/pages.component.ts

feat(bug fix, my task): hide my task if logged in user is not employee

---

apps/gauzy/src/app/@shared/time-off/time-off-mutation.components.scss
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request--mutation.component.ts
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.ts

feat: request days off functionality implemented on front end

---

apps/api/src/app/goal/goal.seed.ts

---
Fix goal seed failing issue

fix: goal seed failing fix

---

apps/api/src/app/app.module.ts
apps/api/src/app/core/core.module.ts
apps/api/src/app/time-off-request/time-off-request.controller.ts
apps/api/src/app/time-off-request/time-off-request.entity.ts
apps/api/src/app/time-off-request/time-off-request.module.ts
apps/api/src/app/time-off-request/time-off-request.service.ts
apps/gauzy/src/app/@core/services/time-off.service.ts
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request--mutation.component.ts
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.ts
libs/models/src/lib/time-off.model.ts

feat: back end implementation of request days off functionality

---

docker-compose.yml

fix: docker-compose file fix

---

apps/api/src/app/hubstaff/hubstaff.service.ts
apps/api/src/app/timesheet/commands/activity-create.command.ts
apps/api/src/app/timesheet/commands/handlers/activity-create.handler.ts
apps/api/src/app/timesheet/commands/handlers/screenshot-create.handler.ts
apps/gauzy/src/app/app-routing.module.ts
libs/models/src/lib/timesheet.model.ts

fix: added pagination & changed activities as per new flow

---

.deploy/api/Dockerfile
.deploy/api/entrypoint
.deploy/nginx/log/error.log
.deploy/nginx/nginx.conf
.deploy/webapp/Dockerfile
.deploy/webapp/entrypoint
.deploy/webapp/nginx.conf
docker-compose.yml

Docker-compose changes

---

apps/gauzy/src/app/pages/settings/email-history/email-filters/email-filters.component.ts
apps/gauzy/src/app/pages/settings/email-history/email-history.component.html
apps/gauzy/src/app/pages/settings/email-history/email-history.component.scss
apps/gauzy/src/app/pages/settings/email-history/email-history.component.ts
apps/gauzy/src/app/pages/settings/settings.module.ts

---
https://www.loom.com/share/148d690065df4c5c860166ef9283c43e
feat: sent emails history filter count
filter count badge
https://www.loom.com/share/e6adad1ea3ae473ea551212b723849e3

feat: sent emails history filter count

---

.deploy/api/Dockerfile

Fixed the issue regarding missing 'helmet' module

---

apps/api/src/app/tasks/task.controller.ts
apps/api/src/app/tasks/task.entity.ts
apps/api/src/app/tasks/task.seed.ts
apps/api/src/app/tasks/task.service.ts
apps/api/src/environments/environment.ts
apps/gauzy/src/app/@core/services/my-tasks-store.service.ts
apps/gauzy/src/app/@core/services/tasks-store.service.ts
apps/gauzy/src/app/@core/services/tasks.service.ts
apps/gauzy/src/app/@core/services/team-tasks-store.service.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

---
Implements feature for issue #1557

feat: add a created by field in tasks(1557)

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/organization-department/organization-department.seed.ts

- Updated organization.department.seed file to seed departments for organizations

Seed Department Organization

---

.deploy/webapp/nginx.conf

This PR fixes the issue of the NGINX container not serving the static files with the right type (`text/css` etc).
closes #1594 
---

Fix nginx not serving static files properly

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/organization-positions/organization-position.seed.ts

Seed Organization Position Entity

Seeded Organization Position entity

---

apps/api/src/app/auth/fiverr.strategy.ts
apps/api/src/app/email/email.entity.ts
apps/api/src/app/organization-projects/organization-projects.seed.ts
apps/api/src/app/time-off-request/time-off-request.entity.ts
apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/desktop/src/app/app.service.ts
apps/desktop/src/libs/tray-icon.ts
apps/gauzy/src/app/@core/services/toastr.service.ts
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-hiring/edit-employee-hiring.component.ts
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts

fix: deep scan issues fixed

---

apps/gauzy/src/app/@core/services/time-off.service.ts
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts
apps/gauzy/src/app/pages/time-off/time-off-settings/time-off-settings.component.ts
apps/gauzy/src/app/pages/time-off/time-off.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.ts

refactor: on time off pages promises replaced with rxjs observables

---

apps/desktop/src/app/app.service.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.service.ts
apps/desktop/src/libs/getSetStore.ts
apps/desktop/src/libs/timer.ts
apps/desktop/src/libs/tray-icon.ts

feat: remove all hardcode api host

---

apps/gauzy/src/app/pages/settings/edit-roles-permissions/edit-roles-permissions.component.html
apps/gauzy/src/app/pages/settings/edit-roles-permissions/edit-roles-permissions.component.ts

enable superAdmin roles and permissions

---

apps/api/src/app/time-off-request/time-off-request.controller.ts
apps/api/src/app/time-off-request/time-off-request.service.ts
apps/gauzy/src/app/@core/services/time-off.service.ts
apps/gauzy/src/app/pages/time-off/time-off.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.ts
libs/models/src/lib/time-off.model.ts

feat: time off grid page implemented

---

apps/api/src/app/role-permissions/role-permissions.seed.ts
apps/api/src/app/tasks/task.controller.ts
apps/api/src/app/tasks/task.service.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.ts
apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/role-permission.model.ts

Added a few fixes to my tasks and tasks API

fix: #992 my tasks fix

---

apps/api/src/app/time-off-request/time-off-request.entity.ts
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts
apps/gauzy/src/app/pages/time-off/time-off.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.scss
apps/gauzy/src/app/pages/time-off/time-off.component.ts
libs/models/src/lib/time-off.model.ts

feat: filters implemented on time off main page

---

.scripts/configure.ts
apps/api/package.json
apps/api/src/app/auth/auth.controller.ts
apps/api/src/app/auth/microsoft.strategy.ts
apps/api/src/environments/IMicrosoftConfig.ts
apps/api/src/environments/environment.prod.ts
apps/api/src/environments/environment.ts
apps/gauzy/src/app/@core/auth/auth.module.ts
apps/gauzy/src/environments/environment.ts
apps/gauzy/src/environments/model.ts

-   [ x ] Have you followed the [contributing guidelines](https://github.com/ever-co/gauzy/blob/master/.github/CONTRIBUTING.md)?
-   [ x ] Have you explained what your changes do, and why they add value?
---

fix: microsoft auth, provider and set the environment for gauzy website

---

apps/api/src/app/keyresult/keyresult.entity.ts
apps/gauzy/src/app/pages/goals/edit-keyresults/edit-keyresults.component.html
apps/gauzy/src/app/pages/goals/edit-keyresults/edit-keyresults.component.ts
apps/gauzy/src/app/pages/goals/goals.module.ts
apps/gauzy/src/app/pages/goals/keyresult-details/keyresult-details.component.html
apps/gauzy/src/app/pages/goals/keyresult-details/keyresult-details.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/goals.model.ts

---
Added Task integration for key results.
https://www.loom.com/share/73eb0b26fe43409ba5d10ee4673326c2

feat: task integration into keyresult entity

---

apps/api/src/app/request-approval/request-approval.controller.ts
apps/api/src/app/request-approval/request-approval.service.ts
apps/gauzy/src/app/@core/services/request-approval.service.ts
apps/gauzy/src/app/pages/approvals/approvals.component.scss
apps/gauzy/src/app/pages/approvals/approvals.component.ts
apps/gauzy/src/app/pages/approvals/approvals.module.ts
apps/gauzy/src/app/pages/approvals/table-components/request-approval-action/request-approval-action.component.html
apps/gauzy/src/app/pages/approvals/table-components/request-approval-action/request-approval-action.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

---
approval and refuse request --> https://www.loom.com/share/c86dc5da1bf8465caae13fa21724e4fa

feat: #1132 approval and refuse request by admin

---

apps/gauzy/src/app/pages/employees/appointment/appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/share/public-appointments/pick-employee/pick-employee.component.html
apps/gauzy/src/app/share/public-appointments/pick-employee/pick-employee.component.scss
apps/gauzy/src/app/share/public-appointments/pick-employee/pick-employee.component.ts
apps/gauzy/src/app/share/public-appointments/pick-employee/pick-employee.module.ts
apps/gauzy/src/app/share/public-appointments/pick-employee/pick-employee.routing.module.ts
apps/gauzy/src/app/share/share-routing.module.ts
apps/gauzy/src/assets/i18n/en.json

This PR adds an option to select employee on public appointment page.
---

feat(appointment_scheduling): pick employee on public appointment

---

apps/api/src/app/employee-appointment/employee-appointment.service.ts
apps/api/src/app/keyresult/keyresult.seed.ts
apps/api/src/app/organization-department/organization-department.seed.ts
apps/api/src/app/organization-positions/organization-position.seed.ts
apps/gauzy/src/app/pages/goals/keyresult-details/keyresult-details.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task-settings/task-settings.component.ts
apps/gauzy/src/app/pages/time-off/time-off.component.ts

fix: deep scan and sonar cube issues fixed

---

apps/api/src/app/organization-projects/organization-projects.entity.ts
libs/models/src/lib/organization-projects.model.ts

Added taskListType in organization-project

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/equipment-sharing/equipment-sharing.seed.ts
apps/api/src/app/equipment/equipment.seed.ts
apps/api/src/environments/environment.prod.ts
apps/api/src/environments/environment.ts
apps/api/src/environments/ienvironment.ts

Seed Equipment and Equipment Sharing

---

apps/desktop/src/app/app.component.ts
apps/desktop/src/app/app.service.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/getSetStore.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/notifier.ts
apps/desktop/src/libs/timer.ts
apps/desktop/src/libs/tray-icon.ts

feat: create time-log, and activity from desktop time tracking

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/organization-projects/organization-projects.seed.ts
apps/api/src/app/tasks/task.seed.ts
apps/api/src/app/timesheet/screenshot.entity.ts
apps/api/src/app/timesheet/time-log/time-log.controller.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts
apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/api/src/app/timesheet/time-slot/time-slot.controller.ts
apps/api/src/app/timesheet/time-slot/time-slot.seed.ts
apps/api/src/app/timesheet/time-slot/time-slot.service.ts
apps/api/src/app/timesheet/time-slot/utils.ts
apps/api/src/app/timesheet/timer/timer.service.ts
apps/api/src/app/timesheet/timesheet/timesheet.seed.ts
apps/api/src/app/upwork/upwork.module.ts
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker.module.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.html
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.scss
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
apps/gauzy/src/app/@shared/timer-picker/timer-picker/timer-picker.component.ts
apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.ts
apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
apps/gauzy/src/app/@theme/components/header/header.component.html
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
package.json
yarn.lock

Fix#1496/timer

---

apps/gauzy/src/app/pages/time-off/time-off.component.ts

fix: small fix in translations

---

apps/gauzy/src/app/pages/settings/email-history/email-filters/email-filters.component.html
apps/gauzy/src/app/pages/settings/email-history/email-filters/email-filters.component.ts
apps/gauzy/src/app/pages/settings/email-history/email-history.component.ts

---
https://www.loom.com/share/73e27d985f374709bf2f8df11e911d15

feat: email history added To to the email filters

---

apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.html
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts
package.json

feat: country specific holidays implemented on add holidays

---

apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.module.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/timezone-selector/timezone-selector.component.html
apps/gauzy/src/app/pages/employees/appointment/timezone-selector/timezone-selector.component.ts
apps/gauzy/src/app/pages/employees/appointment/timezone-selector/timezone-selector.module.ts
apps/gauzy/src/app/pages/employees/event-types/event-type-mutation/event-type-mutation.component.html
apps/gauzy/src/assets/i18n/en.json
package-lock.json
package.json
yarn.lock

This PR adds a timezone selector and reflects time zone changes in appointment bookings. Also https://github.com/ever-co/gauzy/issues/1685 is fixed along.
#WIP: Minor changes for public appointment timezone integration
---

feat(appointment_scheduling): integrated timezones in appointments

---

apps/api/src/app/upwork/upwork.service.ts
libs/models/src/lib/upwork.model.ts

feat: earnings/billings reports for freelancer/client

---

apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.html
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts
apps/gauzy/src/app/pages/time-off/time-off.component.ts

fix: holiday name displayed and unused import removed

---

apps/gauzy/src/app/pages/goals/edit-keyresults/edit-keyresults.component.html
apps/gauzy/src/app/pages/goals/edit-keyresults/edit-keyresults.component.ts
apps/gauzy/src/app/pages/goals/goals.component.ts
apps/gauzy/src/assets/i18n/en.json

---
- Feature added to create objectives from already existing key results and assign to Team/Organization/Employee.
https://www.loom.com/share/2ee866fbd89849df9ad771f7ee380a3e

feat: creating objectives from key results

---

apps/api/src/app/equipment-sharing/equipment-sharing.controller.ts
apps/api/src/app/equipment-sharing/equipment-sharing.entity.ts
apps/api/src/app/equipment-sharing/equipment-sharing.seed.ts
apps/api/src/app/equipment-sharing/equipment-sharing.service.ts
apps/gauzy/src/app/@core/services/equipment-sharing.service.ts
apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.component.ts
apps/gauzy/src/app/pages/equipment-sharing/equipment-sharing.component.ts
apps/gauzy/src/app/pages/equipment-sharing/equipment-sharing.module.ts
apps/gauzy/src/app/pages/equipment-sharing/equiqment-shareing.component.scss
apps/gauzy/src/app/pages/equipment-sharing/table-components/equipment-sharing-action/equipment-sharing-action.component.html
apps/gauzy/src/app/pages/equipment-sharing/table-components/equipment-sharing-action/equipment-sharing-action.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
libs/models/src/lib/equipment-sharing.model.ts

feat: #1683 Approval and refuse equipment sharing

---

apps/desktop/src/app/app.component.ts
apps/desktop/src/app/app.service.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.html
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/libs/getSetStore.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/timer.ts
apps/desktop/src/libs/tray-icon.ts

feat: time-log, activity change

---

.deploy/api/Dockerfile

---
This PR resolves the issue mentioned in https://github.com/lovell/sharp/issues/1882 and #1751. Closes #1751.

Fix issues with missing vips dependency

---

apps/api/src/app/time-off-request/time-off-request.service.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.module.ts
libs/models/src/lib/employee-appointment.model.ts

This PR completes timezone integration for public appointments. The default timezone for public appointment page will be based on user machine timezone.
Also, integrated Time Off feature in appointment booking.
Fixed issue where appointment booking at organization level was not possible before.
---

feat(appointment_scheduling): integrated time off & timezone in public appointment

---

apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/timer.ts
apps/desktop/src/libs/tray-icon.ts

feat: integrated tray icon with timetracking window

---

apps/api/src/app/role-permissions/role-permissions.seed.ts
apps/gauzy/src/app/pages/pages.component.ts

fix: #1711 menu sidebar and permission seed

---

apps/api/src/app/candidate-documents/candidate-documents.seed.ts
apps/api/src/app/candidate-feedbacks/candidate-feedbacks.seed.ts
apps/api/src/app/candidate-source/candidate-source.seed.ts
apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/expense/expense.seed.ts
apps/api/src/app/integration/integration.seed.ts
apps/api/src/app/keyresult-update/keyresult-update.seed.ts
apps/api/src/app/keyresult/keyresult.seed.ts
apps/api/src/app/organization-projects/organization-projects.seed.ts
apps/api/src/app/tasks/task.seed.ts
apps/api/src/app/timesheet/timesheet/timesheet.seed.ts

---
- Added **tryExecute()** for all non-essential seed fixes.
- This does **NOT** fix the underlying issues mentioned in #1761 but adds a try-catch for those functions so that the seed becomes more stable even if the underlying seed fails

fix: #1761 seed fixes

---

apps/api/src/app/app.module.ts
apps/api/src/app/core/core.module.ts
apps/api/src/app/organization-documents/organization-documents.controler.ts
apps/api/src/app/organization-documents/organization-documents.entity.ts
apps/api/src/app/organization-documents/organization-documents.module.ts
apps/api/src/app/organization-documents/organization-documents.service.ts
apps/gauzy/src/app/@core/services/organization-documents.service.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-documents/edit-organization-documents/edit-organization-documents.ts
libs/models/src/lib/organization-document.model.ts

feat: upload organization documents implemented on backend

---

apps/gauzy/src/app/@shared/table-components/status-view/status-view.component.html
apps/gauzy/src/app/@shared/table-components/status-view/status-view.component.ts
apps/gauzy/src/app/@shared/table-components/table-components.module.ts
apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/project-view.component.html
apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/tasks-sprint-settings-view/sprint-dialog/sprint-dialog.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/tasks-sprint-settings-view/tasks-sprint-settings-view.component.html
apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/tasks-sprint-settings-view/tasks-sprint-settings-view.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task-settings/task-settings.component.html
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
apps/gauzy/src/app/pages/tasks/components/task/tasks-layouts/tasks-sprint-view/task/task.component.html
apps/gauzy/src/app/pages/tasks/components/task/tasks-layouts/tasks-sprint-view/tasks-sprint-view.component.html

feat: #1770 first two parts of issue

---

apps/gauzy/src/app/@core/services/organization-documents.service.ts
apps/gauzy/src/app/@shared/file-uploader-input/file-uploader-input.component.html
apps/gauzy/src/app/@shared/file-uploader-input/file-uploader-input.component.ts
apps/gauzy/src/app/@shared/file-uploader-input/file-uploader-input.module.ts
apps/gauzy/src/app/@shared/user/forms/delete-confirmation/delete-confirmation.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-documents/edit-organization-documents/edit-organization-documents.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-documents/edit-organization-documents/edit-organization-documents.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/organization-document.model.ts

feat: organization documents upload functionality implemented

---

apps/api/src/app/tasks/task.entity.ts

Organization sprint delete should make null in tasks

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/environments/environment.prod.ts
apps/api/src/environments/environment.ts
apps/api/src/environments/ienvironment.ts

Added randomconfig in seeddataservice

---

apps/api/src/app/role-permissions/role-permissions.seed.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
apps/gauzy/src/app/@theme/components/header/header.component.ts
apps/gauzy/src/app/@theme/components/theme-settings/theme-settings.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/role-permission.model.ts

Create button permissions fixed, added missing permissions as mentioned in #1599 
"+ Create" button with permissions:
https://www.loom.com/share/aa5c1871f1b84f23bf62f4e7c0e5ffc0
Start timer opens a popup:
https://www.loom.com/share/c6642ce265ad46669e1526807713aa26

fix: #1599 create button functionality

---

Jenkinsfile

Fix parsing issues with Jenkinsfile

---

Jenkinsfile

Final improvements for Jenkins Pipeline

---

apps/api/src/app/tags/tag.entity.ts
apps/api/src/app/tags/tag.seed.ts

Some fix in tag

---

apps/gauzy/src/app/@theme/components/header/header.component.ts

---
Fixed add dialog open from "create" button shortcut
https://www.loom.com/share/4c7ec411dc3b424cb2012364a1ba3ad1

fix: #1599 open add dialog

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.scss
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-teams/edit-organization-teams.component.ts

---
PR: Make employees clickable on the Teams page

feat: #1805 make employees clickable on Teams page

---

Jenkinsfile

Fixed parsing and security issues.

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/equipment-sharing/equipment-sharing.entity.ts
apps/api/src/app/organization-documents/organization-documents.module.ts
apps/api/src/app/organization-documents/organization-documents.seed.ts
apps/api/src/app/time-off-request/time-off-request.entity.ts
apps/api/src/app/time-off-request/time-off-request.seed.ts
apps/api/src/app/upwork/upwork.service.ts
apps/gauzy/src/app/@core/services/organization-documents.service.ts
apps/gauzy/src/app/@shared/file-uploader-input/file-uploader-input.component.html
apps/gauzy/src/app/@shared/time-off/time-off-mutation.components.scss
apps/gauzy/src/app/@shared/time-off/time-off-mutation.module.ts
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.html
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
apps/gauzy/src/app/pages/tasks/components/task/tasks-layouts/tasks-sprint-view/task/task.component.ts
apps/gauzy/src/app/pages/tasks/components/task/tasks-layouts/tasks-sprint-view/tasks-sprint-view.component.ts
apps/gauzy/src/app/pages/time-off/time-off.component.ts
libs/models/src/lib/time-off.model.ts

feat: request days off document upload functionality implemented

---

apps/api/src/app/contact/contact.seed.ts
apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/organization-contact/organization-contact.seed.ts

Seed Contact, Organization_contact, Organization_team entities

---

apps/api/src/app/role-permissions/role-permissions.seed.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/employee-schedules/employee-schedules.component.html
apps/gauzy/src/app/pages/employees/appointment/employee-schedules/employee-schedules.component.ts
apps/gauzy/src/app/pages/employees/appointment/employee-schedules/employee-schedules.module.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.module.ts
apps/gauzy/src/app/pages/employees/event-types/event-type.component.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/role-permission.model.ts

This PR includes changes for https://github.com/ever-co/gauzy/issues/1806
And also, added check for employee availability during appointment booking. The end user can choose to proceed if the available slots are intersecting with the selected time for appointment. In case there is no slot around the selected time, it will not allow to select that employee
#WIP for some use cases to check date specific availability and other scenarios
---

feat(appointment_scheduling): added check for employee availability

---

.github/workflows/desktop-app.yml

Configure GitHub Actions for desktop builds

---

apps/api/src/app/upwork/upwork.service.ts

fix: name undefined client sync

---

apps/api/src/app/organization-documents/organization-documents.seed.ts
apps/gauzy/src/app/@shared/time-off/time-off-mutation.components.scss
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.html
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts
apps/gauzy/src/app/pages/pages.component.ts

feat: request forms for paid and unpaid days off seeded in db

---

apps/api/src/app/invoice-item/invoice-item.entity.ts
apps/gauzy/src/app/@core/services/expenses.service.ts
apps/gauzy/src/app/@shared/invoice/generate-pdf.ts
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-download/invoice-download-mutation.component.ts
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.html
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
apps/gauzy/src/app/pages/invoices/invoice-email/invoice-email-mutation.component.ts
apps/gauzy/src/app/pages/invoices/invoice-view/inner-component/invoice-view-inner.component.ts
apps/gauzy/src/app/pages/invoices/invoice-view/invoice-view.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/invoices/invoices.module.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-expense-selector.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/invoice-item.model.ts
libs/models/src/lib/invoice.model.ts

Added invoice type "By Expenses"
Video: https://www.loom.com/share/6dc7d601d5fc4dae946ac56ec848c35a

feat: added invoice type for expenses

---

apps/desktop/package.json
apps/desktop/src/package.json
tools/build/webpack.config.js

fix: desktop api error build beacuse of sharp module

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/assets/i18n/en.json

Added button that generates invoice items for all uninvoiced expenses.
Video: https://www.loom.com/share/a843fe4d09814ec48daacd1e148fa2b5

feat: added invoice item generation for all uninvoiced expenses

---

apps/api/src/app/candidate-criterions-rating/candidate-criterion-rating.seed.ts
apps/api/src/app/candidate-interviewers/candidate-interviewers.seed.ts
apps/api/src/app/candidate-skill/candidate-skill.seed.ts
apps/api/src/app/candidate/candidate.seed.ts
apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/employee-recurring-expense/employee-recurring-expense.seed.ts
apps/api/src/app/employee-setting/employee-setting.seed.ts
apps/api/src/app/goal-kpi/goal-kpi.seed.ts
apps/api/src/app/organization-contact/organization-contact.seed.ts

Seed Entities

---

Jenkinsfile

Fix problems with deprecated API call

---

.dockerignore
Jenkinsfile

Fix JSON parsing issues

---

Jenkinsfile

Changed the Jenkins url to use https

---

angular.json
apps/desktop/desktop-api/src/app/app.controller.spec.ts
apps/desktop/desktop-api/src/app/app.controller.ts
apps/desktop/desktop-api/src/app/app.module.ts
apps/desktop/desktop-api/src/app/app.service.spec.ts
apps/desktop/desktop-api/src/app/app.service.ts
apps/desktop/desktop-api/src/app/wakatime/branches.entity.ts
apps/desktop/desktop-api/src/app/wakatime/entities.entity.ts
apps/desktop/desktop-api/src/app/wakatime/language.entity.ts
apps/desktop/desktop-api/src/app/wakatime/machine.entity.ts
apps/desktop/desktop-api/src/app/wakatime/os.entity.ts
apps/desktop/desktop-api/src/app/wakatime/projects.entity.ts
apps/desktop/desktop-api/src/app/wakatime/wakatime.controller.ts
apps/desktop/desktop-api/src/app/wakatime/wakatime.entity.ts
apps/desktop/desktop-api/src/app/wakatime/wakatime.module.ts
apps/desktop/desktop-api/src/app/wakatime/wakatime.service.ts
apps/desktop/desktop-api/src/environments/environment.prod.ts
apps/desktop/desktop-api/src/environments/environment.ts
apps/desktop/desktop-api/src/main.ts
apps/desktop/desktop-api/tsconfig.app.json
apps/desktop/desktop-api/tsconfig.json
apps/desktop/desktop-api/tsconfig.spec.json
apps/desktop/desktop-api/tslint.json
apps/desktop/package.json
nx.json
package.json

feat: setup new api for Third party coding activity collection

---

Jenkinsfile

Implement pending commit status while Jenkins runs

---

Jenkinsfile

Fix typo in Jenkinsfile.

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/help-center-article/help-center-article.seed.ts
apps/api/src/app/help-center-author/help-center-author.seed.ts
apps/api/src/app/organization-languages/organization-languages.seed.ts
apps/api/src/app/organization-projects/organization-projects.seed.ts
apps/api/src/app/organization-recurring-expense/organization-recurring-expense.seed.ts
apps/api/src/app/organization-sprint/organization-sprint.seed.ts
apps/api/src/app/organization-team-employee/organization-team-employee.seed.ts
apps/api/src/app/pipeline-stage/pipeline-stage.seed.ts
apps/api/src/app/pipeline/pipeline.seed.ts

Seed tables

---

apps/api/src/app/hubstaff/hubstaff.service.ts
apps/api/src/app/upwork/upwork.controller.ts
apps/api/src/app/upwork/upwork.service.ts
apps/gauzy/src/app/@core/services/upwork-store.service.ts
apps/gauzy/src/app/@core/services/upwork.service.ts
apps/gauzy/src/app/pages/upwork/components/reports/reports.component.ts

fix: reports feature in upwork integration

---

apps/api/src/app/approval-policy/approval-policy.entity.ts
apps/api/src/app/approval-policy/approval-policy.seed.ts
apps/api/src/app/approval-policy/approval-policy.service.ts
apps/api/src/app/equipment-sharing/equipment-sharing.controller.ts
apps/api/src/app/equipment-sharing/equipment-sharing.module.ts
apps/api/src/app/equipment-sharing/equipment-sharing.service.ts
apps/api/src/app/organization/organization.seed.ts
apps/api/src/app/request-approval/request-approval.entity.ts
apps/api/src/app/tenant/tenant.seed.ts
libs/models/src/lib/approval-policy.model.ts

feat: #1683 add seeding and requestid for request approval

---

.github/workflows/desktop-app.yml

---
Requires a tag to automatically publish after the build, but this is expected behavior.

Fix Desktop App builds on GitHub Actions

---

apps/api/src/app/deal/deal.entity.ts
apps/api/src/app/pipeline/pipeline.module.ts
apps/api/src/app/pipeline/pipeline.service.ts
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deal-created-by/pipeline-deal-created-by.ts
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deal-form/pipeline-deal-form.component.html
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deal-form/pipeline-deal-form.component.ts
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deals.component.ts

feat: sales deals functionality improvements

---

apps/gauzy/src/app/pages/candidates/candidates.module.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-calendar/interview-calendar.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.html
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.scss
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/table-components/actions/actions.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/table-components/candidate/candidate.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/table-components/criterions/criterions.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/table-components/date/date.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/table-components/interviewers/interviewers.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/table-components/rating/rating.component.ts
apps/gauzy/src/assets/i18n/en.json

---
- fixed feedback edit card showing
- started working on making table for interview list

fix: interview table[ref:#1156]

---

apps/api/src/app/app.service.ts
apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/core/seeds/index.ts

Yarn start:api will seed only default necessary data

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/gauzy/src/app/pages/pipelines/pipelines.component.ts

fix: default time off policy seed fixed

---

apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.html
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.html
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.scss
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html

**Operating System** : Mac
**browser** : Google chrome
**node** : >=10.15.0
**yarn**: >=1.13.0
In Empoyees > Timesheet
Removed duplicate headers Weekly, Daily, Calendar, approval

removed duplicate header from employee timesheet

---

apps/api/src/app/timesheet/commands/handlers/time-slot-create.handler.ts
apps/api/src/app/timesheet/time-slot-minute.entity.ts
apps/api/src/app/timesheet/time-slot/time-slot.service.ts
apps/api/src/app/upwork/upwork.service.ts

fix: timeslot create/update and timeslot minute activity

---

apps/gauzy/src/app/pages/pipelines/pipeline-form/pipeline-form.component.html
apps/gauzy/src/app/pages/pipelines/pipeline-form/pipeline-form.component.scss
apps/gauzy/src/app/pages/pipelines/pipeline-form/pipeline-form.component.ts
apps/gauzy/src/app/pages/pipelines/pipelines.component.ts
apps/gauzy/src/app/pages/pipelines/stage-form/stage-form.component.html
apps/gauzy/src/app/pages/pipelines/stage-form/stage-form.component.ts

feat: add pipeline dialog window improved in terms of ui/ux

---

apps/api/src/app/timesheet/screenshot/screenshot.seed.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts

#1897 Feature seed data for timesheet

---

apps/api/src/app/approval-policy/approval-policy.controller.ts
apps/api/src/app/approval-policy/approval-policy.entity.ts
apps/api/src/app/approval-policy/approval-policy.seed.ts
apps/api/src/app/approval-policy/approval-policy.service.ts
apps/api/src/app/time-off-request/time-off-request.controller.ts
apps/api/src/app/time-off-request/time-off-request.module.ts
apps/api/src/app/time-off-request/time-off-request.service.ts
apps/gauzy/src/app/@core/services/approval-policy.service.ts
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.ts
apps/gauzy/src/app/@shared/equipment-sharing/equipment-sharing-mutation.component.ts
libs/models/src/lib/approval-policy.model.ts
libs/models/src/lib/time-off.model.ts

feat: #1683 link timeoff to request approval and update approvalType

---

apps/gauzy/src/app/pages/pipelines/pipeline-form/pipeline-form.component.scss
apps/gauzy/src/app/pages/pipelines/pipeline-form/pipeline-form.component.ts
apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.html
apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.ts
apps/gauzy/src/app/pages/proposals/proposals.module.ts

fix: job post content fixed on proposal details page

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/employee-recurring-expense/employee-recurring-expense.seed.ts
apps/api/src/app/employee/employee.seed.ts
apps/api/src/app/invite/invite.seed.ts
apps/api/src/app/invoice/invoice.seed.ts
apps/api/src/app/organization/organization.seed.ts
apps/api/src/app/proposal/proposal.seed.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts
apps/api/src/app/timesheet/timesheet/timesheet.seed.ts

Multiple seed correction

---

apps/api/src/app/export_import/export-all.module.ts
apps/api/src/app/upwork/upwork-report.service.ts
apps/api/src/app/upwork/upwork.service.ts
libs/models/src/lib/upwork.model.ts

fix: moved code into report seervice

---

apps/api/package.json
apps/api/src/app/core/seeds/seedAll.ts
package.json

Added yarn seed and yarn seed:all command in package.json

---

.deploy/api/Dockerfile

Use PM2 instead of bare nodeJS for the CMD

---

apps/gauzy/src/app/pages/candidates/candidates.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-profile.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-profile.component.scss
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-profile.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate.component.scss
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate.component.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.scss
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.scss
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts

---
PR:
1. Add Back in Edit Employees and Candidates.
2. Remove extra page in Edit Candidates and switch to '/pages/employees/candidates/edit/e8f73ae5-4f76-4e42-b5e3-681518694502/profile/account' url.
3. Add notification in candidate profile from extra page of Candidate.

feat: #1892 add back in edit candidate and employee

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/estimate-email/estimate-email.seed.ts
apps/api/src/app/event-types/event-type.seed.ts
apps/api/src/app/income/income.seed.ts
apps/api/src/app/integration-map/integration-map.seed.ts
apps/api/src/app/organization-languages/organization-languages.seed.ts
apps/api/src/app/tenant/tenant.seed.ts
apps/api/src/app/timesheet/screenshot/screenshot.seed.ts

multiple solution for seed data

---

apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.html
apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-payment-overdue.component.ts
apps/gauzy/src/app/pages/payments/payments.component.html
apps/gauzy/src/app/pages/payments/payments.component.ts
apps/gauzy/src/app/pages/payments/payments.module.ts

Payments can now be added without invoices.
Video: https://www.loom.com/share/d7ada8d2b5cb4e3e9707be61b73600eb

feat: added payments without invoices

---

apps/gauzy/src/app/@theme/components/header/header.component.ts

fixed paths for button create in header

fix: fixed paths for button create in header [ref:#1862]

---

apps/api/src/app/export_import/export-all.controller.ts
apps/api/src/app/export_import/export-all.service.ts
apps/gauzy/src/app/@core/services/exportAll.service.ts
apps/gauzy/src/app/pages/import-export/export/export.component.html
apps/gauzy/src/app/pages/import-export/export/export.component.scss
apps/gauzy/src/app/pages/import-export/export/export.component.ts
apps/gauzy/src/app/pages/import-export/export/export.module.ts
apps/gauzy/src/app/pages/pages.component.ts

---
0. All the checkboxes are selected by default (i.e, all the tables are exported)
1.  selected checkboxes exports specific types
2. Change in the design both Import and Export are on the same page

feat : export specific types

---

apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts

fix: #2007 Search for employees to be case insensitive

---

apps/gauzy/src/app/pages/equipment-sharing/equipment-sharing.component.html
apps/gauzy/src/app/pages/equipment/equipment.component.html
apps/gauzy/src/app/pages/inventory/components/table-inventory-items/table-inventory.component.html

feat: #1952 Move buttons below header in Equipment

---

apps/gauzy/src/app/@core/services/upwork-store.service.ts
apps/gauzy/src/app/pages/upwork/components/reports/reports.component.html
apps/gauzy/src/app/pages/upwork/components/reports/reports.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

feat: date range filter for report section in upwork integration #712

---

apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/timezone-selector/timezone-selector.component.ts
apps/gauzy/src/app/pages/tags/tags.component.html
apps/gauzy/src/app/pages/tags/tags.component.ts

This PR fixes search in Tags, hides previous days on appointment booking page, also shows current timezone in timezone selector.
---

feat(appointment_scheduling): fixes #1956 #1932 #1928

---

apps/api/src/app/request-approval/request-approval.module.ts
apps/api/src/app/request-approval/request-approval.service.ts
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.ts
apps/gauzy/src/app/pages/approvals/approvals.module.ts
apps/gauzy/src/app/pages/approvals/table-components/request-approval-status/request-approval-status.component.html

feat: #1683 Use badges and update request approval service

---

apps/api/src/app/time-off-request/time-off-request.controller.ts
apps/api/src/app/time-off-request/time-off-request.service.ts
apps/gauzy/src/app/@core/services/time-off.service.ts
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.html
apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts
apps/gauzy/src/app/pages/time-off/time-off.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

feat: edit time off request functionality implemented

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/goal/goal.seed.ts
apps/api/src/app/keyresult/keyresult.seed.ts
apps/api/src/app/organization-documents/organization-documents.seed.ts
apps/api/src/app/payment/payment.seed.ts
apps/api/src/app/product-option/product-option.seed.ts
apps/api/src/app/product-settings/product-settings.seed.ts
apps/api/src/app/product-type/product-type.seed.ts
apps/api/src/app/product-variant-price/product-variant-price.seed.ts
apps/api/src/app/product-variant/product-variant.seed.ts

'seedData'

---

apps/api/src/app/organization-contact/organization-contact.entity.ts
apps/api/src/app/organization-projects/organization-projects.entity.ts
apps/api/src/app/payment/payment.entity.ts
apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.scss
apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.html
apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
apps/gauzy/src/app/pages/payments/payments.component.ts
libs/models/src/lib/organization-projects.model.ts
libs/models/src/lib/payment.model.ts

Contact, project and tags can now be added to payments.
Video: https://www.loom.com/share/6b9d0ae1b3714a8aa104ed88a43924db

feat: added contact project and tags to payments

---

apps/gauzy/src/app/pages/time-off/time-off.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.scss
apps/gauzy/src/app/pages/time-off/time-off.component.ts

fix: filter time off requests by selected employee fixed

---

apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html

feat: #1878 Add labels to AddExpense/AddIncome dialogs

---

apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts

fix: #2024 Search to be case insensitive at Add Income page

---

apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.html

Now the pop-up window is split to 2 input lines.
---

fix: #1938 edit approval policy dialog box UI fixes

---

apps/gauzy/src/app/pages/approvals/approvals.component.scss
apps/gauzy/src/app/pages/approvals/table-components/request-approval-status/request-approval-status.component.ts
apps/gauzy/src/app/pages/candidates/candidates.component.scss
apps/gauzy/src/app/pages/employees/employees.component.scss
apps/gauzy/src/app/pages/employees/table-components/employee-work-status/employee-work-status.component.scss

all status badges now are with rounded corners.
---

feat: #1939 use rounded corner badges

---

apps/api/src/app/keyresult/keyresult.seed.ts
apps/api/src/app/product-category/category.seed.ts
apps/api/src/app/product-type/type.seed.ts

'minorFix'

---

apps/api/src/app/employee/employee.entity.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts
apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/api/src/app/timesheet/time-slot/time-slot.controller.ts
apps/api/src/app/timesheet/time-slot/time-slot.service.ts
apps/api/src/app/timesheet/timesheet/timesheet.seed.ts
apps/gauzy/src/app/@shared/tasks/task-select/task/task.component.html
apps/gauzy/src/app/@shared/tasks/task-select/task/task.component.ts
apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.html
apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.scss
apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.ts
apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.module.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.scss
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.module.ts
apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
apps/gauzy/src/app/pages/dashboard/dashboard.module.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.module.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity.module.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.html
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot.module.ts
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
libs/models/src/lib/employee.model.ts
libs/models/src/lib/timesheet.model.ts

Feat#1950/tracking dashboard

---

apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.html
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

---
The final result after my fix is the following: https://i.imgur.com/pCOjTQU.png

fix: #1889 Add/Edit Proposal UI fixes

---

apps/gauzy/src/app/pages/approvals/approvals.component.html
apps/gauzy/src/app/pages/expenses/expenses.component.html

---
After today's confirmation from R. Magon by Slack ("Rachit Magon 1:08 PM Yes please fix the other pages too") I fixed also pages:
- Accounting/Expences - https://i.imgur.com/TT5oAuS.png
- Employees/Approval Request - https://i.imgur.com/Mvft2W4.png

feat: #1952 Move buttons below header in Equipment - additional

---

apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.html
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html

---
I moved the "Add time" button to the left side in 'Daily', 'Weekly' and 'Calendar' pages:
- https://i.imgur.com/tI6vGj8.png
- https://i.imgur.com/v41QqCH.png
- https://i.imgur.com/eksf15z.png

fix: #1900 Timesheet UI fixes

---

apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html
apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts

Default contact type dropdown is set to 'Client'
---

feat: #1958 default contact type selection

---

apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html

fix: #1957 Contact save/cancel buttons should be at the bottom

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/invite/invite.seed.ts
apps/api/src/app/invoice/invoice.seed.ts
apps/api/src/app/payment/payment.seed.ts

Added defaultEmployeeInvite

---

apps/gauzy/src/app/@shared/product-mutation/product-category-mutation/product-category-mutation.component.html
apps/gauzy/src/app/@shared/product-mutation/product-category-mutation/product-category-mutation.component.scss
apps/gauzy/src/app/@shared/product-mutation/product-category-mutation/product-category-mutation.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.ts
apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.html

This PR includes fixes for https://github.com/ever-co/gauzy/issues/1954
---

feat(appointment_scheduling): fixes 1954

---

apps/desktop/desktop-api/src/app/wakatime/wakatime.controller.ts
apps/desktop/desktop-api/src/app/wakatime/wakatime.service.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.html

fix: change format response of heartbeats.bulk

---

apps/api/src/app/request-approval/request-approval.entity.ts
apps/api/src/app/request-approval/request-approval.service.ts
apps/api/src/app/tags/tag.entity.ts
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.html
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.scss
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.ts
apps/gauzy/src/app/@shared/approvals/approvals-mutation.module.ts
apps/gauzy/src/app/pages/approvals/approvals.component.ts
apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
libs/models/src/lib/request-approval.model.ts

feat: #1937 and #1960 add tags RA and set default project

---

apps/api/src/app/tasks/task.entity.ts
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html
apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.component.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.html
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
apps/gauzy/src/app/pages/tasks/components/task/task.component.html
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts

feat(appointment_scheduling): fixes 1896, 2052, 2059, 2060

---

apps/api/src/app/app.module.ts
apps/api/src/app/employee/employee.entity.ts
apps/api/src/app/organization-projects/organization-projects.entity.ts
apps/api/src/app/tasks/task.entity.ts
apps/api/src/app/timesheet/statistic/statistic.controller.ts
apps/api/src/app/timesheet/statistic/statistic.service.ts
apps/api/src/app/timesheet/time-slot/time-slot.controller.ts
apps/api/src/app/timesheet/time-slot/time-slot.service.ts
apps/api/src/app/timesheet/timesheet.module.ts
apps/gauzy/src/app/@shared/timesheet/activities/activity-item/activity-item.component.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
apps/gauzy/src/app/@shared/timesheet/timesheet-statistics.service.ts
apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.module.ts
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
libs/models/src/index.ts
libs/models/src/lib/timesheet-statistics.model.ts
libs/models/src/lib/timesheet.model.ts

---
Displayed recent activities on dashboard and created apis for the dashboard

feat: displayed recent activities on dashboard and created apis

---

apps/api/src/app/income/commands/handlers/income.create.handler.ts
apps/api/src/app/income/commands/handlers/income.delete.handler.ts
apps/api/src/app/income/commands/handlers/income.update.handler.ts
apps/api/src/app/income/commands/handlers/index.ts
apps/api/src/app/income/commands/income.delete.command.ts
apps/api/src/app/income/commands/income.update.command.ts
apps/api/src/app/income/income.controller.ts
apps/api/src/app/income/income.module.ts
apps/api/src/app/income/income.service.ts
apps/gauzy/src/app/@core/services/income.service.ts
apps/gauzy/src/app/pages/income/income.component.ts

https://www.loom.com/share/2f6f6b034e9c4166b3590b0c1d0a4914
-calculated income/bonuses average when expense is added/edited/deleted using CQRS

fix: average income/bonuses calculation[ref:#1894]

---

apps/gauzy/src/app/pages/time-off/time-off.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.scss
apps/gauzy/src/app/pages/time-off/time-off.component.ts

fix: #1942 time off ui improvements

---

apps/api/src/app/upwork/upwork-report.service.ts
apps/api/src/app/upwork/upwork.service.ts

fix: prevent duplicate records for client, income and expense

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/help-center-article/help-center-article.seed.ts
apps/api/src/app/help-center-author/help-center-author.seed.ts
apps/api/src/app/invite/invite.seed.ts
apps/api/src/app/organization-awards/organization-awards.controller.ts
apps/api/src/app/organization-languages/organization-languages.controller.ts
apps/api/src/app/organization-languages/organization-languages.entity.ts
apps/api/src/app/organization/organization.seed.ts
apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.ts
apps/gauzy/src/app/share/organization/organization.component.html
apps/gauzy/src/app/share/organization/organization.component.scss
apps/gauzy/src/app/share/organization/organization.component.ts

feed default data

---

apps/gauzy/src/app/pages/invoices/invoices.component.html
apps/gauzy/src/app/pages/invoices/invoices.component.scss
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/invoices/invoices.module.ts

Moved the column selector and status selector to a settings dialog.
Video: https://www.loom.com/share/1754a612df33432d91a4658f3b865e6e

feat: moved column selector and status selector to a settings dialog

---

apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
apps/gauzy/src/app/pages/projects/projects.component.html
apps/gauzy/src/app/pages/projects/projects.component.ts
apps/gauzy/src/app/pages/projects/projects.module.ts

feat: #1959 list view for projects

---

apps/api/src/app/availability-slots/availability-slots.seed.ts
apps/api/src/app/candidate-criterions-rating/candidate-criterion-rating.seed.ts
apps/api/src/app/candidate-feedbacks/candidate-feedbacks.seed.ts
apps/api/src/app/candidate-interview/candidate-interview.seed.ts
apps/api/src/app/candidate-interviewers/candidate-interviewers.seed.ts
apps/api/src/app/candidate-personal-qualities/candidate-personal-qualities.seed.ts
apps/api/src/app/candidate-technologies/candidate-technologies.seed.ts
apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/email/email.seed.ts
apps/api/src/app/employee-appointment/employee-appointment.seed.ts
apps/api/src/app/equipment-sharing/equipment-sharing.seed.ts
apps/api/src/app/invoice/invoice.seed.ts
apps/api/src/app/organization-department/organization-department.seed.ts
apps/api/src/app/organization-recurring-expense/organization-recurring-expense.seed.ts
apps/api/src/app/organization/organization.seed.ts
apps/api/src/app/pipeline/pipeline.seed.ts
apps/api/src/app/time-off-request/time-off-request.seed.ts
apps/api/src/app/timesheet/screenshot/screenshot.seed.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts
apps/gauzy/src/app/share/organization/organization.component.html

seed default datas

---

apps/api/src/app/organization-contact/organization-contact.entity.ts
apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.html
apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.scss
apps/gauzy/src/app/@shared/entity-with-members-card/entity-with-members-card.component.ts
apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.html
apps/gauzy/src/app/@shared/table-components/notes-with-tags/notes-with-tags.component.scss
apps/gauzy/src/app/pages/contacts/clients/clients.component.html
apps/gauzy/src/app/pages/contacts/clients/clients.component.ts
apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html
apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.scss
apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
apps/gauzy/src/app/pages/contacts/contact-routing.module.ts
apps/gauzy/src/app/pages/contacts/contact.component.html
apps/gauzy/src/app/pages/contacts/contact.component.ts
apps/gauzy/src/app/pages/contacts/contact.module.ts
apps/gauzy/src/app/pages/contacts/customers/customers.component.html
apps/gauzy/src/app/pages/contacts/customers/customers.component.ts
apps/gauzy/src/app/pages/contacts/leads/leads.component.html
apps/gauzy/src/app/pages/contacts/leads/leads.component.ts
apps/gauzy/src/app/pages/contacts/table-components/contact-action/contact-action.component.html
apps/gauzy/src/app/pages/contacts/table-components/contact-action/contact-action.component.ts
apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/organization-contact.model.ts

---
https://www.loom.com/share/3cd10a540b9c49a1bee49835478d2c18
In this PR: 
1. Filter leads, customers, and clients in contacts.
2. Added Image uploading feature in contacts.
3. Added table view in contacts.
Some points left in Table View, still working on them.

feat: #2063 contacts page improve

---

apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deal-form/pipeline-deal-form.component.ts
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deals.component.html
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deals.component.scss
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deals.component.ts
apps/gauzy/src/app/pages/pipelines/pipelines.component.html
apps/gauzy/src/assets/i18n/en.json

fix: #2097 deals filters by stage and organization implemented

---

apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html
apps/gauzy/src/assets/i18n/en.json

fix: add Income dialog change 'All Contacts' to 'Contact' #2106

---

apps/api/src/app/product/product.entity.ts
apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.html
apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.ts
libs/models/src/lib/product.model.ts

fix: #1953-Language-dropdown-in-Edit-Inventory-Item

---

apps/api/src/app/deal/deal.entity.ts
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deal-form/pipeline-deal-form.component.html
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deal-form/pipeline-deal-form.component.scss
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deal-form/pipeline-deal-form.component.ts
apps/gauzy/src/app/pages/pipelines/pipeline-deals/pipeline-deals.component.ts
libs/models/src/lib/contact.model.ts
libs/models/src/lib/deal.model.ts

feat: #490 client and organization added to deal model

---

apps/gauzy/src/app/app.component.ts

fix: on server down the page is loading persistently #2117

---

apps/gauzy/src/app/pages/pages.component.ts

---
https://www.loom.com/share/191e726fd1eb466cb738fb75461c44cb

fix: #2040 sidebar highlight

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts
apps/gauzy/src/app/share/organization/organization.component.html
apps/gauzy/src/app/share/organization/organization.component.ts
apps/gauzy/src/assets/i18n/en.json

---
Fixed/Checked the following cases:
User has permission and is super admin: All organizations editable
User has permission, but access to just one organization: Only that organization editable
User doesn't have permission: No organization editable
User logged out: No organization editable
https://www.loom.com/share/2d9803a73276455c89daf1d2be100ce0

feat: #2039 public page edit permission

---

apps/api/src/app/timesheet/statistic/statistic.service.ts
apps/api/src/app/timesheet/time-slot/time-slot.service.ts
apps/gauzy/src/app/@shared/timesheet/timesheet-statistics.service.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.module.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity.module.ts
libs/models/src/lib/timesheet-statistics.model.ts
libs/utils.ts

Feat#1950/tracking dashboard 2

---

apps/api/src/app/employee/commands/handlers/index.ts
apps/api/src/app/employee/commands/handlers/update-employee-total-worked-hours.handler.ts
apps/api/src/app/employee/commands/index.ts
apps/api/src/app/employee/commands/update-employee-total-worked-hours.command.ts
apps/api/src/app/employee/employee.entity.ts
apps/api/src/app/employee/employee.module.ts
apps/api/src/app/timesheet/time-log/commands/handlers/time-log-create.handler.ts
apps/api/src/app/timesheet/time-log/commands/handlers/time-log-delete.handler.ts
apps/api/src/app/timesheet/time-log/commands/handlers/time-log-update.handler.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity.module.ts
apps/gauzy/src/app/share/organization/organization.component.html
apps/gauzy/src/app/share/organization/organization.component.scss
libs/models/src/lib/employee.model.ts

---
Feature: Companies Page - Total number of hours worked over Gauzy #2037

feat: total number of hours worked over gauzy

---

apps/api/src/app/export_import/export-all.module.ts
apps/api/src/app/proposal/commands/handlers/index.ts
apps/api/src/app/proposal/commands/handlers/proposal-create.handler.ts
apps/api/src/app/proposal/commands/proposal-create.command.ts
apps/api/src/app/proposal/proposal.module.ts
apps/api/src/app/upwork/upwork-job.service.ts
apps/api/src/app/upwork/upwork-offers.service.ts
apps/api/src/app/upwork/upwork.controller.ts
apps/api/src/app/upwork/upwork.module.ts
apps/api/src/app/upwork/upwork.service.ts
apps/gauzy/src/app/@core/services/upwork-store.service.ts
libs/models/src/lib/integration.model.ts
libs/models/src/lib/upwork.model.ts

feat: #712 manage offers/proposals in upwork integration

---

apps/api/src/app/timesheet/activity/activity.controller.ts
apps/api/src/app/timesheet/timer/timer.service.ts
apps/desktop/desktop-api/src/main.ts
apps/desktop/src/app/app.component.ts
apps/desktop/src/app/app.service.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/timer.ts
apps/desktop/src/local-data/coding-activity.ts
apps/desktop/src/local-data/timer.ts

feat: integrate wakatime with timesheet

---

angular.json
apps/desktop/src/index.ts

fix: electron build api-desktop

---

apps/api/src/app/user-organization/user-organization.controller.ts

fix: #2124 Removing a user gives an error

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

fix: #2122 manager Organization

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/invoice/invoice.seed.ts
apps/api/src/app/timesheet/timesheet/timesheet.seed.ts

solved feat-2130, feat-2133, feat-1886

---

apps/api/src/app/expense/commands/handlers/expense.create.handler.ts
apps/api/src/app/expense/commands/handlers/expense.delete.handler.ts
apps/api/src/app/expense/commands/handlers/expense.update.handler.ts
apps/api/src/app/income/commands/handlers/income.create.handler.ts
apps/api/src/app/income/commands/handlers/income.delete.handler.ts
apps/api/src/app/income/commands/handlers/income.update.handler.ts
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.html
apps/gauzy/src/app/pages/expenses/expenses.component.scss
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/assets/i18n/en.json

---
PR: income and expense data on load fixed
https://www.loom.com/share/4f57a7b905274265ac77c7a1df1f8709

fix: #2107 income and expense data on load fixed

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/tasks/task.seed.ts
apps/api/src/app/timesheet/screenshot.entity.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts

feat/1897 - timesheet resolved

---

.deploy/api/Dockerfile

fix: resolve pm2 issue in Docker

---

apps/gauzy/src/app/pages/employee-levels/employee-level.component.html
apps/gauzy/src/app/pages/employee-levels/employee-level.component.ts
apps/gauzy/src/app/pages/employee-levels/employee-level.module.ts
apps/gauzy/src/app/pages/employment-types/employment-types.component.html
apps/gauzy/src/app/pages/employment-types/employment-types.component.ts
apps/gauzy/src/app/pages/positions/positions.component.html
apps/gauzy/src/app/pages/positions/positions.component.ts
apps/gauzy/src/app/pages/positions/positions.module.ts
apps/gauzy/src/assets/i18n/en.json

https://www.loom.com/share/3798ba3ed62e44ed89cd925112396385
- added grid/table view for Positions and Employee levels

fix: added card view for positions, employee levels[ref:#2061]

---

apps/desktop/desktop-api/src/app/app.module.ts
apps/desktop/src/libs/timer.ts

fix: desktop app not running

---

apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.html
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.scss

fix ui changes for feat/1875-uiFix

---

apps/api/src/app/organization-projects/organization-projects.seed.ts
apps/api/src/app/timesheet/statistic/statistic.controller.ts
apps/api/src/app/timesheet/statistic/statistic.service.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts
apps/api/src/app/timesheet/timesheet/timesheet.seed.ts
apps/api/src/app/user/user.entity.ts
apps/gauzy/src/app/@shared/components/avatar/avatar.component.html
apps/gauzy/src/app/@shared/components/avatar/avatar.component.scss
apps/gauzy/src/app/@shared/components/avatar/avatar.component.ts
apps/gauzy/src/app/@shared/pipes/duration-format.pipe.ts
apps/gauzy/src/app/@shared/timesheet/timesheet-statistics.service.ts
apps/gauzy/src/app/app.module.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
libs/models/src/lib/timesheet-statistics.model.ts
libs/models/src/lib/user.model.ts

---
- Fix error in the time tracking dashboard api
- Added statistics in time tracking dashboard

Feat#1950/tracking dashboard 3

---

apps/api/src/app/export_import/import/import-all.controller.ts

fix: destination access file system

---

apps/gauzy/src/assets/i18n/en.json

fix: missing translations

---

apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html
apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts
apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.html
apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.ts

https://www.loom.com/share/188e8e53ca5e4628a1eb7037c5315f87
- displayed expenses for all employees

fix: expenses for all employee[ref:#2062]

---

apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts

---
https://www.loom.com/share/5b530dfcd43e48cdae4298329484a769

fix: edit estimate error

---

apps/api/src/app/equipment-sharing/commands/equipment-sharing.create.command.ts
apps/api/src/app/equipment-sharing/commands/handlers/equipment-sharing.create.handler.ts
apps/api/src/app/equipment-sharing/equipment-sharing.controller.ts
apps/gauzy/src/app/pages/approvals/table-components/approval-policy/approval-policy.component.html

feat: #2163 Organization Requets Equipment Sharing Error

---

docker-compose.demo.yml

fix: improve demo docker-compose file

---

apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.scss

Issue #1879 has been resolved. Below is screen shot.

fix: #1879 tooltip related issue resolved

---

apps/desktop/README.md
apps/desktop/src/app/pages/setup/setup.component.html
apps/desktop/src/app/pages/setup/setup.component.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.html
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.module.ts
apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts

fix: validation input

---

apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts

---
https://www.loom.com/share/7189eb299efa44b7ba0e8ce3492c47e0

fix: delete invoice payment error

---

apps/gauzy/src/app/pages/payments/payments.component.ts

---
https://www.loom.com/share/b134ec9e90c24fe2873bc37f09c8197b

fix: delete payments payment error

---

apps/api/src/app/hubstaff/hubstaff.service.ts
apps/api/src/app/timesheet/commands/handlers/screenshot-create.handler.ts
apps/api/src/app/timesheet/commands/handlers/time-slot-create.handler.ts
libs/models/src/lib/employee.model.ts

fix: hubstaff synced info

---

apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html
apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
apps/gauzy/src/app/pages/contacts/contact.component.ts

fix: #2178 fix issue for null value of postcode

---

apps/api/src/app/candidate-interview/candidate-interview.service.ts
apps/gauzy/src/app/@shared/star-rating/star-rating-output/star-rating-output.component.html
apps/gauzy/src/app/@shared/star-rating/star-rating-output/star-rating-output.component.scss
apps/gauzy/src/app/@shared/star-rating/star-rating-output/star-rating-output.component.ts
apps/gauzy/src/app/pages/candidates/candidates.component.html
apps/gauzy/src/app/pages/candidates/candidates.component.scss
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.html
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.scss
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/table-components/actions/actions.component.ts
apps/gauzy/src/assets/i18n/en.json

https://www.loom.com/share/6b5fe1afd83d4719b7cd972ea5a7866f
- added Archive button for interviews
- added Add feedback button for interviews
- added badges for past and archived interview
- displayed interview list with archived interviews by clicking checkbox
i disable buttons according to
- we cannot leave feedback about an interview that has not happened yet
- we cannot leave feedback if all interviewers have already left their feedback
- we cannot change or delete past interviews, only archive

fix: added archive btn for interviews[ref:#868]

---

.circleci/config.yml

feat: add pulumi to CircleCI

---

apps/api/src/app/organization/organization.entity.ts
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.scss
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.html
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.scss
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/organization.model.ts

Added option in the invoice/estimate form to calculate the discount before or after the tax.
Added option in organization settings to set the default calculation.
Video: https://www.loom.com/share/ebb53d04039e44e89ba435d70be62bb4

feat: added option for calculating discount after tax

---

apps/api/src/app/upwork/upwork.service.ts

fix: #712 synced data for upwork integration 

---

apps/gauzy/src/app/pages/tasks/components/task/task.component.html

---
https://www.loom.com/share/0dd92e0eb307434991509a3368bceceb

fix: tasks grid layout buttons disabled

---

apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.html

---
https://www.loom.com/share/ce74cb899a894893b66abc634e63788b

fix: employees manage interviews error

---

apps/desktop/src/libs/timer.ts

fix: metadata json or text selected db

---

apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/tasks-sprint-settings-view/tasks-sprint-settings-view.component.html

---
https://www.loom.com/share/a161f0d726164686a2d1f810a00e7c28

fix: delete sprint dialog broken styling

---

apps/api/src/app/candidate-feedbacks/candidate-feedbacks.controller.ts
apps/api/src/app/candidate-feedbacks/commands/candidate-feedbacks.delete.command.ts
apps/api/src/app/candidate-feedbacks/commands/handlers/candidate-feedbacks.delete.handler.ts
apps/gauzy/src/app/@core/services/candidate-feedbacks.service.ts
apps/gauzy/src/app/@shared/candidate/candidate-confirmation/delete-feedback/delete-feedback.component.ts
apps/gauzy/src/app/pages/candidates/candidates.module.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.scss
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/table-components/status/status.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-interview/edit-candidate-interview.component.html
apps/gauzy/src/assets/i18n/en.json

- added some improvements into feedback delete query and CQRS
- added table view for feedbacks

fix: added table view for feedbacks, fixed delete query[ref:#868]

---

apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts

---
Fixed when timeslot is deleted to be registered not only in database but on UI also
https://www.loom.com/share/4848a5b31f3d4fe1833d40194925d5b6

fix: delete timeslot not registered on frontend

---

apps/api/src/app/candidate-source/candidate-source.controller.ts
apps/api/src/app/candidate-source/candidate-source.module.ts
apps/api/src/app/candidate-source/candidate-source.service.ts
apps/api/src/app/candidate/candidate.module.ts
apps/api/src/app/candidate/commands/handlers/candidate.bulk.create.handler.ts
apps/gauzy/src/app/@core/services/candidate-source.service.ts
apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.ts

https://www.loom.com/share/99dab2e7ffa44202acdd66165235083b
- finished creating candidate source during adding candidate

fix: candidate source  [ref:#868]

---

Jenkinsfile

---
This adds a hook that starts a GitHub Actions workflow that Jenkins will trigger after it's done pushing the images. The hook targets `gauzy-pulumi` repository.

feat: add webhook to trigger pulumi to update

---

Jenkinsfile

fix: typo and missing , in Jenkinsfile

---

Jenkinsfile

fix: add missing quote

---

Jenkinsfile

Finalize Jenkinsfile for Pulumi updates

---

apps/api/src/app/app.module.ts
apps/api/src/app/core/file-storage.ts
apps/api/src/app/timesheet/statistic/statistic.service.ts
apps/api/src/environments/environment.prod.ts
apps/api/src/environments/environment.ts
apps/api/src/environments/ienvironment.ts
apps/desktop/desktop-api/src/app/app.module.ts
apps/desktop/package.json
apps/desktop/src/app/app-routing.module.ts
apps/desktop/src/app/app.component.ts
apps/desktop/src/app/app.module.ts
apps/desktop/src/app/app.service.ts
apps/desktop/src/app/pages/screen-capture/screen-capture.component.html
apps/desktop/src/app/pages/screen-capture/screen-capture.component.scss
apps/desktop/src/app/pages/screen-capture/screen-capture.component.spec.ts
apps/desktop/src/app/pages/screen-capture/screen-capture.component.ts
apps/desktop/src/app/pages/screen-capture/screen-capture.module.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.html
apps/desktop/src/app/pages/time-tracker/time-tracker.component.scss
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.service.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/notifier.ts
apps/desktop/src/libs/screenshot.ts
apps/desktop/src/libs/timer.ts
apps/desktop/src/libs/tray-icon.ts
apps/desktop/src/local-data/timer.ts
apps/desktop/src/package.json

feat: gauzy desktop screenshot

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/hubstaff/hubstaff-entity-settings.ts

fix: #2275 added integrations default seed

---

apps/api/src/app/employee-appointment/employee-appointment.entity.ts
apps/api/src/app/employee-appointment/employee-appointment.seed.ts

fix: default employee appointment join columns issue

---

.gitignore
apps/api/.gitignore
apps/api/src/app/core/utils.ts
apps/api/src/app/export_import/export-all.service.ts
apps/api/src/app/export_import/import/import-all.controller.ts
apps/api/src/app/export_import/import/import-all.service.ts
apps/gauzy/src/app/pages/import-export/export/export.component.ts
apps/gauzy/src/app/pages/import-export/import/import.component.ts
apps/gauzy/src/assets/i18n/en.json

fix: #2174 import and export entity process

---

apps/gauzy-e2e/src/integration/InviteUserTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/InviteUserPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/InviteUserPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/InviteUser.po.ts
apps/gauzy-e2e/src/support/Base/utils/util.ts

---
Made e2e tests for Invite new user/s
https://www.loom.com/share/af67a086696840b689c217f80531a21e

feat: invite users e2e tests

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/deal/deal.entity.ts
apps/api/src/app/deal/deal.seed.ts
apps/api/src/app/organization/organization.entity.ts
apps/api/src/app/timesheet/screenshot/screenshot.seed.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts

fix:#2260 yarn seed all command

---

apps/gauzy/src/app/pages/employee-levels/employee-level.component.html
apps/gauzy/src/app/pages/employee-levels/employee-level.component.ts
apps/gauzy/src/app/pages/positions/positions.component.html
apps/gauzy/src/app/pages/positions/positions.component.ts

fix:#1489 improved functionality and UI

---

apps/gauzy-e2e/src/integration/AddUserTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/AddUserPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddUserPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/AddUser.po.ts

---
Added e2e tests for Add new User functionality!
https://www.loom.com/share/73fe7ddb8cf34f7da50cdfe8cf8f86d2

feat: add new user e2e tests

---

apps/gauzy-e2e/src/integration/AddExistingUserTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/AddExistingUserPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddExistingUserPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/AddExistingUser.po.ts
apps/gauzy-e2e/src/support/Base/utils/util.ts

---
Added e2e tests for Add Existing User/s functionality!
https://www.loom.com/share/7f680da2b3474c6290259df09338ae49

feat: add existing user e2e tests

---

apps/gauzy/src/app/pages/employee-levels/employee-level.component.ts
apps/gauzy/src/app/pages/employment-types/employment-types.component.html
apps/gauzy/src/app/pages/employment-types/employment-types.component.ts
apps/gauzy/src/app/pages/positions/positions.component.ts

fix: improved employee types and added unsubscribe

---

apps/gauzy/src/app/pages/vendors/vendors.component.html
apps/gauzy/src/app/pages/vendors/vendors.component.scss
apps/gauzy/src/app/pages/vendors/vendors.component.ts
apps/gauzy/src/assets/i18n/en.json

fix: vendor page UI and bugs

---

apps/api/src/app/tags/tag.entity.ts
apps/api/src/app/user/user.controller.ts
apps/api/src/app/user/user.service.ts
libs/models/src/lib/user.model.ts

fix:#2288 edit profile page credentials issue

---

apps/gauzy-e2e/src/integration/RemoveUserTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/RemoveUserPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/RemoveUserPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/RemoveUser.po.ts

---
Added e2e tests for Remove User functionality!
https://www.loom.com/share/c58368dc477448f3b04bc20c8b75b968

feat: remove user e2e tests

---

apps/api/src/app/export_import/export-all.service.ts
apps/gauzy/src/app/pages/import-export/export/export.component.html
apps/gauzy/src/app/pages/import-export/export/export.component.ts
apps/gauzy/src/app/pages/import-export/export/export.module.ts
apps/gauzy/src/app/pages/settings/settings.component.html
apps/gauzy/src/app/pages/settings/settings.component.ts
apps/gauzy/src/app/pages/settings/settings.module.ts

feat:#2050 added export checkbox categorization

---

apps/api/src/app/integration/integration-type.seed.ts
apps/api/src/app/integration/integration.entity.ts
apps/api/src/app/tags/tag.entity.ts
apps/api/src/app/tags/tag.service.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/integration.model.ts

feat:#1121 integrations improvements

---

apps/api/src/app/integration/commands/handlers/integration.get.handler.ts
apps/gauzy/src/app/@core/services/integrations-store.service.ts
apps/gauzy/src/app/@core/services/integrations.service.ts
apps/gauzy/src/app/pages/integrations/components/integrations-list/integrations-list.component.html
apps/gauzy/src/app/pages/integrations/components/integrations-list/integrations-list.component.scss
apps/gauzy/src/app/pages/integrations/components/integrations-list/integrations-list.component.ts
libs/models/src/lib/integration.model.ts

fix:#1121 integrations paid filter feature

---

apps/gauzy-e2e/src/integration/ManageUserInvitesTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/ManageUserInvitesPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ManageUserInvitesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/ManageUserInvites.po.ts

---
Added e2e tests for Manage Invites with Copy, Resend and Delete invite functionalities
https://www.loom.com/share/a2fae9835ec642388272ce0c8f4dacf4

feat: manage invites e2e tests

---

apps/api/src/app/candidate-education/candidate-education.controller.ts
apps/api/src/app/country/country.controller.ts
apps/api/src/app/email-template/email-template.controller.ts
apps/api/src/app/email/email.controller.ts
apps/api/src/app/employee-award/employee-award.controller.ts
apps/api/src/app/employee-statistics/employee-statistics.controller.ts
apps/api/src/app/estimate-email/estimate-email.controller.ts
apps/api/src/app/integration-tenant/integration-tenant.controller.ts
apps/api/src/app/organization-awards/organization-awards.controller.ts
apps/api/src/app/organization-projects/organization-projects.controller.ts
apps/api/src/app/tags/tag.controller.ts

feat:#1281 added auth guard for missing api

---

apps/api/src/app/organization-team-employee/organization-team-employee.entity.ts

fix: rename missing entity name

---

apps/gauzy-e2e/src/integration/EmailTempatesTest.ts
apps/gauzy-e2e/src/integration/ManageUserInvitesTest.ts

---
Refactored e2e tests for Email Templates and Manage User Invites

feat: refactored e2e tests

---

apps/api/src/app/integration-tenant/integration-tenant.module.ts
apps/api/src/app/integration/integration.controller.ts
apps/api/src/app/integration/integration.module.ts
apps/api/src/app/integration/integration.service.ts
apps/api/src/app/upwork/upwork.controller.ts
apps/api/src/app/upwork/upwork.service.ts
apps/gauzy/src/app/@core/services/hubstaff.service.ts
apps/gauzy/src/app/@core/services/upwork.service.ts
apps/gauzy/src/app/pages/hubstaff/components/hubstaff-authorize/hubstaff-authorize.component.ts
apps/gauzy/src/app/pages/hubstaff/components/hubstaff/hubstaff.component.html
apps/gauzy/src/app/pages/hubstaff/components/hubstaff/hubstaff.component.ts
apps/gauzy/src/app/pages/hubstaff/components/settings-dialog/settings-dialog.component.ts
apps/gauzy/src/app/pages/hubstaff/hubstaff-routing.module.ts
apps/gauzy/src/app/pages/hubstaff/hubstaff.module.ts
apps/gauzy/src/app/pages/upwork/components/upwork/upwork.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

feat:#2318 hubstaff integration remember state

---

apps/gauzy-e2e/src/integration/OrganizationTagsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationTagsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationTagsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationTags.po.ts

---
Finished Organization tags e2e tests

feat: organization tags e2e tests

---

apps/api/src/app/tags/tag.controller.ts
apps/api/src/app/tags/tag.service.ts
apps/gauzy/src/app/@core/services/tags.service.ts
apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.ts
apps/gauzy/src/app/@shared/tags/tags-mutation.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/tags/tags.component.ts

fix:#2091 tags and income pages issue

---

apps/api/src/app/timesheet/activity/activity.controller.ts
apps/api/src/app/timesheet/activity/activity.service.ts
apps/api/src/app/timesheet/activity/commands/bulk-activites-save.command.ts
apps/api/src/app/timesheet/activity/commands/handlers/bulk-activites-save.handler.ts
apps/api/src/app/timesheet/activity/commands/handlers/index.ts
apps/api/src/app/timesheet/time-slot/commands/handlers/create-time-slot.handler.ts
apps/api/src/app/timesheet/timesheet.module.ts
libs/models/src/lib/timesheet.model.ts

fix: bulk save activity api

---

apps/api/src/app/availability-slots/availability-slots.service.ts
apps/api/src/app/availability-slots/commands/handlers/availability-slots.bulk.create.handler.ts
apps/api/src/app/time-off-request/time-off-request.service.ts
apps/api/src/app/timesheet/activity/activity.service.ts
apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/api/src/app/timesheet/time-slot/time-slot.service.ts
apps/api/src/app/timesheet/timesheet/timesheet.service.ts
apps/gauzy/src/app/@shared/project-select/project/project.component.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.ts
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.ts
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
libs/models/src/lib/availability-slots.model.ts
libs/models/src/lib/time-off.model.ts
libs/models/src/lib/timesheet.model.ts

fix:#2091 added tenantId related changes in the employees menus

---

apps/desktop/src/app/app.service.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/timer.ts
apps/desktop/src/libs/tray-icon.ts
apps/desktop/src/local-data/timer.ts
apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
apps/gauzy/src/app/@core/auth/auth.guard.ts

fix: create timeslot

---

apps/api/src/app/app.module.ts
apps/api/src/app/core/file-storage/file-storage.ts
apps/api/src/app/tenant/tenant-setting/tenant-setting.module.ts
apps/api/src/app/tenant/tenant-setting/tenant-setting.service.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.ts
apps/gauzy/src/assets/i18n/en.json

Fix#2278/setting issue

---

apps/api/src/app/core/context/request-context.ts
apps/api/src/app/timesheet/activity/commands/handlers/bulk-activites-save.handler.ts
apps/api/src/app/timesheet/time-log/commands/handlers/time-log-create.handler.ts
apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/api/src/app/timesheet/time-slot/commands/handlers/create-time-slot-minutes.handler.ts
apps/api/src/app/timesheet/time-slot/commands/handlers/create-time-slot.handler.ts
apps/api/src/app/timesheet/time-slot/commands/handlers/time-slot-bulk-create-or-update.handler.ts
apps/api/src/app/timesheet/time-slot/commands/handlers/time-slot-bulk-create.handler.ts
apps/api/src/app/timesheet/time-slot/commands/handlers/update-time-slot.handler.ts
apps/api/src/app/timesheet/time-slot/time-slot.service.ts
apps/api/src/app/timesheet/timer/timer.service.ts
apps/api/src/app/timesheet/timesheet/commands/handlers/timesheet-first-or-create.handler.ts
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts

fix: save time logs and display time logs issue

---

apps/api/src/app/timesheet/time-log/commands/handlers/time-log-create.handler.ts
apps/api/src/app/timesheet/timer/timer.service.ts
apps/api/src/app/timesheet/timesheet/commands/handlers/timesheet-first-or-create.handler.ts
apps/api/src/app/timesheet/timesheet/commands/timesheet-first-or-create.command.ts
apps/gauzy/src/app/@core/services/toastr.service.ts
apps/gauzy/src/app/@shared/contact-selector/contact-selector.component.html
apps/gauzy/src/app/@shared/contact-selector/contact-selector.component.ts
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.scss
apps/gauzy/src/app/@shared/project-select/project/project.component.html
apps/gauzy/src/app/@shared/project-select/project/project.component.ts
apps/gauzy/src/app/@shared/tasks/task-select/task/task.component.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.html
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.html
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.scss
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.ts
apps/gauzy/src/app/@shared/timesheet/timesheet-filter.service.ts
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
libs/models/src/lib/timesheet.model.ts
libs/utils.ts

fix: timer isssue

---

apps/api/src/app/employee/commands/handlers/update-employee-total-worked-hours.handler.ts
apps/api/src/app/timesheet/statistic/statistic.service.ts
apps/api/src/app/timesheet/time-log/commands/handlers/time-log-update.handler.ts
apps/api/src/app/timesheet/time-log/commands/time-log-update.command.ts
apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/desktop/src/app/app.service.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/libs/getSetStore.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/screenshot.ts
apps/desktop/src/libs/tray-icon.ts
apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts

fix: duration today, complete parameter, manage tray icon

---

apps/api/src/app/employee/commands/handlers/update-employee-total-worked-hours.handler.ts
apps/api/src/app/timesheet/statistic/statistic.service.ts
apps/api/src/app/timesheet/time-log/commands/handlers/time-log-update.handler.ts
apps/api/src/app/timesheet/time-log/commands/time-log-update.command.ts
apps/api/src/app/timesheet/time-log/time-log.service.ts
apps/api/src/app/timesheet/timer/timer.controller.ts
apps/api/src/app/timesheet/timer/timer.service.ts
apps/desktop/src/app/app.service.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/libs/getSetStore.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/screenshot.ts
apps/desktop/src/libs/tray-icon.ts
apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.ts
apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.spec.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.ts
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
libs/models/src/lib/timesheet.model.ts

fix: added start and stop timer api

---

apps/desktop/src/index.ts
apps/desktop/src/libs/menu.ts
apps/desktop/src/libs/tray-icon.ts

feat: add item in menubar

---

apps/api/src/app/help-center-author/commands/handlers/help-center-author.bulk.create.handler.ts
apps/api/src/app/help-center-author/commands/help-center-author.bulk.create.command.ts
apps/api/src/app/help-center-author/help-center-author.controller.ts
apps/api/src/app/help-center/help-center.controller.ts
apps/api/src/app/organization-projects/organization-projects.entity.ts
apps/gauzy/src/app/@core/services/help-center-author.service.ts
apps/gauzy/src/app/@core/services/help-center.service.ts
apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html
apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts
apps/gauzy/src/app/@shared/sidebar/edit-base/edit-base.component.ts
apps/gauzy/src/app/@shared/sidebar/sidebar.component.ts
apps/gauzy/src/app/pages/departments/departments.component.ts
apps/gauzy/src/app/pages/documents/documents.component.ts
apps/gauzy/src/app/pages/employment-types/employment-types.component.ts
apps/gauzy/src/app/pages/expense-recurring/expense-recurring.component.ts
apps/gauzy/src/app/pages/help-center/add-article/add-article.component.ts
apps/gauzy/src/app/pages/help-center/help-center.component.ts
apps/gauzy/src/app/pages/positions/positions.component.ts
apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
apps/gauzy/src/app/pages/projects/projects.component.html
apps/gauzy/src/app/pages/projects/projects.component.ts
apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.ts
apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.ts
apps/gauzy/src/app/pages/teams/teams.component.html
apps/gauzy/src/app/pages/teams/teams.component.ts
apps/gauzy/src/app/pages/time-off/time-off.component.ts
apps/gauzy/src/app/pages/vendors/vendors.component.ts
libs/models/src/lib/help-center-article.model.ts
libs/models/src/lib/help-center-menu.model.ts
libs/models/src/lib/organization-recurring-expense.model.ts

fix: multiple API calls and tenant and organization related fixes

---

apps/desktop/package.json

fix: different sharp vesion

---

apps/desktop/desktop-api/src/main.ts
apps/desktop/src/index.ts
apps/desktop/src/window/gauzy.ts

fix: added logging error and quit window

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/goal-kpi/goal-kpi.seed.ts
apps/api/src/app/tasks/task.seed.ts
apps/api/src/app/timesheet/activity/activities.seed.ts
apps/api/src/app/timesheet/screenshot.entity.ts
apps/api/src/app/timesheet/screenshot/screenshot.seed.ts
apps/api/src/app/timesheet/time-log/time-log.seed.ts
apps/api/src/app/timesheet/timesheet/timesheet.seed.ts
apps/gauzy/src/app/@core/services/my-tasks-store.service.ts
apps/gauzy/src/app/@core/services/tasks-store.service.ts
apps/gauzy/src/app/@core/services/tasks.service.ts
apps/gauzy/src/app/@core/services/team-tasks-store.service.ts
apps/gauzy/src/app/pages/payments/payments.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
libs/models/src/lib/task-entity.model.ts

fix:#2091 activity and timelog seeder issue

---

apps/api/src/app/core/file-storage/providers/local.provider.ts
apps/desktop/src/app/pages/settings/settings.component.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/getSetStore.ts
apps/desktop/src/libs/ipc.ts

fix: gauzy desktop windows

---

apps/api/src/app/hubstaff/hubstaff-entity-settings.ts
apps/api/src/app/hubstaff/hubstaff.controller.ts
apps/api/src/app/hubstaff/hubstaff.service.ts
apps/api/src/app/integration-entity-setting-tied-entity/integration-entity-setting-tied-entity.seed.ts
apps/api/src/app/integration-tenant/integration-tenant.entity.ts
apps/api/src/app/organization/commands/handlers/index.ts
apps/api/src/app/organization/commands/handlers/organization.update.handler.ts
apps/api/src/app/organization/commands/index.ts
apps/api/src/app/organization/commands/organization.update.command.ts
apps/api/src/app/timesheet/commands/handlers/activity-create.handler.ts
apps/api/src/app/upwork/upwork.controller.ts
apps/api/src/app/upwork/upwork.service.ts
apps/gauzy/src/app/@core/services/hubstaff.service.ts
apps/gauzy/src/app/@core/services/store.service.ts
apps/gauzy/src/app/@core/services/upwork.service.ts
apps/gauzy/src/app/app-routing.module.ts
apps/gauzy/src/app/pages/hubstaff/components/hubstaff-authorize/hubstaff-authorize.component.ts
apps/gauzy/src/app/pages/hubstaff/components/hubstaff/hubstaff.component.ts
apps/gauzy/src/app/pages/upwork/components/upwork-authorize/upwork-authorize.component.ts
libs/models/src/lib/hubstaff.model.ts
libs/models/src/lib/integration.model.ts
libs/models/src/lib/organization.model.ts
libs/models/src/lib/upwork.model.ts

feat:#2091 working on hubstaff integration tenant organization base

---

apps/api/src/app/timesheet/time-slot/commands/handlers/time-slot-bulk-create-or-update.handler.ts
apps/api/src/app/timesheet/time-slot/commands/handlers/time-slot-bulk-create.handler.ts
apps/api/src/app/timesheet/time-slot/commands/handlers/time-slot-merge.handler.ts
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html

Fix#489/time traking 4

---

apps/api/src/app/expense/commands/handlers/expense.create.handler.ts
apps/api/src/app/hubstaff/hubstaff.service.ts
apps/api/src/app/income/commands/handlers/income.create.handler.ts
apps/api/src/app/integration-setting/commands/handlers/integration-setting.get.handler.ts
apps/api/src/app/integration-setting/commands/handlers/integration-setting.getMany.handler.ts
apps/api/src/app/integration-tenant/integration-tenant.entity.ts
apps/api/src/app/integration-tenant/integration-tenant.seed.ts
apps/api/src/app/integration-tenant/integration-tenant.service.ts
apps/api/src/app/integration/integration.controller.ts
apps/api/src/app/integration/integration.service.ts
apps/api/src/app/timesheet/commands/handlers/timesheet-create.handler.ts
apps/api/src/app/upwork/upwork-transaction.service.ts
apps/api/src/app/upwork/upwork.controller.ts
apps/api/src/app/upwork/upwork.service.ts
apps/gauzy/src/app/@core/services/hubstaff.service.ts
apps/gauzy/src/app/@core/services/upwork-store.service.ts
apps/gauzy/src/app/@core/services/upwork.service.ts
apps/gauzy/src/app/pages/hubstaff/components/hubstaff-authorize/hubstaff-authorize.component.ts
apps/gauzy/src/app/pages/upwork/components/reports/reports.component.ts
apps/gauzy/src/app/pages/upwork/components/transactions/transactions.component.ts
apps/gauzy/src/app/pages/upwork/components/upwork-authorize/upwork-authorize.component.ts
apps/gauzy/src/app/pages/upwork/components/upwork/upwork.component.ts
libs/models/src/lib/integration.model.ts
libs/models/src/lib/timesheet.model.ts
libs/models/src/lib/upwork.model.ts

Fix:#2091 App and Integrations menu tenant and organization base

---

apps/api/src/app/core/seeds/SeedDataService.ts
apps/api/src/app/email-template/email-template.seed.ts
apps/api/src/app/email-template/queries/handlers/email-template.find.handler.ts
apps/api/src/app/employee/employee.entity.ts
apps/api/src/app/export_import/export-all.controller.ts
apps/api/src/app/export_import/export-all.service.ts
apps/api/src/app/skills/skill.entity.ts
apps/api/src/app/skills/skill.seed.ts
apps/api/src/app/tenant/tenant-setting/tenant-setting.entity.ts
apps/api/src/app/timesheet/activity/activities.seed.ts
apps/gauzy/src/app/@core/services/exportAll.service.ts
apps/gauzy/src/app/@core/services/store.service.ts
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
apps/gauzy/src/app/@theme/components/header/header.component.ts
apps/gauzy/src/app/pages/email-templates/email-templates.component.ts
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/import-export/export/export.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts
apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
apps/gauzy/src/app/pages/projects/projects.component.html
apps/gauzy/src/app/pages/projects/projects.component.ts
apps/gauzy/src/app/pages/settings/email-history/email-filters/email-filters.component.ts
apps/gauzy/src/app/pages/settings/email-history/email-history.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
apps/gauzy/src/app/pages/teams/teams.component.html
apps/gauzy/src/app/share/employee/employee.component.ts
libs/models/src/lib/email-template.model.ts
libs/models/src/lib/skill-entity.model.ts

fix:#2091 settings menu and header open popup fixes

---

apps/api/src/app/core/seeds/allEntity.ts
apps/api/src/app/employee-statistics/employee-statistics.service.ts
apps/api/src/app/employee-statistics/queries/handlers/aggregate-employee-statistic.handler.ts
apps/api/src/app/employee-statistics/queries/handlers/employee-statistics-history.handler.ts
apps/api/src/app/employee-statistics/queries/handlers/month-aggregated-employee-statistics.handler.ts
apps/api/src/app/tenant/tenant-setting/tenant-setting.entity.ts
apps/api/src/app/timesheet/statistic/statistic.service.ts
apps/gauzy/src/app/@shared/dashboard/records-history/records-history.component.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.ts
apps/gauzy/src/app/pages/dashboard/human-resources/human-resources.component.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/payments/payments.component.html
apps/gauzy/src/app/pages/payments/payments.component.ts
apps/gauzy/src/app/pages/payments/payments.module.ts
libs/models/src/lib/employee-statistics.model.ts
package.json
yarn.lock

fix:# 2091 employee login fixes

---

apps/api/src/app/timesheet/timesheet/timesheet.controller.ts
apps/api/src/app/timesheet/timesheet/timesheet.service.ts
apps/gauzy/src/app/@shared/contact-selector/contact-selector.component.html
apps/gauzy/src/app/@shared/contact-selector/contact-selector.component.ts
apps/gauzy/src/app/@shared/project-select/project/project.component.html
apps/gauzy/src/app/@shared/project-select/project/project.component.ts
apps/gauzy/src/app/@shared/tasks/task-select/task/task.component.html
apps/gauzy/src/app/@shared/tasks/task-select/task/task.component.ts
apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
libs/models/src/lib/organization-contact.model.ts

Fix#489/time traking 5

---

apps/api/src/app/role/role.entity.ts
apps/api/src/app/tasks/task.controller.ts
apps/gauzy/src/app/@core/services/tasks-store.service.ts
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
apps/gauzy/src/app/pages/invoices/invoice-email/invoice-email-mutation.component.ts
apps/gauzy/src/app/pages/invoices/invoice-view/invoice-view.component.html
apps/gauzy/src/app/pages/invoices/invoices.component.html
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-employees-selector.component.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-product-selector.component.ts
apps/gauzy/src/app/pages/invoices/table-components/invoice-tasks-selector.component.ts

fix: #2091 observable unsubscribe and functionality fixes

---

apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts

fix:#2414 task creation

---

apps/desktop/src/app/app.service.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/menu.ts
apps/desktop/src/libs/screenshot.ts
apps/desktop/src/libs/timer.ts
apps/desktop/src/window/setup.ts

fix: timeslot and actity desktop app

---

apps/api/src/app/organization-sprint/organization-sprint.service.ts
apps/api/src/app/tasks/task.service.ts
apps/gauzy/src/app/@core/services/organization-sprint-store.service.ts
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.html
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.ts
apps/gauzy/src/app/@shared/employee/employee-mutation/employee-mutation.component.ts
apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html
apps/gauzy/src/app/@shared/expenses/recurring-expense-block/recurring-expense-block.component.html
apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html
apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
apps/gauzy/src/app/@theme/components/header/selectors/organization/organization.component.ts
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/expense-recurring/expense-recurring.component.html
apps/gauzy/src/app/pages/expense-recurring/expense-recurring.component.ts
apps/gauzy/src/app/pages/payments/payments.component.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts
apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.html
apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/tasks-sprint-settings-view/tasks-sprint-settings-view.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
apps/gauzy/src/app/pages/tasks/components/task/tasks-layouts/tasks-sprint-view/tasks-sprint-view.component.ts
apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts

fix: functionality fixes

---

apps/api/src/app/approval-policy/approval-policy.controller.ts
apps/api/src/app/approval-policy/approval-policy.module.ts
apps/api/src/app/approval-policy/approval-policy.service.ts
apps/api/src/app/auth/auth.service.ts
apps/api/src/app/core/context/request-context.ts
apps/api/src/app/role-permissions/role-permissions.controller.ts
apps/api/src/app/shared/decorators/permissions.ts
apps/api/src/app/shared/guards/auth/tenant-permission.guard.ts
apps/api/src/app/tenant/tenant.entity.ts
apps/gauzy/src/app/pages/settings/edit-roles-permissions/edit-roles-permissions.component.ts
libs/models/src/lib/approval-policy.model.ts
libs/models/src/lib/http-status.enum.ts
libs/models/src/lib/tenant.model.ts

Feat: #2332 created tenant permission guard

---

apps/api/src/app/shared/guards/auth/tenant-permission.guard.ts

fix: #2332 tenant mismatch fixes

---

apps/gauzy/src/app/@core/services/job.service.ts
apps/gauzy/src/app/@shared/contact-selector/contact-selector.component.ts
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.html
apps/gauzy/src/app/pages/jobs/job-layout/job-layout.component.html
apps/gauzy/src/app/pages/jobs/job-layout/job-layout.component.spec.ts
apps/gauzy/src/app/pages/jobs/job-layout/job-layout.component.ts
apps/gauzy/src/app/pages/jobs/jobs-routing.module.ts
apps/gauzy/src/app/pages/jobs/jobs.module.ts
apps/gauzy/src/app/pages/jobs/matching/matching-routing.module.ts
apps/gauzy/src/app/pages/jobs/matching/matching.module.ts
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.html
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.spec.ts
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.ts
apps/gauzy/src/app/pages/jobs/search/search-routing.module.ts
apps/gauzy/src/app/pages/jobs/search/search.module.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.spec.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/index.ts
libs/models/src/lib/employee-job.model.ts

---
- Added Jobs Menu
- Added Jobs Page

feat: added jobs menu and page

---

apps/api/src/app/core/entities/base.ts
apps/api/src/app/employee-job/employee-job.controller.ts
apps/api/src/app/employee-job/employee-job.entity.ts
apps/api/src/app/employee-job/employee-job.module.ts
apps/api/src/app/employee-job/employee-job.seed.ts
apps/api/src/app/employee-job/employee-job.service.ts
apps/api/src/app/employee-job/jobPost.entity.ts
apps/gauzy/src/app/@core/services/job.service.ts
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.ts
apps/gauzy/src/app/pages/jobs/search/search.module.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.scss
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/index.ts
libs/models/src/lib/core.model.ts
libs/models/src/lib/employee-job.model.ts
libs/models/src/lib/timesheet.model.ts

feat: change filter ui and make api call

---

apps/api/src/app/shared/guards/auth/organization-permission.guard.ts
apps/api/src/app/shared/guards/auth/tenant-permission.guard.ts
apps/api/src/app/user/user.seed.ts
apps/api/src/environments/environment.ts
apps/api/src/environments/ienvironment.ts

Feat: #2422 added global setting for AllowSuperAdminRole

---

apps/desktop/src/app/pages/screen-capture/screen-capture.component.html
apps/desktop/src/app/pages/screen-capture/screen-capture.component.scss
apps/desktop/src/app/pages/screen-capture/screen-capture.component.ts
apps/desktop/src/app/pages/settings/settings.component.html
apps/desktop/src/app/pages/settings/settings.component.scss
apps/desktop/src/app/pages/settings/settings.component.ts
apps/desktop/src/app/pages/settings/settings.module.ts
apps/desktop/src/libs/getSetStore.ts
apps/desktop/src/libs/menu.ts
apps/desktop/src/libs/screenshot.ts

feat: added setting enable/disable notification

---

apps/desktop/src/app/pages/time-tracker/time-tracker.component.html
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.service.ts
apps/desktop/src/libs/screenshot.ts
apps/desktop/src/libs/tray-icon.ts

fix: added Tenan-ID header

---

apps/api/src/app/employee-job-preset/commands/handlers/create-job-preset.handler.ts
apps/api/src/app/employee-job-preset/commands/handlers/index.ts
apps/api/src/app/employee-job-preset/commands/handlers/save-employee-preset.handler.ts
apps/api/src/app/employee-job-preset/commands/handlers/save-preset-criterion.handler.ts
apps/api/src/app/employee-job-preset/commands/save-employee-preset.command.ts
apps/api/src/app/employee-job-preset/commands/save-preset-criterion.command.ts
apps/api/src/app/employee-job-preset/employee-job-preset.controller.ts
apps/api/src/app/employee-job-preset/employee-upwork-jobs-search-criterion.entity.ts
apps/api/src/app/employee-job-preset/job-preset.entity.ts
apps/api/src/app/employee-job-preset/job-preset.service.ts
apps/gauzy/src/app/@core/services/job-preset.service.ts
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.html
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.ts
libs/models/src/lib/job-matching.model.ts

feat: save criterion in job preset and for employee

---

apps/api/src/app/core/core.module.ts
apps/api/src/app/core/seeds/allEntity.ts
apps/api/src/app/employee-job-preset/commands/handlers/create-job-preset.handler.ts
apps/api/src/app/employee-job-preset/employee-job-preset.module.ts
apps/api/src/app/employee-job-preset/employee-upwork-jobs-search-criterion.entity.ts
apps/api/src/app/employee-job-preset/job-preset-upwork-job-search-criterion.entity.ts
apps/api/src/app/employee-job-preset/job-preset.service.ts
apps/api/src/app/employee-job-preset/job-search-category/job-search-category.controller.ts
apps/api/src/app/employee-job-preset/job-search-category/job-search-category.entity.ts
apps/api/src/app/employee-job-preset/job-search-category/job-search-category.service.ts
apps/api/src/app/employee-job-preset/job-search-occupation/job-search-occupation.controller.ts
apps/api/src/app/employee-job-preset/job-search-occupation/job-search-occupation.entity.ts
apps/api/src/app/employee-job-preset/job-search-occupation/job-search-occupation.service.ts
apps/gauzy/src/app/@core/services/job-search-category.service.ts
apps/gauzy/src/app/@core/services/job-search-occupation.service.ts
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.html
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.ts
libs/models/src/index.ts
libs/models/src/lib/job-matching.model.ts
libs/models/src/lib/job-search-category.model.ts
libs/models/src/lib/job-search-occupation.model.ts

---
- Save category and occupation in db
- Fix seed all issue

Feat#2429/configure matching

---

apps/gauzy/src/app/@shared/components/avatar/avatar.component.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

fix: added employee avatar in smart grid

---

libs/integration-ai/src/lib/gauzy-ai.service.ts
libs/integration-ai/src/lib/sdk/gauzy-ai-sdk.ts
libs/integration-ai/src/lib/sdk/queries/query.graphql
libs/integration-ai/src/lib/sdk/schema.graphql

feat: add more logic for communication with Gauzy AI

---

apps/api/src/app/organization-contact/organization-contact.controller.ts
apps/api/src/app/organization-contact/organization-contact.service.ts
apps/api/src/app/organization-projects/organization-projects.controller.ts
apps/api/src/app/organization-projects/organization-projects.service.ts
apps/api/src/app/role-permissions/role-permissions.seed.ts
apps/api/src/app/tags/tag.controller.ts
apps/api/src/app/tags/tag.service.ts
apps/gauzy/src/app/@core/services/organization-contact.service.ts
apps/gauzy/src/app/@core/services/organization-projects.service.ts
apps/gauzy/src/app/@core/services/tags.service.ts
apps/gauzy/src/app/@shared/contact-selector/contact-selector.component.ts
apps/gauzy/src/app/@shared/project-select/project/project.component.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.html
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
apps/gauzy/src/app/@theme/components/header/header.component.html
apps/gauzy/src/app/@theme/components/header/header.component.ts
apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.ts
apps/gauzy/src/app/pages/dashboard/human-resources/human-resources.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-contact/edit-employee-contact.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-projects/edit-employee-projects.component.ts
apps/gauzy/src/app/pages/goal-settings/goal-settings.component.ts
apps/gauzy/src/app/pages/tags/tags.component.ts
libs/models/src/lib/role-permission.model.ts
libs/models/src/lib/timesheet.model.ts

Fix: bugs and tenant fixes

---

apps/api/src/app/employee-job-preset/commands/handlers/save-preset-criterion.handler.ts
apps/api/src/app/employee-job-preset/employee-job-preset.module.ts
libs/integration-ai/src/lib/gauzy-ai.service.ts
libs/models/src/lib/job-matching.model.ts

fix: save employee criterion issue

---

apps/gauzy-e2e/src/integration/OrganizationTagsTest.ts
apps/gauzy-e2e/src/integration/RemoveUserTest.ts
apps/gauzy-e2e/src/support/Base/pages/EditUser.po.ts

fix: refactored user and tags e2e tests

---

apps/gauzy-e2e/src/integration/TimeOffTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/TimeOffPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/TimeOffPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/TimeOff.po.ts

feat: started time off page e2e tests

---

apps/api/src/app/role-permissions/role-permissions.service.ts
apps/api/src/app/role/commands/handlers/index.ts
apps/api/src/app/role/commands/handlers/tenant-role-bulk-create.handler.ts
apps/api/src/app/role/commands/tenant-role-bulk-create.command.ts
apps/api/src/app/role/role.module.ts
apps/api/src/app/role/role.service.ts
apps/api/src/app/tenant/tenant.entity.ts
apps/api/src/app/tenant/tenant.module.ts
apps/api/src/app/tenant/tenant.service.ts
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.ts
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts

fix: tenant and filters issue

---

apps/api/src/app/employee-job/employee-job.controller.ts
apps/api/src/app/employee-job/employee-job.service.ts
apps/gauzy/src/app/@core/services/job.service.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
libs/models/src/lib/employee-job.model.ts

feat: set actions on job search page

---

apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.html
apps/gauzy/src/app/@shared/employee/employee-multi-select/employee-multi-select.component.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.html
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.ts
apps/gauzy/src/app/@shared/timesheet/timesheet-filter.service.ts
apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal/view-time-log-modal.component.html
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts

Fix: timer-tracker on/off and timesheets filters issue

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

feat: set color for applied lable

---

apps/api/src/app/timesheet/activity/activity.service.ts
apps/api/src/app/timesheet/activity/commands/bulk-activities-save.command.ts
apps/api/src/app/timesheet/activity/commands/handlers/bulk-activities-save.handler.ts
apps/api/src/app/timesheet/activity/commands/handlers/index.ts
apps/api/src/app/timesheet/time-slot/commands/handlers/create-time-slot.handler.ts
apps/gauzy/src/app/@shared/timesheet/activity.service.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.ts

fix: activities dispaly issue

---

apps/api/src/app/role-permissions/role-permissions.seed.ts
apps/gauzy/src/app/pages/settings/edit-roles-permissions/edit-roles-permissions.component.html
apps/gauzy/src/app/pages/users/edit-user-mutation/edit-user-mutation.component.ts
apps/gauzy/src/app/pages/users/users.component.html
apps/gauzy/src/app/pages/users/users.component.ts
apps/gauzy/src/app/pages/users/users.module.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/role-permission.model.ts
libs/models/src/lib/user.model.ts

fix users sidebar menu issue

---

libs/models/src/lib/role-permission.model.ts

fix: re added deleted permission

---

apps/gauzy/src/app/pages/employees/appointment/appointment.component.html
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
libs/utils/src/lib/utils.ts

fix: appointment fullcalendar onload issue

---

apps/gauzy-e2e/src/integration/AddEmployeeLevelTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/AddEmployeeLevelPageData.ts
apps/gauzy-e2e/src/support/Base/pagedata/EditProfilePageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddEmployeeLevelPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/AddEmployeeLevel.po.ts

feat: added employee levels e2e tests

---

apps/gauzy-e2e/src/integration/AddEmployeePositionTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/AddEmployeePositionPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddEmployeePositionPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/AddEmployeePosition.po.ts

feat: added employee positions e2e tests

---

apps/gauzy/src/app/@shared/pipes/index.ts
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.html
apps/gauzy/src/app/pages/jobs/search/search.module.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

Fix#2429/configure matching 2

---

apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json

Fix: Layout Setting Sidebar Dropdown

---

apps/gauzy-e2e/src/integration/AddTasksTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/AddTasksPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddTasksPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/AddTasks.po.ts

feat: added tasks e2e tests

---

apps/api/src/app/candidate/candidate.entity.ts
apps/api/src/app/employee-appointment/commands/handlers/employee-appointment.create.handler.ts
apps/api/src/app/event-types/commands/handlers/event-type.create.handler.ts
apps/gauzy/src/app/pages/candidates/candidates.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-feedbacks/edit-candidate-feedbacks.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/timezone-selector/timezone-selector.component.ts
apps/gauzy/src/app/pages/employees/event-types/event-type-mutation/event-type-mutation.component.ts
apps/gauzy/src/app/pages/employees/event-types/event-type.component.ts
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.html
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.ts
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.module.ts
apps/gauzy/src/app/share/public-appointments/public-appointments.component.ts
libs/models/src/lib/availability-slots.model.ts
libs/models/src/lib/candidate.model.ts
libs/models/src/lib/employee-appointment.model.ts
libs/models/src/lib/event-type.model.ts
libs/utils/src/lib/utils.ts

Fix: Appointment/Schedule/Candidate Page

---

apps/desktop/src/app/pages/settings/settings.component.html
apps/desktop/src/app/pages/settings/settings.component.scss
apps/desktop/src/app/pages/settings/settings.component.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/menu.ts
apps/desktop/src/libs/screenshot.ts
apps/desktop/src/libs/tray-icon.ts
apps/desktop/src/window/settings.ts
apps/desktop/src/window/timeTracker.ts

fix: advanced setting

---

apps/gauzy-e2e/src/integration/TimesheetsTest.ts
apps/gauzy-e2e/src/support/Base/pageobjects/TimesheetsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Timesheets.po.ts

feat: started timesheets e2e tests

---

apps/gauzy-e2e/src/integration/AddEmployeePositionTest.ts
apps/gauzy-e2e/src/integration/AddTasksTest.ts
apps/gauzy-e2e/src/integration/EventTypesTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/EventTypesPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/EventTypesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/EventTypes.po.ts

feat: added event types page e2e tests

---

apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts

fix: #2485 invalid date e2e timesheet timelog testing

---

apps/gauzy-e2e/src/support/Base/pagedata/EditProfilePageData.ts

---
Previous tests failed with login with new credentials after profile was edited because regular users are don't have permission to change their data so added test to use local.admin instead.

fix: edit profile and login with new credentials

---

apps/gauzy-e2e/src/integration/ApprovalRequestTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/ApprovalRequestPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ApprovalRequestPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/ApprovalRequest.po.ts

feat: added approval request page e2e tests

---

apps/gauzy-e2e/src/integration/TimesheetsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/TimesheetsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/TimesheetsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Timesheets.po.ts

feat: add new time log e2e tests

---

apps/api/src/app/candidate-criterions-rating/commands/handlers/candidate-criterions-rating.bulk.create.handler.ts
apps/api/src/app/candidate-education/candidate-education.seed.ts
apps/api/src/app/candidate-interview/candidate-interview.seed.ts
apps/api/src/app/candidate/candidate.controller.ts
apps/api/src/app/candidate/candidate.entity.ts
apps/api/src/app/core/seeds/seed-data.service.ts
apps/api/src/app/organization-department/organization-department.entity.ts
apps/api/src/app/organization-employment-type/organization-employment-type.entity.ts
apps/api/src/app/organization-employment-type/organization-employment-type.seed.ts
apps/api/src/app/organization-positions/organization-positions.controller.ts
apps/api/src/app/organization-team/organization-team.seed.ts
apps/api/src/app/user/user.seed.ts
apps/gauzy/src/app/@shared/candidate/candidate-interview-feedback/candidate-interview-feedback.component.ts
apps/gauzy/src/app/pages/candidates/candidate-statistic/candidate-statistic-charts/criterions-rating-chart/criterions-rating-chart.component.ts
apps/gauzy/src/app/pages/candidates/candidate-statistic/candidate-statistic.component.ts
apps/gauzy/src/app/pages/candidates/candidates.component.html
apps/gauzy/src/app/pages/candidates/candidates.component.ts
apps/gauzy/src/app/pages/candidates/candidates.module.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-employment/edit-candidate-employment.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-employment/edit-candidate-employment.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-interview/edit-candidate-interview.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-profile.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/table-components/actions/actions.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.ts
libs/models/src/lib/candidate-criterions-rating.model.ts
libs/models/src/lib/candidate.model.ts
libs/models/src/lib/organization-department.model.ts
libs/models/src/lib/organization-employment-type.model.ts

Fix: Candidate edit profile pages

---

apps/gauzy-e2e/src/integration/AddEmployeeLevelTest.ts
apps/gauzy-e2e/src/integration/AddEmployeePositionTest.ts
apps/gauzy-e2e/src/integration/AddExistingUserTest.ts
apps/gauzy-e2e/src/integration/AddTasksTest.ts
apps/gauzy-e2e/src/integration/ApprovalRequestTest.ts
apps/gauzy-e2e/src/integration/ManageUserInvitesTest.ts
apps/gauzy-e2e/src/integration/OrganizationTagsTest.ts
apps/gauzy-e2e/src/integration/RecurringExpensesTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/AddExistingUserPageData.ts
apps/gauzy-e2e/src/support/Base/pagedata/AddTasksPageData.ts
apps/gauzy-e2e/src/support/Base/pagedata/ApprovalRequestPageData.ts
apps/gauzy-e2e/src/support/Base/pagedata/RecurringExpensesPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddExistingUserPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddTasksPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationTagsPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/RecurringExpensesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/AddEmployeePosition.po.ts
apps/gauzy-e2e/src/support/Base/pages/AddExistingUser.po.ts
apps/gauzy-e2e/src/support/Base/pages/AddTasks.po.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationTags.po.ts
apps/gauzy-e2e/src/support/Base/pages/RecurringExpenses.po.ts
apps/gauzy-e2e/src/support/Base/utils/util.ts

feat: recurring expenses e2e tests plus refactoring

---

apps/gauzy-e2e/src/integration/AddEmployeeLevelTest.ts
apps/gauzy-e2e/src/integration/ExpensesTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/ExpensesPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ExpensesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Expenses.po.ts

feat: expenses page e2e tests

---

apps/gauzy/src/app/@shared/directives/img.directive.ts

fix: local image src not showing

---

apps/gauzy-e2e/src/integration/PaymentsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/PaymentsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/PaymentsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Payments.po.ts

feat: payments e2e tets

---

apps/gauzy-e2e/src/integration/PipelinesTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/PipelinesPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/PipelinesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Pipelines.po.ts

feat: pipelines e2e tests

---

apps/gauzy-e2e/src/integration/ManageEmployeesTest.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ManageEmployeesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/ManageEmployees.po.ts

feat: manage employees e2e tests

---

apps/gauzy-e2e/src/integration/OrganizationProjectsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationProjectsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationProjectsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationProjects.po.ts

feat: organization projects e2e tests

---

apps/gauzy-e2e/src/integration/OrganizationVendorsTest.ts
apps/gauzy-e2e/src/integration/TimesheetsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationVendorsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationVendorsPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/TimesheetsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationVendors.po.ts
apps/gauzy-e2e/src/support/Base/pages/Timesheets.po.ts

feat: organization vendors e2e tests

---

apps/api/src/app/shared/guards/auth/organization-permission.guard.ts
apps/api/src/app/shared/guards/auth/tenant-base.guard .ts
apps/api/src/app/shared/guards/auth/tenant-permission.guard.ts
apps/api/src/app/timesheet/time-log/time-log.controller.ts
apps/api/src/app/timesheet/timer/timer.service.ts
apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
apps/gauzy/src/app/@theme/components/header/header.component.ts
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.html
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts

Fix/#2332 Tenant base guard and time tracker issue

---

apps/gauzy-e2e/src/integration/ManageEmployeesTest.ts
apps/gauzy-e2e/src/integration/OrganizationDepartmentsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationDepartmentsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationDepartmentsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationDepartments.po.ts

feat: organization departments e2e tests

---

apps/gauzy/src/app/pages/jobs/job-layout/job-layout.component.ts
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.scss
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/employee-job.model.ts
libs/models/src/lib/job-matching.model.ts

Fix: #2525 jobs page loading multiple API calls

---

apps/api/src/app/core/seeds/entities.ts
apps/api/src/app/reports/report-category.controller.ts
apps/api/src/app/reports/report-category.entity.ts
apps/api/src/app/reports/report.controller.ts
apps/api/src/app/reports/report.entity.ts
apps/api/src/app/reports/report.seed.ts
apps/gauzy/src/app/@core/services/server-connection.service.ts
apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/app/pages/reports/all-report/all-report.module.ts
apps/gauzy/src/app/pages/reports/all-report/all-report/all-report.component.html
apps/gauzy/src/app/pages/reports/all-report/all-report/all-report.component.scss
apps/gauzy/src/app/pages/reports/all-report/all-report/all-report.component.ts
apps/gauzy/src/app/pages/reports/all-report/report.server.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/report.model.ts

fix: seed issue and added toggle switch to display in menubar

---

apps/api/src/app/reports/report-category.controller.ts
apps/gauzy/src/app/@core/services/server-connection.service.ts
apps/gauzy/src/app/pages/pages.component.ts

fix: loading issue when not logged in

---

apps/gauzy-e2e/src/integration/OrganizationTeamsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationTeamsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationTeamsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationTeams.po.ts

feat: organization teams e2e tests

---

apps/gauzy/src/app/@shared/invite/invites/invites.component.html
apps/gauzy/src/app/@shared/invite/invites/invites.component.ts
apps/gauzy/src/app/pages/approvals/approvals-routing.module.ts
apps/gauzy/src/app/pages/approvals/approvals.component.ts
apps/gauzy/src/app/pages/approvals/approvals.module.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.scss
apps/gauzy/src/app/pages/employees/employees-routing.module.ts
apps/gauzy/src/app/pages/employees/employees.component.html
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.html
apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.html
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/payments/payments.component.ts
libs/models/src/lib/employee.model.ts
libs/models/src/lib/invite.model.ts

Fix: #2523 employee manage page and other permission fixes

---

apps/gauzy-e2e/src/integration/OrganizationInventoryTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationInventoryPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationInventoryPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationInventory.po.ts
apps/gauzy-e2e/src/support/Base/utils/util.ts

feat: organization inventory e2e tests

---

apps/gauzy-e2e/src/integration/OrganizationDocumentsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationDocumentsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationDocumentsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationDocuments.po.ts
apps/gauzy-e2e/src/support/Base/utils/util.ts

feat: organization documents e2e tests

---

apps/gauzy-e2e/src/integration/OrganizationEmploymentTypesTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationEmploymentTypesPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationEmploymentTypesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationEmploymentTypes.po.ts

feat: organization employment types e2e tests

---

apps/gauzy-e2e/src/integration/ContactsLeadsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/ContactsLeadsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ContactsLeadsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/ContactsLeads.po.ts

feat: contacts leads e2e tests

---

apps/api/src/app/employee-proposal-template/employee-proposal-template.controller.ts
apps/api/src/app/employee-proposal-template/employee-proposal-template.service.ts
apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select.module.ts
apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select/proposal-template-select.component.html
apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select/proposal-template-select.component.scss
apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select/proposal-template-select.component.spec.ts
apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select/proposal-template-select.component.ts
apps/gauzy/src/app/pages/jobs/proposal-template/add-edit-proposal-template/add-edit-proposal-template.component.html
apps/gauzy/src/app/pages/jobs/proposal-template/add-edit-proposal-template/add-edit-proposal-template.component.ts
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template.service.ts
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.html
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.html
apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.ts
apps/gauzy/src/app/pages/proposals/proposals.component.html
apps/gauzy/src/app/pages/proposals/proposals.module.ts
apps/gauzy/src/assets/i18n/en.json

feat: added proposal select and copy default template in clipboard

---

apps/gauzy-e2e/src/integration/OrganizationRecurringExpensesTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationRecurringExpensesPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationRecurringExpensesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationRecurringExpenses.po.ts

feat: organization recurring expenses e2e tests

---

apps/gauzy-e2e/src/integration/OrganizationHelpCenterTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationHelpCenterPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationHelpCenterPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationHelpCenter.po.ts

feat: organization help center e2e tests

---

apps/gauzy-e2e/src/integration/TimesheetsTest.ts
apps/gauzy-e2e/src/support/Base/pageobjects/TimesheetsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Timesheets.po.ts

feat: add time e2e test

---

apps/api/src/app/core/seeds/random-seed-config.ts
apps/api/src/app/core/seeds/seed-data.service.ts
apps/api/src/app/invoice-item/invoice-item.seed.ts
apps/api/src/app/invoice/invoice.seed.ts

Fix: #2130 invoice inner view items seed issue

---

apps/api/src/app/employee/commands/get-employee-job-statistics.command.ts
apps/api/src/app/employee/commands/handlers/get-employee-job-statistics.handler.ts
apps/api/src/app/employee/commands/handlers/index.ts
apps/api/src/app/employee/commands/handlers/update-employee-job-search-status.handler.ts
apps/api/src/app/employee/commands/update-employee-job-search-status.command.ts
apps/api/src/app/employee/employee.controller.ts
apps/api/src/app/employee/employee.entity.ts
apps/api/src/app/employee/employee.module.ts
apps/api/src/app/employee/employee.service.ts
apps/gauzy/src/app/@core/services/employees.service.ts
apps/gauzy/src/app/@shared/smart-table/smart-table-toggle/smart-table-toggle.component.html
apps/gauzy/src/app/@shared/smart-table/smart-table-toggle/smart-table-toggle.component.spec.ts
apps/gauzy/src/app/@shared/smart-table/smart-table-toggle/smart-table-toggle.component.ts
apps/gauzy/src/app/@shared/smart-table/smart-table-toggle/smart-table-toggle.module.ts
apps/gauzy/src/app/pages/jobs/employees/employees-routing.module.ts
apps/gauzy/src/app/pages/jobs/employees/employees.module.ts
apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.html
apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.spec.ts
apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.ts
apps/gauzy/src/app/pages/jobs/jobs-routing.module.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/employee.model.ts

feat: created employees job statistics page and api

---

apps/gauzy/src/app/@core/services/job.service.ts
apps/gauzy/src/app/pages/jobs/search/search.module.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.scss
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
apps/gauzy/src/assets/i18n/en.json

feat: added hide all button in job search

---

apps/api/src/app/approval-policy/approval-policy.controller.ts
apps/api/src/app/approval-policy/approval-policy.module.ts
apps/api/src/app/approval-policy/approval-policy.service.ts
apps/api/src/app/approval-policy/commands/approval-policy.create.command.ts
apps/api/src/app/approval-policy/commands/approval-policy.get.command.ts
apps/api/src/app/approval-policy/commands/approval-policy.update.command.ts
apps/api/src/app/approval-policy/commands/handlers/approval-policy.create.handler.ts
apps/api/src/app/approval-policy/commands/handlers/approval-policy.get.handler.ts
apps/api/src/app/approval-policy/commands/handlers/approval-policy.update.handler.ts
apps/api/src/app/approval-policy/commands/handlers/index.ts
apps/api/src/app/approval-policy/commands/handlers/request-approval-policy.get.handler.ts
apps/api/src/app/approval-policy/commands/index.ts
apps/api/src/app/approval-policy/commands/request-approval-policy.get.command.ts
apps/gauzy/src/app/@core/services/approval-policy.service.ts
apps/gauzy/src/app/@shared/approval-policy/approval-policy-mutation.component.html
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.html
apps/gauzy/src/app/@shared/approvals/approvals-mutation.component.ts
apps/gauzy/src/app/pages/approval-policy/approval-policy-routing.module.ts
apps/gauzy/src/app/pages/approval-policy/approval-policy.component.html
apps/gauzy/src/app/pages/approval-policy/approval-policy.component.ts
apps/gauzy/src/app/pages/approval-policy/approval-policy.module.ts
libs/models/src/lib/approval-policy.model.ts
libs/models/src/lib/core.model.ts

Feat: #2427 approval policy commands and handlers

---

apps/gauzy/src/app/pages/pages.component.ts

fix: sidebar menu automatically collapse issue

---

.env.sample
apps/api/src/app/core/seeds/seed-data.service.ts
apps/api/src/app/email-template/commands/handlers/email-template.save.handler.ts
apps/api/src/app/email-template/email-template.seed.ts
apps/api/src/app/email-template/queries/handlers/email-template.find.handler.ts
apps/api/src/app/email/email.service.ts
apps/api/src/app/invoice/commands/handlers/invoice.send.email.handler.ts
apps/api/src/app/invoice/invoice.service.ts
apps/api/src/environments/ISMTPConfig.ts
apps/api/src/environments/environment.ts
apps/api/src/environments/ienvironment.ts
apps/gauzy/src/app/@core/services/invoices.service.ts
apps/gauzy/src/app/pages/email-templates/email-templates.component.ts
apps/gauzy/src/app/pages/invoices/invoice-email/invoice-email-mutation.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
libs/models/src/lib/email-template.model.ts
libs/models/src/lib/invite.model.ts

Fix/#2230 SMTP configuration for estimate email 

---

apps/api/src/app/country/country.controller.ts
apps/api/src/app/invite/commands/handlers/invite.accept-organization-contact.handler.ts
apps/api/src/app/invite/commands/invite.accept-organization-contact.command.ts
apps/api/src/app/invite/invite.controller.ts

Fix: #2180 invite register emails issue

---

apps/api/src/app/invite/commands/handlers/invite.organization-contact.handler.ts
apps/gauzy/src/app/pages/contacts/contact.component.ts
libs/models/src/lib/invite.model.ts

Fix: missing tenant issue in invite API

---

apps/desktop/src/app/pages/settings/settings.component.html
apps/desktop/src/app/pages/settings/settings.component.ts
apps/desktop/src/app/pages/setup/setup.component.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/screenshot.ts
apps/desktop/src/window/gauzy.ts
apps/desktop/src/window/settings.ts
apps/desktop/src/window/setup.ts
apps/desktop/src/window/timeTracker.ts
apps/gauzy/src/app/@theme/components/header/header.component.html
apps/gauzy/src/app/@theme/components/header/header.component.ts
apps/gauzy/src/app/app.module.guards.ts

fix: duplicate tray menu and duplicate window

---

apps/gauzy-e2e/src/integration/JobsProposalsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/JobsProposalsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/JobsProposalsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/JobsProposals.po.ts
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.html

feat: jobs proposals e2e tests

---

apps/gauzy-e2e/src/integration/AddTasksTest.ts
apps/gauzy-e2e/src/integration/TeamsTasksTest.ts
apps/gauzy-e2e/src/integration/TimesheetsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/TeamsTasksPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/TeamsTasksPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/AddTasks.po.ts
apps/gauzy-e2e/src/support/Base/pages/TeamsTasks.po.ts
apps/gauzy-e2e/src/support/commands.ts

feat: teams tasks e2e tests

---

apps/gauzy-e2e/src/integration/CustomSMTPTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/CustomSMTPPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/CustomSMTPPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/CustomSMTP.po.ts

feat: custom SMTP e2e test

---

apps/gauzy-e2e/src/integration/TimesheetsTest.ts
apps/gauzy-e2e/src/support/Base/pageobjects/TimesheetsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Timesheets.po.ts

feat: view, edit and delete time

---

apps/gauzy-e2e/src/integration/AddEmployeeLevelTest.ts
apps/gauzy-e2e/src/integration/AddEmployeePositionTest.ts
apps/gauzy-e2e/src/integration/AddOrganizationTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/AddOrganizationPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddEmployeeLevelPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddEmployeePositionPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddOrganizationPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/AddEmployeeLevel.po.ts
apps/gauzy-e2e/src/support/Base/pages/AddEmployeePosition.po.ts
apps/gauzy-e2e/src/support/Base/pages/AddOrganization.po.ts
apps/gauzy-e2e/src/support/Base/utils/util.ts

feat: refactoring e2e tests

---

apps/api/src/app/core/seeds/seed-data.service.ts
apps/api/src/app/reports/report.service.ts

Feat#2598/seed reports

---

apps/gauzy-e2e/src/integration/AddOrganizationTest.ts
apps/gauzy-e2e/src/integration/AddTasksTest.ts
apps/gauzy-e2e/src/integration/AddUserTest.ts
apps/gauzy-e2e/src/integration/ApprovalRequestTest.ts
apps/gauzy-e2e/src/integration/CandidatesTest.ts
apps/gauzy-e2e/src/integration/ClientsTest.ts
apps/gauzy-e2e/src/integration/ContactsLeadsTest.ts
apps/gauzy-e2e/src/integration/CustomersTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/AddOrganizationPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddTasksPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/AddUserPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ApprovalRequestPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/CandidatesPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ClientsPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ContactsLeadsPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/CustomersPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/AddOrganization.po.ts
apps/gauzy-e2e/src/support/Base/pages/AddTasks.po.ts
apps/gauzy-e2e/src/support/Base/pages/AddUser.po.ts
apps/gauzy-e2e/src/support/Base/pages/ApprovalRequest.po.ts
apps/gauzy-e2e/src/support/Base/pages/Candidates.po.ts
apps/gauzy-e2e/src/support/Base/pages/Clients.po.ts
apps/gauzy-e2e/src/support/Base/pages/ContactsLeads.po.ts
apps/gauzy-e2e/src/support/Base/pages/Customers.po.ts
apps/gauzy-e2e/src/support/Base/pages/DeleteOrganization.po.ts

feat: e2e tests refactoring

---

apps/api/src/environments/environment.prod.ts

fix: gauzy api env production

---

apps/api/src/app/expense/expense.controller.ts
apps/api/src/app/expense/expense.entity.ts
apps/api/src/app/expense/expense.map.service.ts
apps/api/src/app/expense/expense.module.ts
apps/api/src/app/expense/expense.service.ts
apps/gauzy/src/app/@core/services/expenses.service.ts
apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.html
apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.scss
apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.spec.ts
apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.ts
apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.module.ts
apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report-routing.module.ts
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report.module.ts
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.html
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.spec.ts
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.ts
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/environments/environment.ts
libs/models/src/lib/expense.model.ts

feat: create expenses report page and api

---

apps/gauzy/src/app/@core/services/country.service.ts
apps/gauzy/src/app/@shared/country/country.component.ts
apps/gauzy/src/app/@shared/forms/location/location-form.component.html
apps/gauzy/src/app/@shared/forms/location/location-form.component.ts
apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html
apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
apps/gauzy/src/app/pages/contacts/contact.component.html
apps/gauzy/src/app/pages/contacts/contact.component.ts
apps/gauzy/src/app/pages/contacts/contact.module.ts
libs/models/src/lib/organization-contact.model.ts

Fix: contact page location component fixes

---

apps/api/src/app/expense/expense.controller.ts
apps/api/src/app/expense/expense.service.ts
apps/gauzy/src/app/@core/services/expenses.service.ts
apps/gauzy/src/app/pages/reports/charts/expanses-report-horizontal-chart/expanses-report-horizontal-chart.component.html
apps/gauzy/src/app/pages/reports/charts/expanses-report-horizontal-chart/expanses-report-horizontal-chart.component.scss
apps/gauzy/src/app/pages/reports/charts/expanses-report-horizontal-chart/expanses-report-horizontal-chart.component.spec.ts
apps/gauzy/src/app/pages/reports/charts/expanses-report-horizontal-chart/expanses-report-horizontal-chart.component.ts
apps/gauzy/src/app/pages/reports/charts/expanses-report-horizontal-chart/expanses-report-horizontal-chart.module.ts
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report.module.ts
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.html
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.ts
libs/models/src/index.ts
libs/models/src/lib/chart.model.ts

Feat#2619/expense reports

---

apps/api/src/app/payment/payment.controller.ts
apps/api/src/app/payment/payment.entity.ts
apps/api/src/app/payment/payment.map.service.ts
apps/api/src/app/payment/payment.module.ts
apps/api/src/app/payment/payment.service.ts
apps/gauzy/src/app/@core/services/payment.service.ts
apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.html
apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.html
apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.scss
apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.spec.ts
apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.ts
apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.module.ts
apps/gauzy/src/app/pages/pages-routing.module.ts
apps/gauzy/src/app/pages/reports/charts/line-chart/line-chart.component.html
apps/gauzy/src/app/pages/reports/charts/line-chart/line-chart.component.scss
apps/gauzy/src/app/pages/reports/charts/line-chart/line-chart.component.ts
apps/gauzy/src/app/pages/reports/charts/line-chart/line-chart.module.ts
apps/gauzy/src/app/pages/reports/payment-report/payment-report-routing.module.ts
apps/gauzy/src/app/pages/reports/payment-report/payment-report.module.ts
apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.html
apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.spec.ts
apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.ts
apps/gauzy/src/assets/i18n/en.json
libs/models/src/lib/payment.model.ts

Feat#2629/payments report

---

apps/api/src/app/candidate/candidate.seed.ts
apps/api/src/app/candidate/candidate.ts
apps/api/src/app/core/seeds/random-seed-config.ts
apps/api/src/app/core/seeds/seed-data.service.ts
apps/api/src/app/employee/employee.seed.ts
apps/api/src/app/employee/employee.service.ts
apps/api/src/app/employee/employee.ts
apps/api/src/app/event-types/event-type.seed.ts
apps/api/src/app/expense-categories/expense-categories.seed.ts
apps/api/src/app/expense/expense.seed.ts
apps/api/src/app/goal-kpi-template/goal-kpi-template.seed.ts
apps/api/src/app/goal-template/goal-template.seed.ts
apps/api/src/app/help-center-article/help-center-article.seed.ts
apps/api/src/app/help-center-author/help-center-author.seed.ts
apps/api/src/app/income/income.seed.ts
apps/api/src/app/invoice/invoice.seed.ts
apps/api/src/app/keyresult-template/keyresult-template.seed.ts
apps/api/src/app/keyresult-update/keyresult-update.seed.ts
apps/api/src/app/organization/organization.seed.ts
apps/api/src/app/organization/organization.ts
apps/api/src/app/product-type/type.seed.ts
apps/api/src/app/request-approval-employee/request-approval-employee.seed.ts
apps/api/src/app/role-permissions/role-permissions.seed.ts
apps/api/src/app/role/role.seed.ts
apps/api/src/app/skills/skill.seed.ts
apps/api/src/app/user-organization/user-organization.seed.ts
apps/api/src/app/user/user.seed.ts
libs/models/src/lib/organization.model.ts

Fix: #2633 default employees load after switch sqlite first time

---

.scripts/configure.ts
apps/desktop/src/app/app.component.ts
apps/desktop/src/app/pages/setup/setup.component.html
apps/desktop/src/app/pages/setup/setup.component.scss
apps/desktop/src/app/pages/setup/setup.component.ts
apps/desktop/src/app/pages/setup/setup.module.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/libs/tray-icon.ts
apps/gauzy/src/app/app.module.guards.ts
apps/gauzy/src/environments/model.ts

feat: desktop setup progress bar

---

apps/gauzy/src/app/pages/settings/email-history/email-history.component.html
apps/gauzy/src/app/pages/settings/email-history/email-history.component.scss

Moved avatar image, filter button and date.

Feature: improvements to Email History page

---

apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
apps/gauzy/src/environments/environment.ts

Fixed payment adding.
Video: https://www.loom.com/share/46442ea4b699429bb86e9ad94e20dc7b

fix: fixed payment adding

---

apps/api/src/app/organization-contact/organization-contact.controller.ts
apps/api/src/app/organization-contact/organization-contact.seed.ts
apps/api/src/app/organization/organization.entity.ts
apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts
apps/gauzy/src/app/share/employee/employee.module.ts
apps/gauzy/src/app/share/organization/organization.component.html
apps/gauzy/src/app/share/organization/organization.component.ts
apps/gauzy/src/app/share/organization/organization.module.ts
apps/gauzy/src/app/share/share.component.ts
apps/gauzy/src/app/share/share.module.ts
libs/models/src/lib/organization-awards.model.ts
libs/models/src/lib/organization-languages.model.ts
libs/models/src/lib/organization.model.ts

Fix: #2636 organization edit public page redirecting to dashboard

---

apps/desktop/src/app/app-routing.module.ts
apps/desktop/src/app/app.module.ts
apps/desktop/src/app/pages/image-viewer/image-viewer.component.html
apps/desktop/src/app/pages/image-viewer/image-viewer.component.scss
apps/desktop/src/app/pages/image-viewer/image-viewer.component.spec.ts
apps/desktop/src/app/pages/image-viewer/image-viewer.component.ts
apps/desktop/src/app/pages/image-viewer/image-viewer.module.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.html
apps/desktop/src/app/pages/time-tracker/time-tracker.component.scss
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.module.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.service.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/ipc.ts
apps/desktop/src/window/imageView.ts
apps/desktop/src/window/timeTracker.ts

feat: delete or view last screenshot

---

apps/gauzy/src/app/@shared/country/country.component.ts
apps/gauzy/src/app/@shared/forms/location/location-form.component.scss
apps/gauzy/src/app/@shared/forms/location/location-form.component.ts
apps/gauzy/src/app/@shared/forms/maps/leaflet/leaflet.component.ts
apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.html
apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.ts

Fix: google place and leaflet map in modal

---

apps/api/src/app/timesheet/time-slot/commands/handlers/create-time-slot.handler.ts
apps/desktop/src/libs/timer.ts
apps/gauzy/src/app/@theme/components/header/header.component.ts

Fix: Time tracker activities fixes

---

apps/api/src/app/invoice-item/commands/handlers/index.ts
apps/api/src/app/invoice-item/commands/handlers/invoice-item.bulk.create.handler.ts
apps/api/src/app/invoice-item/commands/index.ts
apps/api/src/app/invoice-item/commands/invoice-item.bulk.create.command.ts
apps/api/src/app/invoice-item/invoice-item.controller.ts
apps/api/src/app/invoice-item/invoice-item.module.ts
apps/api/src/app/invoice-item/invoice-item.service.ts
apps/gauzy/src/app/@core/services/invoice-item.service.ts
apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
libs/models/src/lib/invoice-item.model.ts
yarn.lock

---
@evereq 
I have completed this task. Can you please review it once and provide some feedback on it.
I have removed the multiple API calls of same API and managed it using single API call.
I have attached the video link below. Please check it for the overview of this task.
https://www.loom.com/share/acf4d5a3dced45b9b091cb749e3f392b

fix: removed multiple APIs calls of invoice item from estimate section #2724

---

apps/api/src/environments/IUnleashConfig.ts
apps/api/src/environments/environment.prod.ts
apps/api/src/environments/environment.ts
apps/gauzy/src/app/@shared/feature-toggle/feature-toggle.component.ts
apps/gauzy/src/app/app.module.ts

Fix:#2493 feature toggle server side response issue

---

apps/desktop/package.json
apps/desktop/src/app/pages/settings/settings.component.html
apps/desktop/src/app/pages/settings/settings.component.scss
apps/desktop/src/app/pages/settings/settings.component.ts
apps/desktop/src/app/pages/settings/settings.module.ts
apps/desktop/src/index.ts
apps/desktop/src/libs/menu.ts
apps/desktop/src/libs/tray-icon.ts
apps/desktop/src/package.json
apps/desktop/src/window/gauzy.ts
apps/desktop/src/window/settings.ts

feat: move gauzy desktop update button

---

apps/api/src/app/availability-slots/commands/handlers/get-conflict-availability-slots.handler.ts
apps/api/src/app/timesheet/time-log/commands/handlers/get-conflict-time-log.handler.ts
apps/api/src/app/timesheet/time-log/commands/handlers/time-log-update.handler.ts
apps/api/src/app/timesheet/time-log/commands/time-log-update.command.ts
apps/api/src/app/timesheet/timer/timer.service.ts
apps/desktop/src/app/pages/time-tracker/time-tracker.component.ts
apps/desktop/src/libs/screenshot.ts
apps/desktop/src/libs/tray-icon.ts

fix: duplicate timeslot, error overlaps query

---

apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts
apps/gauzy/src/app/@shared/invite/invite-mutation/invite-mutation.component.ts
apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.html
apps/gauzy/src/app/@shared/organizations/public-page-mutation/public-page-mutation.component.ts
apps/gauzy/src/app/pages/users/users.component.ts
apps/gauzy/src/assets/i18n/en.json

fix: notification for page and income mutation

---

.deploy/api/Dockerfile
.deploy/api/entrypoint
.deploy/webapp/Dockerfile
.deploy/webapp/entrypoint
.deploy/webapp/entrypoint.prod.sh
.deploy/webapp/nginx.conf
.vscode/settings.json
docker-compose.demo.yml
docker-compose.yml

fix: make sure docker containers can run without compose too

---

.deploy/api/Dockerfile
.deploy/api/entrypoint
.deploy/webapp/Dockerfile
.deploy/webapp/entrypoint
.deploy/webapp/entrypoint.prod.sh
.deploy/webapp/nginx.conf
docker-compose.demo.yml
docker-compose.yml

feat: optimize Dockers

---

.deploy/k8s/README.md
.github/workflows/docker.yml

feat: split build and push of Docker images

---

.deploy/webapp/Dockerfile
.deploy/webapp/entrypoint.compose.sh
.deploy/webapp/entrypoint.prod.sh
.deploy/webapp/nginx.compose.conf
.deploy/webapp/nginx.prod.conf

feat: more fixes for Docker / Compose

---

.github/workflows/deploy-do.yml

fix: deployment to DO

---

.github/workflows/deploy-do.yml

fix: finally DO deployments done

---

.deploy/api/Dockerfile
.deploy/api/entrypoint.sh
.deploy/webapp/Dockerfile
.deploy/webapp/entrypoint.compose.sh
.deploy/webapp/entrypoint.prod.sh

feat: some refactoring in Dockers

---

.deploy/api/Dockerfile
package.json
packages/common-angular/package.json
packages/common-angular/tsconfig.build.json
packages/common-angular/tsconfig.json

fix: docker builds

---

.deploy/api/Dockerfile

fix: api docker file

---

package.json

fix: oh my electron :D

---

.deploy/api/Dockerfile

feat: decrease size of Docker image for API

---

packages/contracts/src/role-permission.model.ts
packages/core/src/image-asset/image-asset.controller.ts

fix: add inventory gallery permission

---

apps/gauzy/package.json
package.json
yarn.lock

feat: fixed lock file

---

.deploy/k8s/k8s-manifest.demo.yaml
.deploy/k8s/k8s-manifest.prod.yaml
apps/api/src/plugin-config.ts
apps/desktop/src/index.ts
packages/config/src/default-configuration.ts
packages/config/src/environments/environment.prod.ts
packages/config/src/environments/environment.ts
packages/core/src/main.ts

feat: fix env vars naming (HOST, PORT)

---

.deploy/k8s/k8s-manifest.demo.yaml
.deploy/k8s/k8s-manifest.prod.yaml

feat: switch to HTTPS in DO

---

.deploy/k8s/k8s-manifest.demo.yaml
.deploy/k8s/k8s-manifest.prod.yaml

feat: switch load loadbalancers to HTTPS in DO

---

apps/desktop/src/index.ts
apps/desktop/tsconfig.json

fix: revert ts build desktop to es2016

---

.deploy/api/Dockerfile
.deploy/k8s/k8s-manifest.demo.yaml
.deploy/k8s/k8s-manifest.prod.yaml

feat: more fixes for DO / Docker

---

.deploy/api/Dockerfile

fix: docker builds for API

---

packages/core/src/graphql/graphql-helper.ts

fix: ops one more place to fix CORS :D

---

libs/desktop-api/src/main.ts
packages/core/src/bootstrap/index.ts
packages/core/src/core/core.module.ts
packages/core/src/graphql/graphql-helper.ts

feat: more for CORS

---

libs/desktop-api/src/main.ts
packages/core/src/bootstrap/index.ts
packages/core/src/core/core.module.ts
packages/core/src/graphql/graphql-helper.ts

fix: allow more Headers in CORS (especially 'Language' we use)

---

apps/gauzy/src/app/@core/auth/token.interceptor.ts
apps/gauzy/src/app/@core/tenant.interceptor.ts
libs/desktop-api/src/main.ts
libs/desktop-libs/src/lib/desktop-screenshot.ts
libs/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
packages/core/src/bootstrap/index.ts
packages/core/src/core/core.module.ts
packages/core/src/graphql/graphql-helper.ts
packages/core/src/shared/guards/auth/tenant-base.guard .ts

feat: enable CORS for Tenant-Id header

---

packages/core/src/shared/guards/auth/tenant-base.guard .ts

fix: 2905 request header tenant-id

---

apps/gauzy-e2e/src/integration/ManageCandidatesInvitesTest.ts
apps/gauzy-e2e/src/integration/ManageInterviewsCriterionsTest.ts
apps/gauzy-e2e/src/integration/ManageInterviewsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/ManageCandidatesInvitesPageData.ts
apps/gauzy-e2e/src/support/Base/pagedata/ManageInterviewsCriterionsPageData.ts
apps/gauzy-e2e/src/support/Base/pagedata/ManageInterviewsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ManageCandidatesInvitesPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ManageInterviewsCriterionsPageObject.ts
apps/gauzy-e2e/src/support/Base/pageobjects/ManageInterviewsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/ManageCandidatesInvites.po.ts
apps/gauzy-e2e/src/support/Base/pages/ManageInterviews.po.ts
apps/gauzy-e2e/src/support/Base/pages/ManageInterviewsCriterions.po.ts
apps/gauzy-e2e/src/support/commands.ts

feat: new e2e tests

---

apps/api/.gitignore

fix: gitignore public folder

---

packages/contracts/src/invoice-item.model.ts

fix: ci build

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-view/inner-component/invoice-view-inner.component.ts
packages/core/src/invoice/generate-invoice-pdf.ts
packages/core/src/invoice/invoice.controller.ts

fix: default invoice items pdf issue

---

.vscode/settings.json

feat: update visual setting

---

apps/desktop-timer/src/app/app.component.scss
apps/desktop-timer/src/app/app.component.ts
apps/desktop-timer/src/app/app.module.ts
apps/desktop-timer/src/app/server-down/server-down.page.html
apps/desktop-timer/src/app/server-down/server-down.page.ts
apps/desktop-timer/src/index.html
libs/desktop-ui-lib/src/lib/image-viewer/image-viewer.component.html
libs/desktop-ui-lib/src/lib/image-viewer/image-viewer.component.scss
libs/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
libs/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
libs/desktop-window/src/lib/desktop-window-image-viewer.ts
libs/desktop-window/src/lib/desktop-window-setup.ts
libs/desktop-window/src/lib/desktop-window-timer.ts

fix: desktop timer

---

apps/gauzy/src/app/@core/services/inventory-store.service.ts
apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/options-form/options-form.component.html
apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/options-form/options-form.component.scss
apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/options-form/options-form.component.ts
apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
packages/contracts/src/product.model.ts

Added UI improvements on Product Options form

Feat/product options UI fixes

---

.deploy/api/Dockerfile
.deploy/webapp/Dockerfile

fix: docker containers updated with changelog plugin

---

.deploy/desktop-timer/Dockerfile.linux
.deploy/desktop-timer/Dockerfile.win
.github/workflows/desktop-timer-app.yml

feat: add Desktop Timer App builds

---

apps/desktop-timer/src/package.json
apps/desktop/src/package.json
libs/desktop-libs/src/lib/desktop-menu.ts

fix: build artifact name

---

apps/gauzy/src/app/@core/services/navigation-builder/navigation-builder.service.ts
apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts

fix: duplicate navigation renderer issue

---

apps/gauzy/src/app/@core/services/app-init-service.ts
apps/gauzy/src/app/app.module.ts
apps/gauzy/src/app/pages/pages.component.ts

fix: make bookmarked urls as working

---

apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html
apps/gauzy/src/app/pages/contacts/contact.component.ts

fix: create new Customer / Client

---

apps/gauzy/src/app/@theme/components/header/selectors/organization/organization.component.ts

fix: create new organization issue

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-location/edit-organization-location.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts

fix: organization change issue

---

apps/desktop-timer/src/app/auth/token.interceptor.ts
libs/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
libs/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

fix: screenshot not taking

---

apps/api/.gitignore
libs/desktop-window/src/lib/desktop-window-image-viewer.ts
libs/desktop-window/src/lib/desktop-window-setup.ts
libs/desktop-window/src/lib/desktop-window-timer.ts
libs/desktop-window/src/lib/desktop-window-updater.ts
packages/core/src/core/file-storage/providers/local.provider.ts
packages/core/src/core/file-storage/providers/s3.provider.ts
packages/core/src/timesheet/screenshot/screenshot.seed.ts

Fix: Added desktop window titles back

---

apps/gauzy/src/app/@core/services/app-init-service.ts
apps/gauzy/src/app/pages/pages.component.ts

fix: login issue

---

.scripts/electron.env.ts
apps/desktop-timer/package.json
apps/desktop-timer/src/environments/environment.prod.ts
apps/desktop-timer/src/environments/environment.ts
apps/desktop-timer/src/index.ts
apps/desktop-timer/src/package.json
apps/desktop-timer/src/sentry.ts
apps/desktop/package.json
apps/desktop/src/environments/environment.prod.ts
apps/desktop/src/environments/environment.ts
apps/desktop/src/index.ts
apps/desktop/src/package.json
apps/desktop/src/sentry.ts
package.json

feat: added sentry to desktop

---

apps/desktop-timer/src/index.ts
apps/desktop/src/index.ts
libs/desktop-ui-lib/src/lib/settings/settings.component.html
libs/desktop-ui-lib/src/lib/settings/settings.component.ts
libs/desktop-ui-lib/src/lib/setup/setup.component.ts
libs/desktop-window/src/lib/desktop-window-timer.ts

fix: server advanced setting

---

apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
apps/gauzy/src/app/pages/projects/projects.component.html
apps/gauzy/src/app/pages/projects/projects.component.ts

- https://www.loom.com/share/46278e9e88a247b1bffcd686f551c25b
---

fix: added empty message

---

apps/gauzy/src/app/pages/employees/event-types/event-type.component.html
apps/gauzy/src/app/pages/employees/event-types/event-type.component.ts

- https://www.loom.com/share/4fd3858afe324bf6b5c13cdb7a62248b
---

fix: event type page issue

---

apps/gauzy/src/app/@shared/equipment/equipment-mutation.component.ts

- https://www.loom.com/share/759f901bcce8460db52e27e7dd1c04dc
---

fix: equipment page open popup issue

---

apps/gauzy/src/app/pages/settings/email-history/email-history.component.ts

- https://www.loom.com/share/dafd528f23664adaaa31744bc0d92ddc
---

fix: email history page multiple api call issue

---

.deploy/api/Dockerfile
.deploy/webapp/Dockerfile

fix: pin alpine version and fix other deps

---

apps/desktop-timer/src/index.ts
apps/desktop/src/index.ts

fix: build failing due to electron updater changes

---

.github/workflows/desktop-app.yml
.github/workflows/desktop-timer-app.yml

feat: switch to Node 16 for apps builds in Github Actions

---

.github/workflows/desktop-app.yml
.github/workflows/desktop-timer-app.yml

fix: switch electron builds to node 15 for now

---

apps/gauzy/src/app/@theme/styles/_overrides.scss
apps/gauzy/src/app/@theme/styles/site-menu.scss

- https://www.loom.com/share/d47a8754815b400b87e2c287c1434867
---

fix: scrolling disappear issue

---

apps/gauzy/src/app/@theme/styles/_overrides.scss
apps/gauzy/src/app/@theme/styles/site-menu.scss

fix: scroll scroll issue

---

apps/gauzy/src/app/@core/services/accounting-template.service.ts
apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.ts
packages/core/src/accounting-template/accounting-template.service.ts

- https://www.loom.com/share/7869917ea75d43a4916c4ef56017883c
---

fix: accounting template organization charge on preview issue

---

apps/gauzy/src/app/pages/equipment-sharing/equipment-sharing.component.html
apps/gauzy/src/app/pages/projects/projects.component.html
apps/gauzy/src/app/pages/time-off/time-off.component.html

- https://www.loom.com/share/ad9090914cb444e0aef3aca52c09089b
---

fix: change button text

---

apps/gauzy/src/app/pages/employment-types/employment-types.component.html
apps/gauzy/src/app/pages/employment-types/employment-types.component.ts
apps/gauzy/src/app/pages/expense-recurring/expense-recurring.component.html
apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.html

---
-Before unify page images
-After unify page images

Fix #3083/unify pages

---

apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.html
apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.ts
packages/core/src/accounting-template/accounting-template.controller.ts
packages/core/src/accounting-template/accounting-template.service.ts

---
https://www.loom.com/share/3be9c0df74f44c159c43a7249b79baa3

fix: account template save issue and preview error

---

.github/workflows/desktop-app.yml
.github/workflows/desktop-timer-app.yml
.scripts/bump-version-electron.js

fix: versioning gauzy desktop

---

apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.ts
apps/gauzy/src/app/pages/time-off/time-off.component.html

Fix: on page reload accounting template issue

---

.scripts/bump-version-electron.js

fix: failed bumped version gauzy desktop

---

.scripts/bump-version-electron.js

fix: failed bumped version on windows

---

apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-form/merchant-form.component.ts
apps/gauzy/src/app/pages/inventory/inventory.module.ts

Fix/Production Build

---

.scripts/bump-version-electron.js
apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-form/merchant-form.component.ts
apps/gauzy/src/app/pages/inventory/inventory.module.ts

feat: release

---

apps/desktop-timer/src/package.json
apps/desktop/src/package.json
packages/core/package.json
yarn.lock

fix: gauzy all desktop updater for windows and update sqlite to latest

---

apps/desktop-timer/package.json
apps/desktop/package.json
package.json

chore: upgrade electron-builder to 22.11.4

---

apps/gauzy/src/app/@shared/sidebar/knowledeg-base/knowledeg-base.component.html
apps/gauzy/src/app/@shared/sidebar/knowledeg-base/knowledeg-base.component.ts
apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.ts
apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/index.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/index.ts
apps/gauzy/src/app/pages/employees/employees-routing.module.ts
apps/gauzy/src/app/pages/employees/employees.module.ts
apps/gauzy/src/app/pages/employees/table-components/index.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts

fix: knowledge base and employee edit issue on load

---

apps/gauzy/src/app/pages/inventory/components/manage-merchants/merchant-routing.module.ts
apps/gauzy/src/app/pages/inventory/components/manage-product-categories/product-categories-routing.module.ts
apps/gauzy/src/app/pages/inventory/components/manage-product-types/product-types-routing.module.ts
apps/gauzy/src/app/pages/inventory/components/manage-warehouses/warehouses-routing.module.ts

fix: wrong Router import

---

apps/gauzy/src/app/@core/utils/smart-table/server-source.conf.ts
apps/gauzy/src/app/@core/utils/smart-table/server.data-source.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
packages/core/src/core/crud/crud.controller.ts
packages/core/src/core/crud/crud.service.ts
packages/core/src/core/crud/icrud.service.ts
packages/core/src/invoice/invoice.service.ts

* feat: #3160/invoice server side filter
* fix: #3160-remove commented  code
* fix: #3160/ fix date search
* fix: wrong import path
* fix: #3160  updated api route
* fix: #3160  updated api route
* fix: updated yarn.lock to previous version
Co-authored-by: RAHUL RATHORE <rahulrathore576@gmail.com>
---

feat: #3160/invoice server side filter (#3167)

---

packages/core/src/invoice/invoice.controller.ts
packages/core/src/invoice/pdfmaker.service.ts
packages/core/src/payment/payment.seed.ts

Fix/#3136 Preview and download invoice/estimate and payment seed fixes

---

packages/core/src/core/seeds/random-seed-config.ts
packages/core/src/core/seeds/seed-data.service.ts
packages/core/src/timesheet/activity/activities.seed.ts
packages/core/src/timesheet/screenshot/screenshot.seed.ts
packages/core/src/timesheet/time-log/time-log.seed.ts
packages/core/src/timesheet/timesheet/timesheet.seed.ts

Fix: Screenshots Seeder

---

apps/gauzy/src/app/pages/invoices/invoices.component.ts
packages/core/src/core/crud/crud.service.ts
packages/core/src/invoice/invoice.service.ts

Fix/3161 Server side relationship query issue

---

.deploy/api/Dockerfile
.deploy/webapp/Dockerfile
.github/workflows/desktop-app.yml
.github/workflows/desktop-timer-app.yml
apps/desktop-timer/package.json
apps/desktop/package.json
package.json
yarn.lock

chore: update packages / dockers and attempt to fix desktop builds

---

.deploy/api/Dockerfile
.deploy/webapp/Dockerfile
packages/core/package.json
yarn.lock

chore: update Sharp lib and downgrade alpine

---

apps/gauzy/src/app/@shared/table-filters/input-filter.component.ts
apps/gauzy/src/app/@shared/table-filters/table-filters.module.ts
apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
packages/core/src/core/crud/query-builder.ts
packages/core/src/core/utils.ts
packages/core/src/expense/expense.service.ts
packages/core/src/income/income.service.ts
packages/core/src/invoice/invoice.seed.ts
packages/core/src/invoice/invoice.service.ts
packages/core/src/payment/payment.service.ts

fix: query fixes in SQLite

---

apps/gauzy/src/app/pages/jobs/proposal-template/add-edit-proposal-template/add-edit-proposal-template.component.html
apps/gauzy/src/app/pages/jobs/proposal-template/add-edit-proposal-template/add-edit-proposal-template.component.ts
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.html
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts

Fix/#3161 Proposal template pagination

---

apps/gauzy/src/app/@shared/pagination/pagination-filter-base.component.ts
apps/gauzy/src/app/@shared/table-filters/input-filter.component.ts
apps/gauzy/src/app/pages/pipelines/pipelines.component.html
apps/gauzy/src/app/pages/pipelines/pipelines.component.ts
apps/gauzy/src/app/pages/pipelines/pipelines.module.ts
packages/core/src/pipeline/pipeline.service.ts

Fix: Pipeline pagination and GRID view edit & delete issue

---

apps/gauzy/src/app/@core/services/organization-sprint.service.ts
apps/gauzy/src/app/@shared/tasks-sprint-settings-view/tasks-sprint-settings-view.component.html
apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/project-view.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.html
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
apps/gauzy/src/app/pages/tasks/components/task/tasks-layouts/tasks-sprint-view/tasks-sprint-view.component.ts
packages/core/src/core/crud/query-builder.ts
packages/core/src/tasks/task.service.ts

* fix: #3161 sprint view pagination & fixes
* fix: loading
---

Fix/#3161 Sprint task view pagination & other fixes (#3210)

---

apps/gauzy-e2e/cypress.json
apps/gauzy-e2e/package-lock.json
apps/gauzy-e2e/package.json
apps/gauzy-e2e/src/plugins/index.ts
apps/gauzy-e2e/src/support/commands.ts
apps/gauzy-e2e/src/support/step_definitions/AddEmployeeLevelTest.feature
apps/gauzy-e2e/src/support/step_definitions/AddEmployeeLevelTest/AddEmployeeLevelTest.ts
apps/gauzy-e2e/src/support/step_definitions/LoginTest.feature
apps/gauzy-e2e/src/support/step_definitions/LoginTest/LoginTest.ts
package.json

feat: e2e tests with cypress and gherkin

---

apps/gauzy-e2e/src/support/step_definitions/AddEmployeeLevelTest.feature
apps/gauzy-e2e/src/support/step_definitions/AddEmployeeLevelTest/AddEmployeeLevelTest.ts
apps/gauzy-e2e/src/support/step_definitions/AddEmployeePositionTest.feature
apps/gauzy-e2e/src/support/step_definitions/AddEmployeePositionTest/AddEmployeePositionTest.ts
apps/gauzy-e2e/src/support/step_definitions/LoginTest/LoginTest.ts

feat: employee position e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pagedata/AddExistingUserPageData.ts
apps/gauzy-e2e/src/support/step_definitions/AddRemoveExistingUserTest.feature
apps/gauzy-e2e/src/support/step_definitions/AddRemoveExistingUserTest/AddRemoveExistingUserTest.ts

feat: add remove user e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/CustomSMTPTest.feature
apps/gauzy-e2e/src/support/step_definitions/CustomSMTPTest/CustomSMTPTest.ts

feat: custom smtp e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pagedata/AddOrganizationPageData.ts
apps/gauzy-e2e/src/support/step_definitions/AddOrganizationTest.feature
apps/gauzy-e2e/src/support/step_definitions/AddOrganizationTest/AddOrganizationTest.ts
apps/gauzy/src/app/@shared/currency/currency.component.html

feat: add organization e2e test with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/AddTasksPageObject.ts
apps/gauzy-e2e/src/support/step_definitions/AddTasksTest.feature
apps/gauzy-e2e/src/support/step_definitions/AddTasksTest/AddTasksTest.ts

feat: tasks e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest.feature
apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest/AppointmentsTest.ts

feat: appointments e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/AppsIntegrationsTest.feature
apps/gauzy-e2e/src/support/step_definitions/AppsIntegrationsTest/AppsIntegrationsTest.ts

feat: integrations e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/ApprovalRequestPageObject.ts
apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest.feature
apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest/ApprovalRequestTest.ts

feat: approval request e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/CandidatesTest.feature
apps/gauzy-e2e/src/support/step_definitions/CandidatesTest/CandidatesTest.ts

feat: employee candidates e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/ClientsTest.feature
apps/gauzy-e2e/src/support/step_definitions/ClientsTest/ClientsTest.ts

feat: clients e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/ContactsLeadsTest.feature
apps/gauzy-e2e/src/support/step_definitions/ContactsLeadsTest/ContactsLeadsTest.ts

feat: contacts e2e tests with gherkin

---

.github/workflows/deploy-do.yml
.github/workflows/test.yml
apps/gauzy-e2e/src/support/Base/pages/AddUser.po.ts

Feat/e2e on GitHub actions

---

apps/gauzy-e2e/src/support/step_definitions/AACustomersTest.feature
apps/gauzy-e2e/src/support/step_definitions/AACustomersTest/AACustomersTest.ts

feat: customers e2e tests with gherkin

---

apps/gauzy/src/app/@shared/pipes/datetime-format.pipe.ts
apps/gauzy/src/app/pages/import-export/import-export.component.ts
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts
packages/core/src/accounting-template/accounting-template.entity.ts
packages/core/src/auth/auth.service.ts
packages/core/src/auth/commands/handlers/auth.register.handler.ts
packages/core/src/email-template/email-template.entity.ts
packages/core/src/employee-proposal-template/employee-proposal-template.entity.ts
packages/core/src/export-import/import/commands/handlers/import-entity-field-map-or-create.handler.ts
packages/core/src/export-import/import/import-all.service.ts
packages/core/src/feature/feature.module.ts
packages/core/src/gauzy-cloud/commands/handlers/gauzy-cloud-user.migrate.handler.ts
packages/core/src/organization/commands/handlers/organization.create.handler.ts
packages/core/src/role-permissions/default-role-permissions.ts
packages/core/src/tenant/tenant.module.ts
packages/core/src/tenant/tenant.service.ts
packages/core/src/user-organization/user-organization.entity.ts
packages/core/src/user/user.entity.ts

Fix/#3208 After Migrate Fixes

---

.github/workflows/test.yml

feat: added working directory to test file

---

apps/gauzy-e2e/package.json

feat: added yarn commands to cypress package json

---

apps/gauzy-e2e/package.json

feat: updated package json yarn commands

---

apps/gauzy-e2e/package.json

fix: added missing yarn commands to package json

---

apps/gauzy-e2e/package.json

fix: more yarn commands

---

.github/workflows/test.yml
apps/gauzy-e2e/package.json

feat: testing without build

---

.github/workflows/test.yml
apps/gauzy-e2e/package.json

feat: increasing the number of watchers

---

.github/workflows/test.yml

fix: test yml indentation fix

---

.github/workflows/test.yml

feat: added config file path to test yml

---

apps/server/package.json
apps/server/src/environments/environment.prod.ts
apps/server/src/environments/environment.ts
apps/server/src/index.ts
apps/server/src/package.json
apps/server/src/preload/desktop-server-ui.ts
package.json

feat: gauzy server initial server

---

apps/gauzy-e2e/src/support/step_definitions/AddRemoveExistingUserTest.feature
apps/gauzy-e2e/src/support/step_definitions/AddRemoveExistingUserTest/AddRemoveExistingUserTest.ts

feat: edit user e2e test with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/EditProfilePageObject.ts
apps/gauzy-e2e/src/support/Base/pages/EditProfile.po.ts
apps/gauzy-e2e/src/support/step_definitions/EditProfileTest.feature
apps/gauzy-e2e/src/support/step_definitions/EditProfileTest/EditProfileTest.ts

feat: edit user profile e2e tests

---

apps/gauzy/src/app/pages/import-export/import-export.component.ts
packages/contracts/src/index.ts
packages/contracts/src/role-permission.model.ts
packages/contracts/src/role.model.ts
packages/core/src/email-template/email-template.entity.ts
packages/core/src/email/email.entity.ts
packages/core/src/export-import/import-record/commands/handlers/import-record-update-or-create.handler.ts
packages/core/src/export-import/import/import-all.service.ts
packages/core/src/gauzy-cloud/commands/handlers/gauzy-cloud-tenant.migrate.handler.ts
packages/core/src/gauzy-cloud/commands/index.ts
packages/core/src/gauzy-cloud/gauzy-cloud.controller.ts
packages/core/src/gauzy-cloud/gauzy-cloud.module.ts
packages/core/src/gauzy-cloud/gauzy-cloud.service.ts
packages/core/src/organization-team/organization-team.module.ts
packages/core/src/organization/commands/handlers/organization.create.handler.ts
packages/core/src/role-permissions/role-permissions.controller.ts
packages/core/src/role-permissions/role-permissions.module.ts
packages/core/src/role-permissions/role-permissions.service.ts
packages/core/src/role/role.controller.ts
packages/core/src/role/role.module.ts
packages/core/src/role/role.service.ts

Fix/#3208 Migrate roles/permissions

---

apps/gauzy-e2e/src/support/Base/pageobjects/ExpensesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Expenses.po.ts
apps/gauzy-e2e/src/support/step_definitions/ExpensesTest.feature
apps/gauzy-e2e/src/support/step_definitions/ExpensesTest/ExpensesTest.ts

feat: expenses e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pages/AddUser.po.ts
apps/gauzy-e2e/src/support/Base/pages/EditProfile.po.ts
apps/gauzy-e2e/src/support/Base/pages/EventTypes.po.ts
apps/gauzy-e2e/src/support/Base/pages/Expenses.po.ts
apps/gauzy-e2e/src/support/Base/utils/util.ts
apps/gauzy-e2e/src/support/commands.ts
apps/gauzy-e2e/src/support/step_definitions/ExpensesTest/ExpensesTest.ts

feat: expenses e2e refactoring

---

apps/gauzy-e2e/src/support/Base/pageobjects/EstimatesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Estimates.po.ts
apps/gauzy-e2e/src/support/step_definitions/EstimatesTest.feature
apps/gauzy-e2e/src/support/step_definitions/EstimatesTest/EstimatesTest.ts

feat: estimates e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/IncomeTest.feature
apps/gauzy-e2e/src/support/step_definitions/IncomeTest/IncomeTest.ts

feat: income e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pages/EventTypes.po.ts
apps/gauzy-e2e/src/support/Base/pages/Expenses.po.ts
apps/gauzy-e2e/src/support/commands.ts
apps/gauzy-e2e/src/support/step_definitions/AddEmployeePositionTest.feature
apps/gauzy-e2e/src/support/step_definitions/AddEmployeePositionTest/AddEmployeePositionTest.ts
apps/gauzy-e2e/src/support/step_definitions/AddTasksTest.feature
apps/gauzy-e2e/src/support/step_definitions/AddTasksTest/AddTasksTest.ts
apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest/AppointmentsTest.ts
apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest/ApprovalRequestTest.ts
apps/gauzy-e2e/src/support/step_definitions/CandidatesTest/CandidatesTest.ts
apps/gauzy-e2e/src/support/step_definitions/ClientsTest/ClientsTest.ts
apps/gauzy-e2e/src/support/step_definitions/ContactsLeadsTest/ContactsLeadsTest.ts
apps/gauzy-e2e/src/support/step_definitions/CustomersTest/CustomersTest.ts
apps/gauzy-e2e/src/support/step_definitions/EstimatesTest/EstimatesTest.ts
apps/gauzy-e2e/src/support/step_definitions/EventTypesTest.feature
apps/gauzy-e2e/src/support/step_definitions/EventTypesTest/EventTypesTest.ts
apps/gauzy-e2e/src/support/step_definitions/ExpensesTest/ExpensesTest.ts
apps/gauzy-e2e/src/support/step_definitions/IncomeTest/IncomeTest.ts

feat: e2e refactoring

---

apps/gauzy-e2e/src/support/Base/pagedata/GoalsPageData.ts
apps/gauzy-e2e/src/support/Base/pages/Goals.po.ts
apps/gauzy-e2e/src/support/step_definitions/GoalsTest.feature
apps/gauzy-e2e/src/support/step_definitions/GoalsTest/GoalsTest.ts

feat: goals e2e tests with gherkin

---

apps/gauzy-e2e/src/support/commands.ts
apps/gauzy-e2e/src/support/step_definitions/AddEmployeeLevelTest/AddEmployeeLevelTest.ts
apps/gauzy-e2e/src/support/step_definitions/AddEmployeePositionTest/AddEmployeePositionTest.ts
apps/gauzy-e2e/src/support/step_definitions/AddTasksTest/AddTasksTest.ts
apps/gauzy-e2e/src/support/step_definitions/AppointmentsTest/AppointmentsTest.ts
apps/gauzy-e2e/src/support/step_definitions/ApprovalRequestTest/ApprovalRequestTest.ts
apps/gauzy-e2e/src/support/step_definitions/CandidatesTest/CandidatesTest.ts
apps/gauzy-e2e/src/support/step_definitions/ClientsTest/ClientsTest.ts
apps/gauzy-e2e/src/support/step_definitions/ContactsLeadsTest/ContactsLeadsTest.ts
apps/gauzy-e2e/src/support/step_definitions/CustomersTest/CustomersTest.ts
apps/gauzy-e2e/src/support/step_definitions/EstimatesTest/EstimatesTest.ts
apps/gauzy-e2e/src/support/step_definitions/EventTypesTest/EventTypesTest.ts
apps/gauzy-e2e/src/support/step_definitions/ExpensesTest/ExpensesTest.ts
apps/gauzy-e2e/src/support/step_definitions/GoalsTest/GoalsTest.ts
apps/gauzy-e2e/src/support/step_definitions/IncomeTest/IncomeTest.ts

feat: e2e refactoring to be more persistent on page redirection

---

apps/gauzy-e2e/src/support/Base/pagedata/DangerZonePageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/DangerZonePageObject.ts
apps/gauzy-e2e/src/support/Base/pages/DangerZone.po.ts
apps/gauzy-e2e/src/support/step_definitions/DangerZoneTest.feature
apps/gauzy-e2e/src/support/step_definitions/DangerZoneTest/DangerZoneTest.ts

feat: danger zone e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/EmailHistoryTest.feature
apps/gauzy-e2e/src/support/step_definitions/EmailHistoryTest/EmailHistoryTest.ts

feat: email history e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pagedata/EmailTempatesPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/EmailTempatesPageObject.ts
apps/gauzy-e2e/src/support/step_definitions/EmailTempatesTest.feature
apps/gauzy-e2e/src/support/step_definitions/EmailTempatesTest/EmailTempatesTest.ts

feat: email templates e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pagedata/RegisterPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/RegisterPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/Register.po.ts
apps/gauzy-e2e/src/support/step_definitions/AAGoalsTest.feature
apps/gauzy-e2e/src/support/step_definitions/AAGoalsTest/AAGoalsTest.ts
apps/gauzy-e2e/src/support/step_definitions/RegisterTest.feature
apps/gauzy-e2e/src/support/step_definitions/RegisterTest/RegisterTest.ts

feat: register e2e tests with gherkin

---

apps/gauzy/src/app/@shared/pagination/pagination-filter-base.component.ts
apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select/proposal-template-select.component.html
apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select/proposal-template-select.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/payments/payments.component.ts
apps/gauzy/src/app/pages/pipelines/pipelines.component.ts
apps/gauzy/src/app/pages/proposals/proposal-register/proposal-register.component.ts
apps/gauzy/src/app/pages/proposals/proposals.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
packages/core/src/core/seeds/seed-data.service.ts
packages/core/src/income/income.entity.ts
packages/core/src/income/income.seed.ts
packages/core/src/shared/handlers/recurring-expense.edit.handler.ts

Fix/Custom filters & proposal auto selected template

---

apps/gauzy/src/app/@shared/employee/employee-location/employee-location.component.ts
apps/gauzy/src/app/@shared/forms/location/location-form.component.html
apps/gauzy/src/app/@shared/forms/location/location-form.component.ts
apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.ts
apps/gauzy/src/app/pages/goals/goals.component.html
apps/gauzy/src/app/pages/goals/goals.component.ts
apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
packages/contracts/src/contact.model.ts
packages/contracts/src/geo-location.model.ts
packages/contracts/src/invite.model.ts
packages/core/src/candidate/candidate.controller.ts
packages/core/src/contact/contact.entity.ts
packages/core/src/contact/contact.seed.ts
packages/core/src/invite/commands/handlers/invite.accept-employee.handler.ts
packages/core/src/invite/invite.entity.ts
packages/core/src/invite/invite.service.ts
packages/core/src/organization-contact/organization-contact.entity.ts

Fix/ Postcode organization location contact save issue

---

apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
packages/core/package.json
yarn.lock

Fix: Project mutation & Upgrade date-fns package

---

apps/gauzy/src/app/pages/goals/goals.component.ts
packages/core/src/income/income.seed.ts

Fix/Goal settings & Income seed

---

apps/gauzy/src/app/pages/goals/edit-objective/edit-objective.component.ts

Fix/ Own Objectives e2e

---

apps/gauzy-e2e/src/support/Base/pageobjects/InvoicesPageObject.ts
apps/gauzy-e2e/src/support/commands.ts
apps/gauzy-e2e/src/support/step_definitions/GoalsTest/GoalsTest.ts
apps/gauzy-e2e/src/support/step_definitions/InvoicesTest.feature
apps/gauzy-e2e/src/support/step_definitions/InvoicesTest/InvoicesTest.ts
apps/gauzy-e2e/src/support/step_definitions/PaymentsTest/PaymentsTest.ts

feat: invoices e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/FileStoragePageObject.ts
apps/gauzy-e2e/src/support/step_definitions/AAFileStorageTest.feature
apps/gauzy-e2e/src/support/step_definitions/AAFileStorageTest/FileStorageTest.ts

feat: file storage e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/JobsProposalsTest.feature
apps/gauzy-e2e/src/support/step_definitions/JobsProposalsTest/JobsProposalsTest.ts

feat: job proposals e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest.feature
apps/gauzy-e2e/src/support/step_definitions/ManageCandidatesInvitesTest/ManageCandidatesInvitesTest.ts

feat: manage candidate invites e2e tests with gherkin

---

packages/core/src/reports/report.seed.ts
packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-menu.ts
packages/desktop-libs/src/lib/desktop-timer-activity.ts
packages/desktop-libs/src/lib/desktop-timer.ts
packages/desktop-libs/src/lib/desktop-tray.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

Fix/Desktop Latest Screen Capture

---

apps/gauzy-e2e/src/support/Base/pageobjects/ManageInterviewsCriterionsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/ManageInterviewsCriterions.po.ts
apps/gauzy-e2e/src/support/step_definitions/AAManageInterviewsCriterionsTest.feature
apps/gauzy-e2e/src/support/step_definitions/AAManageInterviewsCriterionsTest/ManageInterviewsCriterionsTest.ts

feat: manage interviews criterions e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pagedata/ManageOrganizationPageData.ts
apps/gauzy-e2e/src/support/step_definitions/AAManageOrganizationTest.feature
apps/gauzy-e2e/src/support/step_definitions/AAManageOrganizationTest/ManageOrganizationTest.ts

feat: manage organization e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/ManageEmployeesTest.feature

fix: small e2e step fix

---

apps/gauzy-e2e/src/integration/OrganizationDepartmentsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationDepartmentsPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationDepartmentsPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationDepartments.po.ts
apps/gauzy-e2e/src/support/step_definitions/OrganizationDepartmentsTest.feature
apps/gauzy-e2e/src/support/step_definitions/OrganizationDepartmentsTest/OrganizationDepartmentsTest.ts

feat: organization departments e2e tests with gherkin

---

apps/gauzy/src/app/pages/invoices/invoices.component.ts
packages/core/src/core/seeds/random-seed-config.ts
packages/core/src/employee/default-employees.ts
packages/core/src/invoice-estimate-history/invoice-estimate-history.entity.ts
packages/core/src/invoice/invoice.entity.ts
packages/core/src/invoice/invoice.seed.ts
packages/core/src/organization-contact/organization-contact.seed.ts
packages/core/src/organization-projects/organization-projects.seed.ts
packages/core/src/tags/tag.entity.ts
packages/core/src/tasks/task.entity.ts
packages/core/src/tasks/task.seed.ts

Fix/ Task and invoice estimate history seeder

---

packages/core/package.json

Fix/Copying i18n assets folder #3314

---

apps/gauzy-e2e/src/integration/OrganizationDocumentsTest.ts
apps/gauzy-e2e/src/support/Base/pagedata/OrganizationDocumentsPageData.ts
apps/gauzy-e2e/src/support/step_definitions/OrganizationDocumentsTest.feature
apps/gauzy-e2e/src/support/step_definitions/OrganizationDocumentsTest/OrganizationDocumentsTest.ts

feat: organization documents e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pagedata/OrganizationEmploymentTypesPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationEmploymentTypesPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationEmploymentTypes.po.ts
apps/gauzy-e2e/src/support/step_definitions/AAOrganizationEmploymentTypesTest.feature
apps/gauzy-e2e/src/support/step_definitions/AAOrganizationEmploymentTypesTest/OrganizationEmploymentTypesTest.ts

feat: organization employment types e2e tets with gherkin

---

apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.ts
apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.ts
apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.ts
apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.html
apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.ts
apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.ts
apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report.module.ts
apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.html
apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.ts
apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report.module.ts
apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.html
apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.ts
apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.ts
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report.module.ts
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.html
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.ts
apps/gauzy/src/app/pages/reports/payment-report/payment-report.module.ts
apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.html
apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.ts
apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.ts
apps/gauzy/src/app/pages/reports/time-reports/time-reports.module.ts
apps/gauzy/src/app/pages/reports/time-reports/time-reports/time-reports.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
packages/contracts/src/report.model.ts

Fix/Expenses & Payments & Amount owed charts colors

---

apps/gauzy-e2e/src/support/Base/pagedata/OrganizationEquipmentPageData.ts
apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationEquipmentPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationEquipment.po.ts
apps/gauzy-e2e/src/support/step_definitions/OrganizationEquipmentTest.feature
apps/gauzy-e2e/src/support/step_definitions/OrganizationEquipmentTest/OrganizationEquipmentTest.ts

feat: organization equipment e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationRecurringExpensesPageObject.ts
apps/gauzy-e2e/src/support/step_definitions/OrganizationRecurringExpensesTest.feature
apps/gauzy-e2e/src/support/step_definitions/OrganizationRecurringExpensesTest/OrganizationRecurringExpensesTest.ts

feat: organization recurring expense e2e tests with gherkin

---

apps/gauzy-e2e/src/support/step_definitions/OrganizationProjectsTest.feature
apps/gauzy-e2e/src/support/step_definitions/OrganizationProjectsTest/OrganizationProjectsTest.ts

feat: organization projects e2e tests with gherkin

---

apps/gauzy/src/app/@core/validators/index.ts
apps/gauzy/src/app/@core/validators/url-pattern.validator.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-hiring/edit-employee-hiring.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-networks/edit-employee-networks.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-networks/edit-employee-networks.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts

Fix/Employee networks on load & save data issue

---

apps/gauzy-e2e/src/support/step_definitions/OrganizationTagsTest.feature
apps/gauzy-e2e/src/support/step_definitions/OrganizationTagsTest/OrganizationTagsTest.ts

feat: organization tags e2e tests with gherkin

---

apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.html
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.ts
apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.module.ts
packages/contracts/src/availability-slots.model.ts
packages/core/src/accounting-template/accounting-template.controller.ts
packages/core/src/availability-slots/availability-slots.controller.ts
packages/core/src/availability-slots/availability-slots.service.ts
packages/core/src/availability-slots/commands/availability-slots.bulk.create.command.ts
packages/core/src/availability-slots/commands/handlers/availability-slots.bulk.create.handler.ts
packages/core/src/availability-slots/commands/handlers/availability-slots.create.handler.ts
packages/core/src/availability-slots/commands/handlers/get-conflict-availability-slots.handler.ts
packages/core/src/availability-slots/commands/index.ts
packages/core/src/invite/invite.controller.ts
packages/core/src/invite/invite.entity.ts

Fix/Availability employee slots tenant organization & other fixes

---

apps/gauzy-e2e/cypress.json
apps/gauzy-e2e/src/support/step_definitions/AddEmployeeLevelTest/AddEmployeeLevelTest.ts
apps/gauzy-e2e/src/support/step_definitions/OrganizationEquipmentTest/OrganizationEquipmentTest.ts
apps/gauzy-e2e/src/support/step_definitions/OrganizationTeamsTest.feature
apps/gauzy-e2e/src/support/step_definitions/OrganizationTeamsTest/OrganizationTeamsTest.ts
apps/gauzy-e2e/src/support/step_definitions/OrganizationVendorsTest.feature
apps/gauzy-e2e/src/support/step_definitions/OrganizationVendorsTest/OrganizationVendorsTest.ts

feat: organization vendors e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pages/Proposals.po.ts
apps/gauzy-e2e/src/support/commands.ts
apps/gauzy-e2e/src/support/step_definitions/OrganizationEmploymentTypesTest/OrganizationEmploymentTypesTest.ts
apps/gauzy-e2e/src/support/step_definitions/ProposalsTest.feature
apps/gauzy-e2e/src/support/step_definitions/ProposalsTest/ProposalsTest.ts

feat: proposals e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/RecurringExpensesPageObject.ts
apps/gauzy-e2e/src/support/step_definitions/RecurringExpensesTest.feature
apps/gauzy-e2e/src/support/step_definitions/RecurringExpensesTest/RecurringExpensesTest.ts

feat: recurring expense e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationEquipmentPageObject.ts
apps/gauzy-e2e/src/support/Base/pages/OrganizationEquipment.po.ts
apps/gauzy-e2e/src/support/step_definitions/OrganizationEquipmentTest/OrganizationEquipmentTest.ts

fix: organization equipment e2e small refactoring

---

apps/gauzy-e2e/src/integration/RegisterTest.ts
apps/gauzy-e2e/src/support/step_definitions/SalesEstimatesTest.feature
apps/gauzy-e2e/src/support/step_definitions/SalesEstimatesTest/SalesEstimatesTest.ts

feat: sales estimates e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/SalesInvoicesPageObject.ts
apps/gauzy-e2e/src/support/step_definitions/SalesInvoicesTest.feature
apps/gauzy-e2e/src/support/step_definitions/SalesInvoicesTest/SalesInvoicesTest.ts

feat: sales invoices e2e tests with gherkin

---

apps/server/src/index.ts
apps/server/src/package.json
apps/server/src/preload/ui-server.ts
packages/desktop-libs/src/lib/desktop-server.ts
packages/desktop-ui-lib/src/lib/server-dashboard/server-dashboard.component.html
packages/desktop-ui-lib/src/lib/server-dashboard/server-dashboard.component.scss
packages/desktop-ui-lib/src/lib/server-dashboard/server-dashboard.component.ts
packages/desktop-ui-lib/src/lib/server-dashboard/server-dashboard.module.ts
packages/desktop-ui-lib/src/lib/settings/settings.component.html
packages/desktop-ui-lib/src/lib/setup/setup.component.html
packages/desktop-ui-lib/src/lib/setup/setup.component.ts
packages/desktop-window/src/lib/desktop-window-server.ts

fix: gauzy server on windows

---

apps/gauzy-e2e/src/support/step_definitions/OrganizationEquipmentTest/OrganizationEquipmentTest.ts

fix: organization equipment e2e refactoring

---

apps/gauzy-e2e/src/support/step_definitions/OrganizationEquipmentTest/OrganizationEquipmentTest.ts
apps/gauzy-e2e/src/support/step_definitions/TimeOffTest/TimeOffTest.ts

fix: time off request e2e refactoring

---

apps/gauzy-e2e/src/support/step_definitions/RolesPermissionsTest.feature
apps/gauzy-e2e/src/support/step_definitions/RolesPermissionsTest/RolesPermissionsTest.ts

feat: roles permissions e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/SettingsButtonPageObject.ts
apps/gauzy-e2e/src/support/step_definitions/SettingsButtonTest.feature
apps/gauzy-e2e/src/support/step_definitions/SettingsButtonTest/SettingsButtonTest.ts

feat: settigns button e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pages/HumanResources.po.ts
apps/gauzy-e2e/src/support/Base/utils/util.ts
apps/gauzy-e2e/src/support/step_definitions/HumanResourcesTest.feature
apps/gauzy-e2e/src/support/step_definitions/HumanResourcesTest/HumanResourcesTest.ts

feat: human resources e2e tests with gherkin

---

apps/gauzy-e2e/src/support/Base/pageobjects/ImportExportPageObject.ts
apps/gauzy-e2e/src/support/step_definitions/ImportExportTest.feature
apps/gauzy-e2e/src/support/step_definitions/ImportExportTest/ImportExportTest.ts

feat: import export e2e test with gherkin

---

apps/gauzy-e2e/src/support/Base/pagedata/SettingsFeaturesPageData.ts
apps/gauzy-e2e/src/support/step_definitions/SettingsFeaturesTest.feature
apps/gauzy-e2e/src/support/step_definitions/SettingsFeaturesTest/SettingsFeaturesTest.ts

feat: settings features e2e tests with gherkin

---

apps/gauzy/src/app/@core/services/accounting-template.service.ts
apps/gauzy/src/app/@core/services/email-template.service.ts
packages/contracts/src/accounting-template.model.ts
packages/contracts/src/email-template.model.ts
packages/core/src/accounting-template/accounting-template.controller.ts
packages/core/src/accounting-template/accounting-template.service.ts
packages/core/src/core/crud/crud.service.ts
packages/core/src/email-template/email-template.controller.ts
packages/core/src/email-template/email-template.service.ts
packages/core/src/email-template/queries/email-template.find.query.ts
packages/core/src/email-template/queries/handlers/email-template.find.handler.ts
packages/core/src/shared/decorators/index.ts
packages/core/src/shared/decorators/language.decorator.ts

Fix/Email & Accounting template API access
