ever-co/ever-gauzy

angular.json, apps/gauzy/src/app/pages/dashboard/dashboard.component.scss, apps/gauzy/src/app/pages/employees/employees.component.scss, apps/gauzy/src/app/pages/expenses/expenses.component.scss, apps/gauzy/src/app/pages/income/income.component.html, apps/gauzy/src/app/pages/income/income.component.scss, apps/gauzy/src/app/pages/organizations/organizations.component.scss, tsconfig.json
I fixed it like set value `false` on sourceMap field on compilerOptions and remove not needed scss imports.
Now is recompiling for 1sec before was 16sec.
=> feat: improved recompile speed after change scss

apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.ts, apps/gauzy/src/app/@theme/components/header/header.component.ts, apps/gauzy/src/assets/i18n/en.json
Sort by date, descending by default implemented. At the top of the table the latest records are shown.
Date column moved to the left.
=> feat: sort by date descending by default on profit report popup

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
Fixed #313 to only show "Username: __" if the username is not null
=> Fix: hide username if empty

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.html, apps/gauzy/src/assets/i18n/en.json
Fixed #309 
1. Added header in Edit Organization settings
2. Added header in Edit Employee Profile page
Test cases:
2.1 (First Name OR Last Name) & username exist: **Manage Employee First Last (username)**
2.2 Only username: **Manage Employee 'username'**
2.3 Only First Name OR Last Name: **Manage Employee First Last**
=> Fix for #309 add missing headers

apps/gauzy/src/app/pages/employees/employees.component.html, apps/gauzy/src/app/pages/employees/employees.component.ts, apps/gauzy/src/app/pages/expenses/expenses.component.html, apps/gauzy/src/app/pages/expenses/expenses.component.ts, apps/gauzy/src/app/pages/income/income.component.html, apps/gauzy/src/app/pages/income/income.component.ts, apps/gauzy/src/app/pages/organizations/organizations.component.html, apps/gauzy/src/app/pages/organizations/organizations.component.ts, apps/gauzy/src/app/pages/proposals/proposals.component.html, apps/gauzy/src/app/pages/proposals/proposals.component.ts
There is an existing issue with ng2-smart-table which is causing #335 
1. https://github.com/akveo/ng2-smart-table/issues/462
2. https://github.com/akveo/ng2-smart-table/issues/502
I have currently fixed it only for review, just for the organization settings table as explained in this comment: https://github.com/akveo/ng2-smart-table/issues/462#issuecomment-339380137 
Please let me know if this is okay, we will then need to implement it in all **ng2-smart-table** in the application
=> fix: organization page manage btn

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.scss, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.scss, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.ts
**Fixed:**
1. Moved the tabs on top, and profile image under the main section
2. Moved the profile Image ts code into the main component instead of the parent
3. I had to create organization-container and organization-photo style classes similar to employee-container and employee-photo since these are in a different component now and not under nb-card-body as specified in the employee module.
4. I also had to use ::ng-deep for reducing the left/right padding of nb-tabs.
The table now looks like:
**Remaining:**
Using only the responsive icons when screen resolution is <1600 (might need help with this)
Please review & merge. Issue #324 
This merge will unblock #310  so we can create more tabs and close the issue.
=> fix: organization card overflow issue for small screen

apps/gauzy/src/app/pages/expenses/expenses.component.ts, apps/gauzy/src/app/pages/income/income.component.ts
Fixes #229 
Looks like that for every load, the expense & income tables were always sending two requests to the backend. One actual request and one with all fields as null.
The behavior looked random because the data was displayed depending upon which response was received later. 
Please review the code changes, I have removed the second null call, I am not sure why the second request was added, looks like it was added for some fake data in this commit: https://github.com/ever-co/gauzy/commit/403df1404fa2689580996e74118bba7a8021c65d
=> fix: expenses page random behaviour

apps/api/src/app/employee-statistics/employee-statistics.service.ts, apps/gauzy/src/app/@shared/dashboard/profit-history/profit-history.component.ts, apps/gauzy/src/app/pages/dashboard/dashboard.component.ts
Fixes #383
---
- Earlier, as income and expense were integers `a + b` worked correctly even without typecasting.
- Since they were converted to float the issue boiled up as typecasting is required.
- Wherever I could see that we are adding income or expense, I've added the `+` unary operator.
- We'll need to make sure we do this in the future as well.
=> fix: #383 dashboard calculations

apps/gauzy/src/app/@core/utils/selector.service.ts, apps/gauzy/src/app/pages/pages.component.ts
Fixes #391 
---
Changes
- Summary of the change in `pages.component.ts`: Earlier we were re-creating the menu items object on navigation, selected organization change. Now we're modifying the same object.
- Added a `showOrganizationShortcuts` in selector.service which will return true when organization shortcuts need to be displayed. 
- Earlier we were using the `showOrganizationsSelector` but when we're editing organizations in pages like http://localhost:4200/#/pages/organizations/edit/93ab1477-093e-41e1-84f0-74e628fa9644/settings/projects .. it makes sense to show the shortcuts with the active one highlighted even though the selector is not visible.
Translation hack:
- There is a small issue which is there even in the existing app, when we log in for the first time, or hard refresh the …
=> fix: #391 highlight sidebar items

apps/api/src/app/core/seeds/SeedDataService.ts, apps/api/src/app/income/income-seed-data/november-19.ts, apps/api/src/app/income/income.seed.ts
Income data seeded for November 2019 for all employees at Ever Technologies. The data from XLS was converted to CSV and finally to JSON, so it can be seeded in the DB, using our implemented seeding functionality. Gauzy calculated total income and bonuses correctly. 
Below is the data represented on different pages
Income Page:
Dashboard Page:  
Employees Page:
=> feat: income data seeded for November 2019

apps/gauzy/src/app/pages/dashboard/dashboard.component.html, apps/gauzy/src/app/pages/dashboard/dashboard.component.ts, apps/gauzy/src/assets/i18n/en.json
feat: cosmetic changes on Dashboard page, according to #407 
fix: Calculation of Profit. 
If user inputs negative numbers for expenses (minus by minus equals plus), now profit will be calculated correctly.
=> feat: cosmetic changes on dashboard and fix on negative expenses

apps/api/src/app/expense/commands/handlers/expense.create.handler.ts, apps/api/src/app/expense/expense.entity.ts, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.scss, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts, apps/gauzy/src/app/pages/expenses/expenses.component.ts, libs/models/src/lib/expense.model.ts
Feature to "Include Taxes" on Expenses pages partialy implemented.  The required inputs added to Add Expense popup and data for "TaxType" ("%" or "Value"), Tax Label and Tax Rate (value or %) is stored in the Expense table in the DB.
TODO: Display data on Expenses page and represent calculations on taxes (%, value).
=> feat: expenses include taxes partially implemented

apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts
On expenses pages (add/ edit) "Asign to" functionality implemented on Front-end (component and template) with two dropdowns: "Client" and "Project" (both optional). This will allow assigning an Expense to specific project/client.
=> feat: on expenses pages assign to functionality implemented in fe

apps/api/src/app/expense/commands/handlers/expense.create.handler.ts, apps/api/src/app/expense/expense.entity.ts, apps/gauzy/src/app/@core/services/error-handling.service.ts, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.scss, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.module.ts, apps/gauzy/src/app/pages/expenses/expenses.component.ts, libs/models/src/lib/expense.model.ts
An additional selector (above other inputs) for the type of Expense (radio boxes, only one selection is valid): "Tax Deductible" (default), "Not Tax Deductible", "Billable to Client" implemented on Expense Add/ Edit pages. Idea is that if Tax-Deductible Expense is selected, the company can claim it in official accounting. If it's "Not Tax Deductable", it means that it't can't be claimed in official accounting. If it's "Billable to client" it means that companie's client will refund for it. Note: if Billable to Client is selected, the popup require selection of Client.
=> feat: expense type selector implemented

apps/gauzy/src/app/pages/employees/employees.component.ts
Fixes #415 
I have added Math.floor because that was already being used in other fields.
Please let me know if it needs to be rounded to two decimal places or some other way.
@AlexTasev please let me know if there are these calculations on any other pages, since what I've noticed others seem to be fixed :)
=> fix: #415 float calculation

apps/api/src/app/income/commands/handlers/income.create.handler.ts, apps/api/src/app/invite/commands/handlers/index.ts, apps/api/src/app/invite/commands/handlers/invite.accept-employee.handler.ts, apps/api/src/app/invite/commands/handlers/invite.accept-user.handler.ts, apps/api/src/app/invite/commands/invite.accept-employee.command.ts, apps/api/src/app/invite/commands/invite.accept-user.command.ts, apps/api/src/app/invite/invite.controller.ts, apps/api/src/app/invite/invite.module.ts, apps/api/src/app/invite/invite.service.ts, apps/gauzy/src/app/@core/services/invite.service.ts, apps/gauzy/src/app/@shared/invite/invites/invites.component.ts, apps/gauzy/src/app/auth/accept-invite/accept-invite-form/accept-invite-form.component.html, apps/gauzy/src/app/auth/accept-invite/accept-invite.component.ts, apps/gauzy/src/app/auth/accept-invite/accept-invite.module.ts, apps/gauzy/src/app/pages/employees/employees.component.html, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/invite.model.ts
1. Added feature to send a test email using ethereal
2. Handled expired invitations. Please note: In the backend, the status will always be INVITED or ACCEPTED. Expired is calculated at runtime from expire time.
3. As discussed, created two different command handlers to handle user creation and employee creation when they accept invites.
4. Added employee invites.
5. Improved feedback for password and name fields to show red/green borders when validation fails.
Fixes #161 
Fixes #162 
Fixes #163 
Fixes #164 
Created a new issue #437 to track invite employee enhancements (projects, clients, departments)
=> feat: #161 #162 invite employee & user

apps/api/src/app/invite/invite.module.ts
Newly created EmailModule imported in InviteModule, because the lack of it resulted in build error.
=> fix: newly created email module imported in invite module

apps/gauzy/src/app/@shared/employee/employee-recurring-expense-mutation/employee-recurring-expense-mutation.component.html, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html, apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html, apps/gauzy/src/app/@shared/table-components/income-amount/income-amount.component.ts, apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-rate/edit-employee-rate.component.html, apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-rate/edit-employee-rate.component.ts, apps/gauzy/src/app/pages/expenses/expenses.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects-mutation/edit-organization-projects-mutation.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-projects/edit-organization-projects-mutation/edit-organization-projects-mutation.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts
Currency drop downs made read-only and it will default to the organization currency in create-mode in the following places:
1. Income mutation popup
1. Expense mutation popup
1. Employee Recurring Expense
1. Edit Employee > Rates
1. Edit Organisation Recurring Expense
1. Edit Organisation > Projects
Added currency to the following tables:
1. Income table - added currency to the value
1. Expense table - added currency to the value
Solves the initial part of #404
=> feat: disabled currency dropdowns #404

apps/api/src/app/employee-statistics/employee-statistics.module.ts, apps/api/src/app/employee-statistics/employee-statistics.service.ts, apps/api/src/app/employee-statistics/queries/handlers/aggregate-employee-statistic.handler.ts, apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.ts
Added bonus calculation logic in the dashboard page to calculate bonus based on the organization's bonus type and percentage preferences. The calculations are shown:
1. In the Employee table in Dashboard with All Employees selection.
2. In the Dashboard page with a single employee selected and the employee chart.
@evereq Bonus calculation logic is common for both the frontend and the backend. Currently, the calculation code is duplicated in employee-statistics.component and employee-statistics.service files. Can we move this to a shared file? If yes, please suggest.
=> feat(#401): employee statistics bonus calculation

apps/gauzy/src/app/@core/services/store.service.ts, apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts, apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts, apps/gauzy/src/app/pages/expenses/expenses.component.ts, apps/gauzy/src/app/pages/income/income.component.ts
For #397 
1. Fixed application crash when a non-employee user logs in without the change selected employee permission.
2. Created two default constants called `ALL_EMPLOYEES_SELECTED` and `NO_EMPLOYEE_SELECTED`
3. Also created an enum `DEFAULT_TYPE` with two values `ALL_EMPLOYEE` and `NO_EMPLOYEE`
4. Removed code to select `All Employees` if selected employee is null from store
We need to handle the `No Employee` selection in all pages, created a ticket #563 for that
=> fix: #397 non user without change selected employee permission

apps/gauzy/src/app/pages/dashboard/dashboard.component.html, apps/gauzy/src/app/pages/dashboard/dashboard.component.ts, apps/gauzy/src/app/pages/dashboard/dashboard.module.ts, apps/gauzy/src/app/pages/dashboard/data-entry-shortcuts/data-entry-shortcuts.component.html, apps/gauzy/src/app/pages/dashboard/data-entry-shortcuts/data-entry-shortcuts.component.scss, apps/gauzy/src/app/pages/dashboard/data-entry-shortcuts/data-entry-shortcuts.component.ts, apps/gauzy/src/app/pages/pages.component.ts, apps/gauzy/src/assets/i18n/en.json
For #397 
What's new
1. A new dashboard that is visible to people who do not have access to the Admin Dashboard, which is basically our 'shortcut' dashboard which will display shortcuts to add/remove items like Expenses, Income, etc based on permissions.
2. Removed the 'dashboard' check from the sidebar, since no matter what role, they will always have a dashboard
This completes the basic 'structure' for supporting multiple roles through permissions within the system.
=> feat: #397 data entry dashboard with shortcuts

apps/api/src/app/invite/invite.controller.ts, apps/api/src/app/organization/organization.entity.ts, apps/api/src/app/role-permissions/role-permissions.seed.ts, apps/gauzy/src/app/@shared/invite/invites/invites.component.html, apps/gauzy/src/app/@shared/invite/invites/invites.component.ts, apps/gauzy/src/app/pages/employees/employees.component.html, apps/gauzy/src/app/pages/employees/employees.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.scss, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.module.ts, apps/gauzy/src/app/pages/users/users.component.html, apps/gauzy/src/app/pages/users/users.component.ts, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/organization.model.ts, libs/models/src/lib/role-permission.model.ts
1. Under Organization > Edit Organization > Settings, added fields to enable or disable invites for the selected organization and an invite expiry period field defaulting to 7 days.
2. Under Settings> Roles & Permissions, the General panel now contains 2 new permissions to view and edit the invites.
3. Invite button in Employee and User Tab is displayed only if the user has edit permission.
4. Manage invites page does not show Invite, Copy Link, Resend and Delete buttons if the user does not have invite edit permission.
5. Added permission guards in the backend to prevent users from creating, resending or deleting invites when edit permission is revoked for the user.
Todo:
Use the newly inviteExpiryPeriod from the organization table to calculate the validity of invites.
Disable invites …
=> feat: #433 invite expiry setting and permission

apps/api/src/app/email-template/email-template.seed.ts
The path string in Windows FS looks like `password\\bg\\html.mjml` and the same in Linux based FS is `password/bg/html.mjml`
The string was split on `/` to extract the file extension which worked fine in Mac and Linux but not on windows. 
Have added fix to replace `\\` in the string to `/` and the email_template table is seeding as expected.
=> fix: #600 email template seeding in Windows

apps/gauzy/src/app/pages/dashboard/dashboard.component.ts
---
Fixes #613 
Fixes #591 
1. Removed the `if(emp)` check from dashboard component so that dashboard always loads even when emp is null, which happens when we switch over from editing an organization or a page where the organization is changed
2. This results in a slight flicker in the dashboard when an employee logs in, which we will need to see how to remove later.
=> fix: #613 #591 dashboard loading issue

apps/api/src/app/role-permissions/role-permissions.seed.ts, apps/gauzy/src/app/@core/services/expenses.service.ts, apps/gauzy/src/app/pages/dashboard/data-entry-shortcuts/data-entry-shortcuts.component.html, apps/gauzy/src/app/pages/dashboard/data-entry-shortcuts/data-entry-shortcuts.component.scss, apps/gauzy/src/app/pages/dashboard/data-entry-shortcuts/data-entry-shortcuts.component.ts, apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html, apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts, apps/gauzy/src/app/pages/employees/employees.component.html, apps/gauzy/src/app/pages/employees/employees.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts, apps/gauzy/src/app/pages/organizations/organizations.component.html, apps/gauzy/src/app/pages/organizations/organizations.component.ts, apps/gauzy/src/app/pages/pages.component.ts, apps/gauzy/src/assets/i18n/en.json
---
What is new?
1. Dashboard for Data Entry user has 2 new shortcuts, one to add recurring expenses for Organization and another for adding recurring expenses for Employees.
2. Organizations and Employees shortcuts are also enabled for this user on the sidebar.
3. A single data entry operator may add expenses for multiple organizations or employees of multiple organizations, therefore permission to change the organization is also added in the seed. 
4. Only …
=> feat: #567 recurring expenses by data entry user

apps/gauzy/src/app/@shared/dashboard/info-block/info-block.component.html, apps/gauzy/src/app/@shared/dashboard/info-block/info-block.component.scss, apps/gauzy/src/app/@shared/dashboard/info-block/info-block.component.ts, apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.html, apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.scss, apps/gauzy/src/assets/i18n/en.json
---
Improvements for #467 
**Following improvements done:**
1. Where we show formulas (e.g. 10% of the income). We can also show how it's calculated, e.g. "10% from income 4100 BGN"
Profit (Net Income) = Total Income 4100 BGN - Total Expenses 3063.64 BGN
2. I would also highlight more Salary //Check the 7th point on what to do with Salary
3. I would also highlight more Profit
(in both salary and Profit best to increase size of font I think
i.e. biggest attention …
=> feat: #467 bonus and statistics improvements

apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.html
---
**If bonus is set to None in organization settings then it should also be disabled in the dashboard**
1. With bonus not set to null
2. With bonus set to null
=> feat: #467 disable bonus in dashboard if bonus type is none

apps/api/src/app/organization/organization.entity.ts, apps/api/src/app/organization/organization.seed.ts, apps/gauzy/src/app/@theme/components/header/selectors/date/date.component.html, apps/gauzy/src/app/@theme/components/header/selectors/date/date.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/organization.model.ts
---
1. The organization entity has a new field to store the organization registration date.
2. The value of the organization registration date can be updated from the Organization edit page.
3. Seed organization registration date with random past dates.
4. Dates before the selected organization's registration date are disabled for selection through the header component's Period selector.  
**Sample screenshots:**
=> feat: #790 limit period selection to organization registration date

apps/api/src/app/employee-statistics/employee-statistics.module.ts, apps/api/src/app/employee-statistics/employee-statistics.service.ts, apps/api/src/app/employee-statistics/queries/handlers/month-aggregated-employee-statistics.handler.ts
---
What got added?
The organization's split expenses were not taken into account for calculating the employee's expense in the employee-statistics chart. This has now been added.
2 new issues(#822 #825) were identified during the implementation of this ticket, which makes the discrepancies still exist between the calculations shown in the chart and employee statistics. Fixing these issues will help overcome these discrepancies.
=> fix: #816 organization split recurring expenses in employee stat chart

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-positions/edit-organization-positions.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-positions/edit-organization-positions.component.ts
Added "positionExists" boolean property and set it to false if 
organizationPositionsService.getAll() in loadPositions() returns empty array and true if not empty. Then added *ngif to Position name header that renders it if positionExists is true.
=> feat: removed position name header if no positions

apps/gauzy/src/app/@theme/components/header/selectors/date/date.component.ts
---
What got changed?
Max and Min limit shared the same date object which was causing some side effect of max limit being overridden to Dec instead of the current month. 
Now, Max and Min use a separate date object to avoid such side effects.
=> feat: #790 removed shared date object to avoid side effects

apps/gauzy/src/app/pages/dashboard/dashboard-routing.module.ts, apps/gauzy/src/app/pages/dashboard/dashboard.component.html, apps/gauzy/src/app/pages/dashboard/dashboard.component.ts, apps/gauzy/src/app/pages/dashboard/dashboard.module.ts, apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.html, apps/gauzy/src/app/pages/dashboard/employee-statistics/employee-statistics.component.ts, apps/gauzy/src/app/pages/dashboard/organization-employees/organization-employees.component.ts, apps/gauzy/src/app/pages/dashboard/project-management/project-management.component.html, apps/gauzy/src/app/pages/dashboard/project-management/project-management.component.ts, apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html, apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts, apps/gauzy/src/app/pages/pages.component.ts, apps/gauzy/src/assets/i18n/en.json
Initial implementation for #664 
---
---
@evereq if this is ok then I'll do a little refactoring to rename the components to resemble the tab names.
The ticket said that the accounting tab will be conditional and will only be visible when an employee is not selected. So to maintain consistency I have made the Human Resources tab also conditional. 
What I've done is: 
1. If the employee is not selected then all organization data is shown in the **Accounting** tab …
=> feat: #664 multi tabs dashboard initial architecture

apps/gauzy/src/app/@shared/tags/tags-mutation.component.ts
tag.name wasnt showing now is :)
=> fix: added when a tag is edited to show tag.name

apps/api/src/app/shared/handlers/recurring-expense.delete.handler.ts, apps/api/src/app/shared/handlers/recurring-expense.edit.handler.ts
---
This PR Fixes #822 
Split expenses were not being copied when creating a new DB entry for a recurring expense from an existing entry. Fixed that for delete and edit both.
=> fix: #822 organization split expense

apps/api/src/app/organization-recurring-expense/queries/handlers/organization-recurring-expense.find-split-expense.handler.ts, apps/api/src/app/organization-recurring-expense/queries/organization-recurring-expense.find-split-expense.query.ts, apps/gauzy/src/app/pages/dashboard/human-resources/human-resources.component.ts
---
Expense details in Employee Dashboard page showed organization split recurring expenses of the organization employee belonged to. However, expenses that had ended or begin after the chosen period also showed up. Added a filter to select only desired expenses from the DB.
**Demo**
https://www.loom.com/share/8ce20e4a599840e98d00e7b3499f37c3
=> fix: #825 set boundaries fetch org recurring split expenses

apps/api/src/app/core/utils.ts, apps/api/src/app/employee-recurring-expense/commands/handlers/employee-recurring-expense.edit.handler.ts, apps/api/src/app/employee-recurring-expense/employee-recurring-expense.controller.ts, apps/api/src/app/employee-recurring-expense/queries/employee-recurring-expense.update-type.query.ts, apps/api/src/app/employee-recurring-expense/queries/handlers/employee-recurring-expense.start-date-update-type.handler.ts, apps/api/src/app/employee-recurring-expense/queries/handlers/index.ts, apps/api/src/app/organization-recurring-expense/commands/handlers/organization-recurring-expense.edit.handler.ts, apps/api/src/app/organization-recurring-expense/organization-recurring-expense.controller.ts, apps/api/src/app/organization-recurring-expense/queries/handlers/index.ts, apps/api/src/app/organization-recurring-expense/queries/handlers/organization-recurring-expense.start-date-update-type.handler.ts, apps/api/src/app/organization-recurring-expense/queries/organization-recurring-expense.update-type.query.ts, apps/api/src/app/shared/handlers/index.ts, apps/api/src/app/shared/handlers/recurring-expense.delete.handler.ts, apps/api/src/app/shared/handlers/recurring-expense.edit.handler.ts, apps/api/src/app/shared/handlers/recurring-expense.find-by-month.handler.ts, apps/api/src/app/shared/handlers/recurring-expense.find-update-type.handler.ts, apps/gauzy/src/app/@core/services/employee-recurring-expense.service.ts, apps/gauzy/src/app/@core/services/organization-recurring-expense.service.ts, apps/gauzy/src/app/@core/utils/date.ts, apps/gauzy/src/app/@shared/expenses/recurring-expense-block/recurring-expense-block.component.html, apps/gauzy/src/app/@shared/expenses/recurring-expense-block/recurring-expense-block.component.ts, apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html, apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts, apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.module.ts, apps/gauzy/src/app/@shared/expenses/reecurring-expense-history/recurring-expense-history.component.ts, apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html, apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts, libs/models/src/lib/recurring-expense.model.ts
---
So finally I'm almost through with this feature. I just need to do some testing and refactoring, also I think I've successfully managed to change the base of 'month' to 0 so that it is the same with javascript date.getMonth()
For an employee expense, change start date within a month, increase start date without conflict, reduce start date without conflict
https://www.loom.com/share/5670a821a4754656bc94d1a9477e3cb3
Add organization expense, reduce start date …
=> feat: #676 edit recurring expense start date

apps/gauzy/src/app/@theme/components/header/header.component.ts, apps/gauzy/src/app/pages/dashboard/data-entry-shortcuts/data-entry-shortcuts.component.ts, apps/gauzy/src/app/pages/equipment/equipment.component.html, apps/gauzy/src/app/pages/equipment/equipment.component.scss, apps/gauzy/src/app/pages/equipment/equipment.component.ts, apps/gauzy/src/app/pages/pages-routing.module.ts, apps/gauzy/src/app/pages/pages.component.ts, apps/gauzy/src/app/pages/time-off/time-off.component.ts, apps/gauzy/src/app/pages/work-in-progress/work-in-progress-routing.module.ts, apps/gauzy/src/app/pages/work-in-progress/work-in-progress.component.ts, apps/gauzy/src/app/pages/work-in-progress/work-in-progress.module.ts, apps/gauzy/src/assets/i18n/en.json
---
Please check the video for the new organization menu items. 
1. I have added **all items** given in #850 and the ones which have not implemented route to a dummy component. I have done this so that future implementations are easy, now we will just need to change the route and do nothing with the sidebar code.
2. If required we can also comment out the dummy sidebar items and then uncomment them when implemented.
3. There was a 'Candidates' route which was not …
=> feat: #850 reorganize main menu

apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
---
This condition did not match up in the markup `*ngIf="!(!isEmployee || !isCandidate)"` 
Updating the condition to `*ngIf="!(isEmployee || isCandidate)"` with an assumption that role needs to be role needs to be enabled when the component inputs `isCandidate` or `isEmployee` is **not** set to `true`.
**Demo after fix**
https://www.loom.com/share/00238f092491465eab2960f767b6e5b0
=> fix: #921 fixed role selector load condition

apps/api/src/app/employee-statistics/employee-statistics.service.ts, apps/api/src/app/employee-statistics/queries/handlers/aggregate-employee-statistic.handler.ts, apps/api/src/app/employee-statistics/queries/handlers/month-aggregated-employee-statistics.handler.ts, apps/api/src/app/employee/employee.controller.ts, apps/api/src/app/employee/employee.service.ts, apps/gauzy/src/app/@core/services/employees.service.ts, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html, apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html, apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts, apps/gauzy/src/app/pages/employees/employees.component.ts, apps/gauzy/src/app/pages/employees/table-components/employee-work-status/employee-work-status.component.html, apps/gauzy/src/app/pages/employees/table-components/employee-work-status/employee-work-status.component.scss, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/employee-statistics.model.ts
---
**Not Working Employees**
1. An employee is 'not working' If the _startWorksOn_ date is not set
2. Such an employee will not be shown in the dashboard as well as the employee selector 
3. Also in windows like Add Income, Add Expense. The employees shown will depend on the date selected (Because it does not make sense to add an Employee's expense if he/she is not working)
Video No 1: https://www.loom.com/share/d6ed6596f43b4c5cada10f36c350da43
**Split Expenses & …
=> feat: #673 consider working employees only

apps/api/src/app/organization/organization.seed.ts, apps/api/src/app/role/role.seed.ts, apps/api/src/app/tenant/tenant.seed.ts, apps/api/src/app/user/user.seed.ts
---
**What is new?**
1. Make single insert call to DB to save all user types.
2. There are multiple user types, Admin, Super Admin, Employee, Candidate, Random Candidate and Random users that need to be created as part of User seeding. Awaiting for fake data generation several users in user type slowed down the seeding process. This now is made to run in parallel using promise.all().  
3. Organization ->Tenant mapping in Organization seed
**Time to seed Users …
=> fix: #981 fixed slow user data seeding

apps/api/src/app/organization/organization.controller.ts, apps/api/src/app/organization/organization.entity.ts, apps/api/src/app/organization/organization.seed.ts, apps/gauzy/src/app/@core/services/organizations.service.ts, apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.html, apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts, apps/gauzy/src/app/app-routing.module.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.scss, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts, apps/gauzy/src/app/share/organization/organization-routing.module.ts, apps/gauzy/src/app/share/organization/organization.component.html, apps/gauzy/src/app/share/organization/organization.component.ts, apps/gauzy/src/app/share/organization/organization.module.ts, apps/gauzy/src/app/share/share-routing.module.ts, apps/gauzy/src/app/share/share.component.ts, apps/gauzy/src/app/share/share.module.ts, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/organization.model.ts
1. A new column name "profile_link", has been added to the organization table. As well as it's connected with seed as task requirement format.
2. Custom Profile Link Input added on the organization edit main tab section,
3. A new link added name(edit public profile) on the organization edit page,
4. Added a new route with "share" prefix, so the organization profile link is like,
http://localhost:4200/#/share/organization/ever_technologies_ltd
5. When someone visit on the url they will see the blank page with the organization name.
-  Profile preveiw without logged in user,
- Profile preview with logged in user,
=> feat(public-page): companies public page : part 1 #944

apps/api/src/app/auth/auth.service.ts, apps/api/src/app/invite/commands/handlers/invite.accept-user.handler.ts, apps/api/src/app/user-organization/commands/handlers/user-organization.delete.handler.ts, apps/api/src/app/user-organization/commands/index.ts, apps/api/src/app/user-organization/commands/user-organization.delete.command.ts, apps/api/src/app/user-organization/user-organization.controller.ts, apps/api/src/app/user-organization/user-organization.module.ts, apps/gauzy/src/app/@core/services/users-organizations.service.ts, apps/gauzy/src/app/pages/users/users.component.html, apps/gauzy/src/app/pages/users/users.component.ts, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/user-organization.model.ts
---
1. Super admins deletion is allowed only for super admins
2. Prevent Super admins from deleting all Super admins (there must be at least one Super admin in a Tenant) 
3. Deleting Super admin user will also remove this user from all the organizations in the Tenant.
4. For normal users, 
- If the user belonged to multiple organizations,  user delete action must remove the user only from the specified organization. 
- If the user belonged to …
=> feat: #987 tenant for new users and user delete API

apps/gauzy/src/app/pages/candidates/candidates-routing.module.ts, apps/gauzy/src/app/pages/candidates/candidates.component.html, apps/gauzy/src/app/pages/candidates/candidates.component.scss, apps/gauzy/src/app/pages/candidates/candidates.component.ts, apps/gauzy/src/app/pages/candidates/candidates.module.ts, apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-documents/edit-candidate-documents.component.html, apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-documents/edit-candidate-documents.component.scss, apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate.component.html, apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate.component.scss, apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate.component.ts, apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.html, apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/manage-candidate-interviews.component.ts, apps/gauzy/src/assets/i18n/en.json
Added manage interviews button & new page with a calendar(in the feature will display interviews with candidates)
Added notification icon(in the feature will display if the candidate has planed interview)
Added info about document(updated time&date) and icon for document
---
=> feat: add calendar for interview and  icons[ref:#1156]

.prettierrc, apps/gauzy/src/app/@shared/equipment/equipment-mutation.component.html, apps/gauzy/src/app/@shared/equipment/equipment-mutation.component.ts, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts, apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.html, apps/gauzy/src/app/@shared/income/income-mutation/income-mutation.component.ts, apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.html, apps/gauzy/src/app/@shared/organizations/organizations-step-form/organizations-step-form.component.ts, apps/gauzy/src/app/@shared/product-mutation/product-form/product-form.component.html, apps/gauzy/src/app/@shared/product-mutation/product-form/product-form.component.ts, apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.html, apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.scss, apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.ts, apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.module.ts, apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html, apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.ts, apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html, apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts, apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-employment/edit-candidate-employment.component.html, apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-employment/edit-candidate-employment.component.ts, apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-employment/edit-employee-employment.component.html, apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-employment/edit-employee-employment.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-departments/edit-organization-departments-mutation/edit-organization-departments-mutation.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts, apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.html, apps/gauzy/src/app/pages/tasks/components/task-dialog/task-dialog.component.ts
---
1. Browser warning related to `tags-color-input` component have been resolved.
2. `tags-color-input` component was used in multiple parts of the app but there was no uniform way of interacting with this component. Each page had its own implementation. Refactored all usages of `tags-color-input` component to have a uniform behaviour.
3. Removed unused input properties from `tags-color-input` component. After refactoring,  `tags-color-input` …
=> fix: #1178 fixed browser warnings, refactored tags-color-input component

apps/gauzy/src/app/@theme/styles/_overrides.scss
---
The icons in the sidebar menu are grey in the default theme. The screen looks something like this.
Assuming that the icons in the sidebar needed to appear more prominent, updated the css rule more specific so that it is applied to the menu icons but not the icons within the buttons.
**Screens in each theme after making the change**
**Light**
**Dark**
**Cosmic**
**Corporate**
=> fix: #1159 style specificity for icons in buttons

apps/gauzy/src/app/@theme/components/header/header.component.html
Issue number - https://github.com/ever-co/gauzy/issues/1019 
Change rendering logic so that only one employee selector has to be loaded at a time, which will stop duplicate get query to api
---
=> fix: #1019 fix duplicate get queries when header loads

apps/gauzy/src/app/@theme/components/header/header.component.html, apps/gauzy/src/app/@theme/components/header/selectors/date/date.component.ts
We had an issue where the function responsible for tracking "click outside calendar" was malfunctioning due to having two instances of date picker component being loaded at the same time in DOM. The solution was to change rendering logic so we only load each date picker when necessary
---
=> fix: #1009 fix date selector malfunction

apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.ts, apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.html, apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.ts, apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.module.ts, apps/gauzy/src/app/pages/tags/tags-color/tags-color.component.html, apps/gauzy/src/app/pages/tags/tags-color/tags-color.component.ts, apps/gauzy/src/assets/i18n/en.json, libs/utils.ts
---
- Ability to add a new tag directly from the Tags combobox was removed during refactoring. This feature has been added back.
- Tag names in badges for darker colours were unreadable, the text colour for badges set based on the background colour of the badge.
Before:
After:
**demo**
https://www.loom.com/share/103192e77a224fa18b619c0d5bf30cbf
=> fix: #1266 create tags from combobox and background contrast

apps/api/src/app/email-template/email-template.controller.ts, apps/api/src/app/email-template/email-template.module.ts, apps/api/src/app/email-template/queries/email-template.find.query.ts, apps/api/src/app/email-template/queries/email-template.generate-preview.query.ts, apps/api/src/app/email-template/queries/handlers/email-template.find.handler.ts, apps/api/src/app/email-template/queries/handlers/email-template.generate-preview.handler.ts, apps/api/src/app/email-template/queries/handlers/index.ts, apps/api/src/app/email-template/queries/index.ts, apps/api/src/app/email/email.service.ts, apps/gauzy/src/app/@core/services/email-template.service.ts, apps/gauzy/src/app/pages/email-templates/email-templates-routing.module.ts, apps/gauzy/src/app/pages/email-templates/email-templates.component.html, apps/gauzy/src/app/pages/email-templates/email-templates.component.scss, apps/gauzy/src/app/pages/email-templates/email-templates.component.ts, apps/gauzy/src/app/pages/email-templates/email-templates.module.ts, apps/gauzy/src/app/pages/pages-routing.module.ts, libs/models/src/lib/email-template.model.ts
---
**What got added**
1. API's to fetch Email templates based on name, language and organization.
- if organization does not have a customized template, default template is loaded for editing.
2. Live preview of of the edited mjml is shown in the UI. API calls to recompile the template to html is debounced at 500ms and allowed previous template text is different from the current template text.
**TODO**
1. Save modified templates to the DB
2. Styling the UI
=> feat: #1123 email template live edit preview and fetch APIs

apps/api/src/app/employee-appointment/employee-appointment.entity.ts, apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts, apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.html, apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.scss, apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts, apps/gauzy/src/app/share/public-appointments/appointment-form/appointment-form.component.html, apps/gauzy/src/app/share/public-appointments/appointment-form/appointment-form.component.ts, apps/gauzy/src/app/share/public-appointments/confirm-appointment/confirm-appointment,routing.module.ts, apps/gauzy/src/app/share/public-appointments/confirm-appointment/confirm-appointment.component.html, apps/gauzy/src/app/share/public-appointments/confirm-appointment/confirm-appointment.component.ts, apps/gauzy/src/app/share/public-appointments/confirm-appointment/confirm-appointment.module.ts, apps/gauzy/src/app/share/share-routing.module.ts, apps/gauzy/src/assets/i18n/en.json
This PR adds functionality to show booked slots on the calendar. The user can see the booked slots but cannot click on it, so the user is only allowed to book appointments from the free slots (the green ones). This implementation took longer than expected because it needed thoughts on the various cases possible and merge the availability slot timings with booked slot timings so that they do not overlap. 
If we select 60 min duration or any other duration, then free slots with greater or equal duration will only be shown. For eg: See the second appointment creation in below video, after …
=> feat(appointment_scheduling): render booked slots on calendar

apps/api/src/app/payment/payment.entity.ts, apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts, apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.html, apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts, apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.html, apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts, apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts, apps/gauzy/src/app/pages/invoices/invoices.component.html, apps/gauzy/src/app/pages/invoices/invoices.component.ts, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/invoice.model.ts, libs/models/src/lib/payment.model.ts
Added "Convert to invoice" button to the estimates page that converts the selected estimate to an invoice.
Added a dropdown to the payment add/edit form for payment methods.
When adding an invoice/estimate the invoice/estimate date is now set to today's date by default and the due date is set to 1 month after the invoice/estimate date.
Added translations.
Video: https://www.loom.com/share/3b950847e6744ba6a0c9e2b498d78f3c
=> feat: added estimate conversion and payment methods

apps/api/src/app/employee-appointment/commands/handlers/employee-appointment.update.handler.ts, apps/api/src/app/employee-appointment/employee-appointment.controller.ts, apps/api/src/app/employee-appointment/employee-appointment.service.ts, apps/gauzy/src/app/@core/services/employee-appointment.service.ts, apps/gauzy/src/app/@shared/timer-picker/timer-range-picker/timer-range-picker.component.ts, apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts, apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts, apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.module.ts, apps/gauzy/src/app/share/public-appointments/appointment-form/appointment-form.component.ts, apps/gauzy/src/app/share/public-appointments/confirm-appointment/confirm-appointment.component.html, apps/gauzy/src/app/share/public-appointments/confirm-appointment/confirm-appointment.component.ts, apps/gauzy/src/app/share/public-appointments/edit-appointment/edit-appointment.component.html, apps/gauzy/src/app/share/public-appointments/edit-appointment/edit-appointment.component.ts, apps/gauzy/src/app/share/public-appointments/edit-appointment/edit-appointment.module.ts, apps/gauzy/src/app/share/public-appointments/edit-appointment/edit-appointment.routing.module.ts, apps/gauzy/src/app/share/share-routing.module.ts, apps/gauzy/src/assets/i18n/en.json
This PR adds functionality to edit public appointments. The reschedule link shown on the confirm appointment page will be sent over email to the end user so that they can choose to reschedule later. The appointment link is encoded using JWT token.
#WIP: Modify time for public appointment edit based on available time slots - Thinking of showing a full calendar with available slots on the appointment date and the actual appointment in red. The user can click on appointment and select time from one of the free slots but the event duration will be same as that of the original appointment.
---
=> feat(appointment_scheduling): added public appointment edit page

apps/api/src/app/upwork/upwork.service.ts, apps/gauzy/src/app/@core/services/upwork-store.service.ts, apps/gauzy/src/app/pages/upwork/components/reports/reports.component.html, apps/gauzy/src/app/pages/upwork/components/reports/reports.component.ts, apps/gauzy/src/app/pages/upwork/upwork-routing.module.ts, apps/gauzy/src/app/pages/upwork/upwork.module.ts
=> feat: reports for upwork integration by employee

apps/gauzy/src/app/@shared/time-off/time-off-request-mutation/time-off-request-mutation.component.ts, apps/gauzy/src/app/pages/time-off/table-components/time-off-status.component.html, apps/gauzy/src/app/pages/time-off/table-components/time-off-status.component.ts, apps/gauzy/src/app/pages/time-off/time-off.component.ts, apps/gauzy/src/app/pages/time-off/time-off.module.ts
=> feat: delete confirmation and status badges added to time-off page

apps/api/src/app/invoice/invoice.entity.ts, apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html, apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts, apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.html, apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts, apps/gauzy/src/app/pages/invoices/invoice-email/invoice-email-mutation.component.ts, apps/gauzy/src/app/pages/invoices/invoice-send/invoice-send-mutation.component.ts, apps/gauzy/src/app/pages/invoices/invoice-view/inner-component/invoice-view-inner.component.ts, apps/gauzy/src/app/pages/invoices/invoices.component.html, apps/gauzy/src/app/pages/invoices/invoices.component.scss, apps/gauzy/src/app/pages/invoices/invoices.component.ts, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/invoice.model.ts
When adding/editing invoices the user can now choose to save and immediately send the invoice (either via email or the client in gauzy).
Invoices can now have one of multiple statuses. The status can be changed by the user manually.
When there are more than 5 invoice items (in the add/edit page) and more than 10 invoices (in the invoices page) they will be separated into pages.
Video: https://www.loom.com/share/c3547726270a40bd8e576e2e0fb305dc
=> feat: added save and send functinality

.deploy/desktop/Dockerfile, .deploy/desktop/Dockerfile.linux, .deploy/desktop/Dockerfile.win
=> Add Dockerfile for Windows and Linux builds

apps/api/src/app/upwork/upwork.service.ts
=> feat:#712 sync freelancer expense/income successfully in upwork integration

apps/api/src/app/expense/commands/handlers/expense.create.handler.ts, apps/api/src/app/expense/expense.entity.ts, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html, apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.ts, apps/gauzy/src/app/pages/expenses/expenses.component.ts, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/expense.model.ts
When creating an expense if the expense type is set to 'Billable to Client' the user can add a status to the expense.
If the expense type is different the status is set to 'Not Billable'.
Video: https://www.loom.com/share/75664ff84815454ca256c455c6c19ade
=> feat: added status to expenses

apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts, apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
This PR adds case for consideration of recurring availability for picking employees on booking appointment page. Also fixed an issue with public appointment page not considering time off feature correctly
---
=> feat(appointment_scheduling): finish pick employee based on availability

apps/gauzy/src/app/@core/services/store.service.ts, apps/gauzy/src/app/@theme/components/theme-settings/theme-settings.component.ts, apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.html, apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts, apps/gauzy/src/app/app.component.ts, apps/gauzy/src/app/pages/pages.component.ts
---
https://www.loom.com/share/53a2efb2aaf345ccbd41ca7f09ace65c
So this is an interesting issue, we were currently loading languages inside the theme-settings component which is the right sidebar as shown in the video. Until this was loaded other components were already loaded and so components with pipes i.e. ` XYZ | translate` was still working because it was re-rendering them but components that used function the this.getTranslate() on Init were failing.
This …
=> fix: #1581 load translation on app start

.github/workflows/desktop-app.yml
---
A `tag` should be automatically created/bumped when a commit is pushed/merged to `master` and `electron-builder` should be able to use this tag to publish the Desktop App artifacts to GitHub Releases.
=> Automate tagging when pushed to master

apps/api/src/app/core/seeds/SeedDataService.ts, apps/api/src/app/event-types/event-type.seed.ts, apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.ts, apps/gauzy/src/app/share/public-appointments/public-appointments.component.ts
This PR completes integration of Time off feature with Schedules page. So now, schedules page is all ready. Also, added default seed for event types such that if an employee does not have any event types then it will show the organization level event types
---
=> feat(appointment_scheduling): finish schedules & seed event types

.gitignore, apps/api/src/app/core/seeds/SeedDataService.ts
---
When we run `yarn seed` or `yarn seed:all` then all success queries are logged into a file. Failures through and exception so they. get logged on the console.
Console:
Log File `gauzy/ormlogs.log`:
This will have no effect on `yarn start:api` since in that case the connection is not created from SeedDataService.
=> feat: #1761 remove success logging from seed

Jenkinsfile
---
This fixes the issue because the commit sha of `Gauzy` does not exist in the context of `gauzy-pulumi` repo.
=> fix: change webhook to use master ref

apps/api/src/app/email/email.controller.ts, apps/api/src/app/email/email.entity.ts, apps/gauzy/src/app/@core/services/email.service.ts, apps/gauzy/src/app/pages/settings/email-history/email-history.component.html, apps/gauzy/src/app/pages/settings/email-history/email-history.component.scss, apps/gauzy/src/app/pages/settings/email-history/email-history.component.ts, apps/gauzy/src/assets/i18n/en.json, libs/models/src/lib/email.model.ts
The emails are now ordered chronologically.
The date of the email is now displayed below "To:".
The latest email is now selected by default.
After the filter is used and no emails are found "No emails sent" is displayed.
Added button "Archive".
When emails are archived they are no longer displayed.
Emails are now loaded in 10 at a time. To load more the user needs to scroll down the list.
Renamed "+ADD FILTER" button to "Filter"
Added "Email History" header.
Emails sent to employees and contacts have the avater of the employee/contact over them. Other emails have a default image over them.
The gauzy logo in the emails doesn't load because the src url is saved in the email content as {{host}}/assets/images/logos/logo_Gauzy.svg it should be /assets/images/logos/logo_Gauzy.svg but I'm not …
=> Feature:#2639-email-history-improvements

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html, apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts, apps/gauzy/src/assets/i18n/en.json, packages/contracts/src/organization.model.ts, packages/core/src/organization/organization.entity.ts
Added an input to the organization settings under the 'Accounting' section that lets the user set how many days after the invoice date the due date is set by default. If the input is left empty the default is 1 month after the invoice date.
=>  Freature/default-days-until-due

apps/gauzy/src/app/pages/settings/email-history/email-history.component.ts
---
Before([demo](https://demo.gauzy.co/#/pages/settings/email-history))
After
=> Fix/ Email content empty on email history page

apps/api/src/plugin-config.ts, packages/core/src/dev-config.ts
=> Fix/Option to run migrations in 1-transaction-per-migration mode

package.json, tsconfig.json, yarn.lock
---
autoprefixer: replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
=> Fix :: Deprecated build warnings ⚠

apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.html, apps/gauzy/src/app/@theme/components/gauzy-logo/gauzy-logo.component.scss, apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.html, apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.scss, apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.ts
---
We have to move "Download Apps" from menu at top to bottom menu.
**To**
Here is the final result:
Fix #4806
Cc @evereq
=> Fix :: move download apps icons from top to bottom menu

packages/desktop-libs/src/lib/desktop-timer.ts
---
For some reason in production, database can't cast float value to integer
=> fix: invalid input syntax for type integer

apps/gauzy/src/app/@theme/styles/gauzy/_gauzy-overrides.scss
Fixes #5195 
The color is selected dropdown item is now black
---
=> fix :: Color of selected item is black

packages/core/src/database/migrations/1668064327561-AlterOrganizationTable.ts
=> Fix :: Organization inactivity time limit default value migration

packages/common-angular/src/utils/shared-utils.ts, packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
---
https://www.loom.com/share/713ca6a3d1e74ad9bd1cc48c608ff461
=> Fix: show capture screen directly avoiding long wait for server response after saving timeslots.

packages/desktop-libs/src/lib/desktop-ipc.ts
---
This reverts partially commit 03d4a9836672028e113b6eb417bcb16c760cbaba.
`ipcMain extends EventEmitter`
https://nodejs.org/api/events.html#emitterremovealllistenerseventname
> It is bad practice to remove listeners added elsewhere in the code, particularly when the EventEmitter instance was created by some other component or module
=> Revert "fix: add more listerners to remove"

apps/gauzy/src/app/@shared/project-select/project/project.component.html, apps/gauzy/src/app/@shared/project-select/project/project.component.ts, apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.html, apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.ts, apps/gauzy/src/app/pages/teams/teams.component.html, apps/gauzy/src/app/pages/teams/teams.component.ts, apps/gauzy/src/app/pages/teams/teams.module.ts, apps/gauzy/src/assets/i18n/bg.json, apps/gauzy/src/assets/i18n/en.json, apps/gauzy/src/assets/i18n/es.json, apps/gauzy/src/assets/i18n/fr.json, apps/gauzy/src/assets/i18n/he.json, apps/gauzy/src/assets/i18n/ru.json, packages/contracts/src/organization-team.model.ts
---
https://github.com/ever-co/ever-gauzy/assets/23419372/834b0355-c677-498e-a518-843d71184177
=> Adding project while team create

apps/gauzy/src/app/@core/services/gauzy-ai/gauzy-ai.service.ts, packages/core/src/app.module.ts, packages/core/src/integration/gauzy-ai/integration-ai.module.ts, packages/core/src/integration/gauzy-ai/integration-ai.service.ts, packages/core/src/integration/hubstaff/hubstaff.module.ts, packages/core/src/integration/hubstaff/hubstaff.service.ts, packages/core/src/integration/integration.module.ts
=> Fix :: Integration Missing API (Hubstaff & AI)

packages/contracts/src/task.model.ts, packages/core/src/tasks/dto/get-task-by-id.dto.ts, packages/core/src/tasks/dto/index.ts, packages/core/src/tasks/task.controller.ts, packages/core/src/tasks/task.entity.ts, packages/core/src/tasks/task.service.ts
=> feat: #6932 Added Task By Id API with rootEpic field

apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.scss
=> (total, subtotal boxes) & (Save as Draft btn) in edit estimate aren't the same as the design

apps/gauzy/src/app/@core/auth/auth-strategy.service.ts, apps/gauzy/src/app/app.component.ts
---
---
Fix the issue: when logging out, the language set while the user is logged in is being reset to default (en-english) so the user will see the auth pages in english.
=> [Fix] language reset to default (en-english) on logout

apps/gauzy/src/app/app.component.ts
=> Translate date when language change

apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html, apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
---
**Before**
**After**
**Before**
**After**
=> [Fix] :: Manual Time Added Reason (Time Tracking)

apps/gauzy/src/app/auth/accept-invite/accept-invite-form/accept-invite-form.component.html
=> [fix] undefined passwords labels in accept invitation page

apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.scss
=> fix: screenshot item date label text transform

packages/core/src/auth/auth.controller.ts, packages/core/src/auth/auth.service.ts
=> [Fix] Email / Password Authentication

apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.html, apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.ts, apps/gauzy/src/app/pages/settings/file-storage/file-storage.module.ts, apps/gauzy/src/assets/i18n/en.json, packages/common/src/interfaces/IAwsConfig.ts, packages/common/src/interfaces/IDigitalOceanConfig.ts, packages/common/src/interfaces/IWasabiConfig.ts, packages/common/src/interfaces/index.ts, packages/config/src/environments/environment.prod.ts, packages/config/src/environments/environment.ts, packages/config/src/environments/ienvironment.ts, packages/contracts/src/file-provider.ts, packages/core/src/core/file-storage/providers/digitalocean-s3.provider.ts, packages/core/src/core/file-storage/providers/index.ts, packages/core/src/core/file-storage/providers/s3.provider.ts, packages/core/src/core/file-storage/providers/wasabi-s3.provider.ts, packages/core/src/database/migration-executor.ts, packages/core/src/database/migrations/1711564805530-AlterStorageProvider.ts, packages/core/src/tenant/tenant-setting/commands/handlers/tenant-setting.get.handler.ts, packages/core/src/tenant/tenant-setting/dto/aws-s3-provider-config.dto.ts, packages/core/src/tenant/tenant-setting/dto/cloudinary-provider-config.dto.ts, packages/core/src/tenant/tenant-setting/dto/create-tenant-setting.dto.ts, packages/core/src/tenant/tenant-setting/dto/digitalocean-s3.provider-config.dto.ts, packages/core/src/tenant/tenant-setting/dto/index.ts, packages/core/src/tenant/tenant-setting/dto/trim.decorator.ts, packages/core/src/tenant/tenant-setting/dto/wasabi-s3-provider-config.dto.ts, packages/core/src/tenant/tenant-setting/tenant-setting.controller.ts, packages/core/src/tenant/tenant-setting/tenant-setting.service.ts
=> [Feat] Support DigitalOcean Spaces Storage

packages/contracts/src/social-account.model.ts, packages/core/src/auth/auth.controller.ts, packages/core/src/auth/auth.service.ts, packages/core/src/auth/social-account/dto/social-login.dto.ts, packages/core/src/auth/social-account/social-account.module.ts, packages/core/src/auth/social-account/social-account.service.ts
* feat: ever teams social signup services
* fix: remove get user by emails methods and route
---
=> Ever teams social signup services (#7878)

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts, packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
=> [Fix] Activity Watch integration issue

packages/core/src/time-tracking/timer/timer.service.ts
=> [Fix] async-await handling in conflict deletion to ensure proper command execution

apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
=> [Enhancement] Align fields with header (Limit TODO && Add Tooltip)

packages/desktop-libs/src/lib/desktop-timer.ts
=> [Fix] Remove unecessary line

packages/desktop-libs/src/lib/desktop-tray.ts
=> [Fix] Remove unnecessary `createSettingsWindow` calls.

packages/contracts/src/base-entity.model.ts, packages/contracts/src/comment.model.ts, packages/contracts/src/mention.model.ts, packages/contracts/src/subscription.model.ts, packages/contracts/src/task.model.ts, packages/core/src/comment/comment.service.ts, packages/core/src/comment/dto/create-comment.dto.ts, packages/core/src/comment/dto/update-comment.dto.ts, packages/core/src/database/migrations/1732775571004-AtlerMentionTableAddParentEntityFields.ts, packages/core/src/mention/dto/index.ts, packages/core/src/mention/dto/mentioned-user-ids.dto.ts, packages/core/src/mention/mention.entity.ts, packages/core/src/mention/mention.module.ts, packages/core/src/mention/mention.service.ts, packages/core/src/subscription/subscription.service.ts, packages/core/src/tasks/commands/handlers/task-create.handler.ts, packages/core/src/tasks/dto/create-task.dto.ts, packages/core/src/tasks/task.service.ts
=> [Fix] Improve Mention and Subscription APIs

apps/gauzy/src/app/pages/employment-types/employment-types.component.ts, packages/ui-core/i18n/assets/i18n/ach.json, packages/ui-core/i18n/assets/i18n/ar.json, packages/ui-core/i18n/assets/i18n/bg.json, packages/ui-core/i18n/assets/i18n/de.json, packages/ui-core/i18n/assets/i18n/en.json, packages/ui-core/i18n/assets/i18n/es.json, packages/ui-core/i18n/assets/i18n/fr.json, packages/ui-core/i18n/assets/i18n/he.json, packages/ui-core/i18n/assets/i18n/it.json, packages/ui-core/i18n/assets/i18n/nl.json, packages/ui-core/i18n/assets/i18n/pl.json, packages/ui-core/i18n/assets/i18n/pt.json, packages/ui-core/i18n/assets/i18n/ru.json, packages/ui-core/i18n/assets/i18n/zh.json
=> [Fix] Users Can Add Duplicate Employment Types

apps/gauzy/src/app/pages/employees/employees.component.ts, packages/ui-core/i18n/assets/i18n/ach.json, packages/ui-core/i18n/assets/i18n/ar.json, packages/ui-core/i18n/assets/i18n/bg.json, packages/ui-core/i18n/assets/i18n/de.json, packages/ui-core/i18n/assets/i18n/en.json, packages/ui-core/i18n/assets/i18n/es.json, packages/ui-core/i18n/assets/i18n/fr.json, packages/ui-core/i18n/assets/i18n/he.json, packages/ui-core/i18n/assets/i18n/it.json, packages/ui-core/i18n/assets/i18n/nl.json, packages/ui-core/i18n/assets/i18n/pl.json, packages/ui-core/i18n/assets/i18n/pt.json, packages/ui-core/i18n/assets/i18n/ru.json, packages/ui-core/i18n/assets/i18n/zh.json, packages/ui-core/shared/src/lib/employee/employee-end-work-popup/employee-end-work.component.html, packages/ui-core/shared/src/lib/employee/employee-end-work-popup/employee-end-work.component.scss, packages/ui-core/shared/src/lib/employee/employee-end-work-popup/employee-end-work.component.ts
=>  [Fix] Work End Date Can Be Set Before Work Start Date

.vscode/settings.json
=> [Chore] Exclude `node_modules` from file explorer

packages/contracts/src/lib/organization-team.model.ts, packages/core/src/lib/database/migrations/1739602849367-AlterActivityLogEntityTable.ts, packages/core/src/lib/database/migrations/1739958417359-AlterVideoEntityTable.ts, packages/core/src/lib/database/migrations/1740034146994-AlterOrganizationTeamEntityTable.ts, packages/core/src/lib/organization-team/commands/handlers/organization-team.create.handler.ts, packages/core/src/lib/organization-team/organization-team.entity.ts, packages/core/src/lib/organization-team/organization-team.subscriber.ts
=> [Fix] Alter "OrganizationTeam" Entity Table

packages/config/src/lib/config/keycloak.ts
---
This PR aims to replace a bad comment in the Keycloak OAUTH configuration file.
Replaces Facebook by Keycloak.
=> [FIX] replace Facebook by Keycloak in keycloak OAUTH config file

packages/desktop-lib/src/lib/desktop-ipc.ts
Store the time slot ID in local storage when returning to a time slot.
Also destructure event arguments for clarity.
---
=> [Feat]: Persist time slot id

packages/plugins/videos-ui/src/lib/shared/ui/video-player/video-player.component.html
=> [Chore](video-player): Remove preload metadata attribute

.github/workflows/release-demo.yml, .github/workflows/release-prod.yml, .github/workflows/release-stage.yml
Ensure all commits trigger at least a patch release by setting custom release rules and default bump to patch in the CI workflows. This simplifies commit message requirements for triggering version bumps.
---
=> [CI] Configure release workflows to default to patch
