apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
packages/contracts/src/organization-projects.model.ts
packages/core/src/core/interceptors/transform.interceptor.ts
packages/core/src/organization-project/organization-project.entity.ts

Fix :: Tasks Selector & Entity

---

apps/gauzy/src/app/@core/services/tasks.service.ts
apps/gauzy/src/app/@shared/tasks/task-number/task-number-field.component.ts
packages/core/src/tasks/dto/index.ts
packages/core/src/tasks/dto/task-max-number-query.dto.ts
packages/core/src/tasks/task.controller.ts
packages/core/src/tasks/task.service.ts

Fix :: Task Max Number (API Route Validation)

---

packages/core/src/tasks/task.controller.ts
packages/core/src/tasks/task.service.ts

Fixed :: Task count API & fixed missing query

---

packages/core/src/tasks/task.service.ts

Fix :: Displayed both teams & own tasks timer task selector

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

feat: change api route for employee and teams merged tasks

---

apps/gauzy/src/app/@core/guards/permission.guard.ts
apps/gauzy/src/app/@core/services/auth.service.ts
apps/gauzy/src/app/@shared/tasks/task-select/task/task.component.ts
packages/core/src/auth/auth.controller.ts
packages/core/src/auth/auth.module.ts
packages/core/src/auth/auth.service.ts
packages/core/src/auth/dto/has-permissions-query.dto.ts
packages/core/src/auth/dto/index.ts

Fix :: Has Permissions (Missing API)

---

apps/gauzy/src/app/pages/dashboard/project-management/project-management-details/project-management-details.component.ts
apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.ts

Fix :: #5227 project management dashboard

---

apps/gauzy/src/app/@shared/contact-selector/contact-selector.component.ts
apps/gauzy/src/app/pages/contacts/invite-contact/invite-contact.component.ts

Fix :: Contacts Default Profile

---

apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.html
apps/gauzy/src/app/pages/dashboard/team/team.component.html
packages/core/src/time-tracking/time-log/time-log.service.ts

Fix :: Teams dashboard statistics

---

packages/core/src/core/crud/pagination-params.ts

---
@evereq We have removed default pagination params values, it will transformed value only when value exists in request.

Fix :: Removed default pagination params

---

packages/core/src/database/migrations/1674109138954-AlterEmailSentTable.ts
packages/core/src/email/email.entity.ts
packages/core/src/user/user.entity.ts

Fix :: Emails & Email Templates Cascading

---

packages/core/src/employee/commands/handlers/employee.create.handler.ts

Fix :: Missing employee profile link when registered as employee

---

.cspell.json
packages/common-angular/src/utils/shared-utils.ts
packages/core/src/core/seeds/seed-data.service.ts
packages/core/src/gauzy-cloud/gauzy-cloud.controller.ts

Fix :: Cspell Configuration

---

packages/core/src/auth/auth.service.ts
packages/core/src/candidate/commands/handlers/candidate.create.handler.ts
packages/core/src/employee/commands/handlers/employee.create.handler.ts
packages/core/src/invite/commands/handlers/invite.accept-candidate.handler.ts
packages/core/src/invite/commands/handlers/invite.accept-employee.handler.ts
packages/core/src/invite/commands/handlers/invite.accept-user.handler.ts

Fix :: Accept Invite

---

.cspell.json
apps/gauzy/src/app/@shared/table-components/status-view/status-view.component.html
packages/core/src/core/crud/crud.factory.ts
packages/core/src/core/crud/icrud.controller.ts
packages/core/src/tasks/priorities/priority.controller.ts
packages/core/src/tasks/sizes/size.controller.ts
packages/core/src/tasks/statuses/status.controller.ts

fix(documents): swagger API tags documentation

---

packages/core/src/database/migrations/1675186090641-AlterTaskStatusTable.ts

fix: [table migration] for task_status

---

.vscode/settings.json

Chore :: VSCode Settings

---

packages/core/src/tasks/commands/handlers/task-update.handler.ts
packages/core/src/tasks/task.entity.ts
packages/core/src/tasks/task.service.ts

Fix :: Update task number for same project

---

packages/desktop-ui-lib/src/lib/settings/settings.component.html
packages/desktop-ui-lib/src/lib/settings/settings.component.ts
packages/desktop-ui-lib/src/lib/tasks/tasks.component.html
packages/desktop-ui-lib/src/lib/tasks/tasks.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

---
https://www.loom.com/share/b8a08fbc9c1d4be7b889e9d69cd8e854

Fix/desktop timer UI/UX

---

packages/core/src/time-tracking/time-log/dto/query/time-log-query.dto.ts
packages/core/src/time-tracking/time-log/time-log.controller.ts
packages/core/src/time-tracking/time-slot/time-slot.controller.ts

Fix :: Timelog force delete

---

apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.component.ts
apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.ts
apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts
packages/contracts/src/task.model.ts
packages/core/src/database/migrations/1675410785835-AlterTaskTable.ts
packages/core/src/tasks/dto/task.dto.ts
packages/core/src/tasks/task.entity.ts

Feat :: #5377 task table migration (priority & size)

---

packages/core/src/time-tracking/activity/commands/bulk-activities-save.command.ts
packages/core/src/time-tracking/activity/commands/handlers/bulk-activities-save.handler.ts
packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts

Fix :: Query Failed Error (Sentry)

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-tray.ts
packages/desktop-ui-lib/src/lib/image-viewer/image-viewer.component.html
packages/desktop-ui-lib/src/lib/image-viewer/image-viewer.component.ts
packages/desktop-ui-lib/src/lib/tasks/tasks.component.html
packages/desktop-ui-lib/src/lib/tasks/tasks.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix/ Timer detailled notification & undefined Id

---

packages/desktop-libs/src/lib/desktop-timer-activity.ts
packages/desktop-libs/src/lib/offline/databases/migrations/20230204175836_create-table-window-event.ts
packages/desktop-libs/src/lib/offline/databases/migrations/20230204175925_create-table-afk-events.ts

Refactor/ Queries with query builder && make tables migration

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-ui-lib/src/lib/login/login.component.scss
packages/desktop-ui-lib/src/lib/login/login.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix/ Activity Watch Integration & login UI/UX

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

Fix :: Improved get tags API

---

apps/gauzy/package.json
packages/common-angular/package.json
packages/common-angular/src/utils/shared-utils.ts
packages/core/package.json
yarn.lock

chore(deps): bump moment-timezone from 0.5.37 to 0.5.40

---

packages/core/src/tasks/priorities/default-global-priorities.ts
packages/core/src/tasks/sizes/default-global-sizes.ts
packages/core/src/tasks/statuses/default-global-statuses.ts

Updated Seeder

---

apps/gauzy/src/app/@core/services/crud/crud.service.ts
apps/gauzy/src/app/@core/services/crud/icrud.service.ts
apps/gauzy/src/app/@core/services/tags.service.ts
apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.ts
apps/gauzy/src/app/@shared/tags/tags-mutation.component.html
apps/gauzy/src/app/@shared/tags/tags-mutation.component.ts
apps/gauzy/src/app/pages/tags/tags.component.html
apps/gauzy/src/app/pages/tags/tags.component.ts
packages/contracts/src/tag-entity.model.ts
packages/core/src/core/crud/crud.service.ts
packages/core/src/core/crud/pagination-params.ts
packages/core/src/core/crud/tenant-aware-crud.service.ts
packages/core/src/tags/commands/handlers/tag.list.handler.ts
packages/core/src/tags/commands/tag.list.command.ts
packages/core/src/tags/dto/create-tag.dto.ts
packages/core/src/tags/dto/index.ts
packages/core/src/tags/dto/update-tag.dto.ts
packages/core/src/tags/tag.controller.ts
packages/core/src/tags/tag.entity.ts
packages/core/src/tags/tag.service.ts
packages/core/src/tasks/task.seed.ts

Fix :: #5672 Rest API Standard (Tag Controller)

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-timer.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix/  Increase accurate of timer on start/stop

---

packages/core/src/role-permission/default-role-permissions.ts

fix(permission): enabled task edit permission for employee default

---

apps/gauzy/package.json
apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.html
apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
yarn.lock

chore(deps): bump ngx-daterangepicker-material from ^5.0.2 to ^6.0.4

---

apps/gauzy/src/app/@shared/no-data-message/no-data-message.component.html
apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.html
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

Fix :: #5690 Time and activity empty message

---

angular.json

fix: bad script import

---

packages/desktop-libs/src/lib/offline/services/timer.service.ts

fix: random synced if user start timer in offline mode

---

apps/gauzy/src/app/pages/dashboard/team/all-team/all-team.component.html
apps/gauzy/src/app/pages/dashboard/team/all-team/all-team.component.scss
apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.html
apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.scss
apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.ts
apps/gauzy/src/app/pages/dashboard/team/team.component.html
apps/gauzy/src/app/pages/dashboard/team/team.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

---
https://www.loom.com/share/4d32a1893bcf4c97840b3befccd01485
`PR ✔️`
`Server ❌`

Fix/Teams page duration && add user's activity

---

apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.ts

fix(tags): missing promise for create tags

---

apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.scss
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.module.ts
apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.html
apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.scss
packages/desktop-libs/src/lib/desktop-timer.ts
packages/desktop-libs/src/lib/offline/databases/migrations/20230213140300_alter-table-timer.ts
packages/desktop-libs/src/lib/offline/databases/migrations/20230213140556_alter-table-intervals.ts
packages/desktop-libs/src/lib/offline/dto/interval.dto.ts
packages/desktop-libs/src/lib/offline/dto/timer.dto.ts
packages/desktop-libs/src/lib/offline/models/interval.model.ts
packages/desktop-libs/src/lib/offline/models/timer.model.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

Fix/ Time log app version

---

apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.scss
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.module.ts
apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.html
apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.scss
packages/desktop-libs/src/lib/desktop-timer.ts
packages/desktop-libs/src/lib/offline/databases/migrations/20230213083636_alter-table-timer.ts
packages/desktop-libs/src/lib/offline/databases/migrations/20230213140300_alter-table-timer.ts
packages/desktop-libs/src/lib/offline/databases/migrations/20230213140556_alter-table-intervals.ts
packages/desktop-libs/src/lib/offline/databases/provider-factory.ts
packages/desktop-libs/src/lib/offline/dto/interval.dto.ts
packages/desktop-libs/src/lib/offline/dto/timer.dto.ts
packages/desktop-libs/src/lib/offline/models/interval.model.ts
packages/desktop-libs/src/lib/offline/models/timer.model.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

Fix/ Duration column type limit

---

packages/contracts/src/organization-team-model.ts
packages/core/src/database/migrations/1676351186923-AlterOrganizationTeamTable.ts
packages/core/src/organization-team/dto/create-organization-team.dto.ts
packages/core/src/organization-team/dto/organization-team.dto.ts
packages/core/src/organization-team/organization-team.entity.ts
packages/core/src/organization-team/organization-team.service.ts
packages/core/src/organization-team/organization-team.subscriber.ts

Fix :: Profile Link / Team Type (Organization Team)

---

apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.html

Fix: Duplicated component

---

apps/gauzy/src/app/@core/services/organizations.service.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization.component.ts
apps/gauzy/src/app/share/organization/organization.component.ts
apps/gauzy/src/app/share/organization/public-organization.resolver.ts
apps/gauzy/src/app/share/public-appointments/appointment-form/appointment-form.component.ts
apps/gauzy/src/app/share/share-routing.module.ts
packages/core/src/public-share/organization/public-organization.controller.ts

Fix :: Added organization UUID for public page

---

packages/core/src/invite/commands/handlers/invite.accept-employee.handler.ts

Fix :: Accepted Employee Invite

---

packages/contracts/src/organization-team-employee-model.ts
packages/contracts/src/organization-team-model.ts
packages/core/src/custom-smtp/custom-smtp.controller.ts
packages/core/src/organization-team-employee/dto/delete-team-member-query.dto.ts
packages/core/src/organization-team-employee/organization-team-employee.controller.ts
packages/core/src/organization-team-employee/organization-team-employee.service.ts
packages/core/src/role-permission/default-role-permissions.ts

Fix :: #5693 Team manager can remove other manager

---

packages/core/src/organization-team/organization-team.service.ts

Fix :: #5693 Employee (As a manager) can update team basic details

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.html
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.html

fix: #5720 save as draft button disappears on hover

---

apps/gauzy/src/app/pages/invoices/table-components/invoice-paid.component.ts

---
[fix-paid-status.webm](https://user-images.githubusercontent.com/48500636/219307378-705c7b41-173a-4be0-a0fc-011ae4c69d9b.webm)

fix: #5721 paid status seen through header

---

packages/core/src/organization-team-employee/organization-team-employee.service.ts
packages/core/src/organization-team/organization-team.service.ts

Fix :: #5693 Multiple members created when employee unmake managers

---

packages/contracts/src/organization-team-employee-model.ts
packages/core/src/database/migrations/1676477607906-AddTimeTrackingColumnToOrganizationTeamEmployeeTable.ts
packages/core/src/organization-team-employee/dto/delete-team-member-query.dto.ts
packages/core/src/organization-team-employee/dto/index.ts
packages/core/src/organization-team-employee/dto/update-team-member.dto.ts
packages/core/src/organization-team-employee/organization-team-employee.controller.ts
packages/core/src/organization-team-employee/organization-team-employee.entity.ts
packages/core/src/organization-team-employee/organization-team-employee.service.ts

Fix :: Team Time Tracking Flag

---

packages/core/src/public-share/public-share.module.ts
packages/core/src/public-share/team/public-team.controller.ts
packages/core/src/public-share/team/public-team.module.ts
packages/core/src/public-share/team/public-team.service.ts
packages/core/src/public-share/team/queries/find-public-team.query.ts
packages/core/src/public-share/team/queries/handlers/find-public-organization.handler.ts
packages/core/src/public-share/team/queries/handlers/index.ts
packages/core/src/public-share/team/queries/index.ts

Feat :: #5735 Public team info API

---

packages/core/src/public-share/team/public-team.service.ts

Fix :: #5735 only get public team info

---

packages/contracts/src/organization-team-model.ts
packages/core/src/database/migrations/1676630369336-AddLogoToOrganizationTeamTable.ts
packages/core/src/organization-team/dto/create-organization-team.dto.ts
packages/core/src/organization-team/dto/organization-team.dto.ts
packages/core/src/organization-team/dto/update-organization-team.dto.ts
packages/core/src/organization-team/organization-team.entity.ts
packages/core/src/organization-team/organization-team.service.ts
packages/core/src/organization-team/organization-team.subscriber.ts

Feat :: #5741 Organization team logo

---

apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.ts
apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.module.ts
apps/gauzy/src/app/@shared/user/forms/fields/index.ts
apps/gauzy/src/app/@shared/user/forms/fields/phone/phone.component.html
apps/gauzy/src/app/@shared/user/forms/fields/phone/phone.component.ts
apps/gauzy/src/app/@shared/user/forms/fields/phone/phone.module.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
packages/contracts/src/user.model.ts

Fix :: #5741 User phone number field for Profile

---

apps/desktop-timer/src/index.ts
packages/desktop-ui-lib/src/lib/settings/settings.component.html
packages/desktop-ui-lib/src/lib/settings/settings.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/pipes/humanize.pipe.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.module.ts

Fix/ Desktop timer bugs

---

.cspell.json
packages/desktop-ui-lib/src/lib/time-tracker/pipes/humanize.pipe.ts

fix: mention the origin

---

apps/gauzy/src/app/@shared/timesheet/view-time-log-modal/view-time-log-modal.component.scss

fix: view time log modal position

---

packages/core/src/tasks/priorities/priority.service.ts
packages/core/src/tasks/sizes/size.service.ts
packages/core/src/tasks/statuses/status.service.ts

Icons Seed updated

---

.cspell.json
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
packages/contracts/src/timesheet-statistics.model.ts
packages/contracts/src/timesheet.model.ts
packages/core/src/time-tracking/statistic/dto/index.ts
packages/core/src/time-tracking/statistic/dto/time-tracking-statistic-query.dto.ts
packages/core/src/time-tracking/statistic/dto/today-date-range-query.dto.ts
packages/core/src/time-tracking/statistic/statistic.service.ts

Fixed :: Today Worked Duration 

---

packages/desktop-ui-lib/package.json
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

Fix: Query's parameters

---

apps/gauzy/src/app/pages/vendors/vendors.component.html
apps/gauzy/src/app/pages/vendors/vendors.component.scss
apps/gauzy/src/app/pages/vendors/vendors.component.ts
apps/gauzy/src/assets/i18n/en.json

---
[fix-vendors-header.webm](https://user-images.githubusercontent.com/48500636/219532791-5424b040-5d9b-4311-be9d-e029a60188e0.webm)

fix: #5703 no header title on vendors

---

packages/contracts/src/user.model.ts
packages/core/src/user/user.entity.ts
packages/core/src/user/user.subscriber.ts

Fix :: User Email Verified 

---

packages/contracts/src/timesheet-statistics.model.ts
packages/core/src/time-tracking/statistic/statistic.service.ts

fix: today duration for member block (time tracking dashboard)

---

apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts

fix: #5731 placeholder text cutoff

---

.cspell.json
packages/common/src/interfaces/IAppIntegrationConfig.ts
packages/core/src/auth/auth.controller.ts
packages/core/src/auth/auth.service.ts
packages/core/src/auth/commands/handlers/send-auth-code.handler.ts
packages/core/src/auth/commands/send-auth-code.command.ts
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/bg/html.mjml
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/bg/subject.hbs
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/en/html.mjml
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/en/subject.hbs
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/he/html.mjml
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/he/subject.hbs
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/ru/html.mjml
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/ru/subject.hbs
packages/core/src/email-template/queries/handlers/email-template.generate-preview.handler.ts
packages/core/src/email/email.service.ts

Fix :: Third party app integration for (Password Less Authentication)

---

apps/gauzy/src/app/@shared/currency/currency.component.html
apps/gauzy/src/app/@shared/currency/currency.component.scss
apps/gauzy/src/app/@shared/currency/currency.component.ts

---
[fix-currency-dropdown.webm](https://user-images.githubusercontent.com/48500636/221102579-a2ef660e-c8ba-41d1-a3f2-d2a24c9d6195.webm)

fix: #5730 currency dropdown cutoff

---

packages/contracts/src/role-permission.model.ts
packages/core/src/role-permission/default-role-permissions.ts
packages/core/src/user/commands/handlers/user.delete.handler.ts
packages/core/src/user/commands/user.delete.command.ts
packages/core/src/user/user.controller.ts
packages/core/src/user/user.service.ts

Fix :: #5741 Account will be deleted permanently

---

.cspell.json
apps/desktop-timer/src/index.ts
packages/desktop-libs/src/lib/contexts/database-provider-context.ts
packages/desktop-libs/src/lib/interfaces/i-client-server-provider.ts
packages/desktop-libs/src/lib/interfaces/i-server-less-provider.ts
packages/desktop-libs/src/lib/interfaces/index.ts
packages/desktop-libs/src/lib/offline/dao/interval.dao.ts
packages/desktop-libs/src/lib/offline/databases/mysql-provider.ts
packages/desktop-libs/src/lib/offline/databases/postgres-provider.ts
packages/desktop-libs/src/lib/offline/databases/provider-factory.ts
packages/desktop-libs/src/lib/offline/databases/sqlite-provider.ts
packages/desktop-ui-lib/src/lib/settings/settings.component.html
packages/desktop-ui-lib/src/lib/settings/settings.component.scss
packages/desktop-ui-lib/src/lib/settings/settings.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix/Database providers & bad offline mode image date

---

packages/core/src/database/migrations/1677313663312-AlterEmployeeTable.ts
packages/core/src/employee/employee.entity.ts
packages/core/src/time-tracking/time-log/time-log.entity.ts
packages/core/src/time-tracking/time-slot/time-slot.entity.ts
packages/core/src/time-tracking/timesheet/timesheet.entity.ts

Fix :: #5741 Account will be deleted permanently with (Time Tracking) records

---

packages/core/src/organization-team/organization-team.controller.ts
packages/core/src/organization-team/organization-team.service.ts
packages/core/src/user/user.service.ts

Fix :: #5741 user should be able to remove his/her account

---

packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/bg/html.mjml
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/en/html.mjml
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/he/html.mjml
packages/core/src/core/seeds/data/default-email-templates/password-less-authentication/ru/html.mjml
packages/core/src/email-template/queries/handlers/email-template.generate-preview.handler.ts
packages/core/src/email/email.service.ts

Fix :: Email templates render old variable

---

packages/core/src/public-share/team/dto/index.ts
packages/core/src/public-share/team/dto/public-team-query.dto.ts
packages/core/src/public-share/team/public-team.controller.ts
packages/core/src/public-share/team/public-team.module.ts
packages/core/src/public-share/team/public-team.service.ts
packages/core/src/public-share/team/queries/find-public-team.query.ts
packages/core/src/public-share/team/queries/handlers/find-public-team.handler.ts
packages/core/src/public-share/team/queries/handlers/index.ts
packages/core/src/shared/dto/date-range-query.dto.ts
packages/core/src/time-tracking/statistic/dto/time-tracking-statistic-query.dto.ts
packages/core/src/time-tracking/statistic/index.ts
packages/core/src/time-tracking/statistic/statistic.service.ts
packages/core/src/time-tracking/time-tracking.module.ts
packages/core/src/user/user.subscriber.ts

Fix :: #5741 Statistics Tasks (Public Team)

---

packages/core/src/public-share/team/dto/public-team-query.dto.ts
packages/core/src/public-share/team/public-team.controller.ts
packages/core/src/public-share/team/public-team.service.ts
packages/core/src/public-share/team/queries/handlers/find-public-team.handler.ts

Fix :: #5741 Allow to get some specific relations

---

packages/desktop-libs/src/lib/desktop-updater.ts

Fix: check update failure by notify the error to the renderer

---

packages/desktop-ui-lib/src/lib/settings/settings.component.ts

fix: default values for object appSetting

---

packages/desktop-libs/src/lib/desktop-store.ts

Fix: activity watch switch stored position

---

packages/core/src/public-share/team/dto/public-team-query.dto.ts

Fix :: #5741 Statistics tasks (public team) relations

---

apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
packages/core/src/time-tracking/activity/activity.service.ts
packages/core/src/time-tracking/time-log/commands/handlers/get-conflict-time-log.handler.ts
packages/core/src/time-tracking/time-log/commands/handlers/time-log-create.handler.ts
packages/core/src/time-tracking/time-log/commands/time-log-create.command.ts
packages/core/src/time-tracking/time-log/commands/time-log-update.command.ts
packages/core/src/time-tracking/timer/timer.service.ts
packages/core/src/time-tracking/timesheet/commands/timesheet-first-or-create.command.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix :: Time Tracking Start/Stop

---

packages/core/src/organization-team/organization-team.service.ts

Fix :: #5741 Removed Team Account

---

yarn.lock

chore/ generate lockfile

---

apps/desktop-timer/src/index.ts
packages/desktop-libs/src/lib/contexts/update-context.ts
packages/desktop-libs/src/lib/decorators/abstracts/base-cdn-decorator.ts
packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-menu.ts
packages/desktop-libs/src/lib/desktop-tray.ts
packages/desktop-libs/src/lib/interfaces/i-desktop-update.ts
packages/desktop-ui-lib/src/lib/electron/services/electron/electron.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix/ Missing async await and remove setTimeout

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix: Offline mode false positive

---

packages/desktop-ui-lib/src/lib/time-tracker/organization-selector/organization-selector.component.html
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html

Fix: Typo error when user tries to edit the Desktop Timer App drop-downs

---

packages/core/src/custom-smtp/custom-smtp.entity.ts
packages/core/src/custom-smtp/custom-smtp.service.ts
packages/core/src/email/email.service.ts

Fix :: SMTP email configuration query

---

.deploy/api/Dockerfile
.deploy/webapp/Dockerfile
.github/workflows/desktop-app-prod.yml
.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-prod.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/server-prod.yml
.github/workflows/server-stage.yml

chore: let's try to update node to v18 and see :)

---

.deploy/api/Dockerfile
.deploy/webapp/Dockerfile

chore: let's try also to upgrade Python2 to Python3

---

packages/core/src/organization-team/queries/handlers/get-organization-team-statistic.handler.ts
packages/core/src/public-share/team/public-team.module.ts
packages/core/src/public-share/team/public-team.service.ts

fix: #5741 Added current Timer Status of Member

---

packages/core/src/email-reset/email-reset.module.ts
packages/core/src/email-reset/email-reset.service.ts
packages/core/src/email/email.service.ts

Added Email Record on Email Reset

---

packages/core/src/database/migrations/1678436030249-AlterOrganizationTeamTable.ts
packages/core/src/organization-team/organization-team.entity.ts

Fix :: Organization team default private

---

packages/core/src/time-tracking/screenshot/screenshot.controller.ts

Fix :: Jimp Bad Import

---

.cspell.json

Feat :: #5741 Join Public Team Request

---

apps/desktop-timer/package.json
apps/desktop-timer/src/package.json
apps/desktop/package.json
apps/desktop/src/package.json
apps/server/package.json
apps/server/src/package.json
package.json

chore: bring back ffi-napi

---

packages/core/src/email-reset/email-reset.controller.ts
packages/core/src/email-reset/email-reset.service.ts

fix: Send status OK even though email is exist

---

apps/desktop-timer/src/app/app.component.ts
packages/desktop-ui-lib/src/lib/settings/settings.component.ts

Fix/Login page translation && User persistence

---

packages/core/src/auth/auth.service.ts
packages/core/src/invite/commands/handlers/invite.accept-candidate.handler.ts
packages/core/src/invite/commands/handlers/invite.accept-employee.handler.ts
packages/core/src/invite/commands/handlers/invite.accept-organization-contact.handler.ts
packages/core/src/invite/commands/handlers/invite.accept-user.handler.ts

Fix :: Auto email verification after accept invitation

---

packages/desktop-ui-lib/src/lib/tasks/tasks.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

---
https://www.loom.com/share/b9ade7de52a7456aa562249b6c31ec05

Fix/ Add task even timer running

---

apps/desktop-timer/src/app/app.component.ts

fix: UntilDestroy decorator

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-ui-lib/src/lib/settings/settings.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix: Undefined apiHost on get user

---

packages/desktop-ui-lib/src/lib/settings/settings.component.html

fix: change button text, Restart App to Save & Restart

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Feat/ Weekly Limit

---

packages/core/src/core/seeds/data/default-email-templates/organization-team-join-request/bg/html.mjml
packages/core/src/core/seeds/data/default-email-templates/organization-team-join-request/bg/subject.hbs
packages/core/src/core/seeds/data/default-email-templates/organization-team-join-request/en/html.mjml
packages/core/src/core/seeds/data/default-email-templates/organization-team-join-request/en/subject.hbs
packages/core/src/core/seeds/data/default-email-templates/organization-team-join-request/he/html.mjml
packages/core/src/core/seeds/data/default-email-templates/organization-team-join-request/he/subject.hbs
packages/core/src/core/seeds/data/default-email-templates/organization-team-join-request/ru/html.mjml
packages/core/src/core/seeds/data/default-email-templates/organization-team-join-request/ru/subject.hbs
packages/core/src/email/email.service.ts
packages/core/src/organization-team-join-request/organization-team-join-request.service.ts

Fix :: #5741 Organization team join request email templates

---

apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
packages/contracts/src/email-template.model.ts

fix: email templates missing enum

---

packages/desktop-ui-lib/src/lib/settings/settings.component.ts

fix: pre-check if a member variable is present for setting

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

---
https://www.loom.com/share/adcf6365306d4012ab0f6e5eb1e513c3

Feat: Show tooltip on ActivityWatch switch

---

packages/core/src/database/migrations/1678876700413-EmailTemplateReader.ts
packages/core/src/email-template/email-template-reader.service.ts
packages/core/src/email-template/queries/handlers/email-template.find.handler.ts
packages/core/src/email-template/utils.ts

Fix :: Migrate Pending Email Templates 

---

.cspell.json
.env.compose
.env.docker
.env.local
.env.sample
apps/gauzy/src/app/@shared/selectors/file-provider/file-provider.component.ts
apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.html
apps/gauzy/src/assets/i18n/en.json
packages/common/src/interfaces/ICloudinaryConfig.ts
packages/config/src/environments/environment.prod.ts
packages/config/src/environments/environment.ts
packages/core/package.json
packages/core/src/core/file-storage/providers/cloudinary.provider.ts
packages/core/src/core/interceptors/lazy-file-interceptor.ts
packages/core/src/time-tracking/screenshot/screenshot.controller.ts
yarn.lock

Fix :: #5053 Cloudinary Provider Support (Time Tracking Screenshots)

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Refactor::Time tracker counter

---

packages/core/src/organization-team-join-request/commands/handlers/organization-team-join-request.create.handler.ts
packages/core/src/organization-team-join-request/organization-team-join-request.controller.ts
packages/core/src/organization-team-join-request/organization-team-join-request.service.ts

Fix :: Modify Team Join Request Public API

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-timer.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix: Start/ Stop flows

---

packages/contracts/src/organization-contact.model.ts
packages/contracts/src/organization-projects.model.ts
packages/core/src/organization-contact/commands/handlers/organization-contact-update.handler.ts
packages/core/src/organization-contact/dto/organization-contact.dto.ts
packages/core/src/organization-contact/organization-contact.entity.ts
packages/core/src/organization-contact/organization-contact.subscriber.ts
packages/core/src/organization-project/commands/handlers/organization-project.update.handler.ts
packages/core/src/organization-project/dto/organization-project.dto.ts
packages/core/src/organization-project/organization-project.controller.ts
packages/core/src/organization-project/organization-project.entity.ts
packages/core/src/organization-project/organization-project.subscriber.ts
packages/core/src/organization-team/organization-team.entity.ts
packages/core/src/organization-team/organization-team.subscriber.ts
packages/core/src/tenant/tenant.entity.ts
packages/core/src/tenant/tenant.subscriber.ts
packages/core/src/user/user.entity.ts
packages/core/src/user/user.subscriber.ts

Fix :: #5053 Image asset eager loading

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

---
https://www.loom.com/share/00642afba5a94f48bed41d37604af3d2

Fix: Desktop Timer app is taking a while to stop/start the timer

---

apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.html
apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.ts

Fix :: Reactive Form Validation (File Storage)

---

packages/desktop-libs/src/lib/desktop-screenshot.ts

fix: remove timeout from screenshot

---

packages/core/src/core/file-storage/providers/s3.provider.ts
packages/core/src/core/file-storage/providers/wasabi-s3.provider.ts

fix: if http found in url send as it is

---

README.md

docs: small changes

---

packages/core/src/database/migrations/1679676292810-AddImageAssetColumnToTheOrganizationTable.ts
packages/core/src/organization/dto/create-organization.dto.ts
packages/core/src/organization/organization.entity.ts

Fix :: #5053 Image asset for organization table

---

packages/contracts/src/product.model.ts
packages/core/src/core/entities/internal.ts
packages/core/src/core/entities/subscribers.ts
packages/core/src/database/migrations/1679724221071-AddImageAssetColumnToTheProductCategoryTable.ts
packages/core/src/product-category/dto/product-category.dto.ts
packages/core/src/product-category/product-category.controller.ts
packages/core/src/product-category/product-category.entity.ts
packages/core/src/product-category/product-category.subscriber.ts

Fix :: #5053 Image asset for product category table

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-timer.ts

fix: try/catch block and missing await on start timer

---

packages/desktop-libs/src/lib/desktop-os-inactivity-handler.ts
packages/desktop-libs/src/lib/desktop-updater.ts

fix: change then to async/await

---

packages/plugins/integration-ai/src/sdk/gauzy-ai-sdk.ts
packages/plugins/integration-ai/src/sdk/queries/query.graphql
packages/plugins/integration-ai/src/sdk/schema.graphql

chore: update Gauzy AI SDK

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

fix: missing try/catch block and visibility

---

apps/desktop-timer/src/index.ts

Fix/Remove SetTimeout

---

packages/core/src/organization-team/organization-team.subscriber.ts

fix: #6108 Updating profile-link on updation of Team Name

---

packages/contracts/src/timesheet.model.ts
packages/core/src/organization-team/dto/organization-team-statistic.dto.ts
packages/core/src/organization-team/organization-team.controller.ts
packages/core/src/organization-team/queries/handlers/get-organization-team-statistic.handler.ts
packages/core/src/public-share/team/dto/public-team-query.dto.ts
packages/core/src/public-share/team/public-team.service.ts
packages/core/src/public-share/team/queries/find-public-team.query.ts
packages/core/src/time-tracking/timer/timer.service.ts

Fix :: Public Team Statistic (Last Worked Task)

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

fix: activity watch ping response type

---

apps/desktop-timer/src/app/app.module.ts
apps/desktop-timer/src/app/interceptors/server-error.interceptor.ts
apps/desktop-timer/src/app/services/error-client.service.ts
apps/desktop-timer/src/app/services/error-handler.service.ts
apps/desktop-timer/src/app/services/error-server.service.ts
apps/desktop-timer/src/app/services/index.ts
apps/desktop-timer/src/app/services/native-notification.service.ts
apps/desktop-timer/src/app/services/notification.service.ts
apps/desktop-timer/src/app/services/toastr-notification.service.ts

Feat/ Errors handler

---

packages/desktop-ui-lib/src/lib/settings/settings.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

feat: notify on change setting

---

packages/core/package.json
yarn.lock

 chore(@gauzy/core): added image-size v^1.0.2

---

packages/core/src/database/migrations/1680108987586-AddIndexesColumnsToTheTimeSlotTable.ts
packages/core/src/time-tracking/activity/activity.entity.ts
packages/core/src/time-tracking/screenshot/screenshot.entity.ts
packages/core/src/time-tracking/time-slot/time-slot-minute.entity.ts
packages/core/src/time-tracking/time-slot/time-slot.entity.ts

Fix :: DB Indexes (TimeSlot) entity

---

packages/core/src/database/migrations/1680110810109-AddIndexesColumnsToTheScreenshotTable.ts
packages/core/src/time-tracking/screenshot/screenshot.entity.ts

Fix :: DB Indexes (Screenshot) entity 

---

packages/core/src/database/migrations/1680154573492-AddIndexesColumnsToTheActivityTable.ts
packages/core/src/time-tracking/activity/activity.entity.ts

Fix :: DB Indexes (Activity) entity

---

packages/core/src/database/migrations/1680172332764-AddIndexesColumnsToTheTimeLogTable.ts
packages/core/src/time-tracking/time-log/time-log.entity.ts

Fix :: DB Indexes (TimeLog) entity 

---

packages/desktop-ui-lib/src/lib/settings/settings.component.ts

fix: send event to updater on change enable's state

---

.cspell.json
apps/desktop-timer/src/index.ts
apps/desktop-timer/src/main.ts
apps/desktop/src/index.ts
apps/server/src/index.ts
packages/desktop-libs/src/lib/desktop-menu.ts
packages/desktop-libs/src/lib/desktop-tray.ts
packages/desktop-window/src/lib/desktop-window-about.ts
packages/desktop-window/src/lib/desktop-window-image-viewer.ts
packages/desktop-window/src/lib/desktop-window-server.ts
packages/desktop-window/src/lib/desktop-window-setting.ts
packages/desktop-window/src/lib/desktop-window-setup.ts
packages/desktop-window/src/lib/desktop-window-timer.ts
packages/desktop-window/src/lib/desktop-window-updater.ts
packages/desktop-window/src/lib/desktop-window.ts

Fix::Remote webContents disabled

---

apps/desktop-timer/src/main.ts
packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/offline/dao/interval.dao.ts
packages/desktop-libs/src/lib/offline/services/timer.service.ts
packages/desktop-ui-lib/src/lib/settings/settings.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix::Lock sync process

---

apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.html
apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.ts
packages/desktop-window/src/lib/desktop-window-server.ts

Fix :: Job Browse Page (Header Filter)

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
packages/core/src/employee-job/employee-job.controller.ts
packages/desktop-ui-lib/src/lib/services/employee-cache.service.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts

Fix :: Job Browser Employee Filter

---

apps/gauzy/src/app/pages/jobs/jobs.module.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
apps/gauzy/src/app/pages/jobs/table-components/index.ts
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.html
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.scss
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.ts

Fix :: Job Details Combine Columns (Title & Description)

---

.cspell.json
apps/gauzy/src/app/@core/utils/smart-table/server.data-source.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts

Fix :: Jobs filter by employee

---

apps/gauzy/src/app/@shared/components/header-title/header-title.component.html
apps/gauzy/src/app/@shared/components/header-title/header-title.component.ts

Fix :: Page header title based on permissions

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

Fix :: Job posts column visibility 

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

Fix :: Job posts search filters 

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

Fix :: Job posts filter by employee

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

fix: desktop timer bugs

---

apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.html
apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.ts
packages/core/src/employee-job-preset/dto/index.ts
packages/core/src/employee-job-preset/dto/job-preset-query.dto.ts
packages/core/src/employee-job-preset/job-preset.entity.ts
packages/core/src/employee-job-preset/job-preset.service.ts
packages/core/src/employee-job-preset/job-search-preset.controller.ts

Fix :: #6166 Reset critierions when I create new Preset

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-timer.ts
packages/desktop-ui-lib/src/lib/setup/setup.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix::Swap event Listener to handler on start/stop timer's flow

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.scss
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

Fix  :: #6166 Job search columns vertical align top

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.scss

Fix :: #6166 job search table border bottom

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
packages/contracts/src/employee-job.model.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts

Fix :: #6166 Jobs browse filter by date range

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

Fix :: #6166 Redraw smart table settings only when changed header selectors

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix: Missed Starting

---

packages/core/src/database/migrations/1680866279166-AddDocumentAssetColumnToTheOrganizationDocumentTable.ts

Fix :: DB migration 

---

packages/core/src/auth/auth.service.ts

Fix :: Active user can Login/Password Reset Request

---

apps/gauzy/src/app/@theme/components/user/user.component.html
apps/gauzy/src/app/@theme/components/user/user.component.scss
apps/gauzy/src/app/@theme/components/user/user.component.ts
packages/contracts/src/employee.model.ts
packages/core/src/database/migrations/1681132031905-AddEmployeeStatusColumnsToTheEmployeeTable.ts
packages/core/src/employee/dto/update-employee.dto.ts
packages/core/src/employee/employee.entity.ts
packages/core/src/time-tracking/timer/timer.service.ts

Fix :: User online/offline status

---

packages/core/src/image-asset/image-asset.controller.ts

Fix :: Generate thumbnail for media library

---

packages/core/src/invite/invite.service.ts

Fixed :: Invites can filters by options 

---

packages/core/src/auth/auth.service.ts
packages/core/src/auth/commands/handlers/auth.register.handler.ts
packages/core/src/user-organization/user-organization.services.ts

Fixed :: Add missing tenant to the user organization table

---

apps/server/src/main.ts

fix: bad sentry import for gauzy server

---

packages/core/src/organization-team/organization-team.entity.ts
packages/core/src/public-share/team/dto/public-team-query.dto.ts

Fix :: Task statuses, sizes and priorities for public team

---

packages/core/src/public-share/team/public-team.service.ts

Fix :: #6148 Last worked tasks for public team API

---

packages/desktop-ui-lib/package.json
yarn.lock

chore(deps): nebular auth package

---

packages/core/src/public-share/team/dto/public-team-query.dto.ts

Fix :: Task tags for public team

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.html
packages/contracts/src/employee-job.model.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts

Fix :: Applied job post search filters

---

apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.module.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

Fix :: Apply Job Page Improvements

---

apps/gauzy/src/app/pages/jobs/jobs.module.ts
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.scss
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.module.ts
apps/gauzy/src/app/pages/jobs/table-components/index.ts
apps/gauzy/src/app/pages/jobs/table-components/job-table-components.module.ts

Fix :: Job Post Modal Screen Split

---

packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts

Fix :: Time slots synced

---

packages/core/src/organization-team/queries/handlers/get-organization-team-statistic.handler.ts
packages/core/src/public-share/team/dto/public-team-query.dto.ts
packages/core/src/public-share/team/public-team.service.ts

Fix :: Public Team Timer Statistics 

---

packages/desktop-ui-lib/src/lib/setup/setup.component.ts

fix: server setup bug

---

packages/desktop-ui-lib/src/lib/services/error-handler.service.ts

fix: override the AW error message

---

packages/desktop-window/src/lib/desktop-splash-screen.ts

fix: linux icon path on splash screen

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
packages/contracts/src/employee-job.model.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts

feat: create job application in Gauzy AI

---

.deploy/k8s/k8s-manifest.demo.yaml
.deploy/k8s/k8s-manifest.prod.yaml
.deploy/k8s/k8s-manifest.stage.yaml

chore: switch docker images source to DO registry (instead of GitHub)

---

.deploy/k8s/k8s-manifest.prod.yaml

chore: add PM2 to k8s pods

---

.deploy/api/Dockerfile
.deploy/api/entrypoint.compose.sh
.deploy/api/entrypoint.prod.sh
apps/api/src/pm2bootstrap.ts
apps/gauzy/src/pm2bootstrap.ts

fix: pm2 related

---

.deploy/api/Dockerfile
.deploy/api/entrypoint.compose.sh
.deploy/api/entrypoint.prod.sh

chore: disable for now PM2

---

.deploy/k8s/k8s-manifest.prod.yaml

chore: it's time to use 3 replicas in k8s in production

---

apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select/proposal-template-select.component.ts
apps/gauzy/src/app/@theme/components/header/selectors/employee/employee.component.ts
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
packages/contracts/src/employee.model.ts
packages/core/src/employee/employee.service.ts
packages/plugins/integration-ai/package.json
packages/plugins/integration-ai/src/gauzy-ai.service.ts

Fix (Mutation) :: Job Application Created 

---

.deploy/k8s/k8s-manifest.prod.yaml
.deploy/k8s/k8s-manifest.stage.yaml

chore: increase more qty of replicas in k8s

---

apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts

Fix :: Job matched employee pre selected (Apply Manually)

---

apps/server/src/index.ts

fix: remplace text that depended on ckeditor version

---

apps/server/src/index.ts
packages/desktop-libs/src/lib/desktop-server.ts

feat: server kill child process on exit

---

packages/desktop-ui-lib/src/lib/setup/setup.component.ts

fix: server default ports

---

apps/gauzy/src/app/@core/services/job.service.ts
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.scss
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.module.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
packages/contracts/src/employee-job.model.ts
packages/core/package.json
packages/core/src/employee-job-preset/employee-job-preset.module.ts
packages/core/src/employee-job/employee-job.controller.ts
packages/core/src/employee-job/employee-job.module.ts
packages/core/src/employee-job/employee-job.service.ts
packages/core/src/employee/employee.module.ts
packages/plugins/integration-ai/package.json
packages/plugins/integration-ai/src/config/gauzy-ai.ts
packages/plugins/integration-ai/src/gauzy-ai.module.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts
packages/plugins/integration-ai/src/index.ts
yarn.lock

Fixed :: Generate Proposal Automatically (Gauzy AI)

---

packages/core/src/organization-team-employee/organization-team-employee.service.ts

Fix :: Employee can quite team after accept invitation

---

apps/gauzy/src/app/@theme/components/header/header.component.ts
packages/core/src/time-tracking/timer/dto/timer-status-query.dto.ts
packages/core/src/time-tracking/timer/timer.controller.ts
packages/core/src/time-tracking/timer/timer.service.ts

Fix :: Timer Running Status (Admin can view)

---

packages/contracts/src/organization-team.model.ts
packages/core/src/database/migrations/1686195290990-AlterOrganizationTeamTable.ts
packages/core/src/organization-team/dto/organization-team.dto.ts
packages/core/src/organization-team/organization-team.entity.ts

Added color, emoji, team size in organization_team table

---

apps/gauzy/src/app/@shared/workspaces/workspaces.component.html

Fix: Hide more workspace button

---

apps/gauzy/src/app/@shared/card-grid/card-grid.component.html
apps/gauzy/src/app/@shared/card-grid/card-grid.component.ts
apps/gauzy/src/app/@shared/table-components/project-organization-grid/project-organization-grid.component.html
apps/gauzy/src/app/@shared/table-components/project-organization-grid/project-organization-grid.component.ts
apps/gauzy/src/app/@shared/table-components/visibility/visibility.component.ts
apps/gauzy/src/app/pages/projects/projects.component.html
apps/gauzy/src/app/pages/projects/projects.component.ts

---
👀 [demo](https://www.loom.com/share/7f6360f3c2e343448c4645ff5eadd3bf?sid=46eacaef-48e5-4171-acf8-b280b63db34b)

Fix/Project Visibility Switch

---

apps/gauzy/src/app/@shared/table-components/visibility/visibility.component.html
apps/gauzy/src/app/@shared/table-components/visibility/visibility.component.ts
apps/gauzy/src/app/pages/projects/projects.component.ts

---
https://www.loom.com/share/5ede44de180b41ebbffa1806479ce21e?sid=43b03880-2ca8-425f-92d3-8aebd4ce00d1

fix: project page refresh on visibility change

---

apps/gauzy/src/app/@core/services/tasks/priorities.service.ts
apps/gauzy/src/app/@core/services/tasks/sizes.service.ts
apps/gauzy/src/app/@core/services/tasks/statuses.service.ts

fix: missing provider service for project management

---

apps/desktop-timer/src/index.ts

fix: test the new value before assignment

---

apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.ts

Fix: Add missing async/await and handle empty template result

---

apps/gauzy/src/app/pages/invoices/invoice-view/invoice-view.component.html
apps/gauzy/src/app/pages/invoices/invoice-view/invoice-view.component.ts

---
resolves #6377
https://www.loom.com/share/32106620a25e46b793af93eff2c5c384?sid=befc3fae-fa51-4b55-a14c-ead84a20eb10

Feat: Add print feature

---

packages/core/src/organization-team-join-request/organization-team-join-request.controller.ts
packages/core/src/organization-team-join-request/organization-team-join-request.module.ts
packages/core/src/organization-team-join-request/organization-team-join-request.service.ts

feat: #6378 Added Join Request Accept/Reject API

---

apps/gauzy/src/assets/i18n/en.json

fix: missing translation

---

apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts

Fix :: Apply spin loader on Cover Letter field only

---

apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.scss
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

Fix :: Apply job modal & await/async

---

.cspell.json
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.scss
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

Fix :: #6395 Apply job modal improvements 

---

packages/desktop-ui-lib/src/lib/settings/settings.component.html
packages/desktop-ui-lib/src/lib/settings/settings.component.ts

---
resolves #6408
https://www.loom.com/share/ecfffcce88274b32aaebbdc3dd11f4cc?sid=7bbcf232-aaa7-4d2a-b270-580a8391b575

Feat: Disable notification

---

apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.scss
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
apps/gauzy/src/app/pages/jobs/table-components/job-status/job-status.component.html
apps/gauzy/src/app/pages/jobs/table-components/job-status/job-status.component.scss
apps/gauzy/src/app/pages/jobs/table-components/job-status/job-status.component.ts
apps/gauzy/src/app/pages/jobs/table-components/job-table-components.module.ts
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.html
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.scss

Fix :: #6419 Job Browse/Search improvement 

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

Feat :: #6420 Job applied CTA button for job search page

---

apps/gauzy/src/app/@shared/table-components/editors/number-editor.component.ts
apps/gauzy/src/app/@shared/table-components/table-components.module.ts
apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.html
apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.scss
apps/gauzy/src/app/pages/jobs/employees/employees/employees.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
packages/contracts/src/employee.model.ts
packages/core/src/employee/dto/rates.dto.ts

Fix :: #6423 Jobs -> Employees Rates

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
packages/contracts/src/employee-job.model.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts

Fix :: After applied jobs should disappear #6424

---

apps/gauzy/src/app/@theme/styles/_overrides.scss
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.scss
apps/gauzy/src/app/pages/jobs/search/search/search.component.scss
apps/gauzy/src/app/pages/jobs/table-components/job-status/job-status.component.scss
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.html
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.scss

Fix/#6421 Table selected/hover (Dark/Light)

---

apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.html
apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.scss

feat: hide status and notifications features

---

apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select/proposal-template-select.component.html
apps/gauzy/src/app/@shared/proposal-template-select/proposal-template-select/proposal-template-select.component.ts
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
apps/gauzy/src/app/pages/jobs/table-components/job-table-components.module.ts
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.html
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
packages/core/src/employee-proposal-template/employee-proposal-template.service.ts

Fix :: #6449 Job Browse Page Improvement

---

apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
packages/core/src/employee-job/employee-job.service.ts

fix: wordwrap disabled for html to text conversion

---

apps/gauzy/src/app/@theme/styles/includes/_ng-select.scss
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts

fix: default template content as proposal content

---

apps/gauzy/src/app/pages/jobs/search/search/search.component.html
apps/gauzy/src/app/pages/jobs/search/search/search.component.scss
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts

---
resolves #6474
https://www.loom.com/share/facc71c1ed8049088baf5d2554d5ff92?sid=2eafc9a6-8bf0-4631-9cde-6eaafa5c33fc

fix: refresh button on jobs page

---

packages/contracts/src/timesheet.model.ts
packages/core/src/time-tracking/time-log/time-log.entity.ts
packages/core/src/time-tracking/timer/dto/start-timer.dto.ts
packages/core/src/time-tracking/timer/dto/stop-timer.dto.ts
packages/core/src/time-tracking/timer/dto/timer-status-query.dto.ts
packages/core/src/time-tracking/timer/timer.service.ts

Fix :: Source optional for status & stop time API

---

apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.scss
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
apps/gauzy/src/app/pages/jobs/search/search/search.component.ts
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.html
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.scss
apps/gauzy/src/app/pages/jobs/table-components/job-title-description-details/job-title-description-details.component.ts

Fix :: #6449 Job Search Page UI Improvement

---

packages/core/src/tasks/commands/handlers/task-create.handler.ts
packages/core/src/tasks/commands/handlers/task-update.handler.ts

Fix :: Create Task After Register 

---

packages/contracts/src/task.model.ts
packages/core/src/database/migrations/1688966032457-AddRelatedIssueRelationToTaskTable.ts
packages/core/src/tasks/task.entity.ts

feat: #5782 Added Related Tasks support in Task API

---

apps/gauzy/src/app/@core/utils/smart-table/server-source.conf.ts
apps/gauzy/src/app/@core/utils/smart-table/server.data-source.ts
apps/gauzy/src/app/pages/contacts/contacts.component.ts
packages/contracts/src/organization-contact.model.ts
packages/core/src/organization-contact/commands/handlers/organization-contact-create.handler.ts
packages/core/src/organization-contact/organization-contact.entity.ts
packages/core/src/organization-contact/organization-contact.module.ts
packages/core/src/organization-contact/organization-contact.seed.ts
packages/core/src/organization-contact/organization-contact.service.ts

Fix :: Client Members Sync

---

packages/core/src/organization-contact/organization-contact.module.ts
packages/core/src/organization-project/commands/handlers/organization-project.create.handler.ts
packages/core/src/organization-project/organization-project.module.ts

Fix :: Project Members Sync 

---

packages/core/src/organization-contact/organization-contact.module.ts
packages/core/src/organization-project/commands/handlers/organization-project.create.handler.ts
packages/core/src/organization-project/organization-project.module.ts

Reverts ever-co/ever-gauzy#6511

Revert "Fix :: Project Members Sync "

---

packages/core/src/employee/employee.subscriber.ts

fix: replace conjunction or with and when create a slug

---

apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json
packages/core/src/organization-task-setting/dto/create-organization-task-setting.dto.ts
packages/core/src/organization-task-setting/dto/index.ts
packages/core/src/organization-task-setting/dto/organization-task-setting.dto.ts
packages/core/src/organization-task-setting/dto/update-organization-task-setting.dto.ts
packages/core/src/organization-task-setting/organization-task-setting.controller.ts

Create update DTO created for OrgTaskSetting

---

apps/gauzy/src/app/@shared/time-tracker/components/time-tracker-status/time-tracker-status.service.ts
apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.html
apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.ts
apps/gauzy/src/app/@theme/components/user/user.component.html
apps/gauzy/src/app/@theme/components/user/user.component.ts
apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.html
apps/gauzy/src/app/@theme/layouts/one-column/one-column.layout.ts

---
https://www.loom.com/share/b80a75bdd32e4d8ca9462e49631679bd?sid=8c7729e1-1626-4292-94bc-0efb01b3f06e

Fix/Time Tracker Online Status

---

apps/gauzy/src/assets/i18n/ru.json

fix: wrong russian translation (ru.json)

---

apps/gauzy/src/app/pages/contacts/contacts.component.ts

---
https://www.loom.com/share/19f83ad9d0de4529b87eb30575ab1297?sid=0531b702-a79e-4ed0-9c5d-dffd7b02e370

fix: missing async/await and make sequential api calls

---

apps/gauzy/src/app/@core/constants/app.constants.ts
packages/desktop-ui-lib/src/lib/constants/app.constants.ts

fix: background sync interval to 25sec

---

apps/gauzy/src/app/@shared/table-components/picture-name-tags/picture-name-tags.component.ts
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/users/users.component.ts

---
https://www.loom.com/share/0b6f50cf9b284183b90de4a9cfc635b6?sid=449a914e-df81-4051-9eb4-1632b4e700ec

Fix: Wrong redirection to user details

---

apps/gauzy/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.html
apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
apps/gauzy/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-networks/edit-employee-networks.component.html

fix: form auto complete attribute

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

---
https://www.loom.com/share/909d4779a0974677a45288871c29ad90?sid=83c75fac-be39-4624-9451-465db1d6b57c

feat: handle running remote desktop timer

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

fix: windows UI

---

apps/gauzy/src/app/@shared/time-tracker/components/time-tracker-status/time-tracker-status.service.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker-status/time-tracker-status.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

refactor: time tracker status and fix infinite pending asynchrous tasks

---

apps/desktop-timer/src/app/app.component.ts
apps/desktop-timer/src/app/app.service.ts
apps/gauzy/src/app/@shared/time-tracker/components/time-tracker-status/time-tracker-status.service.ts
apps/gauzy/src/app/@shared/time-tracker/time-tracker.service.ts
packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-store.ts
packages/desktop-ui-lib/src/lib/settings/settings.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/organization-selector/organization-selector.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/organization-selector/user-organization.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker-status/time-tracker-status.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

fix: get user detail flow using api interceptor.

---

.github/workflows/deploy-do-stage.yml

chore: switch to another k8s cluster (WIP)

---

.deploy/k8s/README.md
.github/workflows/deploy-do-prod.yml

chore: final switch to new cluster

---

.github/workflows/deploy-do-stage.yml

fix: try with DB fork cluster

---

.github/workflows/deploy-do-stage.yml

chore: change DB host again

---

packages/core/src/reports/report.controller.ts
packages/core/src/reports/report.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

fix: attempt to fix weird issues with reports

---

packages/plugins/integration-ai/src/config/gauzy-ai.ts
packages/plugins/integration-ai/src/gauzy-ai.module.ts

Fix :: Gauzy AI API integration Settings

---

packages/contracts/src/organization-team-employee-model.ts
packages/core/src/database/migrations/1690167501143-AddActiveTaskColumnToOrganizationTeamEmployee.ts
packages/core/src/organization-team-employee/organization-team-employee.entity.ts
packages/core/src/tasks/task.entity.ts

---
Task: https://github.com/ever-co/ever-gauzy/issues/6595

feat: #6595 Active Task field added in Organization Team Employee

---

packages/core/src/organization-team-employee/organization-team-employee.service.ts

fix: Handled null value for roleId/role.id

---

packages/plugins/knowledge-base/src/help-center-article/commands/handlers/help-center-article.update.handler.ts

fix(api): build issue for help center module

---

apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.component.html
apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.component.ts
apps/gauzy/src/app/@shared/tasks/add-task-dialog/add-task-dialog.module.ts
apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.html
apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts
apps/gauzy/src/app/pages/tasks/tasks.module.ts

Added Editor to Task Descrition

---

packages/plugins/integration-ai/src/sdk/gauzy-ai-sdk.ts
packages/plugins/integration-ai/src/sdk/schema.graphql

feat: for jobs / Gauzy AI integration add Upwork org name

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts

Fix :: Upwork Organization Settings Integration Validation 

---

.env.compose
.env.docker
.env.local
.env.sample
packages/plugins/integration-ai/src/config/gauzy-ai.ts
packages/plugins/integration-ai/src/gauzy-ai.module.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts

Fix :: Gauzy AI API integration Settings #35

---

packages/core/src/request-approval/request-approval.service.ts

Getting approval by currentUserId

---

packages/core/src/candidate/commands/handlers/candidate.hired.handler.ts
packages/core/src/time-tracking/timer/timer.service.ts

Fix :: Query relations default use join

---

packages/core/src/core/utils.ts
packages/core/src/time-tracking/timer/timer.service.ts

Fix :: Validate date range sent by desktop timer

---

apps/gauzy/src/app/@core/services/store.service.ts
apps/gauzy/src/app/@shared/pipes/datetime-format.pipe.ts
apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
packages/contracts/src/invoice.model.ts
packages/core/src/invoice/commands/handlers/invoice.create.handler.ts
packages/core/src/invoice/commands/handlers/invoice.update.handler.ts

Fix :: Missing Invoices In Payment (SQLite)

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/offline/dao/timer.dao.ts
packages/desktop-libs/src/lib/offline/services/timer.service.ts
packages/desktop-ui-lib/src/lib/login/login.component.html
packages/desktop-ui-lib/src/lib/offline-sync/concretes/index.ts
packages/desktop-ui-lib/src/lib/offline-sync/concretes/interrupted-sequence-queue.ts
packages/desktop-ui-lib/src/lib/offline-sync/concretes/sequence-queue.ts
packages/desktop-ui-lib/src/lib/offline-sync/concretes/time-slot-queue.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

---
[demo](https://www.loom.com/share/2ba260c4b59449459303b04cc740c03d?sid=47cfdced-c5a1-49a7-8939-09293e9af7d2) 👀

Feat: Sync interrupted sequences

---

apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.html
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.scss

fix: apply manual modal ui/ux

---

apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.html
apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.ts
apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.module.ts

6616 quick setting should also be closed clicked outside the dialog

---

apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.html
apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts

Fix :: #6645 Add/Edit project logo

---

apps/gauzy/src/app/@theme/components/header/header.component.html
apps/gauzy/src/app/@theme/components/header/header.component.ts
apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
apps/gauzy/src/app/app.component.ts

Date from URL Param complete

---

packages/desktop-ui-lib/src/lib/settings/settings.component.ts

fix: wrong merge (Duplicated lines) for settings windows

---

apps/gauzy/src/app/app.component.ts
apps/gauzy/src/app/pages/dashboard/dashboard.component.ts

Fix Tab Selection Functionality

---

.github/workflows/docker-build-publish-prod.yml
.github/workflows/docker-build-publish-stage.yml

chore: CW deployment

---

.deploy/k8s/k8s-manifest.cw.demo.yaml
.deploy/k8s/k8s-manifest.cw.prod.yaml
.deploy/k8s/k8s-manifest.cw.stage.yaml

* Added CPU affinity and resource limits
* Update k8s-manifest.cw.demo.yaml
* Update k8s-manifest.cw.stage.yaml
* Update k8s-manifest.cw.demo.yaml
* Update k8s-manifest.cw.prod.yaml
---------
---

Coreweave/12 aug (#6679)

---

apps/gauzy/src/app/pages/employees/activity/layout/layout.component.ts
apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.component.ts
apps/gauzy/src/app/pages/settings/custom-smtp/custom-smtp.component.ts
apps/gauzy/src/app/pages/settings/feature/feature.component.ts

Route Tab selection Fixes

---

apps/gauzy/src/app/@core/services/gauzy-ai/gauzy-ai.service.ts
apps/gauzy/src/app/@core/services/hubstaff.service.ts
apps/gauzy/src/app/@core/services/index.ts
apps/gauzy/src/app/@core/services/integrations.service.ts
apps/gauzy/src/app/@core/services/upwork.service.ts
apps/gauzy/src/app/pages/hubstaff/components/hubstaff-authorize/hubstaff-authorize.component.ts
apps/gauzy/src/app/pages/integrations/gauzy-ai/gauzy-ai-authorize/gauzy-ai-authorize.component.html
apps/gauzy/src/app/pages/integrations/gauzy-ai/gauzy-ai-authorize/gauzy-ai-authorize.component.ts
apps/gauzy/src/app/pages/integrations/gauzy-ai/gauzy-ai-routing.module.ts
apps/gauzy/src/app/pages/integrations/gauzy-ai/gauzy-ai.module.ts
apps/gauzy/src/app/pages/upwork/components/upwork-authorize/upwork-authorize.component.ts
packages/contracts/src/integration.model.ts
packages/core/src/app.module.ts
packages/core/src/hubstaff/hubstaff.service.ts
packages/core/src/integration-tenant/commands/handlers/integration-tenant.create.handler.ts
packages/core/src/integration-tenant/commands/integration-tenant.create.command.ts
packages/core/src/integration-tenant/dto/index.ts
packages/core/src/integration-tenant/dto/integration-remember-state-query.dto.ts
packages/core/src/integration-tenant/integration-tenant.controller.ts
packages/core/src/integration-tenant/integration-tenant.entity.ts
packages/core/src/integration-tenant/integration-tenant.seed.ts
packages/core/src/integration-tenant/integration-tenant.service.ts
packages/core/src/integration/gauzy-ai/integration-ai.controller.ts
packages/core/src/integration/gauzy-ai/integration-ai.module.ts
packages/core/src/integration/gauzy-ai/integration-ai.service.ts
packages/core/src/integration/integration.controller.ts
packages/core/src/integration/integration.service.ts

Fix :: Gauzy AI Integration Authorization Page

---

apps/gauzy/src/app/@shared/candidate/candidate-interview-mutation/candidate-interview-mutation.component.ts

Toastr message solved

---

packages/contracts/src/timesheet.model.ts

feat: Added TEAMS source for time tracking

---

packages/contracts/src/organization-contact.model.ts
packages/contracts/src/organization-projects.model.ts
packages/core/src/database/migrations/1692256031607-AddOrganizationProjectTeamRelation.ts
packages/core/src/organization-project/organization-project.entity.ts
packages/core/src/organization-team/organization-team.entity.ts

feat(migration): #6704 project & team [table] relation

---

apps/gauzy/package.json
yarn.lock

chore(deps-dev): bump html-to-text from 6.0.0 to 9.0.5

---

packages/contracts/src/custom-smtp.model.ts
packages/core/src/auth/auth.service.ts
packages/core/src/custom-smtp/commands/custom-smtp.create.command.ts
packages/core/src/custom-smtp/commands/custom-smtp.update.command.ts
packages/core/src/custom-smtp/commands/handlers/custom-smtp.create.handler.ts
packages/core/src/custom-smtp/commands/handlers/custom-smtp.update.handler.ts
packages/core/src/custom-smtp/custom-smtp.controller.ts
packages/core/src/custom-smtp/custom-smtp.entity.ts
packages/core/src/custom-smtp/dto/custom-smtp.query.dto.ts
packages/core/src/custom-smtp/dto/update-custom-smtp.dto.ts
packages/core/src/email/email.service.ts

Fix :: Improved Email Service & Custom SMTP 

---

packages/plugins/integration-jira/.dockerignore
packages/plugins/integration-jira/README.md
packages/plugins/integration-jira/jest.config.js
packages/plugins/integration-jira/package.json
packages/plugins/integration-jira/tsconfig.json
packages/plugins/integration-jira/tsconfig.lib.json
packages/plugins/integration-jira/tsconfig.spec.json
packages/plugins/integration-jira/tslint.json

feat(plugin): jira integration folder setup

---

packages/core/src/core/utils.ts
packages/core/src/invite/invite.service.ts

---
https://github.com/ever-co/ever-gauzy/issues/6772

fix: #6772 Added support of Multiple Team invitations

---

.cspell.json
apps/gauzy/src/app/@core/services/auth.service.ts
apps/gauzy/src/app/auth/auth-routing.module.ts
apps/gauzy/src/app/auth/signin-workspaces/components/multi-workspace/multi-workspace.component.html
apps/gauzy/src/app/auth/signin-workspaces/components/multi-workspace/multi-workspace.component.scss
apps/gauzy/src/app/auth/signin-workspaces/components/multi-workspace/multi-workspace.component.ts
apps/gauzy/src/app/auth/signin-workspaces/signin-workspaces-routing.module.ts
apps/gauzy/src/app/auth/signin-workspaces/signin-workspaces.component.ts
apps/gauzy/src/app/auth/signin-workspaces/signin-workspaces.module.ts
packages/contracts/src/role.model.ts
packages/contracts/src/user.model.ts
packages/core/src/auth/auth.controller.ts
packages/core/src/auth/auth.service.ts
packages/core/src/auth/commands/auth.login.command.ts
packages/core/src/auth/commands/handlers/auth.login.handler.ts
packages/core/src/employee/employee.entity.ts
packages/core/src/role/role.entity.ts
packages/core/src/user/dto/user-login.dto.ts
packages/core/src/user/user.entity.ts

WIP :: #5968 Multi Tenant Login 

---

apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.resolver.ts
apps/gauzy/src/app/app.component.ts

Fix :: #5476 Temporary Revert Changes

---

.circleci/config.yml

chore: more for circle

---

.circleci/config.yml
.cspell.json

chore: tiny :)

---

.cspell.json
.github/workflows/desktop-app-prod.yml
.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-prod.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/server-prod.yml
.github/workflows/server-stage.yml

* Update deploy-do-stage.yml
* chore: spell
* chore: let's try with Node 18 for Electron apps too
---------
---

Merge (#6784)

---

.github/workflows/desktop-app-prod.yml
.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-prod.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/server-prod.yml
.github/workflows/server-stage.yml

chore: pin npm to v9 for now before we upgrade all to node v18

---

apps/gauzy/src/app/pages/inventory/components/edit-inventory-item/product-form.component.ts

fix: #6758 added validation for product type and product category

---

packages/contracts/src/organization-team.model.ts
packages/core/src/organization-team/dto/organization-team.dto.ts
packages/core/src/organization-team/organization-team.service.ts

Added projects field for organization-team

---

packages/core/src/user/commands/handlers/user.delete.handler.ts
packages/core/src/user/user.controller.ts
packages/core/src/user/user.service.ts

Fix :: Not able to Delete Account #1303

---

packages/contracts/src/user.model.ts
packages/core/src/auth/auth.service.ts

Fix :: Return number of workspaces registered

---

packages/desktop-window/src/lib/concretes/default-window.ts
packages/desktop-window/src/lib/screen-capture-notification.ts

---
`Error: src/lib/screen-capture-notification.ts(4,28): error TS2307: Cannot find module '@gauzy/desktop-libs' or its corresponding type declarations.`

Fix/ Unhandle error

---

packages/desktop-ui-lib/src/lib/time-tracker/pipes/duration-format.pipe.ts
packages/desktop-ui-lib/src/lib/time-tracker/task-render/index.ts
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-duration/task-duration.component.html
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-duration/task-duration.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-estimate/task-estimate.component.html
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-estimate/task-estimate.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-progress/task-progress.component.html
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-progress/task-progress.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-progress/task-progress.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-render.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-render.module.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.module.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

Feat::New columns to tasks table

---

apps/desktop/src/index.ts
packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-tray.ts

---
resolves ever-co/ever-gauzy-desktop#4
resolves ever-co/ever-gauzy-desktop#5
resolves ever-co/ever-gauzy-desktop#6 
resolves ever-co/ever-gauzy-desktop#7 
resolves ever-co/ever-gauzy-desktop#8 
resolves ever-co/ever-gauzy-desktop#9 
resolves ever-co/ever-gauzy-desktop#10 
resolves ever-co/ever-gauzy-desktop#11 
resolves ever-co/ever-gauzy-desktop#12 
resolves ever-co/ever-gauzy-desktop#13 
resolves ever-co/ever-gauzy-desktop#14

fix: desktop automatic reports

---

.cspell.json
packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/offline/dao/timer.dao.ts
packages/desktop-libs/src/lib/offline/services/interval.service.ts
packages/desktop-libs/src/lib/offline/services/timer.service.ts
packages/desktop-ui-lib/src/lib/interceptors/timeout.interceptor.ts
packages/desktop-ui-lib/src/lib/offline-sync/concretes/sequence-queue.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

---
https://www.loom.com/share/d7a6492bd3d54452a1ade759cdc3a681?sid=26695efd-c554-4949-987a-db2a57fdb141

Fix: Desktop timer unpredictable behaviour on bad network/offline

---

apps/gauzy/src/app/pages/jobs/matching/matching/matching.component.ts
packages/core/src/employee/commands/handlers/update-employee-job-search-status.handler.ts
packages/core/src/integration/gauzy-ai/integration-ai.middleware.ts
packages/plugins/integration-ai/src/configuration.interface.ts
packages/plugins/integration-ai/src/gauzy-ai.module.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts
packages/plugins/integration-ai/src/request-config.provider.ts
packages/plugins/integration-ai/src/sdk/gauzy-ai-sdk.ts
packages/plugins/integration-ai/src/sdk/queries/query.graphql
packages/plugins/integration-ai/src/sdk/schema.graphql

Feat :: Gauzy AI Authentication By Bearer Token & Tenant

---

apps/gauzy/src/app/pages/reports/all-report/all-report/all-report.component.ts
packages/core/src/employee/commands/handlers/update-employee-job-search-status.handler.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts

Fix :: Exceptions errors handling (Gauzy AI)

---

packages/desktop-libs/src/lib/desktop-ipc.ts

---
resolves ever-co/ever-gauzy-desktop-timer#29

fix: concurrent database access (SQLITE_BUSY: database is locked)

---

packages/plugins/integration-github/package.json
yarn.lock

chore(deps): chore(deps): downgrade octokit from ^3.1.0 to 2.1.0

---

packages/core/src/tasks/linked-issue/dto/create-task-linked-issue.dto.ts
packages/core/src/tasks/linked-issue/dto/index.ts
packages/core/src/tasks/linked-issue/dto/update-task-linked-issue.dto.ts
packages/core/src/tasks/linked-issue/task-linked-issue.controller.ts

Fix :: Task linked issue for crud update action

---

apps/gauzy/src/app/@shared/team-select/team/team.component.html
apps/gauzy/src/app/@shared/team-select/team/team.component.ts
apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.html
apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
apps/gauzy/src/app/pages/projects/projects.component.html
apps/gauzy/src/app/pages/projects/projects.component.ts
apps/gauzy/src/app/pages/projects/projects.module.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/es.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

---
https://github.com/ever-co/ever-gauzy/assets/23419372/5143a443-e4ce-4097-be86-34c2ecd6ca60

#6870 adding team while project create

---

.env.compose
.env.docker
.env.local
.env.sample

chore(envs): added sample of envs

---

apps/desktop-timer/src/app/app.component.ts
apps/desktop-timer/src/index.ts
packages/desktop-ui-lib/src/lib/auth/auth.guard.ts
packages/desktop-ui-lib/src/lib/auth/no-auth.guard.ts
packages/desktop-ui-lib/src/lib/auth/services/auth-strategy.service.ts

Revert "Feat/improve startup flow"

---

apps/gauzy/src/app/@shared/tags/tags-color-input/tags-color-input.component.ts

Tags Bug Resolved

---

packages/core/src/database/migrations/1691493358068-AlterIntegrationTable.ts
packages/core/src/database/migrations/1691494801748-SeedIntegrationTable.ts
packages/core/src/database/migrations/1691756595248-AddUserIdColumnToUserTable.ts
packages/core/src/database/migrations/1692171665427-SeedIntegrationTable.ts
packages/core/src/database/migrations/1692256031607-AddOrganizationProjectTeamRelation.ts
packages/core/src/database/migrations/1692275997367-AlterIntegrationTableRelationCascading.ts
packages/core/src/database/migrations/1692433732267-AlterIntegrationTenantTable.ts
packages/core/src/database/migrations/1693547294428-AlterCodeToAlphaNumericFormat.ts
packages/core/src/database/migrations/1695023907817-AddColumnsToTheIntegrationTable.ts
packages/core/src/database/migrations/1695111838783-AddColumnsToTheIntegrationTypeTable.ts
packages/core/src/database/migrations/1695112275840-SeedIntegrationsAndIntegrationTypes.ts
packages/core/src/integration/utils.ts

fix(migration): SQLite, manually generate a UUID using uuidv4()

---

apps/gauzy/src/app/pages/integrations/github/components/installation/installation.component.ts
apps/gauzy/src/app/pages/integrations/github/components/view/view.component.ts
apps/gauzy/src/app/pages/integrations/github/components/wizard/wizard.component.ts

fix: #6823 github integration on success and error popup

---

packages/contracts/src/timesheet-statistics.model.ts
packages/core/src/time-tracking/statistic/statistic.service.ts

fix: ambiguous order by exception

---

packages/contracts/src/timesheet-statistics.model.ts
packages/contracts/src/timesheet.model.ts

Fix :: Desktop Build

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

fix: undefined tasks

---

packages/contracts/src/organization-projects.model.ts
packages/core/src/organization-project/organization-project.service.ts

Feat/Add organizationTeamId query parameter

---

apps/gauzy/src/app/@shared/project-select/project/project.component.html
apps/gauzy/src/app/@shared/team-select/team/team.component.html

---
`Description`
- Label and dropdown of Project and Teams Aligned
https://github.com/ever-co/ever-gauzy/assets/23419372/36c8cfc8-cb8d-4fac-9f07-a57bd57ee90e

FullWith Added to project and employee

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts

---
`Description`
- Form Control was getting error as property values were undefined.
https://github.com/ever-co/ever-gauzy/assets/23419372/0f82d93a-19f0-45c0-8a00-0ea70712d3cf

set null if property is not defined

---

apps/desktop-timer/src/index.ts
apps/desktop/src/app/app.component.ts
apps/desktop/src/index.ts
apps/server/src/index.ts
packages/desktop-libs/src/lib/decorators/concretes/dialog-error-handler.ts
packages/desktop-libs/src/lib/desktop-tray.ts

---
resolves #6889
https://www.loom.com/share/a4d8ac7134cd49d194220d6b37f93dac?sid=cac2af0e-0e9d-4b01-83de-774e7b184665

[ Fix ] desktop memory bloat

---

apps/desktop-timer/src/app/app.component.ts
packages/desktop-libs/src/lib/desktop-timer-activity.ts
packages/desktop-libs/src/lib/desktop-wakatime.ts
packages/desktop-libs/src/lib/offline/databases/sqlite-provider.ts

fix:  SQLite Busy - Locked

---

packages/desktop-libs/src/lib/desktop-timer.ts
packages/desktop-libs/src/lib/offline/databases/migrations/20231002152910_alter-table-timers.ts
packages/desktop-libs/src/lib/offline/databases/sqlite-provider.ts
packages/desktop-libs/src/lib/offline/dto/timer.dto.ts
packages/desktop-libs/src/lib/offline/models/timer.model.ts
packages/desktop-ui-lib/src/lib/time-tracker/task-render/task-badge-view/task-badge-view.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

Feat/Alter Table Timers

---

.scripts/configure.ts
.scripts/env.ts
apps/gauzy/src/app/pages/integrations/github/components/installation/installation.component.ts
apps/gauzy/src/app/pages/integrations/github/components/wizard/wizard.component.ts
apps/gauzy/src/environments/model.ts
packages/contracts/src/github.model.ts
packages/core/src/integration/github/dto/github-app-install.dto.ts
packages/core/src/integration/github/github-authorization.controller.ts
packages/core/src/integration/github/github.controller.ts
packages/core/src/integration/github/github.service.ts
packages/plugins/integration-github/src/octokit.service.ts

Fix :: #6823 GitHub App Integration (App Callback URL)

---

apps/gauzy/src/app/@shared/team-select/team/default-team.ts

---
`Description`
https://github.com/ever-co/ever-gauzy/assets/23419372/f6a97914-d9f6-441a-bdf1-11707913f65a
Default team was not getting selected - Fixed.

Fix for Team all Team selected

---

.deploy/k8s/k8s-manifest.civo.prod.yaml
.deploy/k8s/k8s-manifest.civo.stage.yaml
.github/workflows/deploy-civo-prod.yml
.github/workflows/deploy-civo-stage.yml
.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/server-stage.yml
.github/workflows/snyk-analysis.yml
.github/workflows/typos.yml

chore: deploy to CIVO

---

apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts

Bug/ Dashboard

---

packages/core/src/organization-team-employee/organization-team-employee.controller.ts

---
`Description`
Super Admin access weren't added thus fixed.

Fix Permission for SuperAdmin

---

packages/core/src/approval-policy/approval-policy.seed.ts
packages/core/src/core/seeds/seed-data.service.ts
packages/core/src/request-approval/request-approval.seed.ts

---
`Description`
Seeded fake data in the Approval Request page with Default Policy.
https://github.com/ever-co/ever-gauzy/assets/23419372/db3837aa-0bd3-43e3-a842-c5b99270a39a

Seeder for default approval req added

---

packages/core/src/time-tracking/statistic/statistic.service.ts

feat: add today duration attribute to task statistics

---

.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/release-apps-stage.yml
.github/workflows/server-stage.yml

chore: release apps

---

packages/core/src/time-tracking/statistic/statistic.service.ts

Bug: task statistics

---

apps/gauzy/src/app/@shared/integrations/github/repository-selector/repository-selector.component.ts
apps/gauzy/src/app/@shared/pipes/hash-number.pipe.ts
apps/gauzy/src/app/@theme/styles/_overrides.scss
apps/gauzy/src/app/pages/integrations/github/components/view/view.component.html
apps/gauzy/src/app/pages/integrations/github/components/view/view.component.ts
apps/gauzy/src/app/pages/integrations/github/github.module.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.scss
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
apps/gauzy/src/assets/i18n/en.json
packages/core/src/integration-map/commands/handlers/integration-map.sync-issue.handler.ts
packages/core/src/integration-map/commands/handlers/integration-map.sync-label.handler.ts
packages/core/src/integration-map/integration-map.module.ts
packages/core/src/integration/github/github-sync.service.ts
packages/core/src/tasks/commands/handlers/task-update.handler.ts
packages/core/src/tasks/task.service.ts

Fix :: #6975 GitHub Sync (Tasks/Labels)

---

packages/core/src/time-tracking/timer/timer.service.ts

fix: remove unnecessary log

---

packages/config/src/environments/environment.prod.ts
packages/config/src/environments/environment.ts

fix: decode GAUZY_GITHUB_APP_PRIVATE_KEY from env var

---

packages/core/src/database/migrations/1697263211513-AddedIntegrationSettingColumnsToTheOrganizationProjectTable.ts

fix: uncommented better sqlite migration

---

packages/core/src/bootstrap/index.ts

fix: process.send is not a function

---

apps/gauzy/src/app/pages/integrations/integrations-routing.module.ts
packages/contracts/src/github.model.ts
packages/core/src/integration-setting/commands/handlers/integration-setting.getMany.handler.ts
packages/core/src/integration/github/github-sync.service.ts
packages/core/src/integration/github/github.hooks.controller.ts
packages/core/src/integration/github/github.hooks.service.ts

Fix :: #6823 Github Webhook (Delete App Installation Event)

---

packages/core/src/integration-map/commands/handlers/integration-map.sync-issue.handler.ts
packages/core/src/integration-map/commands/integration-map.sync-issue.command.ts
packages/core/src/integration/github/github-sync.service.ts
packages/core/src/tasks/commands/handlers/task-create.handler.ts
packages/core/src/tasks/commands/handlers/task-update.handler.ts
packages/core/src/tasks/commands/task-create.command.ts
packages/core/src/tasks/commands/task-update.command.ts

Fix :: #6823 Disable the "2 Way Sync Triggered Event" for manual synchronization

---

apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.html
apps/gauzy/src/app/pages/dashboard/team/team.component.ts

---
**Keep the Focus on user Julia K.**
`Current ❌`
`PR ✔️`
> **Note**
> Each user will need to select a team in the tracker before starting work.

Fix/#6677 Team page

---

packages/core/src/time-tracking/statistic/statistic.service.ts

fix: Total Worked Task Details for members

---

packages/core/src/integration/github/commands/handlers/task.update-or-create.handler.ts
packages/core/src/integration/github/github-sync.service.ts
packages/core/src/integration/github/github.hooks.controller.ts

[Fix] #7000 Check issue created by user/bot (Github Integration)

---

packages/core/src/tasks/task.service.ts

Updated Project condition

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-timer.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix/#6606 Timer Accuracy

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts

fix unable to convert invalid date to date in add new (invoice, estimate)

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix: sending empty activities

---

packages/desktop-ui-lib/src/lib/settings/settings.component.scss

Fix: #7069 Warn message postion (RTL)

---

apps/gauzy/src/app/@core/services/github/github.service.ts
apps/gauzy/src/app/@shared/project/project-mutation/project-mutation.component.ts
apps/gauzy/src/app/@shared/table-components/github/auto-sync-switch/auto-sync-switch.component.html
apps/gauzy/src/app/pages/integrations/github/components/view/view.component.html
apps/gauzy/src/app/pages/integrations/github/components/view/view.component.ts
apps/gauzy/src/assets/i18n/en.json
packages/contracts/src/github.model.ts
packages/core/src/database/migrations/1698991349981-AlterIntegrationOrganizationGithubRepositoryTable.ts
packages/core/src/integration/github/commands/handlers/integration-sync-github-repository.handler.ts
packages/core/src/integration/github/commands/handlers/task.update-or-create.handler.ts
packages/core/src/integration/github/commands/integration-sync-github-repository.command.ts
packages/core/src/integration/github/github-sync.controller.ts
packages/core/src/integration/github/github-sync.service.ts
packages/core/src/integration/github/github.module.ts
packages/core/src/integration/github/repository/dto/index.ts
packages/core/src/integration/github/repository/dto/update-github-repository.dto.ts
packages/core/src/integration/github/repository/github-repository.controller.ts
packages/core/src/integration/github/repository/github-repository.entity.ts
packages/core/src/integration/github/repository/github-repository.service.ts
packages/core/src/integration/github/repository/issue/commands/handlers/integration-sync-github-repository-issue.handler.ts
packages/core/src/integration/github/repository/issue/commands/integration-sync-github-repository-issue.command.ts
packages/plugins/integration-github/src/octokit.service.ts

[Fix] Github Auto Sync (Synced Repository All Issues) 

---

apps/gauzy/src/app/@shared/integrations/github/repository-selector/repository-selector.component.html
apps/gauzy/src/app/@shared/integrations/github/repository-selector/repository-selector.component.scss
apps/gauzy/src/app/@shared/project-select/project/project.component.ts
apps/gauzy/src/app/pages/integrations/github/components/view/view.component.html
apps/gauzy/src/app/pages/integrations/github/components/view/view.component.ts

Fix :: #7000 Repository Selector Improvement

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix: ignored stop method callback

---

apps/gauzy/src/app/@shared/table-components/github/resync-button/resync-button.component.html
apps/gauzy/src/app/@shared/table-components/github/resync-button/resync-button.component.ts
apps/gauzy/src/app/pages/integrations/github/components/view/view.component.ts

[Fix] #7000 Resync Issues (Repository & Project)

---

apps/gauzy/src/app/pages/integrations/components/integration-list/list.component.ts
apps/gauzy/src/app/pages/integrations/github/components/view/view.component.ts
packages/core/src/integration-map/commands/handlers/integration-map.sync-issue.handler.ts
packages/core/src/integration-map/commands/handlers/integration-map.sync-label.handler.ts
packages/core/src/integration-map/commands/handlers/integration-map.sync-task.handler.ts
packages/core/src/integration-tenant/integration-tenant.service.ts
packages/core/src/integration/github/github-sync.service.ts
packages/core/src/organization-project/organization-project.entity.ts
packages/core/src/tags/commands/handlers/automation-label.sync.handler.ts
packages/core/src/tasks/commands/handlers/automation-task.sync.handler.ts

[Fix] #7000 Auto Sync Issues With Delay On Each Request

---

apps/gauzy/src/app/@shared/project/project-mutation/project-mutation.component.html
packages/core/src/expense/expense.entity.ts
packages/core/src/integration/github/repository/github-repository.entity.ts
packages/core/src/invoice-item/invoice-item.entity.ts
packages/core/src/organization-contact/organization-contact.entity.ts
packages/core/src/organization-project/organization-project.entity.ts
packages/core/src/organization-project/organization-project.seed.ts
packages/core/src/organization-sprint/organization-sprint.entity.ts
packages/core/src/payment/payment.entity.ts
packages/core/src/tags/tag.entity.ts
packages/core/src/tasks/priorities/priority.entity.ts
packages/core/src/tasks/related-issue-type/related-issue-type.entity.ts
packages/core/src/tasks/sizes/size.entity.ts
packages/core/src/tasks/statuses/status.entity.ts
packages/core/src/tasks/task.entity.ts
packages/core/src/tasks/versions/version.entity.ts
packages/core/src/time-tracking/activity/activity.entity.ts
packages/core/src/time-tracking/time-log/time-log.entity.ts

Fix :: Organization Project Wrong Relationship

---

.github/workflows/desktop-app-prod.yml
.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-prod.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/server-prod.yml
.github/workflows/server-stage.yml

chore: fixing builds and update to Node v18 for desktop apps

---

.github/workflows/desktop-app-prod.yml
.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-prod.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/server-prod.yml
.github/workflows/server-stage.yml

chore: switch back to Node v16, Electron Build issues with Node-gyp

---

apps/gauzy/src/app/@core/interceptors/tenant.interceptor.ts
apps/gauzy/src/app/@core/services/crud/crud.service.ts
apps/gauzy/src/app/pages/integrations/components/integration-list/list.component.ts
packages/core/src/integration-tenant/commands/handlers/index.ts
packages/core/src/integration-tenant/commands/handlers/integration-tenant.delete.handler.ts
packages/core/src/integration-tenant/commands/index.ts
packages/core/src/integration-tenant/commands/integration-tenant.delete.command.ts
packages/core/src/integration-tenant/integration-tenant.controller.ts
packages/core/src/integration/github/commands/github-installation.delete.command.ts
packages/core/src/integration/github/commands/handlers/github-installation.delete.handler.ts
packages/core/src/integration/github/commands/handlers/index.ts
packages/core/src/integration/github/commands/index.ts
packages/plugins/integration-github/src/octokit.service.ts

[Fix] #7105 GitHub Uninstall App Integration

---

apps/gauzy/src/app/@core/interceptors/tenant.interceptor.ts

[Fix] Tenant Interceptor

---

apps/gauzy/src/app/auth/login/login.component.html
apps/gauzy/src/app/auth/register/register.component.html

Fix :: Workspaces Found Page URL

---

apps/gauzy/src/app/auth/auth-routing.module.ts
apps/gauzy/src/app/auth/login/login.component.html
apps/gauzy/src/app/auth/register/register.component.html
apps/gauzy/src/app/auth/signin-workspaces/signin-workspaces-routing.module.ts

[Fix] Rename Login Workspace Auth Routing 

---

yarn.lock

[Chore] Update Yarn Lock

---

apps/gauzy/src/app/auth/forgot-password/forgot-password.component.html
packages/core/src/auth/auth.service.ts

---
---
- add directive noSpaceEdges to prevent email from having extra spaces.

[Fix] #7125 Forgot password form improvement

---

apps/gauzy/src/app/@core/auth/auth-strategy.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix/Logout Remote Timer

---

apps/gauzy/src/app/pages/pages.component.ts

fix: sidebar menu add icon based on permission

---

apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html

fix (pasword, repeatPassword) input labels

---

apps/gauzy/src/app/auth/auth-routing.module.ts

[Fix] Auth Guard Routing (Login Workspace)

---

apps/gauzy/src/app/pages/pages.component.ts

---
---
@rahul-rocket Please review it and let me know if I have to update or change some permissions!

fix sidebar menu add icon based on permission

---

apps/desktop-timer/src/app/app.component.ts
apps/desktop-timer/src/index.ts

---
https://github.com/ever-co/ever-gauzy/assets/45813955/755e3697-7f4a-4fbf-9b33-3b3dd0d4210b

Fix: Electron Google Oauth2

---

.env.compose
.env.docker
.env.local
.env.sample

chore(env): app configuration env

---

packages/desktop-libs/src/lib/desktop-timer.ts

fix: timer random screenshot

---

packages/auth/src/facebook/facebook.controller.ts
packages/auth/src/facebook/facebook.strategy.ts
packages/auth/src/github/github.strategy.ts
packages/auth/src/request-context.decorator.ts
packages/auth/src/twitter/twitter.strategy.ts
packages/config/src/config.module.ts
packages/config/src/config/facebook.ts

[Fix] #7151 Facebook Social Login #7159

---

packages/auth/src/google/google.strategy.ts
packages/common/src/interfaces/IFacebookConfig.ts
packages/common/src/interfaces/IGoogleConfig.ts
packages/config/src/config.module.ts
packages/config/src/config/facebook.ts
packages/config/src/config/google.ts
packages/config/src/environments/environment.prod.ts
packages/config/src/environments/environment.ts
packages/config/src/environments/ienvironment.ts

[Fix] #7151 Google Social Login

---

.cspell.json
.env.compose
.env.docker
.env.local
.env.sample
packages/auth/src/facebook/facebook.controller.ts
packages/auth/src/github/github.controller.ts
packages/auth/src/google/google.controller.ts
packages/auth/src/linkedin/linkedin.controller.ts
packages/auth/src/linkedin/linkedin.strategy.ts
packages/auth/src/twitter/twitter.controller.ts
packages/common/src/interfaces/ILinkedinIConfig.ts
packages/config/src/config.module.ts
packages/config/src/config/linkedin.ts
packages/config/src/environments/environment.prod.ts
packages/config/src/environments/environment.ts
packages/config/src/environments/ienvironment.ts

[Fix] #7151 LinkedIn Social Login

---

packages/auth/src/social-auth.module.ts

fix: missing social auth http module

---

.env.compose
.env.docker
.env.local
.env.sample
packages/auth/src/twitter/twitter.strategy.ts

chore: more sample env variables

---

packages/desktop-libs/package.json
packages/desktop-ui-lib/package.json
packages/desktop-window/package.json

fix: bad electron installation

---

.scripts/translation/translation-util.ts

fix: failed to download translation

---

apps/gauzy/src/app/auth/@shared/social-links/social-links.component.ts
packages/auth/package.json
packages/auth/src/github/github.controller.ts
packages/auth/src/github/github.strategy.ts
packages/common/src/interfaces/IGithubConfig.ts
packages/config/src/config/github.ts
yarn.lock

[Refactor] #7134 GitHub Social Login 

---

apps/gauzy/src/app/pages/candidates/candidates.component.ts

Fix: broken link

---

apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
apps/gauzy/src/app/pages/employees/timesheet/approvals/approvals/approvals.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
packages/contracts/src/timesheet.model.ts
packages/core/src/database/migrations/1701067699290-AddedEditedAtFeatureToTheTimesheetAndTimeLogTables.ts
packages/core/src/tasks/task.entity.ts
packages/core/src/time-tracking/time-log/dto/create-time-log.dto.ts
packages/core/src/time-tracking/time-log/dto/manual-time-log.dto.ts
packages/core/src/time-tracking/time-log/dto/update-time-log.dto.ts
packages/core/src/time-tracking/time-log/time-log.controller.ts
packages/core/src/time-tracking/time-log/time-log.entity.ts
packages/core/src/time-tracking/time-log/time-log.service.ts
packages/core/src/time-tracking/timesheet/timesheet.entity.ts

[Feat] Manually Edited Times

---

packages/config/src/config/facebook.ts
packages/config/src/config/github.ts
packages/config/src/config/google.ts
packages/config/src/config/linkedin.ts
packages/config/src/config/microsoft.ts
packages/config/src/config/twitter.ts

[Fix] Configs Types

---

yarn.lock

[Chore] Updated Yarn Lock

---

packages/core/src/bootstrap/tracer.ts

chore: more SigNoz

---

apps/gauzy/src/app/pages/invoices/invoices.component.scss

Fix placement formatting (cards, table) icons in Actions Container

---

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts
apps/gauzy/src/app/share/organization/organization.component.html

Fix edit public page that was redirecting to a 404 page due wrong params passed in the URL

---

apps/desktop-timer/src/package.json
apps/desktop/src/package.json
apps/server/src/package.json

Fix: could not locate bindings file

---

packages/core/src/time-tracking/timer/timer.service.ts

[Fix] Web Timer (Dates Comparison Format)

---

apps/gauzy/src/app/auth/login-workspace/login-workspace.component.html
apps/gauzy/src/app/auth/login/login.component.html
apps/gauzy/src/app/auth/register/register.component.html
apps/gauzy/src/assets/i18n/ar.json
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/de.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/es.json
apps/gauzy/src/assets/i18n/fr.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/it.json
apps/gauzy/src/assets/i18n/nl.json
apps/gauzy/src/assets/i18n/pl.json
apps/gauzy/src/assets/i18n/pt.json
apps/gauzy/src/assets/i18n/ru.json
apps/gauzy/src/assets/i18n/zh.json

Add Translation to auth pages

---

apps/gauzy/src/app/@theme/components/header/header.component.ts
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.scss

Fix date string overflow the bar on timesheets weekly tab

---

apps/desktop-timer/src/index.ts

fix: surround splashScreen with try/catch

---

apps/gauzy/src/app/@shared/gallery/gallery.component.html
apps/gauzy/src/app/@shared/gallery/gallery.component.ts
apps/gauzy/src/app/@shared/gallery/gallery.directive.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.module.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.module.ts

[Feat] #7246 Screenshot Analyze Description

---

packages/desktop-ui-lib/src/lib/tasks/tasks.component.scss

fix: #7261 scrolling bug

---

packages/core/src/core/utils.ts
packages/core/src/time-tracking/statistic/statistic.controller.ts
packages/core/src/time-tracking/statistic/statistic.service.ts

[Fix] Better Sqlite3 Query Failings

---

packages/desktop-ui-lib/src/lib/always-on/always-on.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

---
https://github.com/ever-co/ever-gauzy/assets/45813955/d8ee5643-d2a1-4c82-969a-2c17115bba75

Fix: #7263 inconsistent display of time worked in widget

---

apps/gauzy/src/app/@shared/gallery/gallery.component.html
apps/gauzy/src/app/@shared/gallery/gallery.component.scss
apps/gauzy/src/app/@shared/gallery/gallery.directive.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.scss
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.scss
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
packages/core/src/time-tracking/activity/activity.seed.ts
packages/core/src/time-tracking/screenshot/screenshot.seed.ts

[Feat] #7246 Screenshot Analysis Highlight 

---

apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.scss

Fix: info icon position

---

apps/gauzy/src/app/@shared/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts

---
--- 
https://github.com/ever-co/ever-gauzy/assets/78637183/1ae43488-1b24-4cf2-b089-440e9cf05639
https://github.com/ever-co/ever-gauzy/assets/78637183/b485f1c8-35b2-4f03-aaa7-8ddd89d48602

fix Period time value shows NaN as a value when we reset start/end time

---

apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
packages/core/src/employee/employee.subscriber.ts
packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-client.handler.ts
packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-date.handler.ts
packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-employee.handler.ts
packages/core/src/time-tracking/time-log/commands/handlers/get-time-log-group-by-project.handler.ts
packages/core/src/time-tracking/time-log/time-log.service.ts
packages/core/src/time-tracking/time-log/time-log.utils.ts

[Fix] #7245 Project Filtering in "Time and Activity" Report Grid

---

apps/gauzy/src/app/pages/integrations/gauzy-ai/components/view/view.component.html
apps/gauzy/src/app/pages/integrations/gauzy-ai/gauzy-ai.module.ts
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/ru.json

[Feat] #7280 Added Settings UI for "Gauzy AI" integration

---

apps/gauzy/src/app/@shared/gauzy-button-action/gauzy-button-action.component.html

[fix] button actions container have tiny background when no action found

---

apps/gauzy/src/app/@shared/gauzy-button-action/gauzy-button-action.component.html

Reverts ever-co/ever-gauzy#7284

Revert "[fix] button actions container have tiny background when no action found"

---

apps/gauzy/src/app/app.component.ts

[Fix] Dates should be displayed in specific region

---

apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.scss
apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.scss

fix RTL positioning of (add time) button on timesheets page

---

packages/contracts/src/tag.model.ts
packages/core/src/database/migrations/1702452723642-AlterTagEntityTable.ts
packages/core/src/tags/default-tags.ts
packages/core/src/tags/dto/create-tag.dto.ts
packages/core/src/tags/dto/update-tag.dto.ts
packages/core/src/tags/tag.entity.ts

Feat :: Enhancement Tag Table

---

packages/desktop-ui-lib/src/lib/services/index.ts
packages/desktop-ui-lib/src/lib/services/store.service.ts
packages/desktop-ui-lib/src/lib/services/tag-cache.service.ts
packages/desktop-ui-lib/src/lib/services/tag.service.ts
packages/desktop-ui-lib/src/lib/tasks/tasks.component.html
packages/desktop-ui-lib/src/lib/tasks/tasks.component.ts
packages/desktop-ui-lib/src/lib/tasks/tasks.module.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
packages/desktop-ui-lib/src/lib/utils/color-adapter.ts

Fix/#7257 Unable to create tags

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-ui-lib/src/lib/offline-sync/concretes/time-slot-queue.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix/#7259 Incorrect screenshots displayed

---

apps/gauzy/src/app/@core/services/payment.service.ts
apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.ts
apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.ts
apps/gauzy/src/app/@shared/timesheet/timesheet.service.ts
apps/gauzy/src/app/pages/reports/amounts-owed-report/amounts-owed-report/amounts-owed-report.component.ts
apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.ts
apps/gauzy/src/app/pages/reports/payment-report/payment-report/payment-report.component.ts
apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.ts
apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.ts
packages/contracts/src/payment.model.ts
packages/contracts/src/timesheet.model.ts
packages/core/src/payment/dto/query/payment-report-query.dto.ts
packages/core/src/payment/payment.controller.ts
packages/core/src/payment/payment.service.ts
packages/core/src/time-tracking/time-log/dto/query/time-log-limit-query.dto.ts
packages/core/src/time-tracking/time-log/dto/query/time-log-query.dto.ts
packages/core/src/time-tracking/time-log/time-log.controller.ts
packages/core/src/time-tracking/time-log/time-log.service.ts

[Fix] #7289 Time Limit / Client Budget Report

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

---
resolves #7291 
https://github.com/ever-co/ever-gauzy/assets/45813955/7f9d1889-e7d8-42f8-aec6-3a119ed57381

feat: #7291 Automatic status change to 'in progress' when starting timer

---

.github/workflows/deploy-civo-demo.yml
.github/workflows/deploy-civo-prod.yml
.github/workflows/deploy-civo-stage.yml
.github/workflows/deploy-cw-demo.yml
.github/workflows/deploy-cw-prod.yml
.github/workflows/deploy-cw-stage.yml
.github/workflows/deploy-do-demo.yml
.github/workflows/deploy-do-prod.yml
.github/workflows/deploy-do-stage.yml

chore: pass DB_NAME

---

.deploy/k8s/k8s-manifest.prod.yaml

Adjusted production resources for Digital Ocean based on the discussion with @evereq 
---

Adjusted resources for prod env in DO

---

apps/api/src/plugin-config.ts
packages/core/src/bootstrap/bootstrap.module.ts
packages/core/src/bootstrap/index.ts
packages/core/src/bootstrap/tracer.ts

fix: env vars usage

---

apps/api/src/plugin-config.ts
packages/config/src/database.ts
packages/core/src/database/migrations/1674044473393-SeedDefaultGlobalTaskStatus.ts
packages/core/src/database/migrations/1702757210999-AlterTableStatus.ts
packages/core/src/database/migrations/1703485836649-AlterTaskStatusEntityTable.ts
packages/core/src/dev-config.ts
packages/core/src/organization-task-setting/organization-task-setting.service.ts
packages/core/src/tasks/statuses/status.entity.ts
packages/core/src/tasks/statuses/status.service.ts

[Fix] DB Migrations (Task Status Entity Table)

---

packages/desktop-libs/src/lib/decorators/concretes/power-manager-detect-inactivity.ts
packages/desktop-libs/src/lib/desktop-os-inactivity-handler.ts
packages/desktop-libs/src/lib/offline/dao/interval.dao.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix/  Idle time logic

---

packages/core/src/health/health.module.ts

fix: import module for DataSource

---

yarn.lock

chore(deps): updated yarn lock

---

apps/desktop-timer/package.json
apps/desktop-timer/src/package.json
apps/desktop/package.json
apps/desktop/src/package.json
apps/server/package.json
apps/server/src/package.json
yarn.lock

chore: fixes for @sentry/profiling-node

---

apps/server/src/index.ts
packages/desktop-libs/src/lib/desktop-store.ts
packages/desktop-ui-lib/src/lib/server-dashboard/server-dashboard.component.ts
packages/desktop-ui-lib/src/lib/settings/settings.component.html
packages/desktop-ui-lib/src/lib/settings/settings.component.ts

Feat/#7387 Auto start server

---

apps/desktop-timer/config/custom-webpack.config.js
apps/desktop/config/custom-webpack.config.js
package.json
yarn.lock

---
`Fix this error`
`
[2023-12-27 20:51:31.623] [error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
at s.send (node:electron/js2c/browser_init:2:91758)
at _.send (node:electron/js2c/browser_init:2:78126)
at Timeout._onTimeout (C:\Program Files\Ever\Gauzy Desktop Timer\resources\app.asar\node_modules\@gauzy\desktop-libs\dist\lib\desktop-timer.js:119:47)
`

Fix/blank screen 

---

apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.html
apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.ts
apps/gauzy/src/app/pages/settings/file-storage/file-storage.module.ts

---
---
https://github.com/ever-co/ever-gauzy/assets/78637183/18f0463f-9a15-45bd-ae26-024aa38ceeae

add missing loading indicator in (file storage) page

---

apps/desktop-timer/src/index.ts
apps/desktop/src/index.ts
apps/server/src/index.ts

Fix: Sentry deprecated configureScope

---

apps/gauzy/src/app/@shared/card-grid/card-grid.component.scss
apps/gauzy/src/app/pages/tags/tags-color/tags-color.component.scss
apps/gauzy/src/app/pages/tags/tags.component.ts

fix: broken tag render

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Fix: #7429 Can't update status and estimate

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-timer.ts
packages/desktop-libs/src/lib/offline/dto/timer.dto.ts
packages/desktop-libs/src/lib/offline/models/timer.model.ts

Bug/#7428 Timer Error leading decrement

---

apps/desktop-timer/src/app/app.component.ts
apps/desktop/src/app/app.component.ts
packages/desktop-ui-lib/src/lib/integrations/activity-watch/index.ts
packages/desktop-ui-lib/src/lib/integrations/activity-watch/view/activity-watch.component.ts

Fix: Setup activities collection in a different window acting like an independent thread.

---

packages/desktop-libs/src/lib/desktop-os-inactivity-handler.ts

Fix: deleting time slots out of range.

---

packages/plugins/integration-ai/src/gauzy-ai.service.ts
packages/plugins/integration-ai/src/sdk/gauzy-ai-sdk.ts
packages/plugins/integration-ai/src/sdk/schema.graphql

Fix :: Jobs Search Filter By Tenant (Gauzy AI)

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

Feat: stop timer anyway on exit

---

packages/plugins/integration-ai/src/gauzy-ai.service.ts
packages/plugins/integration-ai/src/sdk/gauzy-ai-sdk.ts
packages/plugins/integration-ai/src/sdk/schema.graphql

[Fix] Integration AI (Graphql Query)

---

packages/core/src/integration/gauzy-ai/integration-ai.service.ts

[Fix] Gauzy AI Connection Refuse 

---

packages/core/src/bootstrap/index.ts
packages/core/src/core/context/request-context.ts
packages/core/src/time-tracking/screenshot/screenshot.controller.ts
packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts

[Fix] Screenshot Storage Provider Directory

---

apps/gauzy/src/app/@shared/pagination/pagination-v2/pagination-v2.component.html
apps/gauzy/src/app/@shared/pagination/pagination-v2/pagination-v2.component.scss
apps/gauzy/src/app/@shared/pagination/pagination-v2/pagination-v2.component.ts
apps/gauzy/src/app/@shared/pagination/pagination-v2/pagination-v2.module.ts

---
> [!NOTE] 
We already use this version of pagination in desktop timer app

perf: release v2 pagination

---

apps/gauzy/src/app/pages/income/income.component.html
apps/gauzy/src/app/pages/income/income.module.ts

---
[Demo](https://www.loom.com/share/44e5034307da4151a33d43acdc749545?sid=9ec925fa-a031-4ccf-9acb-f13d5fca9634) 👀
> [!IMPORTANT] 
@coderNadir Please inspire you of this PR to swap the current pagination with the V2 for all components

feat: swap current pagination with v2 pagination for income component

---

apps/gauzy/src/app/@shared/pagination/pagination-v2/pagination-v2.component.ts
apps/gauzy/src/app/@theme/styles/_overrides.scss
apps/gauzy/src/app/pages/income/income.component.html

Fix: V2 pagination selector prefix

---

apps/gauzy/src/app/pages/projects/projects-routing.module.ts

[Fix] Edit Project Routing Resolver

---

packages/core/src/time-tracking/activity/commands/handlers/bulk-activities-save.handler.ts
packages/core/src/time-tracking/statistic/statistic.helper.ts
packages/core/src/time-tracking/statistic/statistic.service.ts
packages/core/src/time-tracking/timer/timer.controller.ts
packages/core/src/time-tracking/timer/timer.service.ts

[Fix] SQLite does not support the CONCAT()

---

packages/core/src/tasks/task.seed.ts
packages/plugins/integration-github/src/probot.helpers.ts

[Fix] Database seeder for postgres & mysql

---

packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts
packages/core/src/time-tracking/time-slot/commands/handlers/time-slot-merge.handler.ts
packages/core/src/time-tracking/time-slot/utils.ts

[Fix] Time Tracking Start/Stop (API)

---

apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.html
packages/core/src/core/crud/pagination-params.ts
packages/core/src/core/crud/pagination.helper.ts
packages/core/src/employee/commands/get-employee-job-statistics.command.ts
packages/core/src/employee/commands/handlers/get-employee-job-statistics.handler.ts
packages/core/src/employee/employee.controller.ts
packages/core/src/employee/employee.service.ts

[Fix]  Escape Query Parameters for pagination

---

apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
packages/core/src/core/crud/pagination-params.ts
packages/core/src/core/crud/pagination.helper.ts
packages/core/src/tasks/task.service.ts

[Fix] Array Query Parameters Escape

---

packages/core/src/auth/auth.controller.ts
packages/core/src/auth/auth.service.ts
packages/core/src/auth/dto/two-factor-dto.ts

[Fix] Signin Workspace Teams

---

packages/desktop-libs/src/lib/offline/dao/interval.dao.ts
packages/desktop-libs/src/lib/offline/dao/timer.dao.ts
packages/desktop-libs/src/lib/offline/databases/migrations/20240203094747_alter-table-interval.ts
packages/desktop-libs/src/lib/offline/dto/interval.dto.ts
packages/desktop-libs/src/lib/offline/models/interval.model.ts
packages/desktop-libs/src/lib/offline/services/interval.service.ts
packages/desktop-libs/src/lib/offline/services/timer.service.ts
packages/desktop-libs/src/lib/offline/services/user.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

---
resolves https://github.com/ever-co/ever-gauzy-desktop-timer/issues/44
resolves https://github.com/ever-co/ever-gauzy-desktop-timer/issues/43
resolves https://github.com/ever-co/ever-gauzy-desktop-timer/issues/40
resolves https://github.com/ever-co/ever-gauzy-desktop-timer/issues/39
resolves https://github.com/ever-co/ever-gauzy-desktop-timer/issues/38
resolves https://github.com/ever-co/ever-gauzy-desktop-timer/issues/37
resolves https://github.com/ever-co/ever-gauzy-desktop-timer/issues/36
resolves https://github.com/ever-co/ever-gauzy-desktop-timer/issues/33
resolves https://github.com/ever-co/ever-gauzy-desktop-timer/issues/31
resolves …

[Fix] Ever-co/ever gauzy desktop#44 automatic report

---

apps/gauzy/src/app/pages/contacts/contacts.component.html

Hide invite client button for none permitted employees

---

packages/core/src/auth/auth.service.ts
packages/core/src/constants.ts

[Feat] Password Less Authentication (Demo Credentials)

---

apps/gauzy/src/app/pages/goals/goals.component.ts

---
---
---
@evereq @rahul-rocket  don't close the issue as I still need to use it for fixing the create/edit objectives

Fix filtering by myObjectives throws an error

---

apps/gauzy/src/app/@core/services/organization-teams.service.ts
apps/gauzy/src/app/@shared/team-select/team/team.component.ts
packages/core/src/core/seeds/seed-data.service.ts
packages/core/src/organization-team/default-organization-teams.ts
packages/core/src/user/user.seed.ts

[Fix] Added email verify automatically using seeder

---

apps/gauzy/src/app/pages/employees/schedules/availability-slots/availability-slots.component.html
packages/core/src/availability-slots/commands/handlers/availability-slots.create.handler.ts
packages/core/src/availability-slots/commands/handlers/get-conflict-availability-slots.handler.ts
packages/core/src/employee-appointment/commands/handlers/employee-appointment.create.handler.ts

Fix appointments schedules broken query

---

packages/config/src/environments/environment.prod.ts
packages/config/src/environments/environment.ts
packages/core/src/core/seeds/seeder.module.ts
packages/plugins/jitsu-analytics/src/jitsu-analytics.plugin.ts
packages/plugins/jitsu-analytics/src/jitsu-helper.ts

[Fix] Jitsu Analytics Plugin (Missing Provider)

---

apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.ts
packages/contracts/src/timesheet.model.ts
packages/core/src/time-tracking/time-log/dto/query/time-log-query.dto.ts
packages/core/src/time-tracking/time-log/time-log.service.ts

Fix Manual Time Edit filtering by actions (ADDED/EDITED)

---

packages/core/src/app.module.ts

[Fix] Moment Deprecated Locale Syntax

---

packages/core/src/invoice/invoice.service.ts
packages/core/src/invoice/pdfmaker.service.ts

Fix Invoice PDF generation failed

---

packages/config/src/database-helpers.ts
packages/config/src/database.ts

[Fix] #7556 DB SSL Mode

---

apps/api/src/plugin-config.ts
packages/common/package.json
packages/common/src/interfaces/IApplicationPluginConfig.ts
packages/config/package.json
packages/config/src/config.service.ts
packages/config/src/database.ts
packages/config/src/default-configuration.ts
packages/core/src/database/database.module.ts
packages/core/src/dev-config.ts
packages/core/src/tasks/issue-type/issue-type.service.ts
packages/core/src/tasks/priorities/priority.service.ts
packages/core/src/tasks/related-issue-type/related-issue-type.service.ts
packages/core/src/tasks/sizes/size.service.ts
packages/core/src/tasks/statuses/status.service.ts
packages/core/src/tasks/versions/version.service.ts

[Fix] Knex DB Connection

---

packages/core/src/tasks/issue-type/issue-type.service.ts
packages/core/src/tasks/priorities/priority.service.ts
packages/core/src/tasks/related-issue-type/related-issue-type.service.ts
packages/core/src/tasks/sizes/size.service.ts
packages/core/src/tasks/statuses/status.service.ts
packages/core/src/tasks/versions/version.service.ts

[Refactor]: Http Exception Filters

---

packages/core/src/tasks/issue-type/issue-type.service.ts
packages/core/src/tasks/priorities/priority.service.ts
packages/core/src/tasks/related-issue-type/related-issue-type.service.ts
packages/core/src/tasks/sizes/size.service.ts
packages/core/src/tasks/statuses/status.service.ts
packages/core/src/tasks/versions/version.service.ts

[Refactor]: Bad Request Exception Filters 

---

apps/gauzy/src/app/@core/services/gauzy-ai/gauzy-ai.service.ts
apps/gauzy/src/app/@core/services/integration/index.ts
apps/gauzy/src/app/@core/services/integration/integration-setting.service.ts
apps/gauzy/src/app/pages/integrations/gauzy-ai/components/integration-setting-card/integration-setting-card.component.html
apps/gauzy/src/app/pages/integrations/gauzy-ai/components/integration-setting-card/integration-setting-card.component.scss
apps/gauzy/src/app/pages/integrations/gauzy-ai/components/integration-setting-card/integration-setting-card.component.ts
apps/gauzy/src/app/pages/integrations/gauzy-ai/components/view/view.component.html
apps/gauzy/src/app/pages/integrations/gauzy-ai/components/view/view.component.scss
apps/gauzy/src/app/pages/integrations/gauzy-ai/components/view/view.component.ts
apps/gauzy/src/app/pages/integrations/gauzy-ai/gauzy-ai.module.ts
packages/contracts/src/index.ts
packages/contracts/src/integration-setting.model.ts
packages/contracts/src/integration.model.ts
packages/core/src/core/crud/tenant-aware-crud.service.ts
packages/core/src/integration-entity-setting/integration-entity-setting.service.ts
packages/core/src/integration-setting/dto/index.ts
packages/core/src/integration-setting/dto/update-integration-setting.dto.ts
packages/core/src/integration-setting/integration-setting.controller.ts
packages/core/src/integration-setting/integration-setting.module.ts
packages/core/src/integration-setting/integration-setting.service.ts
packages/core/src/integration/gauzy-ai/integration-ai.controller.ts
packages/core/src/integration/gauzy-ai/integration-ai.module.ts
packages/core/src/integration/gauzy-ai/integration-ai.service.ts
packages/plugins/integration-ai/src/gauzy-ai.service.ts

[Fix] #7246 Gauzy AI Integration

---

apps/gauzy/package.json
apps/gauzy/src/app/@shared/timesheet/filters/filters.component.ts
apps/gauzy/src/app/@shared/timesheet/filters/filters.module.ts
apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.ts
apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.module.ts
yarn.lock

Chore(Deps): Added @angular-slider/ngx-slider

---

packages/config/src/database.ts

[Fix] Enabled DB SSL Connection

---

packages/contracts/src/job-search-category.model.ts
packages/contracts/src/job-search-occupation.model.ts
packages/core/src/employee-job-preset/employee-upwork-jobs-search-criterion.entity.ts
packages/core/src/employee-job-preset/job-preset-upwork-job-search-criterion.entity.ts
packages/core/src/employee-job-preset/job-preset.entity.ts
packages/core/src/employee-job-preset/job-search-category/job-search-category.entity.ts
packages/core/src/employee-job-preset/job-search-occupation/job-search-occupation.entity.ts

[Fix] Job Occupation & Category Entity

---

packages/core/src/bootstrap/index.ts
packages/core/src/shared/guards/auth.guard.ts
packages/plugins/sentry-tracing/src/sentry.helper.ts

fix: disable some middlewares depending on env settings

---

.github/workflows/docker-build-publish-demo.yml
.github/workflows/docker-build-publish-prod.yml
.github/workflows/docker-build-publish-stage.yml

chore: builds

---

apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.html
apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.ts
packages/core/src/organization-team-employee/organization-team-employee.subscriber.ts
packages/core/src/organization-team/organization-team.controller.ts
packages/core/src/organization-team/organization-team.service.ts
packages/core/src/time-tracking/screenshot/screenshot.subscriber.ts

[Fix] Organization Mutation / Query

---

.github/workflows/deploy-do-droplet-demo.yml
docker-compose.api.yml

Test do droplet

---

.deploy/ssh/.env.template.compose
.github/workflows/deploy-do-droplet-demo.yml

Improve test do droplet

---

.github/workflows/deploy-do-droplet-demo.yml

added docker-compose-api and deploy-do-droplet-demo.yml

---

.do/app.yaml
.github/workflows/deploy-do-app-platform-demo.yml
.github/workflows/deploy-do-app-platform-stage.yml

Deployment to DO App Platform done

---

apps/gauzy/src/app/pages/pages.component.scss

---
---
https://github.com/ever-co/ever-gauzy/assets/78637183/05cc3a88-9f8e-4591-862c-a431ff63d4e7

Fix sticky smart table header

---

apps/gauzy/src/app/pages/miscellaneous/not-found/not-found.component.html
apps/gauzy/src/app/pages/miscellaneous/not-found/not-found.component.scss
apps/gauzy/src/app/pages/miscellaneous/not-found/not-found.component.ts
apps/gauzy/src/assets/i18n/ar.json
apps/gauzy/src/assets/i18n/bg.json
apps/gauzy/src/assets/i18n/de.json
apps/gauzy/src/assets/i18n/en.json
apps/gauzy/src/assets/i18n/es.json
apps/gauzy/src/assets/i18n/fr.json
apps/gauzy/src/assets/i18n/he.json
apps/gauzy/src/assets/i18n/it.json
apps/gauzy/src/assets/i18n/nl.json
apps/gauzy/src/assets/i18n/pl.json
apps/gauzy/src/assets/i18n/pt.json
apps/gauzy/src/assets/i18n/ru.json
apps/gauzy/src/assets/i18n/zh.json

---
--- 
https://github.com/ever-co/ever-gauzy/assets/78637183/811823b8-7e39-4d0f-94b4-c11e8c00198e

Improve 404 Not Found page

---

apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.html
apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.ts
packages/core/src/time-tracking/time-log/time-log.service.ts

[Fix] Manual Timelog Report

---

packages/core/src/core/file-storage/tenant-settings.middleware.ts
packages/core/src/integration/gauzy-ai/integration-ai.middleware.ts
packages/core/src/integration/github/github.middleware.ts
packages/core/src/role-permission/role-permission.service.ts
packages/core/src/shared/guards/feature-flag.guard.ts
packages/core/src/shared/guards/organization-permission.guard.ts
packages/core/src/shared/guards/permission.guard.ts
packages/core/src/shared/guards/tenant-permission.guard.ts

feat: add more caching to guards & middlewares

---

apps/gauzy/src/app/@core/services/employees.service.ts
apps/gauzy/src/app/@theme/components/header/header.component.ts
packages/core/src/core/crud/crud.service.ts
packages/core/src/employee-statistics/employee-statistics.service.ts
packages/core/src/employee/employee.controller.ts
packages/core/src/employee/employee.service.ts

[Fix] Working Employee Count Query

---

packages/core/src/core/crud/crud.service.ts
packages/core/src/core/crud/utils.ts

[Fix] Disabled eager loading for counts API

---

packages/core/src/auth/auth.service.ts

[Fix] Hash Not Null Query Comparison

---

apps/gauzy/package.json
package.json
packages/config/src/database.ts
packages/core/package.json
packages/desktop-libs/package.json
yarn.lock

chore(deps): bump packages

---

yarn.lock

chore: updated lock file

---

apps/gauzy/src/app/onboarding/tenant-details/tenant-details.component.ts
packages/core/src/core/crud/crud.service.ts
packages/core/src/core/entities/base.entity.ts
packages/core/src/employee/commands/handlers/employee.create.handler.ts
packages/core/src/employee/employee.entity.ts
packages/core/src/employee/employee.service.ts
packages/core/src/organization-task-setting/commands/handlers/organization-task-setting.create.handler.ts
packages/core/src/organization-task-setting/organization-task-setting.module.ts
packages/core/src/organization-task-setting/organization-task-setting.service.ts
packages/core/src/organization-task-setting/repository/index.ts
packages/core/src/organization-task-setting/repository/type-orm-organization-task-setting.repository.ts
packages/core/src/organization/commands/handlers/organization.create.handler.ts
packages/core/src/organization/commands/handlers/organization.update.handler.ts
packages/core/src/organization/dto/create-organization.dto.ts
packages/core/src/organization/dto/update-organization.dto.ts
packages/core/src/organization/organization.controller.ts
packages/core/src/organization/organization.entity.ts
packages/core/src/organization/organization.module.ts
packages/core/src/organization/organization.service.ts
packages/core/src/user-organization/repository/index.ts
packages/core/src/user-organization/repository/type-orm-user-organization.repository.ts
packages/core/src/user-organization/user-organization.services.ts
packages/core/src/user/repository/mikro-orm-user.repository.ts

[Fix] Organization API (Mikro ORM)

---

packages/core/src/organization-project/organization-project.subscriber.ts

[Fix] Organization Project Subscriber (Members Count)

---

packages/core/src/core/index.ts
packages/core/src/core/repository/index.ts
packages/plugins/changelog/src/repository/mikro-orm-changelog.repository.ts
packages/plugins/integration-wakatime/src/lib/repository/mikro-orm-wakatime.repository.ts
packages/plugins/integration-wakatime/src/lib/repository/type-orm-wakatime.repository.ts
packages/plugins/knowledge-base/src/help-center-article/help-center-article.module.ts
packages/plugins/knowledge-base/src/help-center-article/help-center-article.service.ts
packages/plugins/knowledge-base/src/help-center-article/repository/index.ts
packages/plugins/knowledge-base/src/help-center-article/repository/mikro-orm-help-center-article.repository.ts
packages/plugins/knowledge-base/src/help-center-article/repository/type-orm-help-center-article.repository.ts
packages/plugins/knowledge-base/src/help-center-author/help-center-author.module.ts
packages/plugins/knowledge-base/src/help-center-author/repository/index.ts
packages/plugins/knowledge-base/src/help-center-author/repository/mikro-orm-help-center-author.repository.ts
packages/plugins/knowledge-base/src/help-center-author/repository/type-orm-help-center-author.repository.ts
packages/plugins/knowledge-base/src/help-center/help-center.module.ts
packages/plugins/knowledge-base/src/help-center/repository/index.ts
packages/plugins/knowledge-base/src/help-center/repository/mikro-orm-help-center.repository.ts
packages/plugins/knowledge-base/src/help-center/repository/type-orm-help-center.repository.ts
packages/plugins/product-reviews/src/entities/repository/mikro-orm-product-review.repository.ts

[Fix] Plugins Builds

---

packages/core/src/core/decorators/entity/relations/many-to-one.decorator.ts
packages/core/src/core/decorators/entity/relations/one-to-one.decorator.ts
packages/core/src/core/decorators/entity/relations/shared-types.ts

[Fix] Multi ORM Relation

---

packages/core/src/feature/feature-organization.service.ts
packages/core/src/feature/feature.module.ts
packages/core/src/feature/feature.service.ts
packages/core/src/feature/repository/index.ts
packages/core/src/feature/repository/type-orm-feature-organization.repository.ts
packages/core/src/feature/repository/type-orm-feature.repository.ts
packages/core/src/organization/commands/handlers/organization.create.handler.ts
packages/core/src/role/commands/handlers/tenant-role-bulk-create.handler.ts
packages/core/src/tasks/statuses/commands/tenant-status-bulk-create.command.ts
packages/core/src/tenant/commands/handlers/tenant-feature-organization.create.handler.ts
packages/core/src/tenant/tenant-setting/commands/handlers/tenant-setting.save.handler.ts
packages/core/src/tenant/tenant.service.ts

[Fix] Onboarding Tenant Performance

---

packages/core/src/core/file-storage/providers/s3.provider.ts
packages/core/src/core/file-storage/providers/wasabi-s3.provider.ts
packages/core/src/image-asset/image-asset.controller.ts

[Fix] Storage Provider ForcePathStyle

---

.github/workflows/desktop-app-prod.yml
.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-prod.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/server-api-prod.yml
.github/workflows/server-api-stage.yml
.github/workflows/server-prod.yml
.github/workflows/server-stage.yml

chore: used different token for apps

---

apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.ts
packages/core/src/core/file-storage/providers/digitalocean-s3.provider.ts

[Fix] Default Enabled Force path style URLs (File Storage)

---

apps/gauzy/src/app/@shared/gallery/gallery.component.html
apps/gauzy/src/app/@shared/gallery/gallery.component.ts
apps/gauzy/src/app/@shared/gallery/gallery.directive.ts
apps/gauzy/src/app/@shared/gallery/gallery.service.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts

[Fix] Screenshots Gallery Preview / Deletion

---

angular.json

fix: warning ⚠ for allowed common js dependencies

---

apps/gauzy/src/app/@core/services/server-connection.service.ts

fix: connection issues detection / resolve

---

.deploy/k8s/k8s-manifest.prod.yaml
.deploy/k8s/k8s-manifest.stage.yaml
.github/workflows/deploy-cw-demo.yml
.github/workflows/deploy-cw-prod.yml
.github/workflows/deploy-cw-stage.yml
.github/workflows/deploy-do-app-platform-demo.yml
.github/workflows/deploy-do-app-platform-prod.yml
.github/workflows/deploy-do-app-platform-stage.yml
.github/workflows/deploy-do-droplet-demo.yml
.github/workflows/deploy-do-droplet-pre-demo.yml
.github/workflows/deploy-do-droplet-pre-prod.yml
.github/workflows/deploy-do-droplet-pre-stage.yml
.github/workflows/deploy-do-droplet-prod.yml
.github/workflows/deploy-do-droplet-stage.yml

chore: disable not used for now

---

packages/core/src/database/database.module.ts
packages/core/src/database/index.ts
packages/core/src/database/transactional-entity-manager.ts

[Feat] Transactional Connection Provider

---

packages/common/src/custom-field-types.ts
packages/common/src/index.ts
packages/common/src/interfaces/IApplicationPluginConfig.ts
packages/common/src/shared-types.ts
packages/config/src/default-configuration.ts
packages/core/src/bootstrap/index.ts
packages/core/src/core/crud/crud.factory.ts
packages/core/src/core/decorators/entity/entity-options.types.ts
packages/core/src/core/entities/custom-entity-fields/custom-entity-fields.ts
packages/core/src/core/entities/custom-entity-fields/custom-field-types.ts
packages/core/src/core/entities/custom-entity-fields/register-custom-entity-fields.ts
packages/core/src/event-bus/event-bus.ts
packages/core/src/organization-contact/organization-contact.entity.ts
packages/core/src/proposal/proposal.entity.ts
packages/core/src/tags/index.ts
packages/core/src/tags/tag.entity.ts
packages/core/src/tags/tag.types.ts

[WIP] Custom Entity Fields (For Plugins)

---

packages/core/src/proposal/commands/handlers/index.ts
packages/core/src/proposal/commands/handlers/proposal-create.handler.ts
packages/core/src/proposal/commands/handlers/proposal-update.handler.ts
packages/core/src/proposal/commands/index.ts
packages/core/src/proposal/commands/proposal-update.command.ts
packages/core/src/proposal/proposal.controller.ts
packages/core/src/proposal/proposal.module.ts

[Fix] Proposal Update Command Handler

---

packages/common/src/custom-field-types.ts
packages/common/src/index.ts
packages/common/src/interfaces/IApplicationPluginConfig.ts
packages/common/src/shared-types.ts
packages/config/src/default-configuration.ts
packages/core/src/bootstrap/index.ts
packages/core/src/core/crud/crud.factory.ts
packages/core/src/core/decorators/entity/entity-options.types.ts
packages/core/src/core/entities/custom-entity-fields/custom-entity-fields.ts
packages/core/src/core/entities/custom-entity-fields/custom-field-types.ts
packages/core/src/core/entities/custom-entity-fields/register-custom-entity-fields.ts
packages/core/src/employee/employee.entity.ts
packages/core/src/event-bus/event-bus.ts
packages/core/src/organization-contact/organization-contact.entity.ts
packages/core/src/proposal/proposal.entity.ts
packages/core/src/tags/index.ts
packages/core/src/tags/tag.entity.ts
packages/core/src/tags/tag.types.ts
packages/core/tsconfig.json

[WIP] Custom Entity Fields

---

apps/gauzy/src/app/@shared/sidebar-menu/sidebar-menu.component.ts
apps/gauzy/src/app/pages/integrations/components/integration-list/list.component.ts

[Fix] Job Browse & Matching Sidebar Menus

---

packages/core/src/database/connection-entity-manager.ts
packages/core/src/database/database.module.ts
packages/core/src/database/index.ts
packages/core/src/deal/deal.module.ts
packages/core/src/deal/deal.service.ts
packages/core/src/deal/repository/index.ts
packages/core/src/export-import/export/export.service.ts
packages/core/src/export-import/import/import.service.ts
packages/core/src/pipeline/pipeline.module.ts
packages/core/src/pipeline/pipeline.service.ts
packages/core/src/pipeline/repository/index.ts

[Fix] Core Database Connection Entity Manager

---

apps/gauzy/src/app/pages/employees/employees.component.ts
packages/config/src/database.ts
packages/core/package.json
packages/core/src/core/crud/crud.service.ts
packages/core/src/core/crud/icrud.service.ts
packages/core/src/core/crud/tenant-aware-crud.service.ts
packages/core/src/core/utils.ts
packages/core/src/employee/employee.controller.ts
packages/core/src/employee/employee.entity.ts
packages/core/src/employee/employee.service.ts
packages/core/src/role-permission/role-permission.controller.ts
packages/core/src/role/role.controller.ts
packages/core/src/role/role.service.ts
packages/core/src/user/user.entity.ts
yarn.lock

[Feat] Mikro ORM (Soft Delete) For Employee

---

packages/auth/package.json
packages/core/package.json
packages/plugins/integration-ai/package.json
yarn.lock

chore(deps): bump axios from ^1.6.5 to ^1.6.8

---

packages/core/src/core/entities/subscribers/index.ts
packages/core/src/core/entities/subscribers/tenant-organization-base-entity.subscriber.ts

[Fix] Tenant Organization Base Entity Subscriber

---

apps/gauzy/src/app/@core/services/employees.service.ts
apps/gauzy/src/app/pages/employees/employees-routing.module.ts
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/employees/table-components/employee-work-status/employee-work-status.component.html
packages/core/src/core/crud/crud.controller.ts
packages/core/src/core/crud/crud.factory.ts
packages/core/src/core/crud/crud.service.ts
packages/core/src/core/crud/icrud.service.ts
packages/core/src/core/crud/tenant-aware-crud.service.ts
packages/core/src/core/entities/base.entity.ts
packages/core/src/employee/commands/employee.update.command.ts
packages/core/src/employee/commands/handlers/employee.update.handler.ts
packages/core/src/employee/employee-job.controller.ts
packages/core/src/employee/employee.controller.ts
packages/core/src/employee/employee.entity.ts
packages/core/src/employee/employee.module.ts
packages/core/src/employee/employee.service.ts
packages/core/src/organization-team-employee/organization-team-employee.entity.ts
packages/core/src/user/user.entity.ts

[Fix] Soft Remove (Employee, User, Team Members)

---

packages/core/src/core/crud/crud.controller.ts
packages/core/src/core/crud/crud.factory.ts
packages/core/src/core/crud/crud.service.ts
packages/core/src/core/crud/icrud.service.ts
packages/core/src/core/utils.ts
packages/core/src/employee/employee.service.ts

[Fix] Mikro ORM Collections (Soft Delete)

---

packages/core/src/tasks/task.service.ts
packages/core/src/user/user.service.ts

[Fix] Unassigned Employee Team Tasks

---

packages/contracts/src/file-provider.ts
packages/contracts/src/image-asset.model.ts
packages/contracts/src/screenshot.model.ts
packages/core/src/core/context/request-context.ts
packages/core/src/core/file-storage/file-storage.ts
packages/core/src/core/file-storage/providers/debug.provider.ts
packages/core/src/core/file-storage/providers/local.provider.ts
packages/core/src/core/file-storage/providers/provider.ts
packages/core/src/feature/feature.subscriber.ts
packages/core/src/image-asset/image-asset.entity.ts
packages/core/src/tenant/tenant-setting/tenant-setting.seed.ts
packages/core/src/time-tracking/screenshot/screenshot.controller.ts
packages/core/src/time-tracking/screenshot/screenshot.entity.ts

[Fix] Request Context Missing ClsService (Seeder)

---

apps/desktop-timer/src/app/app.service.ts
packages/core/src/user-organization/user-organization.services.ts
packages/desktop-ui-lib/src/lib/language/language-selector.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/organization-selector/organization-selector.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/organization-selector/user-organization.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.html

[Fix] Can't Choose Organization on Desktop Timer

---

packages/core/src/bootstrap/index.ts
packages/desktop-api/src/main.ts
packages/desktop-libs/src/lib/server/service/api-service.ts

fix: detect correctly that API server is running in Desktop Server app

---

packages/contracts/src/organization-team.model.ts
packages/core/src/organization-team/dto/organization-team-statistic.dto.ts
packages/core/src/organization-team/organization-team.controller.ts
packages/core/src/organization-team/organization-team.service.ts
packages/core/src/organization-team/queries/handlers/get-organization-team-statistic.handler.ts
packages/core/src/public-share/team/dto/public-team-query.dto.ts
packages/core/src/public-share/team/public-team.service.ts

---
https://github.com/ever-co/ever-teams/pull/2466

[Fix] Spelling Typo

---

packages/core/src/auth/auth.controller.ts
packages/core/src/auth/auth.service.ts
packages/core/src/auth/strategies/jwt-refresh-token.strategy.ts
packages/core/src/employee/employee.service.ts
packages/core/src/user/user.service.ts

[Fix] Get Active Employee With Active User

---

packages/contracts/src/task-status.model.ts
packages/core/src/tasks/statuses/dto/reorder.dto.ts
packages/core/src/tasks/statuses/dto/status-query.dto.ts
packages/core/src/tasks/statuses/queries/handlers/find-statuses.handler.ts
packages/core/src/tasks/statuses/status.controller.ts
packages/core/src/tasks/statuses/status.service.ts

[Feat] Task Status Reordering

---

packages/core/src/tasks/statuses/status.controller.ts

[Fix] Task Status Reordering API

---

apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts

[Fix] Weekly Timesheet Missing Author

---

packages/core/src/tasks/statuses/status.service.ts

[Fix] Task Status Reordering Exception Logging

---

packages/contracts/src/organization-team.model.ts
packages/core/src/database/migrations/1715680147522-AlterOrganizationTeamAddShareProfileViewField.ts
packages/core/src/organization-team/dto/organization-team.dto.ts
packages/core/src/organization-team/organization-team.entity.ts

All details on the PR below : 
[This PR on Ever Teams](https://github.com/ever-co/ever-teams/pull/2518)

Additional Team Setting (Share Profile View)

---

.deploy/api/Dockerfile
.deploy/webapp/Dockerfile
packages/ui-sdk/package.json

[Fix] Core UI SDK Builds

---

packages/ui-sdk/src/lib/package.json
tsconfig.json

[Attempt] Core UI SDK Builds

---

apps/desktop-timer/src/package.json
apps/desktop/src/package.json
apps/gauzy/package.json
apps/server/src/package.json
packages/plugins/job-search-ui/src/lib/package.json
packages/ui-sdk/package.json
packages/ui-sdk/src/lib/package.json

chore(deps): bump tslib from ^2.3.0 to ^2.6.2

---

apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.resolver.ts

[Fix] Route Resolver (Date Range Picker)

---

apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.ts
apps/gauzy/src/app/@shared/report/charts/line-chart/line-chart.component.html
apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.ts
apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.ts
apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.ts
apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.ts
apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.ts

[Fix] Weekly Time Report

---

apps/desktop-timer/package.json
apps/desktop/package.json
apps/gauzy/package.json
apps/server/package.json
packages/common-angular/package.json
packages/core/package.json
packages/desktop-libs/package.json
packages/desktop-ui-lib/package.json
yarn.lock

chore(deps): bump moment-timezone from ^0.5.40 to ^0.5.45

---

apps/desktop-timer/package.json
apps/desktop-timer/src/package.json
apps/desktop/package.json
apps/desktop/src/package.json
apps/gauzy/package.json
apps/server/package.json
apps/server/src/package.json
packages/common-angular/package.json
packages/core/package.json
packages/desktop-libs/package.json
packages/desktop-ui-lib/package.json
packages/plugins/job-proposal/package.json
yarn.lock

chore(deps): bump moment from ^2.29.4 to ^2.30.1

---

packages/core/src/auth/auth.controller.ts
packages/core/src/auth/auth.service.ts

Reverts ever-co/ever-gauzy#7823

Revert "Add a service for social logins on Ever Teams"

---

apps/gauzy/src/app/@shared/pipes/time-format.pipe.ts
apps/gauzy/src/app/@shared/timesheet/gauzy-filters/filters.component.scss
apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.html
apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.component.ts
apps/gauzy/src/app/@shared/timesheet/gauzy-filters/gauzy-filters.module.ts
apps/gauzy/src/app/@shared/timesheet/gauzy-filters/timezone-filter/timezone-filter.component.html
apps/gauzy/src/app/@shared/timesheet/gauzy-filters/timezone-filter/timezone-filter.component.scss
apps/gauzy/src/app/@shared/timesheet/gauzy-filters/timezone-filter/timezone-filter.component.ts
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.html
apps/gauzy/src/app/@shared/timesheet/screenshots/screenshots-item/screenshots-item.component.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.html
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.scss
apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.html
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.html
apps/gauzy/src/app/pages/reports/expenses-report/expenses-report/expenses-report.component.scss
apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.html
packages/common-angular/src/utils/shared-utils.ts
packages/contracts/src/timesheet.model.ts
packages/ui-sdk/src/lib/common/src/utils/shared-utils.ts
packages/ui-sdk/src/lib/core/src/services/navigation/navigation.service.ts

[Feat] Apply Time Format (12 / 24 hours)  

---

packages/core/src/core/utils.ts

[Fix] Days Range Between Dates

---

packages/core/src/core/entities/custom-entity-fields/mikro-orm-base-custom-entity-field.ts
packages/core/src/core/entities/custom-entity-fields/register-custom-entity-fields.ts
packages/core/src/tags/repository/type-orm-tag.repository.ts
packages/core/src/tags/tag.entity.ts
packages/core/src/tags/tag.module.ts
packages/core/src/tags/tag.service.ts

[Fix] Hide Relational Custom Fields

---

apps/gauzy/src/app/@shared/card-grid/card-grid.component.html
apps/gauzy/src/app/@shared/card-grid/card-grid.component.ts
apps/gauzy/src/app/pages/contacts/contacts.component.ts
apps/gauzy/src/app/pages/hubstaff/components/hubstaff/hubstaff.component.ts
apps/gauzy/src/app/pages/inventory/components/table-inventory-items/table-inventory.component.ts
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts
apps/gauzy/src/app/pages/tags/tags-color/tags-color.component.html
apps/gauzy/src/app/pages/tags/tags-color/tags-color.component.ts
apps/gauzy/src/app/pages/tags/tags.component.html
apps/gauzy/src/app/pages/tags/tags.component.ts
apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
packages/core/src/product/dto/create-product.dto.ts
packages/core/src/product/dto/update-product.dto.ts

[Fix] Tags Smart Grid Layout

---

.github/workflows/desktop-timer-app-stage.yml

chore: attempt to fix Desktop app build (#7845)

---

apps/server-api/src/index.ts

fix: missing required key value of pathwindow gauzy api server

---

apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
apps/gauzy/src/app/app.component.ts
packages/ui-sdk/src/lib/core/src/services/selector-builder/selector-builder.service.ts

[Fix] Navigate Query Param (If Date Selector Enabled)

---

packages/contracts/src/organization-team.model.ts
packages/core/src/database/migrations/1718386634024-AlterOrganizationTeamAddRequirePlanToTrackField.ts
packages/core/src/organization-team/dto/organization-team.dto.ts
packages/core/src/organization-team/organization-team.entity.ts

On Ever Teams, we need, in settings, a toggle that can ON/OFF members are required to have a Daily Plan before track time.
More details [here](https://github.com/ever-co/ever-teams/issues/2471)

[Improve] Team settings require plan before track

---

packages/common/src/utils/shared-utils.ts
packages/core/src/organization-team/dto/organization-team-statistic.dto.ts
packages/core/src/organization-team/organization-team.service.ts

[Fix] Organization Team Members Timer Statistics

---

.deploy/api/Dockerfile
.deploy/webapp/Dockerfile
angular.json
nx.json
packages/ui-config/.eslintrc.json
packages/ui-config/README.md
packages/ui-config/jest.config.ts
packages/ui-config/ng-package.json
packages/ui-config/package.json
packages/ui-config/src/index.ts
packages/ui-config/src/public-api.ts
packages/ui-config/src/test-setup.ts
packages/ui-config/tsconfig.json
packages/ui-config/tsconfig.lib.json
packages/ui-config/tsconfig.lib.prod.json
packages/ui-config/tsconfig.spec.json
project.json
tsconfig.json
yarn.lock

[Fix] UI Config By NX Generator

---

apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-profile.component.html
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-profile.component.ts
apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate.component.ts
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-calendar/interview-calendar.component.html
apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-calendar/interview-calendar.component.ts
packages/core/src/candidate-interview/candidate-interview.controller.ts
packages/core/src/candidate-interview/candidate-interview.entity.ts
packages/ui-core/src/lib/shared/src/candidate/candidate-calendar-info/candidate-calendar-info.component.ts
packages/ui-core/src/lib/shared/src/candidate/candidate-interview-feedback/candidate-interview-feedback.component.html
packages/ui-core/src/lib/shared/src/candidate/candidate-interview-info/candidate-interview-info.component.html
packages/ui-core/src/lib/shared/src/candidate/candidate-interview-info/candidate-interview-info.component.ts
packages/ui-core/src/lib/shared/src/candidate/candidate-interview-mutation/candidate-notification-form/candidate-notification-form.component.ts

[Fix] Calendar Interview Page (Candidates & Employees Filters) 

---

packages/core/src/auth/auth.module.ts
packages/core/src/auth/auth.service.ts
packages/core/src/core/context/request-context.ts
packages/core/src/email-history/email-history.module.ts
packages/core/src/email-history/email-history.service.ts
packages/core/src/email-history/repository/index.ts
packages/core/src/email-send/email.service.ts
packages/core/src/email-template/email-template.module.ts
packages/core/src/email-template/email-template.service.ts
packages/core/src/email-template/repository/index.ts
packages/core/src/event-bus/event-bus.module.ts
packages/core/src/event-bus/event-bus.ts
packages/core/src/event-bus/events/account-registration-event.ts
packages/core/src/event-bus/events/account-verified-event.ts
packages/core/src/event-bus/events/handlers/account-registration-handler.ts
packages/core/src/event-bus/events/handlers/account-verified-handler.ts
packages/core/src/event-bus/events/handlers/index.ts

[Fix] Account Register / Verified Events

---

.deploy/webapp/entrypoint.compose.sh
.deploy/webapp/entrypoint.prod.sh

chore: switch back to sh

---

packages/plugins/changelog/package.json
packages/plugins/integration-upwork/package.json

fix: prod build :)

---

apps/api/src/plugins.ts
packages/common/src/custom-embedded-field-types.ts
packages/config/src/default-configuration.ts
packages/core/src/core/entities/custom-entity-fields/custom-entity-fields.ts
packages/core/src/core/entities/custom-entity-fields/organization-project/index.ts
packages/core/src/core/entities/custom-entity-fields/organization-project/mikro-orm-organization-project-entity-custom-fields.ts
packages/core/src/core/entities/custom-entity-fields/organization-project/type-orm-organization-project-entity-custom-fields.ts
packages/core/src/organization-project/organization-project.entity.ts

[Feat] Organization Project Entity Custom Fields Abstract Classes

---

.cspell.json
packages/core/src/database/migrations/1719937371312-AlterOrganizationGithubRepositoryEntityTable.ts
packages/core/src/database/migrations/1719937371312-AlterOrganizationGithubRepositoryTable.ts
packages/core/src/database/migrations/1719994643595-AlterOrganizationGithubRepositoryIssueEntityTable.ts
packages/core/src/integration/github/github-sync.service.ts
packages/core/src/integration/github/repository/github-repository.entity.ts
packages/core/src/integration/github/repository/issue/github-repository-issue.entity.ts
packages/core/src/organization-project/organization-project.entity.ts

[Fix] GitHub Integration (Table Migration)

---

.cspell.json
apps/gauzy/package.json
apps/gauzy/src/index.html
packages/ui-core/package.json
packages/ui-core/src/lib/package.json
yarn.lock

chore(deps): #7925 bump ckeditor from ^4.23.0 to ^4.24.0

---

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-main/edit-employee-main.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.resolver.ts
apps/gauzy/src/app/pages/jobs/search/components/apply-job-manually/apply-job-manually.component.ts
packages/core/src/employee/employee.subscriber.ts
packages/core/src/image-asset/image-asset.controller.ts
packages/core/src/image-asset/image-asset.subscriber.ts
packages/core/src/organization/organization.entity.ts
packages/ui-core/src/lib/core/src/interceptors/api.interceptor.ts
packages/ui-core/src/lib/core/src/services/employee/employee-store.service.ts
packages/ui-core/src/lib/shared/src/file-uploader-input/file-uploader-input.component.ts
packages/ui-core/src/lib/shared/src/image-uploader/image-uploader-base.component.ts
packages/ui-core/src/lib/shared/src/image-uploader/image-uploader.component.ts
packages/ui-core/src/lib/shared/src/selectors/employee/employee.component.html
packages/ui-core/src/lib/shared/src/selectors/employee/employee.component.ts
packages/ui-core/src/lib/shared/src/table-components/picture-name-tags/picture-name-tags.component.ts

[Fix] #7944 Employee Picture Upload

---

packages/contracts/src/daily-plan.model.ts
packages/core/src/tasks/daily-plan/daily-plan.controller.ts
packages/core/src/tasks/daily-plan/daily-plan.service.ts
packages/core/src/tasks/daily-plan/dto/index.ts
packages/core/src/tasks/daily-plan/dto/remove-task-from-plans.dto.ts

[Feat] delete task from many daily plans

---

apps/api/src/plugins.ts

fix: disable temporary Product Review Plugin

---

.cspell.json
apps/api/src/plugins.ts
packages/core/src/database/migrations/1720852356593-CreateProductReviewTable.ts
packages/plugins/product-reviews/package.json
packages/plugins/product-reviews/src/lib/entities/product-review.entity.ts
packages/plugins/product-reviews/src/lib/product-review.types.ts

[Fix] Product Review Plugin Migration

---

packages/core/src/core/utils.ts
packages/core/src/database/migrations/1679765443208-MigrateRolePermisisons.ts
packages/core/src/database/migrations/1721026150876-MigrateRolePermisisons.ts
packages/core/src/role-permission/utils.ts

[Fix] Role Permission Migration

---

apps/gauzy/src/app/pages/dashboard/accounting/accounting.component.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.resolver.ts
apps/gauzy/src/app/pages/recurring-expense-employee/recurring-expense-employee.component.ts
apps/gauzy/src/app/share/public-appointments/appointment-form/appointment-form.component.ts
apps/gauzy/src/app/share/public-appointments/create-appointment/create-appointment.component.ts
packages/ui-core/src/lib/core/src/interceptors/api.interceptor.ts
packages/ui-core/src/lib/theme/src/components/header/header.component.ts

[Fix] Time Tracking Dashboard (Employee)

---

packages/core/src/core/crud/crud.factory.ts
packages/core/src/tasks/statuses/dto/reorder.dto.ts
packages/core/src/tasks/statuses/status.controller.ts
packages/core/src/tasks/statuses/status.service.ts

[Refactor] Task Status Re Order Logging

---

apps/gauzy/src/app/pages/hubstaff/components/hubstaff/hubstaff.component.html
apps/gauzy/src/app/pages/hubstaff/components/hubstaff/hubstaff.component.ts
apps/gauzy/src/app/pages/hubstaff/components/settings-dialog/settings-dialog.component.html
apps/gauzy/src/app/pages/hubstaff/components/settings-dialog/settings-dialog.component.ts
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.html
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts
packages/contracts/src/employee-proposal-template.model.ts
packages/core/src/integration-tenant/integration-tenant.service.ts
packages/plugins/job-proposal/src/lib/proposal-template/employee-proposal-template.controller.ts
packages/plugins/job-proposal/src/lib/proposal-template/employee-proposal-template.entity.ts
packages/plugins/job-proposal/src/lib/proposal-template/employee-proposal-template.service.ts
packages/plugins/job-search/src/lib/employee-job-preset/job-preset.service.ts
packages/plugins/job-search/src/lib/employee-job/employee-job.service.ts
packages/ui-core/src/lib/core/src/services/proposal/proposal-template.service.ts

[Fix] Employee Can Browse Only Own Job Posts

---

apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
packages/core/src/time-tracking/statistic/statistic.controller.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
packages/ui-core/src/lib/core/src/services/timesheet/timesheet-statistics.service.ts

[Fix] Fetch Tasks Statistics

---

packages/core/src/tasks/daily-plan/daily-plan.service.ts

[Fix] Daily plan creation not saved without at least one task

---

angular.json
apps/gauzy/src/main.ts
packages/ui-config/ng-package.json
packages/ui-config/package.json
packages/ui-config/project.json
packages/ui-config/scripts/replace-env-files.ts
packages/ui-config/src/index.ts
packages/ui-config/tsconfig.json
packages/ui-config/tsconfig.lib.json

[Fix] UI Config Entry Point

---

apps/gauzy/src/app/pages/integrations/gauzy-ai/gauzy-ai-routing.module.ts
apps/gauzy/src/app/pages/integrations/github/github-routing.module.ts
apps/gauzy/src/app/pages/jobs/search/search-routing.module.ts
apps/gauzy/src/app/pages/projects/projects-routing.module.ts
packages/plugins/job-search-ui/package.json
packages/plugins/job-search-ui/tsconfig.spec.json
packages/ui-core/src/lib/core/src/resolvers/index.ts
packages/ui-core/src/lib/core/src/resolvers/integration.resolver.ts

[Refactor] Integration Route Resolver

---

packages/core/package.json
packages/plugins/job-search-ui/package.json
yarn.lock

[Fix] Build Packages

---

package.json
packages/core/src/shared/guards/organization-permission.guard.ts
packages/ui-core/src/lib/shared/src/directives/time-tracking-authorized-directive.ts
yarn.lock

chore(deps): camelcase ^6.3.0 resolutions

---

packages/core/src/core/seeds/utils.ts
packages/core/src/image-asset/image-asset.entity.ts
packages/core/src/image-asset/image-asset.subscriber.ts
packages/core/src/tasks/issue-type/issue-type.entity.ts
packages/core/src/tasks/issue-type/issue-type.seed.ts

[Fix] Await/Async Image Asset Subscriber

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

[Fix] Fetch Tasks Statistics (Desktop Timer)

---

packages/desktop-ui-lib/src/lib/settings/plugins/services/plugin-loader.service.ts

[Fix]: Server build

---

apps/gauzy/src/app/app.module.ts

[Fix]: Circular dependencies

---

apps/gauzy/src/app/app.module.ts
apps/gauzy/src/app/pages/jobs/jobs.module.ts
apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template-routing.module.ts
packages/plugins/job-matching-ui/src/lib/components/index.ts
packages/plugins/job-matching-ui/src/lib/components/job-matching/job-matching.component.html
packages/plugins/job-matching-ui/src/lib/components/job-matching/job-matching.component.ts
packages/plugins/job-matching-ui/src/lib/job-matching.module.ts
packages/plugins/job-search-ui/src/lib/components/apply-job-manually/apply-job-manually.component.ts
packages/plugins/job-search-ui/src/lib/components/job-search/job-search.component.ts
packages/plugins/job-search-ui/src/lib/job-search.module.ts
packages/ui-core/core/src/lib/interceptors/language.interceptor.ts
packages/ui-core/i18n/src/lib/i18n.module.ts
packages/ui-core/package.json
tsconfig.json

[Fix] I18n Translation Job Modules

---

packages/desktop-ui-lib/src/lib/recap/+state/recap.service.ts

[Fix]: Daily Data Accuracy

---

packages/desktop-ui-lib/src/lib/ngx-translate/ngx-translate.module.ts

[Fix]: injectorError adding TranslateService to providers in Ngx-translate

---

apps/desktop/src/app/app.component.ts
packages/desktop-libs/src/lib/desktop-tray.ts

* feat: added conditional check for `appConfig.gauzyWindow` before loading URL and showing timeTrackerWindow.
* refactor: TrayIcon class:: updated constructor, replaced `webContents` with `manager.webContents`, and made minor changes to method calls and error handling.
* feat: added conditional IPC renderer call in AppComponent's ngOnInit method based on user being an employee.
---

Fix/#8039 error in full desktop app (#8040)

---

apps/desktop-timer/src/app/app.module.ts

[Fix]: Translate Service Null Injector

---

packages/desktop-ui-lib/src/lib/setup/setup.component.ts
packages/desktop-ui-lib/src/lib/setup/setup.service.ts

fix: desktop setup server host url

---

packages/core/src/database/migrations/1722522985782-AlterUserTableAddDefaultTeamAndWorkspace.ts

[Fix] DB Migration

---

packages/desktop-ui-lib/src/lib/recap/+state/auto-refresh/auto-refresh.store.ts

[Feat]: update auto refresh default value

---

packages/desktop-ui-lib/src/lib/recap/+state/recap.store.ts
packages/desktop-ui-lib/src/lib/services/time-tracker-date.manager.ts

[Fix]: Daily Recap Current Day

---

packages/plugins/integration-ai/src/lib/gauzy-ai.service.ts

[Fix] Filters Employee Job Posts

---

packages/plugins/job-proposal-ui/src/lib/components/add-edit-proposal-template/add-edit-proposal-template.component.ts
packages/plugins/job-proposal-ui/src/lib/components/proposal-template/proposal-template.component.ts

[Fix] Employee Proposal Template

---

packages/contracts/src/task-status.model.ts
packages/core/src/database/migrations/1723645947040-AlterTaskStatusesAddWorkFlowFields.ts
packages/core/src/tasks/statuses/default-global-statuses.ts
packages/core/src/tasks/statuses/dto/create-status.dto.ts
packages/core/src/tasks/statuses/dto/status-query.dto.ts
packages/core/src/tasks/statuses/dto/update-status.dto.ts
packages/core/src/tasks/statuses/standard-statuses-template.ts
packages/core/src/tasks/statuses/status.controller.ts
packages/core/src/tasks/statuses/status.entity.ts
packages/core/src/tasks/statuses/status.service.ts

Task Statuses Templates

---

apps/gauzy/src/app/pages/jobs/job.routes.ts
apps/gauzy/src/app/pages/jobs/jobs.module.ts
apps/gauzy/src/app/server-down/server-down.module.ts
apps/gauzy/src/app/server-down/server-down.routes.ts
packages/plugins/job-employee-ui/src/lib/components/job-employee/job-employee.component.ts
packages/plugins/job-employee-ui/src/lib/job-employee.module.ts
packages/plugins/job-employee-ui/src/lib/job-employee.routes.ts
packages/plugins/job-matching-ui/src/lib/job-matching.module.ts
packages/plugins/job-matching-ui/src/lib/job-matching.routes.ts
packages/plugins/job-proposal-ui/src/lib/job-proposal-template.module.ts
packages/plugins/job-proposal-ui/src/lib/job-proposal-template.routes.ts
packages/plugins/job-search-ui/src/lib/job-search.module.ts
packages/plugins/job-search-ui/src/lib/job-search.routes.ts
packages/ui-auth/src/lib/auth.module.ts
packages/ui-auth/src/lib/auth.routes.ts
packages/ui-core/core/src/lib/common/component-registry.types.ts
packages/ui-core/core/src/lib/services/page/data-table/page-data-table-registry.service.ts
packages/ui-core/core/src/lib/services/page/data-table/page-data-table-registry.types.ts
packages/ui-core/core/src/lib/services/page/index.ts
packages/ui-core/core/src/lib/services/page/page-registry.service.ts
packages/ui-core/core/src/lib/services/page/page-registry.types.ts
packages/ui-core/core/src/lib/services/page/page-route-registry.service.ts
packages/ui-core/core/src/lib/services/page/page-route-registry.types.ts
packages/ui-core/shared/src/lib/directives/index.ts
packages/ui-core/shared/src/lib/directives/trigger-parent-click.directive.ts
packages/ui-core/shared/src/lib/smart-data-layout/smart-table-toggle/smart-table-toggle.component.html
packages/ui-core/shared/src/lib/work-in-progress/work-in-progress.module.ts
packages/ui-core/shared/src/lib/work-in-progress/work-in-progress.routes.ts

[Feat] Data Table Dynamic Columns (Page Location)

---

apps/gauzy/src/app/pages/contacts/contact-view/contact-view.component.ts

fix:incorrect api method called for organization contact update

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts

fix total value showing as NaN in Invoice/Estimates

---

packages/ui-core/theme/src/lib/components/user-menu/user-menu.component.html
packages/ui-core/theme/src/lib/components/user-menu/user-menu.component.ts

replace hardcode platFormSiteUrl in user menu template

---

apps/desktop/package.json
apps/gauzy/package.json
apps/server-api/package.json
apps/server/package.json
packages/auth/package.json
packages/plugins/job-employee-ui/tsconfig.json
packages/plugins/job-matching-ui/tsconfig.json
packages/plugins/job-proposal-ui/tsconfig.json
packages/plugins/job-search-ui/tsconfig.json
packages/plugins/legal-ui/package.json
packages/plugins/legal-ui/tsconfig.json
packages/plugins/onboarding-ui/package.json
packages/plugins/onboarding-ui/tsconfig.json
packages/ui-auth/tsconfig.json

[Fix] Updated Packages TS Paths

---

apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.ts
apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
apps/gauzy/src/app/pages/employees/activity/app-url-activity/app-url-activity/app-url-activity.component.ts
apps/gauzy/src/app/pages/employees/appointment/appointment.component.ts
apps/gauzy/src/app/pages/employees/appointment/manage-appointment/manage-appointment.component.ts
apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/hubstaff/components/settings-dialog/settings-dialog.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/invoices/invoice-payments/payment-mutation/payment-mutation.component.ts
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts
apps/gauzy/src/app/pages/time-off/time-off.component.ts
apps/gauzy/src/app/pages/upwork/components/reports/reports.component.ts
apps/gauzy/src/app/share/employee/employee.component.ts

[Fix] Moment Import Syntax

---

apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.html
apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.ts
apps/gauzy/src/app/pages/employees/timesheet/timesheet-routing.module.ts
apps/gauzy/src/app/pages/employees/timesheet/timesheet.module.ts
packages/ui-core/core/src/index.ts
packages/ui-core/core/src/lib/common/component-registry.types.ts
packages/ui-core/core/src/lib/services/page/index.ts
packages/ui-core/core/src/lib/services/page/page-tab-registry.service.ts
packages/ui-core/core/src/lib/services/page/page-tab-registry.types.ts
packages/ui-core/shared/src/lib/components/dynamic-tabs/dynamic-tabs.component.html
packages/ui-core/shared/src/lib/components/dynamic-tabs/dynamic-tabs.component.scss
packages/ui-core/shared/src/lib/components/dynamic-tabs/dynamic-tabs.component.ts
packages/ui-core/shared/src/lib/components/dynamic-tabs/dynamic-tabs.module.ts
packages/ui-core/shared/src/lib/components/index.ts

[Feat] Dynamic Tabset Registry Providers

---

apps/desktop-timer/src/index.ts

[Fix]: desktop build

---

apps/gauzy/src/app/pages/dashboard/dashboard-routing.module.ts
apps/gauzy/src/app/pages/dashboard/dashboard.component.html
apps/gauzy/src/app/pages/dashboard/dashboard.component.scss
apps/gauzy/src/app/pages/dashboard/dashboard.component.ts
apps/gauzy/src/app/pages/dashboard/dashboard.module.ts
apps/gauzy/src/app/pages/dashboard/data-entry-shortcuts/data-entry-shortcuts.component.html
apps/gauzy/src/app/pages/dashboard/data-entry-shortcuts/data-entry-shortcuts.component.ts
apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.ts
packages/ui-core/core/src/lib/common/component-registry.types.ts
packages/ui-core/core/src/lib/services/page/page-tab-registry.service.ts
packages/ui-core/shared/src/lib/components/dynamic-tabs/dynamic-tabs.component.html
packages/ui-core/shared/src/lib/components/dynamic-tabs/dynamic-tabs.component.ts

[Feat] Dashboard Tabs (Dynamically Add/Remove)

---

apps/desktop/src/package.json
apps/server/src/package.json

[Fix] Server Packages Build

---

apps/desktop/src/index.ts

fix: renamed imageViewWindow to imageViewerWindow.

---

apps/gauzy/src/index.html
apps/gauzy/src/main.ts
packages/ui-core/static/styles/_chat-woot.scss
packages/ui-core/static/styles/_spinner.scss
packages/ui-core/static/styles/styles.scss

[Refactor] Root Index HTML File

---

packages/ui-core/core/src/lib/services/index.ts
packages/ui-core/core/src/lib/services/widget/index.ts
packages/ui-core/core/src/lib/services/widget/widget-registry.service.ts
packages/ui-core/core/src/lib/services/widget/widget-registry.types.ts

[Feat] Widget Registry Provider

---

apps/gauzy/src/app/pages/dashboard/dashboard.component.ts
apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.ts
packages/plugins/job-employee-ui/src/lib/components/job-employee/job-employee.component.html
packages/plugins/job-employee-ui/src/lib/components/job-employee/job-employee.component.ts
packages/plugins/job-employee-ui/src/lib/job-employee.module.ts
packages/plugins/job-employee-ui/src/lib/job-employee.routes.ts
packages/ui-core/core/src/lib/services/page/page-data-table-registry.service.ts
packages/ui-core/core/src/lib/services/page/page-route-registry.service.ts
packages/ui-core/core/src/lib/services/page/page-tab-registry.service.ts
packages/ui-core/core/src/lib/services/page/page-tab-registry.types.ts
packages/ui-core/shared/src/lib/components/dynamic-tabs/dynamic-tabs.component.html
packages/ui-core/shared/src/lib/components/dynamic-tabs/dynamic-tabs.component.ts
packages/ui-core/theme/src/lib/components/theme-sidebar/theme-settings/components/theme-language-selector/theme-language-selector.component.html
packages/ui-core/theme/src/lib/components/theme-sidebar/theme-settings/theme-settings.component.html

[Feat] Dynamic Tabs Component

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

---
https://www.loom.com/share/c014c0ac84bb4ebc9036fb7d109d0ccb?sid=30767ed9-24a6-40c8-a424-3fdcd50b70f0

[Fix]: offline mode stop timer issue

---

packages/ui-core/shared/src/lib/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.module.ts

fix:source display

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

[Bug] Send activities empty data

---

packages/desktop-ui-lib/src/lib/recap/+state/recap.service.ts
packages/desktop-ui-lib/src/lib/recap/weekly/+state/weekly.service.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

[Fix] Data Retrieval Timezone

---

packages/ui-core/shared/src/lib/components/badge-label/badge-label.component.ts
packages/ui-core/shared/src/lib/timesheet/view-time-log-modal/view-time-log-modal.component.scss

Broken UI for Timesheet Modal Log

---

packages/ui-core/shared/src/lib/components/badge-label/badge-label.component.ts
packages/ui-core/shared/src/lib/timesheet/view-time-log-modal/view-time-log-modal.component.html
packages/ui-core/shared/src/lib/timesheet/view-time-log-modal/view-time-log-modal.component.scss

Adjust badge alignment

---

apps/gauzy-e2e/package.json
package.json

[Fix] #7466 Remove ngcc for Angular 16+ #7466

---

apps/gauzy/src/app/pages/settings/file-storage/file-storage-routing.module.ts
apps/gauzy/src/app/pages/settings/file-storage/file-storage.component.html
apps/gauzy/src/app/pages/settings/file-storage/file-storage.module.ts
packages/ui-core/shared/src/lib/invite/invites/invites.component.html
packages/ui-core/shared/src/lib/invite/invites/invites.component.ts
packages/ui-core/shared/src/lib/selectors/employee/default-employee.ts

[Fix] #1880  Remove the image “All”

---

packages/ui-core/core/src/lib/components/sidebar-menu/sidebar-menu.component.ts

Reloading Roles and Permissions Page Causes Console Error

---

apps/gauzy/src/app/pages/dashboard/dashboard-routing.module.ts
apps/gauzy/src/app/pages/dashboard/dashboard.component.ts
apps/gauzy/src/app/pages/employees/employees.component.html
apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.ts
apps/gauzy/src/app/pages/pages.component.ts
apps/gauzy/src/app/pages/pages.module.ts
packages/contracts/src/role-permission.model.ts
packages/core/src/auth/auth.controller.ts
packages/core/src/auth/auth.service.ts
packages/core/src/invite/invite.controller.ts
packages/core/src/invite/invite.module.ts
packages/core/src/role-permission/role-permission.controller.ts
packages/core/src/role-permission/role-permission.module.ts
packages/core/src/role-permission/role-permission.service.ts
packages/plugins/onboarding-ui/src/lib/components/onboarding-complete/onboarding-complete.component.ts
packages/ui-auth/src/lib/components/accept-invite/accept-invite.component.ts
packages/ui-core/core/src/lib/services/app/app-init-service.ts
packages/ui-core/core/src/lib/services/auth/auth.service.ts
packages/ui-core/core/src/lib/services/page/page-tab-registry.service.ts
packages/ui-core/core/src/lib/services/page/page-tab-registry.types.ts
packages/ui-core/core/src/lib/services/permission/permissions.service.ts
packages/ui-core/core/src/lib/services/role/role-permissions.service.ts
packages/ui-core/core/src/lib/services/store/store.service.ts
packages/ui-core/shared/src/lib/components/badge-label/badge-label.component.ts

[Fix] Permissions Loads (Accept Invitation & Register Account)

---

packages/core/src/organization-team-employee/dto/delete-team-member-query.dto.ts
packages/core/src/organization-team-employee/dto/update-organization-team-active-task.dto.ts
packages/core/src/organization-team-employee/dto/update-team-member.dto.ts
packages/core/src/organization-team-employee/organization-team-employee.controller.ts
packages/core/src/organization-team-employee/organization-team-employee.entity.ts
packages/core/src/organization-team-employee/organization-team-employee.module.ts
packages/core/src/organization-team-employee/organization-team-employee.seed.ts
packages/core/src/organization-team-employee/organization-team-employee.service.ts
packages/core/src/organization-team-employee/repository/mikro-orm-organization-team-employee.repository.ts
packages/core/src/organization-team-employee/repository/type-orm-organization-team-employee.repository.ts
packages/core/src/shared/dto/delete-query.dto.ts

[Fix] Team Members Entity / DTOs

---

.github/workflows/desktop-timer-app-stage.yml

chore: output path var value on Windows build

---

.github/workflows/desktop-timer-app-stage.yml

chore: windows build fixes

---

packages/core/src/employee/commands/handlers/employee.bulk.create.handler.ts

Adding multiple employees accept only the second employee in the list

---

packages/contracts/src/task-status.model.ts
packages/core/src/database/migrations/1725794120289-AlterTaskStatusEntityAddingDefaultField.ts
packages/core/src/tasks/statuses/default-global-statuses.ts
packages/core/src/tasks/statuses/status.controller.ts
packages/core/src/tasks/statuses/status.entity.ts
packages/core/src/tasks/statuses/status.service.ts

[Feature] Default Task Status

---

packages/contracts/src/timesheet.model.ts
packages/core/src/time-tracking/time-log/time-log.entity.ts
packages/ui-core/i18n/assets/i18n/ar.json
packages/ui-core/i18n/assets/i18n/bg.json
packages/ui-core/i18n/assets/i18n/de.json
packages/ui-core/i18n/assets/i18n/en.json
packages/ui-core/i18n/assets/i18n/es.json
packages/ui-core/i18n/assets/i18n/fr.json
packages/ui-core/i18n/assets/i18n/he.json
packages/ui-core/i18n/assets/i18n/it.json
packages/ui-core/i18n/assets/i18n/nl.json
packages/ui-core/i18n/assets/i18n/pl.json
packages/ui-core/i18n/assets/i18n/pt.json
packages/ui-core/i18n/assets/i18n/ru.json
packages/ui-core/i18n/assets/i18n/zh.json
packages/ui-core/shared/src/lib/timesheet/gauzy-filters/gauzy-filters.component.ts

[Feat] Added 'CLOC' Time Log Source

---

packages/core/src/database/migrations/1724929664505-CreateProjectModuleTable.ts

[Fix] MySQL Migration

---

apps/desktop-timer/src/index.ts
apps/desktop/src/index.ts
apps/server-api/src/index.ts
apps/server/src/index.ts
packages/desktop-libs/src/lib/desktop-store.ts

[Fix] Missing theme variable and setting default app values on the initial run

---

apps/gauzy/src/app/pages/integrations/github/components/view/view.component.ts
packages/core/src/organization-project/organization-project.controller.ts
packages/core/src/organization-project/organization-project.module.ts

[Fix] Organization Project Optional Custom Fields

---

packages/core/src/organization-project/dto/create-organization-project.dto.ts
packages/core/src/organization-project/dto/organization-project.dto.ts
packages/core/src/organization-project/dto/update-organization-project.dto.ts
packages/core/src/organization-project/dto/update-project-setting.dto.ts
packages/core/src/organization-project/dto/update-task-mode.dto.ts

fix: updated organization project DTOs

---

packages/contracts/src/organization-team-employee-model.ts
packages/core/src/database/migrations/1726037588814-AddColumnsToOrganizationTeamEmployeeEntity.ts
packages/core/src/organization-team-employee/organization-team-employee.entity.ts
packages/core/src/organization-team/organization-team.controller.ts
packages/core/src/organization-team/organization-team.module.ts
packages/core/src/organization-team/organization-team.service.ts

---
- Added [isManager, assignedAt] to OrganizationTeamEmployee entity.

[Feat] Add New Columns to Organization Team Employee Entity

---

apps/gauzy/src/app/pages/integrations/github/components/view/view.component.ts
packages/contracts/src/employee.model.ts
packages/core/src/app.module.ts
packages/core/src/core/decorators/index.ts
packages/core/src/core/decorators/is-favoritable.ts
packages/core/src/employee/employee.entity.ts
packages/core/src/favorite/favorite.controller.ts
packages/core/src/favorite/favorite.module.ts
packages/core/src/favorite/favorite.service.ts
packages/core/src/favorite/global-favorite-service.module.ts
packages/core/src/favorite/global-favorite-service.service.ts
packages/core/src/organization-project/organization-project.controller.ts
packages/core/src/organization-project/organization-project.module.ts
packages/core/src/organization-project/organization-project.service.ts
packages/core/src/organization-team/organization-team.service.ts

Favorite APIs

---

packages/desktop-libs/src/lib/decorators/concretes/power-manager-detect-inactivity.ts
packages/desktop-libs/src/lib/desktop-os-inactivity-handler.ts
packages/desktop-libs/src/lib/offline/dao/interval.dao.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

[Fix] Remove nested event listeners

---

packages/desktop-ui-lib/src/lib/theme-selector/switch-theme/switch-theme.component.html
packages/desktop-ui-lib/src/lib/theme-selector/switch-theme/switch-theme.component.ts

[Fix] Theme switch

---

packages/desktop-ui-lib/src/lib/settings/plugins/component/plugin-layout/plugin-layout.component.scss

[Fix] Plugin Layout Title Margin

---

apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/employees/event-types/event-type.component.ts
apps/gauzy/src/app/pages/expenses/expenses.component.ts
apps/gauzy/src/app/pages/income/income.component.ts
apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
apps/gauzy/src/app/pages/invoices/invoices.component.ts
apps/gauzy/src/app/pages/payments/payments.component.ts
apps/gauzy/src/app/pages/users/users.component.ts
packages/plugins/job-proposal-ui/src/lib/proposal-template/components/proposal-template/proposal-template.component.ts
packages/plugins/job-proposal-ui/src/lib/proposal/components/proposal/proposal.component.ts
packages/plugins/job-search-ui/src/lib/components/job-search/job-search.component.ts

Rename `sort` to `isSortable` in Smart Table columns

---

packages/core/src/database/migrations/1643809486960-MigrateEmailTemplatesData.ts
packages/core/src/database/migrations/1678876700413-EmailTemplateReader.ts
packages/core/src/database/migrations/1680539459969-UpdateEmailTemplates.ts
packages/core/src/database/migrations/1700462617037-AddMultiTenantResetPasswordEmailTemplate.ts
packages/core/src/database/migrations/1701353754397-MigrateEmailTemplates.ts
packages/core/src/email-template/utils.ts

[Fix] Email Templates Migrations

---

packages/core/src/database/migrations/1726506479984-AlterFavoriteEntityIndexing.ts
packages/core/src/favorite/favorite.entity.ts

[Fix] Favorite Entity Columns Indexing

---

packages/core/src/time-tracking/statistic/statistic.helper.ts

[FIX] MySQL syntax error on Time Tracking Dashboard reload

---

packages/desktop-ui-lib/src/lib/offline-sync/concretes/sequence-queue.ts
packages/desktop-ui-lib/src/lib/shared/utils/permission.util.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts

[Fix] Offline sync and permission

---

packages/desktop-ui-lib/src/lib/recap/+state/request/request.store.ts
packages/desktop-ui-lib/src/lib/recap/monthly/+state/monthly.service.ts
packages/desktop-ui-lib/src/lib/recap/weekly/+state/weekly.service.ts

[Fix] Add Timezone Fallback to requests

---

packages/desktop-ui-lib/src/lib/login/login.component.scss
packages/desktop-ui-lib/src/lib/recap/shared/features/activity-report/activity-report.component.scss
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.scss

[Fix] Time tracker and login page styles

---

apps/desktop-timer/src/preload.ts
apps/desktop/src/preload/preload.ts

[Fix] Prevent scroll to desktop-timer and desktop apps.

---

packages/desktop-libs/package.json
packages/desktop-libs/src/lib/desktop-menu.ts
packages/desktop-libs/src/lib/plugin-system/data-access/download-context.factory.ts
packages/desktop-libs/src/lib/plugin-system/data-access/strategies/npm-download.strategy.ts
packages/desktop-libs/src/lib/plugin-system/shared/enumerations/plugin-download-context-type.ts
packages/desktop-libs/src/lib/plugin-system/shared/index.ts
packages/desktop-libs/src/lib/plugin-system/shared/interfaces/plugin-download-strategy.interface.ts
packages/desktop-libs/src/lib/plugin-system/shared/utils/npm.util.ts
packages/desktop-libs/src/lib/plugin-system/shared/utils/tarball.util.ts
packages/desktop-ui-lib/src/lib/directives/desktop-directive.module.ts
packages/desktop-ui-lib/src/lib/directives/text-mask.directive.ts
packages/desktop-ui-lib/src/lib/settings/plugins/component/add-plugin/add-plugin.component.html
packages/desktop-ui-lib/src/lib/settings/plugins/component/add-plugin/add-plugin.component.scss
packages/desktop-ui-lib/src/lib/settings/plugins/component/add-plugin/add-plugin.component.ts
packages/desktop-ui-lib/src/lib/settings/plugins/plugins.module.ts
packages/ui-core/i18n/assets/i18n/en.json
yarn.lock

[Feat] Implement NPM download strategy

---

packages/contracts/src/timesheet.model.ts
packages/core/src/core/utils.ts
packages/core/src/employee/employee.service.ts
packages/core/src/time-tracking/time-log/commands/handlers/schedule-time-log-entries.handler.ts
packages/core/src/time-tracking/time-log/commands/schedule-time-log-entries.command.ts
packages/core/src/time-tracking/time-log/time-log.entity.ts
packages/core/src/time-tracking/timer/dto/start-timer.dto.ts
packages/core/src/time-tracking/timer/dto/stop-timer.dto.ts
packages/core/src/time-tracking/timer/timer.service.ts
packages/ui-core/core/src/lib/services/time-tracker/time-tracker.service.ts

[Fix] Adjust Pending Time Logs Entries

---

packages/core/src/time-tracking/time-log/commands/handlers/schedule-time-log-entries.handler.ts
packages/core/src/time-tracking/time-log/commands/handlers/time-log-create.handler.ts
packages/core/src/time-tracking/time-log/time-log.module.ts
packages/core/src/time-tracking/time-slot/time-slot.entity.ts
packages/core/src/time-tracking/time-slot/time-slot.service.ts
packages/core/src/time-tracking/timer/timer.service.ts
packages/core/src/time-tracking/timesheet/commands/timesheet-first-or-create.command.ts

[Fix] Calculated stopped date for Start/Stop timer

---

packages/ui-core/shared/src/lib/file-uploader-input/file-uploader-input.component.ts
packages/ui-core/shared/src/lib/select-asset-modal/img-preview/img-preview.component.html
packages/ui-core/shared/src/lib/select-asset-modal/select-asset.component.html
packages/ui-core/shared/src/lib/select-asset-modal/select-asset.component.ts

[Fix] Product Type / Product Category Preview thumbnail 

---

packages/core/src/time-tracking/time-log/commands/handlers/schedule-time-log-entries.handler.ts
packages/core/src/time-tracking/timer/timer.service.ts

[Fix]: Duration Clamping

---

apps/gauzy/src/app/pages/invoices/invoice-add/invoice-add.component.ts
apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
packages/ui-core/common/src/lib/utils/shared-utils.ts

 [Fix] Adding Products to Invoices & Estimates Produces Error

---

packages/contracts/src/organization-projects.model.ts
packages/core/src/organization-project/commands/handlers/organization-project-edit-by-employee.handler.ts
packages/core/src/organization-project/commands/organization-project-edit-by-employee.command.ts
packages/core/src/organization-project/organization-project.controller.ts
packages/core/src/organization-project/organization-project.service.ts

[Fix]: Update projects by employee Command and Handler

---

packages/core/src/database/migrations/1727271308311-AddIndexingOrganizationProjectEmployeeEntity.ts
packages/core/src/organization-project/organization-project-employee.entity.ts
packages/core/src/time-tracking/timer/timer.service.ts

[Feat] Missing columns indexing (OrganizationProjectEmployee) entity

---

packages/core/src/core/utils.ts
packages/core/src/employee/employee.service.ts
packages/core/src/time-tracking/screenshot/screenshot.controller.ts
packages/core/src/time-tracking/screenshot/screenshot.helper.ts
packages/core/src/time-tracking/time-log/commands/handlers/schedule-time-log-entries.handler.ts
packages/core/src/time-tracking/timer/timer.controller.ts
packages/core/src/time-tracking/timer/timer.module.ts
packages/core/src/time-tracking/timer/timer.service.ts

[Fix] Adjust Timer Last Stopped Date

---

apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.scss

[Enhancement] Align fields with header - /pages/employees/timesheets

---

packages/plugins/job-employee-ui/src/lib/components/job-employee/job-employee.component.ts

[Fix] Job Employees (Data Table Columns Registry)

---

packages/plugins/integration-upwork/src/lib/upwork.service.ts

[Fix] Packages Build

---

packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts

[Refactor] Timer Stop flow and updated activity building

---

packages/desktop-ui-lib/src/lib/theme-selector/switch-theme/switch-theme.component.scss

[Fix] styles for switch theme

---

apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
packages/core/src/time-tracking/statistic/statistic.service.ts
packages/ui-core/shared/src/lib/components/avatar/avatar.component.html
packages/ui-core/shared/src/lib/components/avatar/avatar.component.scss
packages/ui-core/shared/src/lib/components/avatar/avatar.component.ts

[FEATURE] Add Online/Offline Status Indicator to User Avatar

---

packages/desktop-ui-lib/src/lib/time-tracker/+state/time-tracker.store.ts
packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
packages/desktop-ui-lib/src/lib/time-tracker/timer-tracker-change-dialog/timer-tracker-change-dialog.component.ts

[Fix] Issue with Changing Task on Running Timer

---

packages/desktop-libs/src/lib/desktop-timer.ts

[Fix] Timeslot startedAt variable

---

apps/desktop/src/index.ts
apps/server-api/src/index.ts
apps/server/src/index.ts
packages/desktop-libs/src/lib/desktop-theme-listener.ts

Fix: Desktop theme listener implementation.

---

apps/gauzy/src/app/pages/employees/employees.component.ts
apps/gauzy/src/app/pages/users/users.component.ts
packages/core/src/employee/employee.service.ts
packages/core/src/time-tracking/time-log/time-log.service.ts
packages/ui-core/shared/src/lib/components/avatar/avatar.component.ts
packages/ui-core/shared/src/lib/table-components/picture-name-tags/picture-name-tags.component.ts

[FIX] Online status

---

packages/desktop-libs/src/lib/desktop-store.ts

[Refactor] Set default application setting

---

packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-tray.ts

[feat] use windows manager and add new submenu to the unauth menu

---

packages/desktop-libs/src/lib/desktop-tray.ts
packages/desktop-window/src/lib/desktop-window-setting.ts

[Fix] Auto Logout

---

apps/desktop-timer/src/index.ts
packages/desktop-libs/src/lib/desktop-ipc.ts
packages/desktop-libs/src/lib/desktop-store.ts
packages/desktop-libs/src/lib/desktop-tray.ts
packages/desktop-window/src/lib/desktop-window-setting.ts

[Refactor] Use window manager in desktop IPC

---

apps/desktop-timer/src/index.ts

[Fix] Build issue

---

packages/core/src/organization-project-module/commands/handlers/index.ts
packages/core/src/organization-project-module/commands/handlers/organization-project-module-create.handler.ts
packages/core/src/organization-project-module/commands/handlers/organization-project-module-update.handler.ts
packages/core/src/organization-project-module/commands/index.ts
packages/core/src/organization-project-module/commands/organization-project-module-create.command.ts
packages/core/src/organization-project-module/commands/organization-project-module-update.command.ts
packages/core/src/organization-project-module/organization-project-module.controller.ts
packages/core/src/organization-project-module/organization-project-module.module.ts
packages/core/src/organization-project-module/organization-project-module.service.ts
packages/core/src/tasks/task.service.ts

[Fix] Project Module command and logs

---

packages/desktop-libs/src/lib/plugin-system/data-access/strategies/npm-download.strategy.ts

[Feat] Plugin System , NPM strategy Handle native modules

---

apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html

[Enhancement] Display of dates on the timesheet page

---

packages/contracts/src/timesheet-statistics.model.ts
packages/core/src/core/context/request-context.ts
packages/core/src/time-tracking/statistic/statistic.helper.ts
packages/core/src/time-tracking/statistic/statistic.service.ts
packages/core/src/time-tracking/timer/timer.service.ts

[Fix] #8311 Prevent Negative Values in Timer and Display Accurate Worked Time

---

packages/contracts/src/daily-plan.model.ts
packages/core/src/tasks/daily-plan/daily-plan.service.ts

[Fix]  Daily Plan save by team

---

packages/core/src/organization-project-module/organization-project-module.service.ts
packages/core/src/tasks/commands/handlers/task-create.handler.ts
packages/core/src/tasks/commands/handlers/task-update.handler.ts

[Feature] Task Activity Log

---

packages/core/src/time-tracking/time-slot/commands/handlers/create-time-slot.handler.ts

[Fix] Revert Create / Merge Time Slot

---

packages/contracts/src/timesheet.model.ts
packages/core/src/core/entities/internal.ts
packages/core/src/core/entities/subscribers/index.ts
packages/core/src/time-tracking/timesheet/commands/timesheet-recalculate.command.ts
packages/core/src/time-tracking/timesheet/dto/query/submit-timesheet-status.dto.ts
packages/core/src/time-tracking/timesheet/dto/query/update-timesheet-status.dto.ts
packages/core/src/time-tracking/timesheet/timesheet.controller.ts
packages/core/src/time-tracking/timesheet/timesheet.entity.ts
packages/core/src/time-tracking/timesheet/timesheet.module.ts
packages/core/src/time-tracking/timesheet/timesheet.service.ts
packages/core/src/time-tracking/timesheet/timesheet.subscriber.ts

[Feat] Timesheet Entity Event Subscriber

---

packages/core/src/favorite/favorite.controller.ts
packages/core/src/favorite/favorite.service.ts

[Improvement] Favorites find APIs

---

apps/gauzy/src/app/pages/employees/activity/screenshot/screenshot/screenshot.component.ts
apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
packages/contracts/src/screenshot.model.ts
packages/contracts/src/timesheet.model.ts
packages/core/src/core/entities/subscribers/base-entity-event.subscriber.ts
packages/core/src/core/entities/subscribers/entity-event-subscriber.types.ts
packages/core/src/core/entities/subscribers/entity-event.subsciber.ts
packages/core/src/core/entities/subscribers/entity-event.subscriber.ts
packages/core/src/time-tracking/dto/force-delete.dto.ts
packages/core/src/time-tracking/screenshot/dto/delete-screenshot.dto.ts
packages/core/src/time-tracking/screenshot/screenshot-file-storage.helper.ts
packages/core/src/time-tracking/screenshot/screenshot.controller.ts
packages/core/src/time-tracking/screenshot/screenshot.entity.ts
packages/core/src/time-tracking/screenshot/screenshot.service.ts
packages/core/src/time-tracking/screenshot/screenshot.subscriber.ts
packages/core/src/time-tracking/time-log/commands/delete-time-span.command.ts
packages/core/src/time-tracking/time-log/dto/delete-time-log.dto.ts
packages/core/src/time-tracking/time-log/time-log.controller.ts
packages/core/src/time-tracking/time-slot/dto/delete-time-slot.dto.ts
packages/ui-core/core/src/lib/services/timesheet/timesheet.service.ts
packages/ui-core/shared/src/lib/timesheet/screenshots/screenshots-item/screenshots-item.component.ts

[Fix] Screenshot Soft Removal

---

packages/core/src/shared/dto/filters-query.dto.ts
packages/core/src/shared/validators/is-between-activity.decorator.ts

[Fix] Csepll typo spelling :-) 

---

packages/core/src/tasks/commands/handlers/task-create.handler.ts
packages/core/src/tasks/task.controller.ts
packages/core/src/tasks/task.module.ts
packages/core/src/tasks/task.service.ts

[Fix] Generate Correct Task Number For MySQL

---

apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-projects/edit-employee-projects.component.ts
packages/contracts/src/organization-projects.model.ts
packages/core/src/organization-project/commands/handlers/organization-project-edit-by-employee.handler.ts
packages/core/src/organization-project/organization-project.service.ts
packages/ui-core/core/src/lib/services/organization/organization-projects.service.ts

[Fix] Update Projects By Employee Command/Handler

---

packages/contracts/src/timesheet.model.ts
packages/core/src/shared/dto/selectors-query.dto.ts
packages/core/src/time-tracking/time-log/commands/time-log-delete.command.ts
packages/core/src/time-tracking/time-log/time-log.service.ts
packages/core/src/time-tracking/time-slot/commands/delete-time-slot.command.ts
packages/core/src/time-tracking/time-slot/commands/handlers/delete-time-slot.handler.ts
packages/core/src/time-tracking/time-slot/dto/time-slot-query.dto.ts
packages/core/src/time-tracking/time-slot/time-slot.controller.ts
packages/core/src/time-tracking/time-slot/time-slot.seed.ts
packages/core/src/time-tracking/time-slot/time-slot.service.ts

[Refactor] Optimization Time Slot & Log (Soft Delete)

---

packages/core/src/database/migrations/1727954184608-AlterTokenColumnTypeToTextInPasswordResetTable.ts

[Fix] #8316 Password Reset Migration (MySQL)

---

packages/core/src/employee/commands/handlers/update-employee-total-worked-hours.handler.ts
packages/core/src/time-tracking/time-slot/commands/handlers/delete-time-slot.handler.ts
packages/core/src/time-tracking/time-slot/time-slot.entity.ts

[Fix] Time Slots Cascading For Screenshots

---

packages/core/src/time-tracking/time-log/commands/handlers/delete-time-span.handler.ts

[WIP] Time Span Handler (Soft Delete)

---

packages/desktop-libs/src/lib/plugin-system/data-access/plugin-manager.ts

[Feat] Activate plugin after installation

---

packages/core/src/organization-project/organization-project.service.ts

[Fix] Error when updating project: update of employees or managers

---

packages/ui-core/i18n/assets/i18n/ar.json
packages/ui-core/i18n/assets/i18n/bg.json
packages/ui-core/i18n/assets/i18n/de.json
packages/ui-core/i18n/assets/i18n/en.json
packages/ui-core/i18n/assets/i18n/es.json
packages/ui-core/i18n/assets/i18n/fr.json
packages/ui-core/i18n/assets/i18n/he.json
packages/ui-core/i18n/assets/i18n/it.json
packages/ui-core/i18n/assets/i18n/nl.json
packages/ui-core/i18n/assets/i18n/pt.json
packages/ui-core/i18n/assets/i18n/zh.json

[Fix] Change "Select team" label to "Select Team" #8347

---

packages/contracts/src/employee.model.ts
packages/contracts/src/organization-projects.model.ts
packages/contracts/src/organization-sprint.model.ts
packages/contracts/src/organization-team.model.ts
packages/contracts/src/task.model.ts
packages/core/src/core/dto/index.ts
packages/core/src/core/dto/member-entity-based.dto.ts
packages/core/src/organization-project/dto/organization-project.dto.ts
packages/core/src/organization-project/organization-project.service.ts
packages/core/src/organization-sprint/commands/handlers/index.ts
packages/core/src/organization-sprint/commands/handlers/organization-sprint.create.handler.ts
packages/core/src/organization-sprint/commands/handlers/organization-sprint.update.handler.ts
packages/core/src/organization-sprint/commands/index.ts
packages/core/src/organization-sprint/commands/organization-sprint.create.command.ts
packages/core/src/organization-sprint/dto/create-organization-sprint.dto.ts
packages/core/src/organization-sprint/dto/index.ts
packages/core/src/organization-sprint/dto/organization-sprint.dto.ts
packages/core/src/organization-sprint/dto/update-organization-sprint.dto.ts
packages/core/src/organization-sprint/organization-sprint.controller.ts
packages/core/src/organization-sprint/organization-sprint.module.ts
packages/core/src/organization-sprint/organization-sprint.service.ts
packages/core/src/organization-team-employee/organization-team-employee.service.ts
packages/core/src/organization-team/dto/organization-team.dto.ts
packages/core/src/organization-team/organization-team.service.ts
packages/core/src/tasks/commands/handlers/task-update.handler.ts
packages/core/src/tasks/estimation/commands/handlers/task-estimation-calculate.handler.ts
packages/core/src/tasks/task.module.ts
packages/core/src/tasks/task.service.ts

[Feat] Organization Sprint API improvements

---

packages/core/src/activity-log/dto/get-activity-logs.dto.ts
packages/core/src/resource-link/dto/create-resource-link.dto.ts
packages/core/src/resource-link/dto/index.ts
packages/core/src/resource-link/dto/update-resource-link.dto.ts

fix(cspell): typo spelling :-)

---

apps/gauzy/src/app/pages/employees/activity/activity.module.ts
apps/gauzy/src/app/pages/employees/activity/layout/layout.component.html
apps/gauzy/src/app/pages/employees/activity/layout/layout.component.ts
apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.html
apps/gauzy/src/app/pages/employees/timesheet/layout/layout.component.ts
apps/gauzy/src/app/pages/income/income.component.html
apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.html
apps/gauzy/src/app/pages/invoices/invoices.component.html
packages/ui-core/shared/src/lib/components/date-range-title/date-range-title.component.ts

[Fix] Date Range Title (Timesheets & Activites) Page

---

packages/contracts/src/organization-projects.model.ts
packages/ui-core/theme/src/lib/components/header/header.component.ts

[Fix] Hide/Show Selectors For Employee Login

---

.github/workflows/desktop-app-prod.yml
.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-prod.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/server-api-prod.yml
.github/workflows/server-api-stage.yml
.github/workflows/server-prod.yml
.github/workflows/server-stage.yml
yarn.lock

chore: add build tools

---

.vscode/extensions.json
apps/desktop-timer/package.json
apps/desktop-timer/src/package.json
apps/desktop/package.json
apps/desktop/src/package.json
apps/server-api/package.json
apps/server-api/src/package.json
apps/server/package.json
apps/server/src/package.json
package.json
yarn.lock

chore: remove iconv

---

.circleci/config.yml
.deploy/api/Dockerfile
.github/workflows/desktop-app-prod.yml
.github/workflows/desktop-app-stage.yml
.github/workflows/desktop-timer-app-prod.yml
.github/workflows/desktop-timer-app-stage.yml
.github/workflows/server-api-prod.yml
.github/workflows/server-api-stage.yml
.github/workflows/server-prod.yml
.github/workflows/server-stage.yml
package.json
yarn.lock

chore: attempt to update node-gyp

---

packages/core/src/lib/tasks/screening-tasks/screening-tasks.module.ts
packages/core/src/lib/tasks/screening-tasks/screening-tasks.service.ts

[Fix] Screening Task | Task prefix and Task number

---

packages/plugins/public-layout-ui/src/lib/components/appointment-form/appointment-form.component.ts
packages/ui-core/shared/src/lib/appointments/appointment-calendar/appointment-calendar.component.ts
packages/ui-core/shared/src/lib/appointments/manage-appointment/manage-appointment.component.ts

[FIX] Issue in Opening Appointment && Unable to Pick a Date and Time for Appointment

---

apps/gauzy/src/app/pages/departments/departments.component.ts
apps/gauzy/src/app/pages/employee-levels/employee-level.component.ts
apps/gauzy/src/app/pages/employment-types/employment-types.component.ts
apps/gauzy/src/app/pages/positions/positions.component.ts
packages/ui-core/i18n/assets/i18n/ach.json
packages/ui-core/i18n/assets/i18n/ar.json
packages/ui-core/i18n/assets/i18n/bg.json
packages/ui-core/i18n/assets/i18n/de.json
packages/ui-core/i18n/assets/i18n/en.json
packages/ui-core/i18n/assets/i18n/es.json
packages/ui-core/i18n/assets/i18n/fr.json
packages/ui-core/i18n/assets/i18n/he.json
packages/ui-core/i18n/assets/i18n/it.json
packages/ui-core/i18n/assets/i18n/nl.json
packages/ui-core/i18n/assets/i18n/pl.json
packages/ui-core/i18n/assets/i18n/pt.json
packages/ui-core/i18n/assets/i18n/ru.json
packages/ui-core/i18n/assets/i18n/zh.json

[Fix] Users Can Add Duplicate Employee Level && Duplicate Positions

---

apps/gauzy/src/app/pages/time-off/time-off.component.ts

[Fix] Filters Not Working on “Time Off” Screen (CARDS_GRID Layout)

---

apps/gauzy-e2e/package.json
apps/gauzy/package.json
package.json
yarn.lock

chore(deps): update @angular-devkit/architect to v0.1802.12

---

packages/desktop-ui-lib/project.json
packages/plugins/integration-ai-ui/project.json
packages/plugins/integration-github-ui/project.json
packages/plugins/integration-hubstaff-ui/project.json
packages/plugins/integration-upwork-ui/project.json
packages/plugins/job-employee-ui/project.json
packages/plugins/job-matching-ui/project.json
packages/plugins/job-proposal-ui/project.json
packages/plugins/job-search-ui/project.json
packages/plugins/legal-ui/project.json
packages/plugins/maintenance-ui/project.json
packages/plugins/onboarding-ui/project.json
packages/plugins/public-layout-ui/project.json
packages/ui-auth/project.json
packages/ui-config/project.json
packages/ui-core/project.json

chore(packages): add tsconfig.json to ng-package options configuration

---

packages/core/src/lib/user-organization/dto/find-me-user-organization.dto.ts
packages/core/src/lib/user-organization/user-organization.controller.ts
packages/core/src/lib/user-organization/user-organization.services.ts
packages/core/src/lib/user/user.service.ts

[Fix] User Organization For Me

---

packages/utils/src/index.ts
packages/utils/src/lib/array-random-element.ts

[Feat] Random Array Element Utils

---

packages/core/src/lib/core/seeds/seed-data.service.ts
packages/core/src/lib/employee-notification-setting/employee-notification-setting.entity.ts
packages/core/src/lib/employee-notification-setting/employee-notification-setting.seed.ts
packages/core/src/lib/employee-notification/employee-notification.seed.ts

[Feat] "Employee Notification Setting" Entity Seeder

---

packages/core/src/lib/database/migrations/1740723269734-AlterSubscriptionEntityTable.ts
packages/core/src/lib/entity-subscription/entity-subscription.entity.ts

[Fix] Alter "Subscription" Entity Table

---

packages/contracts/src/lib/user.model.ts
packages/core/src/lib/auth/auth.service.ts
packages/core/src/lib/auth/commands/handlers/auth.register.handler.ts
packages/core/src/lib/invite/invite.service.ts
packages/core/src/lib/organization-team-join-request/organization-team-join-request.service.ts
packages/ui-core/shared/src/lib/user/forms/basic-info/basic-info-form.component.ts

[Fix] Replace 'createdById' to 'createdByUserId'

---

packages/plugins/integration-make-com/src/lib/make-com.module.ts

[Fix] Missing Role Permission Module

---

.deploy/webapp/Dockerfile

Reverts ever-co/ever-gauzy#8854

Revert "[Chore] Docker Deploy Webapp Packages "

---

.github/workflows/agent-prod.yml
.github/workflows/agent-stage.yml
.scripts/bump-version-electron.js
.scripts/env.ts

* chore: init agent build ci
* Update .scripts/bump-version-electron.js
* Update agent-prod.yml
* Update agent-stage.yml
* Update env.ts
* Update env.ts
---------
---

chore: init agent build ci (#8868)

---

packages/ui-config/src/lib/environments/model.ts

[Fix]  Error when opening the "Add Holiday" modal (make DEFAULT_COUNTRY a required field)

---

packages/ui-core/shared/src/lib/invite/forms/email-invite-form/email-invite-form.component.html
packages/ui-core/shared/src/lib/invite/forms/email-invite-form/email-invite-form.component.ts

…Invite Employee” Popup Window
---

[Fix] Unable to remove selection when user use “Select All” Option

---

packages/ui-core/shared/src/lib/expenses/expenses-mutation/expenses-mutation.component.html

[Enhancement] Improve Warning Icon Placement and Color for Expense Form

---

packages/ui-core/shared/src/lib/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html

…00 error on recurring expenses
---

[Fix] Recurring Expenses: Disable "All Employees" Option to Avoid HTTP 400 (#8889)

---

packages/ui-core/shared/src/lib/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html

Reverts ever-co/ever-gauzy#8899

Revert "[Fix] Recurring Expenses: Disable "All Employees" Option to Avoid HTTP 400 (#8889)"

---

apps/api/package.json
packages/plugins/plugin-registry/package.json

[Fix] Missing dependency

---

packages/core/src/lib/database/migrations/1744014217496-CreateZapierWebhookSubscriptionRepositoryTable.ts
packages/plugins/integration-zapier/src/lib/dto/create-zapier-integration.dto.ts
packages/plugins/integration-zapier/src/lib/integration-zapier.plugin.ts
packages/plugins/integration-zapier/src/lib/repository/mikro-orm-zapier.repository.ts
packages/plugins/integration-zapier/src/lib/repository/type-orm-zapier.repository.ts
packages/plugins/integration-zapier/src/lib/zapier-authorization.controller.ts
packages/plugins/integration-zapier/src/lib/zapier-webhook-subscription.entity.ts
packages/plugins/integration-zapier/src/lib/zapier-webhook.controller.ts
packages/plugins/integration-zapier/src/lib/zapier-webhook.service.ts
packages/plugins/integration-zapier/src/lib/zapier.module.ts

[Fix] Zapier Webhook Subscription Entity/Migration

---

.deploy/api/Dockerfile
.deploy/webapp/Dockerfile
.scripts/find-native-deps.js
.scripts/postinstall.js
package.json

[Fix] Migrate postinstall scripts to JavaScript

---

apps/gauzy/package.json
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-settings.module.ts
apps/gauzy/src/app/pages/tags/tags.module.ts
packages/ui-core/core/src/lib/services/app/google-maps-loader.service.ts
packages/ui-core/package.json
packages/ui-core/shared/src/lib/project/project-mutation/project-mutation.module.ts
packages/ui-core/shared/src/lib/sidebar/knowledge-base/knowledge-base.module.ts
packages/ui-core/shared/src/lib/tags/tags-mutation.module.ts
packages/ui-core/static/styles/fonts/_google-fonts.scss
packages/ui-core/static/styles/styles.scss
yarn.lock

[Fix] Color Picker Module

---

packages/plugins/posthog-ui/src/lib/directives/posthog-form-track.directive.ts
packages/plugins/posthog-ui/src/lib/directives/posthog-track.directive.ts
packages/plugins/posthog-ui/src/lib/posthog.module.ts
yarn.lock

[fix] posthog-ui directives import

---

.deploy/webapp/Dockerfile
packages/plugins/posthog-ui/package.json
yarn.lock

[Fix] Docker Build

---

packages/core/src/lib/language/language-utils.ts
packages/core/src/lib/language/language.seed.ts
packages/core/src/lib/organization/commands/handlers/organization.create.handler.ts
packages/core/src/lib/organization/organization.seed.ts
packages/core/src/lib/organization/organization.subscriber.ts
packages/core/src/lib/skills/skill.seed.ts
packages/core/src/lib/tags/tag.subscriber.ts
packages/core/src/lib/tasks/issue-type/issue-type.subscriber.ts
packages/core/src/lib/tasks/priorities/priority.subscriber.ts
packages/core/src/lib/tasks/related-issue-type/related-issue-type.subscriber.ts
packages/core/src/lib/tasks/sizes/size.subscriber.ts
packages/core/src/lib/tasks/statuses/status.subscriber.ts
packages/core/src/lib/tasks/versions/version.subscriber.ts

[Fix] Replace deprecated faker.internet.color() with faker.color.rgb()

---

packages/core/src/lib/bootstrap/bootstrap-trace.ts
packages/core/src/lib/bootstrap/index.ts
packages/core/src/lib/database/migrations/1744014217496-CreateZapierWebhookSubscriptionRepositoryTable.ts
packages/core/src/lib/tasks/versions/version.subscriber.ts

[Fix] Zapier Webhook Migration (SQLite)

---

packages/core/src/lib/database/migration-executor.ts
packages/core/src/lib/database/migrations/1746169515410-AlterTimeSlotEntityTable.ts
packages/core/src/lib/time-tracking/time-slot/time-slot-minute/time-slot-minute.entity.ts
packages/core/src/lib/time-tracking/time-slot/time-slot.entity.ts

[Feat] Alter "TimeSlot" Entity Migration

---

packages/core/src/lib/tasks/daily-plan/daily-plan.controller.ts
packages/core/src/lib/tasks/daily-plan/daily-plan.service.ts

[Fix] Updated query builder for daily plan

---

apps/agent/src/assets/styles/themes.scss
apps/desktop-timer/src/assets/styles/themes.scss
packages/core/src/lib/accounting-template/accounting-template.module.ts
packages/core/src/lib/email-template/email-template.module.ts
packages/core/src/lib/export-import/import-record/import-record.module.ts
packages/core/src/lib/role/role.module.ts
packages/core/src/lib/user-organization/user-organization.module.ts
packages/core/src/lib/user/user.module.ts
packages/plugins/knowledge-base/src/lib/help-center-article/help-center-article.module.ts
packages/plugins/knowledge-base/src/lib/help-center-author/help-center-author.module.ts
packages/plugins/knowledge-base/src/lib/help-center/help-center.module.ts

[Fix] Remove unnecessary forwardRef for ORM entities

---

packages/plugins/integration-zapier/src/lib/zapier.service.ts

[Fix] build issues related to axios version conflict

---

packages/auth/package.json
packages/core/package.json
packages/core/src/lib/core/decorators/entity/embedded-column.decorator.ts
packages/plugins/integration-ai/package.json
packages/plugins/integration-github/package.json
packages/plugins/integration-hubstaff/package.json
packages/plugins/integration-make-com/package.json
packages/plugins/integration-zapier/package.json
yarn.lock

chore: use our fork of NestJs Axios temporary

---

apps/agent/src/app/app.component.ts

fix: failed build component agent app

---

apps/desktop/src/package.json
apps/server-api/src/package.json
apps/server/src/package.json

[Fix] Desktop apps missing plugins

---

packages/core/src/lib/core/dto/base-query.dto.ts
packages/core/src/lib/shared/validators/constraints/organization-belongs-to-user.constraint.ts
packages/plugins/posthog/src/lib/posthog-event.interceptor.ts

[Fix] DTO Request

---

packages/plugins/integration-make-com/src/lib/interfaces/make-com.model.ts
packages/plugins/integration-make-com/src/lib/make-com-authorization.controller.ts
packages/plugins/integration-make-com/src/lib/make-com-oauth.service.ts
packages/plugins/integration-make-com/src/lib/make-com.config.ts
packages/plugins/integration-make-com/src/lib/make-com.controller.ts
packages/plugins/integration-make-com/src/lib/make-com.service.ts
packages/plugins/integration-make-com/src/lib/webhook.service.ts

[FIX] Update integration settings flow with make

---

apps/agent/package.json
apps/agent/src/main/api.ts
apps/agent/src/main/screenshot.ts
apps/agent/src/main/util.ts
apps/agent/src/main/workers/push-activities.ts
apps/agent/src/package.json
packages/desktop-lib/src/lib/interfaces/i-kb-mouse-activity.ts

fix: change temp saving  screenshot taken file to sync
---

fix: saving activities and screenshot to api

---

packages/desktop-activity/src/lib/kb-mouse-activity-stores.ts
packages/desktop-activity/src/lib/kb-mouse-event-counter.ts
packages/desktop-activity/src/lib/kb-mouse-timer.ts
packages/desktop-lib/src/lib/offline/dao/kb-mouse-activity.dao.ts
packages/desktop-lib/src/lib/offline/dto/kb-mouse-activity.dto.ts
packages/desktop-lib/src/lib/offline/models/kb-mouse-activity.model.ts
packages/desktop-lib/src/lib/offline/services/kb-mouse-activity.service.ts
packages/desktop-ui-lib/src/lib/server-dashboard/server-dashboard.component.html
packages/plugins/integration-make-com/src/lib/make-com-authorization.controller.ts
packages/plugins/integration-make-com/src/lib/make-com.controller.ts
packages/ui-core/shared/src/lib/report/charts/line-chart/line-chart.module.ts

[fix]: Improve AI suggestions implementation for PR #8968

---

apps/agent/src/main/workers/push-activities.ts
packages/desktop-lib/src/lib/offline/dto/kb-mouse-activity.dto.ts
packages/desktop-lib/src/lib/offline/models/kb-mouse-activity.model.ts

[Fix] Handle stringified activity data

---

yarn.lock

chore(deps): generate yarn.lock

---

packages/ui-core/static/styles/_overrides.scss

[Fix] override scrollable-container overflow-y for dashboard layout

---

apps/agent/src/app/app-routing.module.ts
apps/agent/src/app/app.component.scss
apps/agent/src/app/app.component.ts
apps/agent/src/constant.ts
apps/agent/src/index.ts
apps/agent/src/main/events/event-handler.ts
apps/agent/src/main/events/events.ts
apps/agent/src/main/init/app.ts
apps/agent/src/main/init/ipcMain.ts
apps/agent/src/main/util.ts
apps/agent/src/main/workers/push-activities.ts
packages/desktop-window/src/lib/desktop-window-setup.ts

fix: agent handle unauthorize state and missing token

---

apps/api/package.json
packages/plugins/camshot/README.md
packages/plugins/camshot/package.json

[Fix] API Missing dependency

---

.cspell.json
packages/common/src/lib/interfaces/IActivepiecesConfig.ts
packages/config/src/lib/environments/ienvironment.ts
packages/plugins/camshot/src/lib/camshot.controller.ts
packages/plugins/camshot/src/lib/commands/delete-camshot.command.ts
packages/plugins/camshot/src/lib/commands/handlers/delete-camshot-command.handler.ts
packages/plugins/integration-activepieces/src/lib/activepieces-authorization.controller.ts
packages/plugins/integration-activepieces/src/lib/activepieces.service.ts
packages/plugins/integration-activepieces/src/lib/activepieces.type.ts
packages/plugins/integration-activepieces/src/lib/dto/activepieces-query.dto.ts
packages/plugins/integration-activepieces/src/lib/integration-activepieces.plugin.ts

[Fix] AI suggestion stage

---

packages/plugins/integration-make-com/README.md
packages/plugins/integration-make-com/src/lib/make-com-oauth.service.ts
packages/plugins/integration-zapier/src/lib/zapier.controller.ts
packages/plugins/integration-zapier/src/lib/zapier.service.ts

[FIX] Enhance security for integration settings

---

.circleci/config.yml

chore: circleCI

---

packages/core/src/lib/favorite/favorite.service.ts

- Improved employeeId handling for favorite creation (prioritize RequestContext, fallback to body)
- Fixed admin logic for favorite deletion (admins can delete any favorite, employees only their own)
---

[fix](favorite): improve and fix favorite deletion logic

---

apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
packages/contracts/src/lib/organization.model.ts
packages/core/src/lib/database/migrations/1752401427774-AddOrganizationAgentTimerSettings.ts
packages/core/src/lib/organization/dto/create-organization.dto.ts
packages/core/src/lib/organization/organization.entity.ts

[Feat] organization agent timer settings

---

packages/contracts/src/lib/invite.model.ts
packages/core/src/lib/invite/invite.service.ts
yarn.lock

[Fix] Improved Invite email callback URL

---

apps/agent/package.json
apps/agent/src/package.json
apps/desktop-timer/package.json
apps/desktop-timer/src/package.json
apps/desktop/package.json
apps/desktop/src/package.json
apps/server-api/package.json
apps/server-api/src/package.json
apps/server-mcp/src/package.json
apps/server/package.json
apps/server/src/package.json
packages/core/package.json
yarn.lock

fix:Update @sentry/electron from 6.8.0 to 6.9.0 (uses @sentry/core 9.43.0)

---

packages/plugins/integration-github/src/lib/github/github.hooks.controller.ts
packages/plugins/integration-github/src/lib/github/github.hooks.service.ts
packages/plugins/integration-github/src/lib/probot/octokit.service.ts
packages/plugins/integration-github/src/lib/probot/probot.discovery.ts
packages/plugins/integration-github/src/lib/probot/probot.helpers.ts

fix: convert probot and octokit imports to dynamic imports for ESM

---

.cspell.json
packages/mcp-server/examples/websocket-client-example.js
packages/mcp-server/package.json
packages/mcp-server/src/lib/common/config.ts
packages/mcp-server/src/lib/config/index.ts
packages/mcp-server/src/lib/config/protocol.ts
packages/mcp-server/src/lib/session/index.ts
packages/mcp-server/src/lib/session/session-manager.ts
packages/mcp-server/src/lib/session/session-middleware.ts
packages/mcp-server/src/lib/session/session-monitor.ts
packages/mcp-server/src/lib/session/session-store.ts
packages/mcp-server/src/lib/transports/http-transport.ts
packages/mcp-server/src/lib/transports/transport-factory.ts
packages/mcp-server/src/lib/transports/websocket-transport.ts
yarn.lock

[Improvement] Implement secure session management for multi-user support for the MCP Server

---

packages/core/src/lib/invite/invite.service.ts
packages/ui-core/shared/src/lib/invite/invites/invites.component.ts

[Feat] invite role array filtering

---

apps/gauzy/src/index.html
packages/ui-core/static/styles/_spinner.scss

[feat] implement skeleton loader system to replace global spinner

---

apps/desktop-timer/src/app/app.module.ts

[Fix] Sentry integration in desktop timer

---

packages/contracts/src/lib/timesheet.model.ts
packages/core/src/lib/core/util/db-serialization-util.ts
packages/core/src/lib/time-tracking/custom-tracking/commands/handlers/process-tracking-data.handler.ts
packages/core/src/lib/time-tracking/custom-tracking/custom-tracking.service.ts

[Fix] SQLite compatibility issues with JSON storage and date binding.

---

packages/core/src/lib/organization-team-employee/organization-team-employee.service.ts

[fix] update active task
